function SFSessionTimer(){this.init()}SFSessionTimer.NOTIFY_BEFORE_SESSION_EXPIRE=1;
SFSessionTimer.prototype=function(){return juic.set(new juic.EventTarget,{init:function(){this.sessionTimeoutController=AjaxService.getMBeanInstance("sessionTimeoutController");var a=this,c=function(b){var c=1E3*b.timeUntilExpires;a.timeAfterReminder=6E4*b.timeUntilWarning;a.timeBeforeSessionExpire=6E4*SFSessionTimer.NOTIFY_BEFORE_SESSION_EXPIRE;a.timeToCallReminder=c-a.timeAfterReminder;a.reset();a._configuredSessionInterval=c;a._configuredSessionTimeoutWarning=b.timeUntilWarning;a.enableSessionTimeoutAutomaticRedirect=
b.enableSessionTimeoutAutomaticRedirect},b=juic.$("sessionTimeoutConfigs");if(b&&((b=b.content)||(b=b["data-content"]),b))try{b=eval("("+b+")")}catch(d){b=null}null!=b?"object"==typeof b&&c(b):this.sessionTimeoutController.getSessionTimeoutConfigs({callback:c})},getSessionInterval:function(){return this._configuredSessionInterval},getSessionTimeoutWarningTime:function(){return this._configuredSessionTimeoutWarning},warning:function(){var a=this;this.beforeSessionExpireId=window.setTimeout(function(){a.beforeSessionExpire()},
this.timeAfterReminder-this.timeBeforeSessionExpire);this.dispatch("sessionWarning")},timedOut:function(){this.dispatch("sessionTimedOut")},beforeSessionExpire:function(){var a=this;this.timeoutId=window.setTimeout(function(){a.timedOut()},this.timeBeforeSessionExpire);this.dispatch("sessionAboutToExpire")},extendSession:function(){this.keepAlive()},keepAlive:function(){this.sessionTimeoutController.keepAlive();this.reset();this.beforeSessionExpireId&&(window.clearTimeout(this.beforeSessionExpireId),
this.beforeSessionExpireId=null);this.timeoutId&&(window.clearTimeout(this.timeoutId),this.timeoutId=null);this.dispatch("sessionExtended")},reset:function(){this.clear();if(this.timeToCallReminder){var a=this;this.warningId=window.setTimeout(function(){a.warning()},this.timeToCallReminder)}},clear:function(){this.warningId&&(window.clearTimeout(this.warningId),this.warningId=null);this.beforeSessionExpireId&&(window.clearTimeout(this.beforeSessionExpireId),this.beforeSessionExpireId=null);this.timeoutId&&
(window.clearTimeout(this.timeoutId),this.timeoutId=null)},cleanup:function(){this.clear()}})}();function SFCountdown(a,c,b){this.register();this._init(a,c,b)}
SFCountdown.prototype=function(){return juic.set(new juic.Component,{_init:function(a,c,b){this._secondsToGo=a;this._startShowingSecondsAt="undefined"!=typeof c?c:60;this._cssClass=b},setSecondsToGo:function(a){this._secondsToGo=a},renderHtml:function(a){a.push('\x3cspan id\x3d"',this.id,'" aria-hidden\x3d"true"\x3e\x3c/span\x3e');a.push('\x3cspan id\x3d"',this.id,'_hidden" class\x3d"hiddenAriaContent" aria-live\x3d"assertive" aria-atomic\x3d"true"\x3e\x3c/span\x3e')},_showCurrentCountdownTime:function(){var a=
this._secondsToGo,c=Math.round(a/60),b,d=!0;0<a&&a<this._startShowingSecondsAt?(b=sfMessageFormat.format(MSGS.COMMON_SESSION_WARNING,this._displayCountdownTime(a),MSGS.COMMON_SESSION_SECONDS),0!=a%10&&(d=!1)):0<a?b=sfMessageFormat.format(MSGS.COMMON_SESSION_WARNING,this._displayCountdownTime(c),59<a&&90>a?MSGS.COMMON_SESSION_MINUTE:MSGS.COMMON_SESSION_MINUTES):(this.clearTimer(),this.dispatch("timerExpired"));if(b&&this._oldVal!=b&&(a=juic.$(this.id)))this._oldVal=a.innerHTML=b;if(d&&(b&&this._oldHiddenVal!=
b)&&(a=juic.$(this.id+"_hidden")))this._oldHiddenVal=a.innerHTML=b},_displayCountdownTime:function(a){return this._cssClass?'\x3cspan class\x3d"'+this._cssClass+'"\x3e'+a+"\x3c/span\x3e":a},startCountdown:function(){var a=this;this._timerId=window.setInterval(function(){a._secondsToGo--;a._showCurrentCountdownTime()},1E3)},cancelCountdown:function(){this.clearTimer();this.dispatch("timerCancelled")},clearTimer:function(){"undefined"!=typeof this._timerId&&(window.clearInterval(this._timerId),delete this._timerId)},
cleanup:function(){this.clearTimer();this.unregister()}})}();
function SFUserActivityListener(){var a=["keypress","click"],c=SFDom.getDocumentRoot();return juic.set(new juic.EventTarget,{startListening:function(){if(!0!==this._listenersAttached){this._listenersAttached=!0;for(var b=a&&a.length,d=0;d<b;d++)SFDOMEvent.addListener(c,a[d],this._handleUserActivity,this)}},stopListening:function(){for(var b=a&&a.length,d=0;d<b;d++)SFDOMEvent.removeListener(c,a[d],this._handleUserActivity);this._listenersAttached=!1},_handleUserActivity:function(a){this.dispatchEvent(new juic.EventTarget.Event("userActivity",
{}))}})};