Util._yui?function(){window.SFCustomEvent=YAHOO.util.CustomEvent}():function(){var a=juic.Logger.getLogger("SFCustomEvent"),b=["type","scope","silent","signature","fireOnce"],c={type:"string",signature:[0,1]};window.SFCustomEvent=function(a,f,g,h,n){juic.set(this,juic.Config.convertArguments(arguments,b,d,c));this.subscribers=[]};juic.set(window.SFCustomEvent,{LIST:0,FLAT:1});var d={scope:window,silent:!0,signature:SFCustomEvent.LIST,fireOnce:!1};juic.extend(SFCustomEvent,Object,{fire:function(){var b=
[].slice.call(arguments,0);if(this.fireOnce){if(this.fired)return!0;this.firedWith=b}this.silent||a.debug(this.type," fired ",b);this.fired=!0;for(var c=0;c<this.subscribers.length;c++)this.notify(this.subscribers[c],b)},subscribe:function(a,b,c){a={fn:a,obj:b,overrideContext:c};this.fireOnce&&this.fired?this.notify(a,this.firedWith):this.subscribers.push(a)},unsubscribe:function(a,b){for(var c=this.subscribers.length-1;0<=c;c--){var d=this.subscribers[c];d.fn===a&&d.obj===b&&this.subscribers.splice(c,
1)}},unsubscribeAll:function(){this.subscribers=[]},notify:function(b,c){var d,h=null,n=!0==b.overrideContext?b.obj:b.overrideContext||this.scope;if(this.signature==SFCustomEvent.FLAT){0<c.length&&(h=c[0]);try{d=b.fn.call(n,h,b.obj)}catch(s){this.lastError=s,a.error(this.type," subscriber exception: ",s)}}else try{d=b.fn.call(n,this.type,c,b.obj)}catch(k){this.lastError=k,a.error(this.type," subscriber exception: ",k)}return d}})}();
"undefined"==typeof SFAnimUtil&&function(){var a=[],b=0,c={easeNone:"linear"};window.SFAnimUtil={animate:function(a,b,f){a="string"==typeof a?juic.$(a):a;var g=f&&f.duration||0.5,h=f&&f.easing||"easeOut",n=f&&f.complete,s=f&&f.context,k=f&&f.tween,p=f&&f.start;f=f&&f.queue;if(Util._yui&&YAHOO.util.Easing){var u={},m;for(m in b){var r=b[m];null!=r.to?u[m]=r:r=u[m]={to:r};isNaN(r.to)&&(r.to=parseInt(r.to));null!=r.from&&isNaN(r.from)&&(r.from=parseInt(r.from))}"string"==typeof h&&(h=YAHOO.util.Easing[h]);
var t=new YAHOO.util.Anim(a,u,g,h);n&&(s?t.onComplete.subscribe(n,s,!0):t.onComplete.subscribe(n));k&&(s?t.onTween.subscribe(k,s,!0):t.onTween.subscribe(k));p&&(s?t.onStart.subscribe(p,s,!0):t.onStart.subscribe(p));var q=new SFCustomEvent({type:"start",fireOnce:!0});t.onStart.subscribe(function(m,a){q.fire.apply(q,a)});var l=new SFCustomEvent({type:"start",fireOnce:!0});t.onComplete.subscribe(function(m,a){l.fire.apply(l,a)});t.animate();return{onStart:q,onComplete:l,onTween:t.onTween,stop:function(m){t.stop(m)}}}jQuery.easing[h]||
(h=c[h]||"swing");var v=jQuery(a),u={};a=null;var q=new SFCustomEvent({type:"start",fireOnce:!0}),x=new SFCustomEvent("tween"),l=new SFCustomEvent({type:"start",fireOnce:!0});for(m in b)r=b[m],null!=r.to?(null!=r.from&&(a=a||{},a[m]=r.from),u[m]=r.to):u[m]=r;a&&v.css(a);var y=(new Date).getTime(),w=0;v.animate(u,{duration:1E3*g,easing:h,queue:!!f,start:function(){q.fire();p&&p.call(s||window)},complete:function(){var m=((new Date).getTime()-y)/1E3,m={duration:m,frames:w,fps:w/m};l.fire(m);n&&n.call(s||
window,m)},step:function(m,a){var b={duration:(new Date).getTime()-y,currentFrame:w++};x.fire(b);k&&k.call(s||window,b)}});return{onStart:q,onComplete:l,onTween:x,stop:function(m,a){!l.fired&&v.stop(a,m)}}},setInterval:function(c){var e;e=b++;var f;f=0==a.length?setInterval(function(){for(var b=0;b<a.length;b++){var c=a[b];try{c.fn.call(window)}catch(d){juic.Logger.error(d)}}},20):a[0].globalID;a.push({globalID:e,intervalId:f,fn:c});return e},clearInterval:function(b){for(var c=0;c<a.length;c++){var f=
a[c];if(f.globalID==b){a.splice(c,1);0==a.length&&clearInterval(f.intervalId);break}}},calculateEasing:function(a,b){if(Util._yui&&YAHOO.util.Easing)return(YAHOO.util.Easing[b]||YAHOO.util.Easing.easeOut)(a,0,1,1);jQuery.easing[b]||(b=c[b]||"swing");return 1.7>parseFloat(jQuery.fn.jquery)||"1.7.1"==jQuery.fn.jQuery||"1.7.0"==jQuery.fn.jQuery?jQuery.easing[b](a,1,0,1):jQuery.easing[b](a)},css3FadeInTransition:function(a,b){if(Util.browserInfo.css3Support){var c=juic.$(a);if(c){var g=b?b:500;Util.addClass(c,
"css3FadeInStart");setTimeout(function(){Util.addClass(c,"css3FadeInEnd")},1);setTimeout(function(){Util.removeClass(c,"css3FadeInStart");Util.removeClass(c,"css3FadeInEnd")},g+1)}}}}}();function SFRegion(a,b,c,d){this.x=d;this.top=this.y=a;this.right=b;this.bottom=c;this.left=d;this.width=this.right-this.left;this.height=this.bottom-this.top;this[0]=d;this[1]=a}
SFRegion.prototype={contains:function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom},getArea:function(){return(this.bottom-this.top)*(this.right-this.left)},move:function(a,b){return new SFRegion(this.top+b,this.right+a,this.bottom+b,this.left+a)},intersect:function(a){var b=Math.max(this.top,a.top),c=Math.min(this.right,a.right),d=Math.min(this.bottom,a.bottom);a=Math.max(this.left,a.left);return d>=b&&c>=a?new SFRegion(b,c,d,a):null},union:function(a){var b=
Math.min(this.top,a.top),c=Math.max(this.right,a.right),d=Math.max(this.bottom,a.bottom);a=Math.min(this.left,a.left);return new SFRegion(b,c,d,a)},equals:function(a){return null!=a&&this.top==a.top&&this.right==a.right&&this.bottom==a.bottom&&this.left==a.left},clone:function(){return new SFRegion(this.top,this.right,this.bottom,this.left)},toString:function(){return"Region {top: "+this.top+", right: "+this.right+", bottom: "+this.bottom+", left: "+this.left+", height: "+this.height+", width: "+
this.width+"}"}};function SFPoint(a,b){SFRegion.call(this,b,a,b,a)}juic.extend(SFPoint,SFRegion,{getDistance:function(a){return a instanceof SFPoint?Math.sqrt(Math.pow(this.x-a.x,2)+Math.pow(this.y-a.y,2)):null},clone:function(){return new SFPoint(this.x,this.y)},toString:function(){return"Point {x: "+this.x+", y: "+this.y+"}"}});
"undefined"==typeof window.SFDom&&function(){function a(m){function a(m,b){return b.toUpperCase()}return s[m]||(s[m]=-1===m.indexOf("-")?m:m.replace(/-([a-z])/gi,a))}function b(m,a){var b=!1;m&&m.tagName&&(a=a||m.ownerDocument,b=SFDom.isAncestor(a.documentElement,m));return b}function c(m,a){var b=parseInt(SFDom.getComputedStyle(m,"borderTopWidth"),10)||0,c=parseInt(SFDom.getComputedStyle(m,"borderLeftWidth"),10)||0;Util.browserInfo.geckoVersion&&/^t(?:able|d|h)$/i.test(m.tagName)&&(c=b=0);a[0]+=
c;a[1]+=b;return a}function d(m){var a;void 0!==m&&(m.exec?a=m:(a=k[m],a||(m=m.replace(/([\.\(\)\^\$\*\+\?\|\[\]\{\}\\])/g,"\\$1"),a=k[m]=RegExp("(?:^|\\s)"+m+"(?\x3d |$)","g"))));return a}function e(m,a){var b=null;if(m){var b=p[a],c=SFDom.getStyle(m,b.dimensionType),d=parseInt(c);if(c&&0>c.indexOf("%")&&!isNaN(d))return d;c=m[b.offsetDimensionType];d=parseInt(SFDom.getStyle(m,"padding-"+b.start));b=parseInt(SFDom.getStyle(m,"padding-"+b.end));b=c-(isNaN(d)?0:d)-(isNaN(b)?0:b)}return b}function f(a,
b,c){for(var d=0,e=a.length;d<e;d++){var k=a[d],g=k.tagName;g&&0<=b.indexOf(","+g+",")&&c.push(k);k=k.childNodes;k.length&&f(k,b,c)}return c}window.SFDom={isElementNode:function(a){return a&&1==a.nodeType},searchDOM:function(a,b){juic.assert("object"==typeof a,"[SFDom] : Dom not available");juic.assert(b,"[String] : elementsToSearch not available");var c=a.childNodes;b=","+b.toUpperCase()+",";return f(c,b,[])},walk:function(a){var b=new juic.Config.convertArguments(arguments,"starter container visitor context backwards checkStart checkHidden".split(" "),
{container:document.body,context:window,backwards:!1,checkStart:!1,checkHidden:!1,walkInside:!0},{visitor:"function",backwards:"boolean",checkStart:"boolean",checkHidden:"boolean"}),c=b.starter,d=b.container,e=b.checkHidden;if(c&&!e)if(this._checkElVisible(d)){if(!this._checkElVisible(c))throw Error("SFDom.walk(): container is visible and starter is not visible.");}else return!1;return this._walk(c,d,b.visitor,b.context,b.backwards,b.checkStart,e,b.walkInside,b.visibleFilter)},_walk:function(a,b,
c,d,e,f,k,g,p){var h=!1;if(a){var n=e?"previousSibling":"nextSibling",u=e?"lastChild":"firstChild";f&&this.isElementNode(a)&&(h=c.call(d,a));if(g&&(k||SFDom.isDisplayedByCssStyle(a)&&(!p||p.call(d,a))))h=h||this._walk(a[u],a,c,d,e,!0,k,!0,p);if(!h&&a!==b){h=a[n];if(!k)for(;h&&(!SFDom.isDisplayedByCssStyle(h)||p&&!p.call(d,h));)h=h[n];h=this._walk(h,a.parentNode,c,d,e,!0,k,!0,p);if(!h){for(a=a.parentNode;a&&a!==b&&!a[n];)a=a.parentNode;a&&a!==b&&(h=this._walk(a[n],b,c,d,e,!0,k,!0,p))}}}return h},_checkElVisible:function(a){if(!a)return!1;
for(;a&&this.isDisplayedByCssStyle(a);)a=a.parentNode;return a?!1:!0},findFocusable:function(a){a=juic.set({},a);return this.walk(juic.set(a,{context:this,visitor:function(b){var c=b&&this.isFocusable(b,a.allowAnchor)?b:!1;c&&("function"==typeof a.filter&&!a.filter.call(a.context,b))&&(c=!1);return c}}))},findNextFocusableElement:function(a,b,c,d){return this.findFocusable({starter:a,container:b,allowAnchor:c,backwards:d})},isFocusable:function(a,b){if(this.isElementNode(a)){switch(a.nodeName){case "INPUT":return!a.disabled&&
"hidden"!=a.type.toLowerCase();case "BUTTON":case "TEXTAREA":case "SELECT":return!a.disabled;case "A":return this._hasTabIndex(a)||!1!==b&&a.href}if(this._hasTabIndex(a))return!0}},_hasTabIndex:function(a){return(a=a.getAttributeNode("tabindex"))&&a.specified?(a=parseInt(a.value,10),!isNaN(a)&&0<=a):!1},setFocus:function(a,b){var c=juic.$(a);if(c)try{if(b){var d=this;setTimeout(function(){d.setFocus(c,!1)},1)}else c.focus&&c.focus()}catch(e){juic.Logger.error("SFDom setFocus():",e)}},isAncestor:function(a,
b){a=juic.$(a);b=juic.$(b);var c=!1;a&&b&&(a.nodeType&&b.nodeType)&&(a.contains&&a!==b?c=a.contains(b):a.compareDocumentPosition&&(c=!!(a.compareDocumentPosition(b)&16)));return c},getParent:function(a){return a.parentNode||a.parentElement},getAncestorByClassName:function(a,b){for(var c=this.getParent(a);!this.hasClass(c,b)&&c!=document.body;)c=this.getParent(c);return c==document.body?null:c},getDocumentHeight:function(){var a=this.getDocumentRoot().scrollHeight;return Math.max(a,this.getViewportHeight())},
getDocumentWidth:function(){var a=this.getDocumentRoot().scrollWidth;return Math.max(a,this.getViewportWidth())},getDocumentRoot:function(){return Util.isSafari()||"BackCompat"==window.document.compatMode?window.document.body:window.document.documentElement},getViewportHeight:function(){var a=self.innerHeight,b=document.compatMode;if(Util.browserInfo.ios&&Util.browserInfo.saf)return a;if(b||Util.browserInfo.ie)a="CSS1Compat"==b?document.documentElement.clientHeight:document.body.clientHeight;return a},
getViewportWidth:function(){var a=self.innerWidth,b=document.compatMode;if(Util.browserInfo.ios&&Util.browserInfo.saf)return a;if(b||Util.browserInfo.ie)a="CSS1Compat"==b?document.documentElement.clientWidth:document.body.clientWidth;return a},getDocumentScrollLeft:function(a){a=a||document;a=Math.max(Math.abs(a.documentElement.scrollLeft),Math.abs(a.body.scrollLeft));Util.isRTL()&&(a=this.getDocumentWidth()-a-this.getViewportWidth());return a},getDocumentScrollTop:function(a){a=a||document;return Math.max(a.documentElement.scrollTop,
a.body.scrollTop)},getRegion:function(a){a=juic.$(a);var b=this.getXY(a);return b?new SFRegion(b[1],b[0]+a.offsetWidth,b[1]+a.offsetHeight,b[0]):!1},getViewportRegion:function(){var a=this.getDocumentScrollTop(),b=this.getViewportHeight(),c=this.getDocumentScrollLeft(),d=this.getViewportWidth();return new SFRegion(a,c+d,a+b,c)},getX:function(a){return this.getXY(a)[0]},getY:function(a){return this.getXY(a)[1]},getXYLegacy:function(a){a=juic.$(a);var d,e,f,k=null,g=a;if("none"!==SFDom.getStyle(a,"display")&&
b(a)){k=[a.offsetLeft,a.offsetTop];d=this.getDocumentScrollLeft(a.ownerDocument);for(e=this.getDocumentScrollTop(a.ownerDocument);g=g.offsetParent;)k[0]+=g.offsetLeft,k[1]+=g.offsetTop,Util.browserInfo.geckoVersion&&(k=c(g,k));if("fixed"!==this.getStyle(a,"position")){for(g=a;(g=g.parentNode)&&g.tagName;)if(a=g.scrollTop,f=g.scrollLeft,Util.browserInfo.geckoVersion&&"visible"!==this.getStyle(g,"overflow")&&(k=c(g,k)),a||f)k[0]-=f,k[1]-=a;k[0]+=d;k[1]+=e}else Util.browserInfo.geckoVersion&&(k[0]+=
d,k[1]+=e);k[0]=Math.floor(k[0]);k[1]=Math.floor(k[1])}return k},getXY:function(a){if(!document.documentElement.getBoundingClientRect)return SFDom.getXYLegacy(a);a=juic.$(a);var c,d,e,f,k,g,p=Math.floor;d=!1;if("none"!==SFDom.getStyle(a,"display")&&b(a)){d=a.getBoundingClientRect();e=a.ownerDocument;a=Util.isRTL()?0-(this.getDocumentWidth()-this.getViewportWidth()-this.getDocumentScrollLeft(e)):this.getDocumentScrollLeft(e);c=this.getDocumentScrollTop(e);d=[p(d.left),p(d.top)];Util.browserInfo.ie&&
8>Util.browserInfo.ieVersion&&(k=f=2,g=e.compatMode,6===parseInt(Util.browserInfo.ieVersion)&&"BackCompat"!==g&&(k=f=0),"BackCompat"===g&&(g=this.getComputedStyle(e.documentElement,"borderLeftWidth"),e=this.getComputedStyle(e.documentElement,"borderTopWidth"),"medium"!==g&&(f=parseInt(g,10)),"medium"!==e&&(k=parseInt(e,10))),d[0]-=f,d[1]-=k);if(c||a)d[0]+=a,d[1]+=c;d[0]=p(d[0]);d[1]=p(d[1])}p=d;a=p[0];null===u&&(u=document.documentElement.clientLeft,e=document,c=document.createElement("div"),e=e.compatMode,
c.getBoundingClientRect&&"BackCompat"===e&&(juic.set(c,{style:{position:"absolute",left:"10px",top:"10px",width:"10px",height:"10px",zIndex:"-1"}}),document.body.appendChild(c),u=c.getBoundingClientRect().left-10,document.body.removeChild(c)));p[0]=a-u;return d},renderStyle:function(a,b){if(b){a.push(' style\x3d"');for(var c in b){var d=b[c];if(""!==d&&null!==d){if("opacity"==c&&Util.browserInfo.ie&&!Util.browserInfo.css3Support)if(b.filter)continue;else c="filter",d="progid:DXImageTransform.Microsoft.Alpha(Opacity\x3d"+
100*d+")";if("transform"==c||"transform-origin"==c){var e="";switch(this.getTransformProperty()){case "WebkitTransform":e="webkit";break;case "msTransform":e="ms";break;case "MozTransform":e="moz";break;case "OTransform":e="o"}c=e?"-"+e+"-"+c:c}a.push(c,":",d,";")}}a.push('"')}},updateStyle:function(a,b){if(b)for(var c in b)this.setStyle(a,c,b[c])},getTransformProperty:function(a){if(!this.__transformProperty)if("string"==typeof a&&(a=juic.$(a)),a){for(var b=["transform","WebkitTransform","msTransform",
"MozTransform","OTransform"],c=0;c<b.length;c++){var d=b[c];if("undefined"!=typeof a.style[d]){this.__transformProperty=d;break}}this.__transformProperty=this.__transformProperty||"transform"}else a=document.createElement("div"),this.getTransformProperty(a);return this.__transformProperty},setStyle:function(){return Util.browserInfo.ie&&10>Util.ieVersion(!0)?function(b,c,d){if(b=juic.$(b)){c=a(c);switch(c){case "opacity":if("string"==typeof b.style.filter&&(b.style.filter="progid:DXImageTransform.Microsoft.Alpha(Opacity\x3d"+
100*d+")",b.style.opacity=d,!b.currentStyle||!b.currentStyle.hasLayout))b.style.zoom=1;return;case "float":c="styleFloat";break;case "transform":if(9>Util.ieVersion(!0))return;c=this.getTransformProperty(b)}b.style[c]=d}}:function(b,c,d){if(b=juic.$(b)){c=a(c);switch(c){case "float":c="cssFloat";break;case "transform":c=this.getTransformProperty(b)}b.style[c]=d}}}(),getComputedStyle:function(b,c){if(window.getComputedStyle)return b.ownerDocument.defaultView?b.ownerDocument.defaultView.getComputedStyle(b,
null)[c]:b.ownerDocument.parentWindow.getComputedStyle(b,null)[c];if(b.currentStyle){c=a(c);var d=b.currentStyle?b.currentStyle[c]:null;return b.style[c]||d}},getComputedWidth:function(a){var b=0;if(a=juic.$(a))b=a.offsetWidth,b+=this.getComputedHorizMargins(a);return b},getComputedHorizMargins:function(a){var b=0;a&&(b+=parseInt(this.getComputedStyle(a,"marginLeft"))||0,b+=parseInt(this.getComputedStyle(a,"marginRight"))||0);return b},getComputedHorizPadding:function(a){var b=0;a&&(b+=parseInt(this.getComputedStyle(a,
"paddingLeft"))||0,b+=parseInt(this.getComputedStyle(a,"paddingRight"))||0);return b},getStyle:function(){if(window.getComputedStyle)return function(b,c){b=juic.$(b);if(this.isElementNode(b)){switch(c){case "float":c="cssFloat";break;case "transform":c=this.getTransformProperty(b);break;default:c=a(c)}var d=b.style[c],e;d||(e=b.ownerDocument.defaultView?b.ownerDocument.defaultView.getComputedStyle(b,null):b.ownerDocument.parentWindow.getComputedStyle(b,null))&&(d=e[c]);return d}return null};if(document.documentElement.currentStyle)return function(b,
c){b=juic.$(b);if(this.isElementNode(b)){var d;switch(c){case "opacity":d=100;try{d=b.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(e){try{d=b.filters("alpha").opacity}catch(f){}}return d/100;case "float":c="styleFloat";break;case "transform":c=this.getTransformProperty(b);break;default:c=a(c)}if((d=b.currentStyle?b.currentStyle[c]:null)&&/^\d+\.?\d*em$/.test(d)){var k=b.style.right;b.style.right=d;d=b.style.pixelRight+"px";b.style.right=k}return b.style[c]||d}return null}}(),hasClass:function(a,
b){var c=!1;if((a=juic.$(a))&&b)c=a.className||"",c=b.exec?b.test(c):b&&-1<(" "+c+" ").indexOf(" "+b+" ");return c},addClass:function(a,b){var c=!1,d;if((a=juic.$(a))&&b)d=a.className||"",this.hasClass(a,b)||(a.className=(d+" "+b).trim(),c=!0);return c},removeClass:function(a,b){var c=!1,e,f;if((a=juic.$(a))&&b)e=a.className||"",a.className=e.replace(d(b),""),f=a.className,e!==f&&(a.className=f.trim(),c=!0);return c},toggleClass:function(a,b){this[this.hasClass(a,b)?"removeClass":"addClass"](a,b)},
replaceClass:function(a,b,c){var e;if((a=juic.$(a))&&c)b?b!==c&&(e=a.className||"",b=(" "+e.replace(d(b)," "+c)).split(d(c)),b.splice(1,0," "+c),a.className=b.join("").trim()):this.addClass(a,c)},toggleAriaAttribute:function(a,b,c){(a=juic.$(a))&&(c?a.setAttribute(b,""):a.setAttribute(b,"true"==a.getAttribute(b)?"false":"true"))},getSuggestedDimension:function(a){var b=null;a&&(b={width:e(a,"x"),height:e(a,"y")});return b},getBorder:function(a,b){var c=p[b||"y"],d=parseInt(this.getStyle(a,"border-"+
c.start+"-width"))||0,c=parseInt(this.getStyle(a,"border-"+c.end+"-width"))||0;return d+c},getPadding:function(a,b){var c=p[b||"y"],d=parseInt(this.getStyle(a,"padding-"+c.start))||0,c=parseInt(this.getStyle(a,"padding-"+c.end))||0;return d+c},getMargin:function(a,b){var c=p[b||"y"],d=parseInt(this.getStyle(a,"margin-"+c.start))||0,c=parseInt(this.getStyle(a,"margin-"+c.end))||0;return d+c},getMarginAndBorder:function(a,b){return this.getMargin(a,b)+this.getBorder(a,b)},getOffsets:function(a,b){return this.getMargin(a,
b)+this.getBorder(a,b)+this.getPadding(a,b)},getMarginToFitDescendant:function(a,b,c){var d=p[c||"y"];return a[d.offsetDimensionType]-b[d.offsetDimensionType]+this.getPadding(b,c)+this.getBorder(b,c)+this.getMargin(a,c)},scrollToWindowTop:function(){window.scrollTo(SFDom.getDocumentScrollLeft(),0)},isDisplayed:function(a){return(0!==a.offsetWidth||0!==a.offsetHeight)&&"none"!=this.getStyle(a,"display")},isDisplayedByCssStyle:function(a){return"none"!=this.getStyle(a,"display")&&"hidden"!=this.getStyle(a,
"visibility")},getStandardFooterHeight:function(){var a=juic.$("page_content"),b=juic.$("footer"),c=0;if(0<=UIVersion.getCurrentInstance().compareTo(UIVersion.V12)&&(a||b))a&&(c+=parseInt(SFDom.getComputedStyle(a,"paddingBottom")||"0",10),c+=parseInt(SFDom.getComputedStyle(a,"borderBottom")||"0",10)),b&&(c+=b.offsetHeight),c+=10;return c},text:function(a){return(a=juic.$(a))&&(a.innerText||a.textContent)||""},getAncestorScale:function(a){a="string"==typeof a?juic.$(a):a;for(var b=this.getScale(a);a&&
(a=a.parentNode);)b*=this.getScale(a);return b},getScale:function(a){var b="string"==typeof a?juic.$(a):a;if(!b)return 1;a=null;Util.browserInfo.ie&&9>Util.ieVersion(!0)?a=b&&b.style&&b.style.zoom:(b=this.getStyle(b,"transform"),"none"!=b&&(a=n.exec(b))&&(a=a[1]));return null!=a?(a=parseFloat(a),isNaN(a)?1:a):1},getLocationOrigin:function(a){a||(a=window.location);var b=a.origin;b||(b=a.protocol+"//"+a.hostname,(a=a.port)&&(b+=":"+a));return b},getElementsByClassName:function(a,b,c,d,e,f){if(Util._yui)return YAHOO.util.Dom.getElementsByClassName(a,
b,c,d,e,f);var k=f?e:window;return jQuery((b?b:"")+"."+a,c).each(function(){d&&d.call(k,this,e)}).toArray()},toggleNonLayerableElementsVisibility:function(a){var b=this.getElementsByClassName("nonLayerable");a=a?"inherit":"hidden";var c,d;for(d=0;d<b.length;d++)c=b[d],c.style.visibility=a},showNonLayerableElements:function(){this.toggleNonLayerableElementsVisibility(!0)},hideNonLayerableElements:function(){this.toggleNonLayerableElementsVisibility(!1)},getElementBy:function(a,b,c){return SFDom.getElementsBy(a,
b,c,null,null,null,!0)},getElementsBy:function(a,b,c,d,e,f,k){if(Util._yui)return YAHOO.util.Dom.getElementsBy(a,b,c,d,e,f,k);var g=f?e:window;b=jQuery(b||"*",c);if(k){var p;k=0;for(c=b.length;!p&&k<c;k++)a.call(g,b[k],e)&&(p=b[k]);p&&d&&d.call(g,p,e);return p}b=b.filter(function(){return a.call(g,this,e)});d&&b.each(function(){d.call(g,this,e)});return b.toArray()},getFirstChild:function(a){return Util._yui?YAHOO.util.Dom.getFirstChild(a):jQuery(a).find("\x3e:first-child")[0]},setScrollLeft:function(a,
b){var c=juic.$(a);if(c){if(c==window||c==document||c==document.body){c=this.getDocumentScrollTop();if(Util.isRTL()){var d;switch(this.getOuterScrollType()){case "default":window.scrollTo(b,c);break;case "negative":d=this.getDocumentWidth()-b-this.getViewportWidth();window.scrollTo(-d,c);break;case "reversed":d=this.getDocumentWidth()-b-this.getViewportWidth(),window.scrollTo(d,c)}}else window.scrollTo(b,c);return b}d=c.scrollWidth-b-c.clientWidth;switch(this.getInnerScrollType()){case "default":c.scrollLeft=
b;break;case "negative":c.scrollLeft=-1*d;break;case "reversed":c.scrollLeft=d}}},setScrollTop:function(a,b){var c=juic.$(a);if(c)if(c==window||c==document||c==document.body)switch(c=this.getDocumentScrollLeft(),this.getOuterScrollType()){case "default":window.scrollTo(c,b);break;case "negative":c=this.getDocumentWidth()-c-this.getViewportWidth();window.scrollTo(-c,b);break;case "reversed":c=this.getDocumentWidth()-c-this.getViewportWidth(),window.scrollTo(c,b)}else c.scrollTop=b},setScrollPosition:function(a,
b,c){this["y"==c?"setScrollTop":"setScrollLeft"](a,b)},getScrollLeft:function(a){if(a=juic.$(a)){if(a==window||a==document||a==document.body)return SFDom.getDocumentScrollLeft();if(Util.isRTL()){var b=a.scrollLeft;switch(this.getInnerScrollType()){case "default":return b;case "negative":case "reversed":return a.scrollWidth-Math.abs(b)-a.clientWidth}}else return a.scrollLeft}},getScrollTop:function(a){if(a=juic.$(a))return a==window||a==document||a==document.body?this.getDocumentScrollTop():a.scrollTop},
getScrollPosition:function(a,b){return this["y"==b?"getScrollTop":"getScrollLeft"](a)},getScrollRegion:function(a){var b=juic.$(a);if(b){a=SFDom.getScrollLeft(b);var c=SFDom.getScrollTop(b),d;b==window||b==document||b==document.body?(d=SFDom.getViewportWidth(),b=SFDom.getViewportHeight()):(d=b.clientWidth,b=b.clientHeight);return new SFRegion(c,a+d,c+b,a)}},getOuterScrollType:function(){if(!h)if(Util.isRTL()){var a=document.createElement("iframe");a.id="test";this.updateStyle(a,{position:"absolute",
right:"-1000em",top:"0",width:"100px",height:"100px"});document.body.appendChild(a);var b=a.contentWindow,c=b.document;c.open();c.write('\x3chtml dir\x3d"rtl"\x3e\x3cbody\x3e\x3cdiv style\x3d"width:200px;height:10px"\x3e\x3c/div\x3e\x3c/body\x3e\x3c/html\x3e');c.close();b.scrollTo(-10,0);h=10==Math.max(Math.abs(c.documentElement.scrollLeft),Math.abs(c.body.scrollLeft))?"negative":"reversed";document.body.removeChild(a)}else h="default";return h},getInnerScrollType:function(){if(!g)if(Util.isRTL()){var a=
document.createElement("div");SFDom.updateStyle(a,{position:"absolute",right:"-1000em",top:"0",width:"100px",height:"100px",overflow:"auto"});a.innerHTML='\x3cdiv style\x3d"width:200px;height:10px"\x3e\x3c/div\x3e';document.body.appendChild(a);0<a.scrollLeft?g="default":(a.scrollLeft=1,g=0===a.scrollLeft?"negative":"reversed");document.body.removeChild(a)}else g="default";return g},getDefaultFontSize:function(a){a=a?a:window.document.body;var b=window.document.createElement("span");b.style.cssText=
"padding:0; line-height:1; position:absolute; visibility:hidden; font-size:1em";b.appendChild(document.createTextNode("W"));a.appendChild(b);var c=[b.offsetWidth,b.offsetHeight];a.removeChild(b);return c},isElementInViewport:function(a){for(var b=SFDom.getXY(a)||[0,0],c=b[0],b=b[1],d=a.offsetWidth,e=a.offsetHeight;a.offsetParent;)a=a.offsetParent,b+=a.offsetTop,c+=a.offsetLeft;a=SFDom.getViewportRegion();return b>=a.y&&c>=a.x&&b+e<=a.y+window.innerHeight&&c+d<=a.x+window.innerWidth}};var g,h,n=/scale\(([^)]*)\)/,
s={},k={},p={x:{dimensionType:"width",offsetDimensionType:"offsetWidth",start:"left",end:"right"},y:{dimensionType:"height",offsetDimensionType:"offsetHeight",start:"top",end:"bottom"}},u=null}();(function(){var a=window.YAHOO&&YAHOO.util&&YAHOO.util.Dom,b=a&&a.getElementsBy;b&&(a.getElementsBy=function(){for(var c=[],d=0;d<arguments.length;d++)c[d]=arguments[d];var e=c[0];"function"==typeof e&&(c[0]=function(){try{return e.apply(this,arguments)}catch(a){}});return b.apply(a,c)})})();
"undefined"==typeof window.SFDOMEvent&&(window.SFDOMEvent=function(){function a(){var a=["HIGHEST","HIGH","MEDIUM","LOW","LOWEST"];h=!0;for(var b=0,c=a.length;b<c;b++){var d=e[a[b]];if(Array.isArray(d)&&0<d.length)for(var f=0,g=d.length;f<g;f++){var q=d[f];try{q.functionHandle.apply(q.scope,q.params||[])}catch(l){if(q.blocking)throw n.error("Function Blocking execution error. ",l),l;n.error("Function failed to execute. ",l)}}}}function b(a,b,c,e){var f=function(c){return("string"==typeof b?a[b]:b).call(a,
c)};f.handler=b;f.elOrId=c;f.event=e;f.contextObj=a;d.push(f);return f}function c(){var a=document.documentElement,b=document.body;return a&&(a.scrollTop||a.scrollLeft)?[a.scrollTop,a.scrollLeft]:b?[b.scrollTop,b.scrollLeft]:[0,0]}var d=[],e={HIGHEST:[],HIGH:[],MEDIUM:[],LOW:[],LOWEST:[]},f={HIGHEST:-1,HIGH:200,MEDIUM:300,LOW:400,LOWEST:500},g=!1,h=!1,n=juic.Logger.getLogger("SFDOMEventException"),s={8:"BACKSPACE",38:"ARROWUP",40:"ARROWDOWN",13:"RETURN",32:"SPACEBAR",9:"TAB",27:"ESCAPE",16:"SHIFT",
17:"CTRL",18:"ALT",20:"CAPS_LOCK",33:"PAGE_UP",34:"PAGE_DOWN",35:"END",36:"HOME",37:"ARROWLEFT",39:"ARROWRIGHT",45:"INSERT",46:"DELETE",91:"LEFT_WIN",92:"RIGHT_WIN",93:"WINDOWS",112:"F1",113:"F2",114:"F3",115:"F4",116:"F5",117:"F6",118:"F7",119:"F8",120:"F9",121:"F10",122:"F11",123:"F12",144:"NUM_LOCK",224:"APPLE_COMMAND"};return juic.set(new juic.EventTarget,{addOnDomReadyListener:function(a,b,c){this.ready(a,b,c,"MEDIUM",!1)},subscribeToOnDomReadyWithPriority:function(a,b,c,d,e){this.ready(b,c,
d,a,e)},ready:function(b){b=juic.Config.convertArguments(arguments,["callback","params","scope","priority","blocking"],{params:[],scope:window,priority:"MEDIUM",blocking:!1},{callback:"function",priority:"string"});juic.assert(Array.isArray(e[b.priority]),"[Prioritized On Dom Ready] Pass a Valid Priority Name.");if(h){var c=function(){b.callback.apply(b.scope,b.params||[])},d=f[b.priority]||f.MEDIUM;0<=d?setTimeout(c,d):c()}else e[b.priority].push({functionHandle:b.callback,params:b.params,scope:b.scope,
blocking:b.blocking});if(!g)if(g=!0,Util._yui)YAHOO.util.Event.onDOMReady(a);else jQuery(document).ready(a)},addEventListener:function(a,b,c,d){window.addEventListener?a.addEventListener(b,c,d):window.attachEvent&&(juic.assert(a==window||a==document,"_addEventListener can only be used with the window or document objects"),a.attachEvent("on"+b,c))},removeEventListener:function(a,b,c,d){window.removeEventListener?a.removeEventListener(b,c,d):a.detachEvent("on"+b,c)},addStopPropagationListener:function(a,
b,c){juic.EventTarget.prototype.addEventListener.call(this,a+"StopPropagation",b,c)},removeStopPropagationListener:function(a,b){juic.EventTarget.prototype.removeEventListener.call(this,a+"StopPropagation",b)},addPreventDefaultListener:function(a,b,c){juic.EventTarget.prototype.addEventListener.call(this,a+"PreventDefault",b,c)},removePreventDefaultListener:function(a,b){juic.EventTarget.prototype.removeEventListener.call(this,a+"PreventDefault",b)},addListener:function(a,c,d,e,f){var g=juic.$(a),
h=d;"undefined"!=typeof e&&(h=b(e,d,a,c));window.addEventListener?g.addEventListener(c,h,f):g.attachEvent("on"+c,h)},removeListener:function(a,b,c,e,f){for(var g=juic.$(a),h=[],l=0;l<d.length;){var n=d[l];n.handler===c&&n.elOrId===a&&n.event===b&&(!e||e===n.contextObj)?h.push(d.splice(l,1)[0]):l++}if(window.removeEventListener){a=0;for(e=h.length;a<e;a++)g.removeEventListener(b,h[a],f);g.removeEventListener(b,c,f)}else if(window.attachEvent){g.detachEvent("on"+b,c);a=0;for(e=h.length;a<e;a++)g.detachEvent("on"+
b,h[a])}},stopPropagation:function(a,b){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;b&&SFDOMEvent.dispatch(a.type+"StopPropagation",{event:a})},preventDefault:function(a,b){a.preventDefault?a.preventDefault():a.returnValue=!1;b&&SFDOMEvent.dispatch(a.type+"PreventDefault",{event:a})},stopEvent:function(a,b){this.stopPropagation(a,b);this.preventDefault(a,b)},getCharCode:function(a){return a.keyCode||a.charCode||0},getKeyName:function(a){a=SFDOMEvent.getCharCode(a);return 48<=a&&57>=a?
"NUMERIC":65<=a&&90>=a?"ALPHA":s[a]||"OTHER"},KEY_CODE:{TAB:9,RETURN:13,SHIFT:16,CTRL:17,ALT:18,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_DOWN:40,PLUS:43,MINUS:45,NUM_0:48,NUM_1:49,NUM_2:50,NUM_3:51,NUM_4:52,NUM_5:53,NUM_6:54,NUM_7:55,NUM_8:56,NUM_9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,
F9:120,F10:121,F11:122,F12:123},KEY_COMMAND_IGNORE:0,KEY_COMMAND_NUMBER:1,KEY_COMMAND_LETTER:2,KEY_COMMAND_INCREMENT:3,KEY_COMMAND_DECREMENT:4,KEY_COMMAND_SPECIAL_KEY:5,KEY_COMMAND_RETURN:6,getKeyCommand:function(a){var b=SFDOMEvent.getCharCode(a);return 38===b?3:13===b?6:40===b?4:48<=b&&57>=b?1:97<=b&&102>=b?2:65<=b&&70>=b?2:-1<"8, 9, 13, 27, 37, 39".indexOf(b)||a.ctrlKey||a.metaKey?5:0},getPageX:function(a){if(0==a.type.indexOf("touch")){if(a.touches&&0<a.touches.length)return a.touches[0].pageX}else{var b=
a.pageX;!b&&0!==b&&(b=a.clientX||0,Util.browserInfo.ie&&(b+=c()[1]));return b}},getPageY:function(a){if(0==a.type.indexOf("touch")){if(a.touches&&0<a.touches.length)return a.touches[0].pageY}else{var b=a.pageY;!b&&0!==b&&(b=a.clientY||0,Util.browserInfo.ie&&(b+=c()[0]))}return b},getXY:function(a){return[this.getPageX(a),this.getPageY(a)]},getTarget:function(a){a=a||window.event;return this.resolveTextNode(a.target||a.srcElement)},getRelatedTarget:function(a){var b=a.relatedTarget;b||("mouseout"==
a.type?b=a.toElement:"mouseover"==a.type&&(b=a.fromElement));return this.resolveTextNode(b)},resolveTextNode:function(a){try{if(a&&3==a.nodeType)return a.parentNode}catch(b){}return a}})}(),function(){var a=new juic.EventTarget,b=!0,c=null,d=null,e=null,f=null,g=null,h=["main-iframe-wrapper","foxclocks-statusbar-iframe"];window.SFBodyEventDispatcher={init:function(){b&&(SFDOMEvent.addOnDomReadyListener(function(){SFBodyEventDispatcher.handleBodyResize(!0);window.setInterval(SFBodyEventDispatcher.handleBodyResize,
1E3)}),b=!1)},addResizeListener:function(b,c){a.addEventListener("bodyResize",b,c);SFBodyEventDispatcher.init()},addResetListener:function(b,c){a.addEventListener("bodyReset",b,c);SFBodyEventDispatcher.init()},removeResizeListener:function(b,c){a.removeEventListener("bodyResize",c)},removeResetListener:function(b,c){a.removeEventListener("bodyReset",c)},handleBodyResize:function(b,s,k){k=k?k:SFDom.getDocumentWidth();var p=SFDom.getDocumentHeight(),u=SFDom.getViewportWidth(),m=SFDom.getViewportHeight(),
r=window.innerWidth,r=r?document.documentElement.clientWidth/r:0,t=!1,q=9==Util.ieVersion()?1:0;if(Util.isChrome())for(var l=0;l<h.length;l++){var v=juic.$(h[l]);v&&(p-=v.offsetHeight)}if(s||Math.abs(c-k)>q||1<Math.abs(d-p)||e!=u||f!=m||g!=r)t=!0,c=k,d=p,e=u,f=m,g=r;t&&a.dispatch("bodyResize",{bodyWidth:k,bodyHeight:p,viewportWidth:u,viewportHeight:m,isFirstPass:b})},handleBodyReset:function(b,c,d){a.dispatch("bodyReset",{resetWidth:c,resetHeight:d});b||window.setTimeout(SFBodyEventDispatcher.handleBodyResize,
1)}}}());function DomUtil(){}DomUtil.ce=function(a,b,c){return Util.ce(a,b,c)};DomUtil.ct=function(a,b){var c=document.createTextNode(a);b&&b.appendChild(c);return c};
DomUtil.tdom=function(a,b){for(var c=0,d={f:"firstChild",l:"lastChild",n:"nextSibling",p:"previousSibling",u:"parentNode"},e={f:"nextSibling",l:"previousSibling",n:"nextSibling",p:"previousSibling"},f=0,g=b.length;f<g;++f){var h=b.charAt(f);if("0"<=h&&"9">=h)c=10*c+1*h;else{do for(a=a[d[h]];a&&3==a.nodeType;)a=a[e[h]];while(0<--c);c=0}}return a};
DomUtil.childNodes=function(a){var b;if(a&&a.hasChildNodes()){a=a.childNodes;b=Array(a.length);for(var c=0,d=0;d<a.length;d++)3!=a[d].nodeType&&(b[c++]=a[d]);b=b.slice(0,c)}return b};DomUtil.DHTML=function(){return document.getElementById||document.all||document.layers};
DomUtil.getObj=function(a){document.getElementById?(this.obj=document.getElementById(a),this.style=document.getElementById(a).style):document.all?(this.obj=document.all[a],this.style=document.all[a].style):document.layers&&(this.obj=document.layers[a],this.style=document.layers[a])};DomUtil.invi=function(a,b,c){DomUtil.DHTML()&&((new DomUtil.getObj(a)).style.display="inline"==c?b?c:"none":"table-row"==c?"Internet Explorer"==browser?b?"block":"none":b?c:"none":b?"block":"none")};
DomUtil.showHideLayers=function(a,b,c){DomUtil.invi(a,1,c);DomUtil.invi(b,0)};DomUtil.toggleClass=function(a,b,c){return Util.toggleClass(a,b,c)};DomUtil.findParent=function(a,b){for(;a.tagName.toUpperCase()!=b;)a=a.parentNode;return a};DomUtil.findIndex=function(a,b){for(var c=DomUtil.childNodes(a),d=0;d<c.length;d++)if(c[d].id==b.id)return d;return-1};
DomUtil.hasClass=function(a,b){if("undefined"==typeof a||null==a||!RegExp)return!1;var c=RegExp("(^|\\s)"+b+"(\\s|$)");return"string"==typeof a?c.test(a):"object"==typeof a&&a.className?c.test(a.className):!1};DomUtil.getParent=function(a){return a.parentNode||a.parentElement};DomUtil.getAncestorByClassName=function(a,b){for(var c=DomUtil.getParent(a);!DomUtil.hasClass(c,b)&&c!=document.body;)c=DomUtil.getParent(c);return c==document.body?null:c};
DomUtil.getAncestorByTagName=function(a,b){for(var c=DomUtil.getParent(a);c.tagName!==b&&c!=document.body;)c=DomUtil.getParent(c);return c==document.body?null:c};DomUtil.createTableRows=function(a,b,c,d,e){a=gebi(a).insertRow(d);d=ce("th",a);e?d.innerHTML=b:ct(b,d);ce("td",a).id=c;return a};
SFDOMEvent.ready(function(){var a=[],b=UIVersion.getCurrentInstance(),c=AccessibilityPrefs.getLowVisionType();c==AccessibilityPrefs.LOWVISION_DARK?a.push("a11y_lowVisionDark"):c==AccessibilityPrefs.LOWVISION_LIGHT&&a.push("a11y_lowVisionLight");AccessibilityPrefs.isKeyboardOnlyNavigationEnabled()&&a.push("globalKeyboardNavigation");Util.browserInfo.ie&&(a.push("ie-only"),c=parseInt(Util.ieVersion(!0)),isNaN(c)||a.push("ie-"+c),a.push("ie-doc-"+document.documentMode),Util.ieCompat()&&a.push("ie-compat"));
Util.browserInfo.ff&&(a.push("ff-only"),a.push("ff-"+parseInt(Util.ffVersion())));Util.browserInfo.saf&&a.push("safari-only");Util.browserInfo.android&&a.push("android-only");Util.browserInfo.ios&&a.push("ios-only");(Util.browserInfo.ios||Util.browserInfo.android)&&a.push("touch-only");Util.browserInfo.css3Support&&a.push("css3");Util.browserInfo.ieQuirks&&(c=parseInt(Util.ieVersion(!0)),a.push("ie-quirks"),a.push("ie-quirks-"+c),8>=c&&Util.isFioriEnabled()&&a.push("ie-quirks-fiori"));b&&b.name&&
a.push("ui-"+b.name);b=(b=window.pageHeaderJsonData)&&b.uiConsistency;if(2016<=b){a.push("uic");for(c=2016;c<=b;c++)a.push("uic"+c)}0<a.length&&Util.addClass(document.body,a.join(" "))});var dateFormatSymbols;
function DateFormatSymbols(){this.shortMonths="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");this.months="January February March April May June July August September October November December".split(" ");this.shortWeekdays="Sun Mon Tue Wed Thu Fri Sat".split(" ");this.weekdays="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");this.ampm=["am","pm"]}var debug=!1;
function DateFormat(a,b){function c(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c}this.pattern=a;this.symbols=b||dateFormatSymbols||new DateFormatSymbols;var d;(function(){var b="",c=a.length,g=!1;d=[];for(var h=0;h<c;++h){var n=a.charAt(h);if("'"==n)0<h&&"'"==a.charAt(h-1)&&(b+="'"),g=!g;else if(!g&&"a"<=n&&"z">=n||"A"<=n&&"Z">=n){for(var s=1;h+s<c&&a.charAt(h+s)==n;)++s;h+=s-1;""!==b&&(d[d.length]={pat:!1,text:b},b="");d[d.length]={pat:!0,type:n,count:s}}else b+=n}""!==b&&(d[d.length]=
{pat:!1,text:b});if(debug){debug.document.write("\x3cpre\x3e");for(h=0;h<d.length;++h)d[h].pat?debug.document.write("pattern: "+d[h].type+","+d[h].count+"\x3cbr\x3e"):debug.document.write("text:    '"+d[h].text+"'\x3cbr\x3e");debug.document.write("\x3c/pre\x3e")}})();this.format=function(a){if(!a)return"";if(!a.getMonth)return a.toString();var b=d.length,g=Array(d.length);debug&&debug.document.write("formatting: "+d.length+"\x3cbr\x3e");for(var h=0;h<b;++h){if(d[h].pat){var n=d[h].count;switch(d[h].type){case "y":g[h]=
4<=n?a.getFullYear().toString():c(a.getFullYear()%100,2);break;case "M":g[h]=2>=n?c(a.getMonth()+1,n):3==n?this.symbols.shortMonths[a.getMonth()]:this.symbols.months[a.getMonth()];break;case "d":g[h]=c(a.getDate(),n);break;case "a":g[h]=this.symbols.ampm[Math.floor(a.getHours()/12)];break;case "H":g[h]=c(a.getHours(),n);break;case "h":var s=a.getHours()%12;0===s&&(s=12);g[h]=c(s,n);break;case "m":g[h]=c(a.getMinutes(),n);break;case "s":g[h]=c(a.getSeconds(),n);break;default:g[h]=""}}else g[h]=d[h].text;
debug&&debug.document.write("text["+h+"] \x3d '"+g[h]+"'\x3cbr\x3e")}return g.join("")};this.parse=function(a){for(var b=d.length,c=0,h=a.length,n=null,s=0,k=0,p=0,u=0,m=0,r=0;r<b;++r){for(;c<h&&" "==a.charAt(c);)++c;if(d[r].pat){var t=d[r].count,q;if(r+1==b)q=a.substr(c),c=h;else if(d[r+1].pat)q=a.substr(c,t),c+=t;else{var l=d[r+1].text.charAt(0);for(q=c++;c<h&&a.charAt(c)!=l&&" "!=a.charAt(c);)++c;q=a.substring(q,c)}l=NaN;/[^0-9]/.test(q)||(l=parseInt(q,10));debug&&debug.document.write("matching pattern "+
d[r].type+","+d[r].count+" against '"+q+"' ("+l+")\x3cbr\x3e");switch(d[r].type){case "y":if(isNaN(l))return null;n=q.length;if(t!==n)return debug&&debug.document.write("year is not ok. number of digits must be "+t+". found "+n+" digits\x3cbr\x3e"),null;2==t&&100>l&&(n=(new Date).getFullYear(),t=n-80,q=n+20,l=100*Math.floor(n/100)+l,l>q&&(l-=100),l<t&&(l+=100),this.minDate&&l<this.minDate.getFullYear()?l+=100:this.maxDate&&l>this.maxDate.getFullYear()&&(l-=100));n=l;break;case "M":if(isNaN(l)){var l=
this.symbols.months,t=this.symbols.shortMonths,v=q.toUpperCase();for(q=0;q<l.length;++q)if(v==l[q].toUpperCase()||v==t[q].toUpperCase()){s=q;break}if(q==l.length)return null}else s=l-1;break;case "d":if(isNaN(l))return null;k=l;break;case "a":v=q.toUpperCase();if(v!=this.symbols.ampm[0].toUpperCase())if(v==this.symbols.ampm[1].toUpperCase())p=12+p;else return null;break;case "H":if(isNaN(l))return null;p=l;break;case "h":if(isNaN(l))return null;12<l&&(l-=12);p=l+p;break;case "m":if(isNaN(l))return null;
u=l;break;case "s":if(isNaN(l))return null;m=l}}else{debug&&debug.document.write("matching: '"+d[r].text+"' against '"+a.substring(c)+"'\x3cbr\x3e");l=d[r].text;for(q=0;q<l.length;++q)if(" "==l.charAt(q)){for(;q+1<l.length&&" "==l.charAt(q+1);)++q;for(;c<h&&" "==a.charAt(c);)++c}else if(l.charAt(q)!=a.charAt(c++))return debug&&debug.document.write("nomatch '"+l.charAt(q)+"' !\x3d '"+a.charAt(c)+"'\x3cbr\x3e"),null}}for(;c<h&&" "==a.charAt(c);)++c;if(c!=h)return null;null==n&&(n=(new Date).getFullYear());
debug&&debug.document.write("new Date("+n+","+s+","+k+","+p+","+u+","+m+")\x3cBR\x3e");a=new Date(n,s,k,p,u,m);a.setFullYear(n);return a.getFullYear()!=n||a.getMonth()!=s||a.getDate()!=k||a.getMinutes()!=u||a.getSeconds()!=m||a.getHours()!=p&&(1!=a.getHours()||0!=p)?null:a}}DateFormat.prototype.toString=function(){return this.pattern};DateFormat.prototype.toLocalString=function(){return this.pattern.toUpperCase()};DateFormat.prototype.toLocalizedString=function(){return this.pattern.toUpperCase()};
function SFSysMsg(a,b,c,d){this.register();this.setMessage(a,b,c,d)}
SFSysMsg.prototype=function(){var a={error:"error",info:"info",confirm:"confirm",alert:"alert"};return juic.set(new juic.Component,{setMessage:function(b,c,d,e){juic.assert(a[b],"[SFSysMsg] Invalid message type. Please pass either: error, info, confirm, or alert");juic.assert(c,"At a minimum, you need to supply the system (bolded) message.");this._msgType=a[b];this._sysMsg=c;this._detailMsg=d?d:"";this._isCloseBtnOn=e;this._ariaRole=this._getAriaRole(this._msgType);if((b=juic.$(this.id+"_msg"))&&
"undefined"!=typeof b)this.setMessageType(this._msgType),this.setSystemMessage(this._sysMsg),this.setDetailMessage(this._detailMsg);switch(this._msgType){case "error":this._iconFontValue="\x26#xe0b1;";this._msgDescription=MSGS.COMMON_Error;break;case "info":this._iconFontValue="\x26#xe202;";this._msgDescription=MSGS.COMMON_Information;break;case "confirm":this._iconFontValue="\x26#xe203;";this._msgDescription=MSGS.COMMON_Confirm;break;case "alert":this._iconFontValue="\x26#xe201;";this._msgDescription=
MSGS.COMMON_ALERT;break;default:this._iconFontValue="\x26#xe202;",this._msgDescription=""}},_getAriaRole:function(a){return"alert"==a||"error"==a?"alert":"status"},setMessageType:function(b){this._msgType=a[b];var c=juic.$(this.id+"_msg");c&&"undefined"!=typeof c&&(c.className="round sysmsg "+this._msgType);c=juic.$(this.id+"_sysMsg");this._ariaRole=this._getAriaRole(b);c&&c.setAttribute("role",this._ariaRole)},setSystemMessage:function(a){this._sysMsg=a;var c=juic.$(this.id+"_sysMsg");c&&"undefined"!=
typeof c&&(c.innerHTML=a)},setDetailMessage:function(a){this._detailMsg=a;var c=juic.$(this.id+"_detailMsg");c&&"undefined"!=typeof c&&(c.innerHTML=a)},getMessageType:function(){return this._msgType},getSystemMessage:function(){return this._sysMsg},getDetailMessage:function(){return this._detailMsg},renderHtml:function(a){var c=UIVersion.getCurrentInstance(),c=c&&0<=c.compareTo(UIVersion.V12);a.push('\x3cdiv id\x3d"'+this.id+'_msg" class\x3d"round sysmsg '+this._msgType+'"\x3e');c||a.push('\x3cspan class\x3d"cnrt"\x3e\x3cspan class\x3d"cnrl"\x3e\x26nbsp;\x3c/span\x3e\x3c/span\x3e');
this._isCloseBtnOn&&a.push('\x3cbutton class\x3d"closeBtn" onclick\x3d"',this.fireCode("_close"),' return false;"',' title\x3d"',MSGS.COMMON_Close,'"\x3e\x3c/button\x3e');a.push("\x3cdl\x3e",'\x3cdd class\x3d"sapIcon ',this._msgType,'"\x3e',this._iconFontValue,"\x3c/dd\x3e",'\x3cdd class\x3d"msg"\x3e\x3cstrong\x3e\x3cspan id\x3d"',this.id,'_sysMsg" aria-live\x3d"polite" class\x3d"important-focus-msg" tabindex\x3d\'',this._sysMsg?" 0":"-1","' role\x3d\"",this._ariaRole,'"\x3e\x3cspan class\x3d"hiddenAriaContent"\x3e',
this._msgDescription,", ",this._sysMsg,"\x3c/span\x3e",this._sysMsg,"\x3c/span\x3e\x3c/strong\x3e",'\x3cdiv id\x3d"',this.id,"_detailMsg\" tabindex\x3d'",this._detailMsg?" 0":"-1","'\x3e",this._detailMsg,"\x3c/div\x3e\x3c/dd\x3e\x3c/dl\x3e");c||a.push('\x3cspan class\x3d"cnrb"\x3e\x3cspan class\x3d"cnrl"\x3e\x26nbsp;\x3c/span\x3e\x3c/span\x3e');a.push("\x3c/div\x3e")},_close:function(){this.dispatch("action",{actionCommand:"hide"})}})}();
function hasXSS(a){return 0<=a.indexOf("\x3cscript")||0<=a.indexOf("\x3ciframe")||0<=a.indexOf("/\x3e")}function isInlineFieldTriggerOnclick(){return Util.isSafari()||Util.isChrome()||Util.browserInfo.moz}function ComponentConsts(){}ComponentConsts.ISO8601DATEFORMAT="yyyy-MM-dd";if("undefined"!=typeof MSGS)var ISO8601Dateformatter=new DateFormat(ComponentConsts.ISO8601DATEFORMAT),dateformatter=new DateFormat(MSGS.COMMON_DateFormat);function EventFilterUtil(){}
EventFilterUtil.catchCR=function(a){if(13==(a.keyCode||a.charCode))return!1};function SFImage(a,b){this.register();this.setValue(a);this._config=b}
SFImage.prototype=function(){return juic.set(new juic.Component,{setValue:function(a){this._value=a},getValue:function(a){return this._value},_handleMouseover:function(){this.dispatch("mouseover")},_handleMouseout:function(){this.dispatch("mouseout")},_handleClick:function(){this.dispatch("click")},renderImage:function(a){juic.assert(""!=this._value,"There is no source to create the image");a.push('\x3cimg src\x3d"'+this._value+'"'+(!this._config||!this._config.disableMouseEventDispatching?' onmouseover\x3d"'+
this.fireCode("_handleMouseover")+'"':"")+(!this._config||!this._config.disableMouseEventDispatching?' onmouseout\x3d"'+this.fireCode("_handleMouseout")+'"':"")+(!this._config||!this._config.disableClickEventDispatching?' onclick\x3d"'+this.fireCode("_handleClick")+'"':"")+(this._config&&this._config.width?" width\x3d'"+this._config.width+"'":"")+(this._config&&this._config.height?" height\x3d'"+this._config.height+"'":"")+(this._config&&void 0!=this._config.border?" border\x3d'"+this._config.border+
"'":"")+(this._config&&this._config.cssClass?" class\x3d'"+this._config.cssClass+"'":"")+(this._config&&this._config.altText?" alt\x3d'"+this._config.altText+"' title\x3d'"+this._config.altText+"'":""));this._config&&this._config.mapName&&a.push(' ismap usemap\x3d"#'+this._config.mapName+'"');a.push(" /\x3e")},renderHtml:function(a){a.push('\x3cdiv id\x3d"'+this.id+'" \x3e');this.renderImage(a);a.push("\x3c/div\x3e")},reRender:function(){var a=[];this.renderImage(a);juic.$(this.id).innerHTML=a.join("")}})}();
function SFLink(a,b){this.register();this._config=b;this._href="javascript:void(0);";this._onClick="click";this._config&&(this._css=this._config.css,this._tabIndex=this._config.tabIndex,this._outerCss=this._config.outerCss,this._maxLength=this._config.maxLength,this._clickParam=this._config.clickParam,this._title=this._config.title,this._iconFontHex=this._config.iconFontHex,this._iconFontSupportClass=this._config.iconFontSupportClass,this._legacyIconFontClass=this._config.legacyIconFontClass,this._config.href?
(juic.assert(null==this._config.onClick,"an Onclick event cannot be assigned to an object with an href."),this._href=this._config.href):this._config.onClick&&(this._onClick=this._config.onClick),this._skipEscaping=this._config.skipEscaping);this._style=!1;this.setValue(a)}
SFLink.prototype=function(){return juic.set(new juic.Component,{setValue:function(a){this._value=a},setCss:function(a){this._css=a},setIconFontHex:function(a){this._iconFontHex=a},setIconFontSupportClass:function(a){this._iconFontSupportClass=a},setLegacyIconFontClass:function(a){this._legacyIconFontClass=a},setTabIndex:function(a){this._tabIndex=a},renderHtml:function(a){a.push('\x3cdiv id\x3d"'+this.id+'"');this._outerCss&&a.push(' class\x3d"'+this._outerCss+'"');a.push("\x3e");this._renderLink(a);
a.push("\x3c/div\x3e")},_renderLink:function(a){a.push("\x3ca");this._href&&a.push(' href\x3d"'+this._href+'"');this._css&&a.push(' class\x3d"'+this._css+'"');this._tabIndex&&a.push(' tabindex\x3d"'+this._tabIndex+'"');this._style&&a.push(' style\x3d"'+this._style+'"');this._onClick&&a.push(' onclick\x3d"'+this.fireCode("_handleClick",this._clickParam?this._clickParam:"")+'return false;"');a.push(' onmouseout\x3d"'+this.fireCode("_handleMouseOut")+'return false;"');a.push(' onmouseover\x3d"'+this.fireCode("_handleMouseOver")+
'return false;"');var b=this._value;this._title?a.push(' title\x3d"'+juic.escapeHTMLIfNeeded(this._title,!this._skipEscaping)+'"'):this._maxLength&&(this._value&&this._value.length>this._maxLength)&&(a.push(' title\x3d"'+juic.escapeHTMLIfNeeded(this._value,!this._skipEscaping)+'"'),b=this._value.truncateByLength(this._maxLength));a.push("\x3e");this._iconFontHex&&a.push('\x3cspan class\x3d"'+this._iconFontSupportClass+'"\x3e\x3cspan class\x3d"'+this._legacyIconFontClass+'"\x3e'+this._iconFontHex+
"\x3c/span\x3e\x3c/span\x3e");a.push(juic.escapeHTMLIfNeeded(b,!this._skipEscaping)+"\x3c/a\x3e")},setStyle:function(a){this._style=a},reRender:function(){var a=[];this._renderLink(a);juic.$(this.id).innerHTML=a.join("")},getContainerElement:function(){return juic.$(this.id)},_handleMouseOut:function(){this.dispatch("mouseout")},_handleMouseOver:function(){this.dispatch("mouseover")},_handleClick:function(){this._onClick&&this.dispatch(this._onClick,{param:this._clickParam?this._clickParam:""})}})}();
function EXPString(a,b){this.register();if(this._config=b)this._dataKey=this._config.dataKey,this._cssClass=this._config.cssClass,this._maxLength=this._config.maxLength;this.setValue(a)}
EXPString.prototype=function(){return juic.set(new juic.Component,{setValue:function(a){_str="";if(this._dataKey)for(var b=0,c=this._dataKey.length;b<c;b++)_str+=!a[this._dataKey[b]]?this._dataKey[b]:a[this._dataKey[b]];this._value=_str},renderHtml:function(a){a.push('\x3cdiv id\x3d"'+this.id+'"');this._cssClass&&a.push(' class\x3d"'+this._cssClass+'"');a.push("\x3e");this._renderString(a);a.push("\x3c/div\x3e")},_renderString:function(a){var b=this._value;this._maxLength&&(b=this._value.truncateByLength(this._maxLength));
a.push(Util.escapeHTML(b))},reRender:function(){var a=[];this._renderString(a);juic.$(this.id).innerHTML=a.join("")}})}();function LabelField(a,b,c){this.register();this.setValue(a,b);c&&(this._config=c,c.link&&(this._link=!0))}
LabelField.prototype=function(){return juic.set(new ComponentLegacy,{setValue:function(a,b){this.value=a;this.displayValue=b?b:a;var c=juic.$(this.id);c&&(c.innerHTML=Util.escapeHTML(this.displayValue))},getValue:function(){return this.value},renderHtml:function(a){if(this._link)a.push('\x3ca id\x3d"'+this.id+'" class\x3d"" target\x3d"new" href\x3d"'+Util.escapeHTML(this.value)+'"\x3e'+Util.escapeHTML(this.displayValue)+"\x3c/a\x3e");else{var b=Util.escapeHTML(this.value),c=Util.escapeHTML(this.displayValue);
a.push('\x3cspan id\x3d"'+this.id+'" class\x3d"" ');this._config&&this._config.mouseoverDisplay&&a.push(' alt\x3d"'+b+'" title\x3d"'+b+'"');a.push("\x3e"+c);Util.browserInfo.ie&&(7>=parseInt(Util.ieVersion())&&this._config&&this._config.renderTailIcon)&&a.push("\x3cspan\x3e\x26nbsp;\x3c/span\x3e");a.push("\x3c/span\x3e")}},setModified:function(a){this._modified=a;if(this.isShowModified()){var b=juic.$(this.id);b&&(this._writable&&(b=b.previousSibling),a?SFDom.addClass(b.id,"unsaved"):SFDom.removeClass(b.id,
"unsaved"))}},isModified:function(){return this._modified},deserializeState:function(a){this.setValue(a.defaultValue,a.value);this.setModified(a.modified)},serializeState:function(){return{value:this.value,modified:this._modified,defaultValue:this.displayValue}}})}();
function IPETextAreaField(a,b){this.register();this.setValue(a);this._readOnlyClass=void 0!=b.readOnlyClass?b.readOnlyClass:"readonly";this._writable=void 0!=b.writable?b.writable:!0;this._rows=b.rows?b.rows:3;this._cols=b.cols?b.cols:40}
IPETextAreaField.prototype=function(){function a(a,c,d){return{undo:function(){a.deserializeState(c)},redo:function(){a.deserializeState(d)}}}return juic.set(new ComponentLegacy,{setValue:function(a){this.value=a;var c=juic.$(this.id);c&&(c.value=Util.escapeHTML(a),this._writable?!a||0==a.trim().length?(c.previousSibling.firstChild.nodeValue="["+MSGS.COMMON_Click_to_edit+"]",SFDom.removeClass(c.previousSibling.id,"editable"),SFDom.addClass(c.previousSibling.id,"empty")):(c.previousSibling.firstChild.nodeValue=
a,SFDom.removeClass(c.previousSibling.id,"empty"),SFDom.addClass(c.previousSibling.id,"editable")):c.value=Util.escapeHTML(this.value))},getValue:function(){return this._writable&&juic.$(this.id)?juic.$(this.id).value:this.value},renderHtml:function(a){var c=this.value;if(!this.value||0==this.value.length)c="["+MSGS.COMMON_Click_to_edit+"]";if(this._writable){var d=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push("\x3ca href\x3d'javascript:void(0)' id\x3d'"+this.id+"_a' "+d+"\x3d'"+this.fireCode("focus")+
"' class\x3d'editable'\x3e"+Util.escapeHTML(c)+"\x3c/a\x3e\x3ctextarea id\x3d'"+this.id+"' rows\x3d'"+this._rows+"' cols\x3d'"+this._cols+"' onblur\x3d'"+this.fireCode("blur")+"' style\x3d'display:none;'\x3e"+Util.escapeHTML(c)+"\x3c/textarea\x3e")}else a.push('\x3cspan id\x3d"'+this.id+'" class\x3d"'+this._readOnlyClass+'"\x3e'+Util.escapeHTML(this.value)+"\x3c/span\x3e")},focus:function(){var a=juic.$(this.id);a.previousSibling.style.display="none";a.style.display="";a.focus();a.select();this.oldValue=
a.value},blur:function(){var b=juic.$(this.id),c=b.previousSibling,d=this.serializeState();b.style.display="none";c.style.display="";this.setValue(b.value);b=b.value;b!=this.oldValue&&(this.isModified()||this.setModified(!0),this.dispatch("change",{oldValue:this.oldValue,newValue:b}),b=this.serializeState(),undoManager.add(a(this,d,b)));delete this.oldValue},setModified:function(a){this._modified=a;if(this.isShowModified()){var c=juic.$(this.id);c&&(this._writable&&(c=c.previousSibling),a?SFDom.addClass(c.id,
"unsaved"):SFDom.removeClass(c.id,"unsaved"))}},isModified:function(){return this._modified},deserializeState:function(a){this.setValue(a.value);this.setModified(a.modified)},serializeState:function(){return{value:this.value,modified:this._modified}}})}();
function IPAutoCompleteFindUser(a,b,c,d,e,f){this.register();a&&this.setValue(a);this._lastErrorMessage;this._labelText=e;this._rendered=!1;b&&(this._writable=b);c&&(this._inputSize=c);d&&(this._maxDisplayed=d);this._userNameHidden=!0;this._usePhoto=!1;this._readOnlyClass="readonly";this._minQueryLength=2;this._recruitEventId=0;f&&(this._userNameHidden=void 0!=f.userNameHidden?f.userNameHidden:!0,this._usePhoto=void 0!=f.usePhoto?f.usePhoto:!1,this._readOnlyClass=void 0!=f.readOnlyClass?f.readOnlyClass:
"readonly",f.required&&(this._required=f.required),""!=a&&f.userDisplayValue&&(this._userDisplayValue=f.userDisplayValue),f.delimChar&&(this._delimChar=f.delimChar),this._clickable=void 0!=f.clickable?f.clickable:!1,this._minQueryLength=void 0!=f.minQueryLength?f.minQueryLength:2,this._recruitEventId=void 0!=f.recruitEventId?f.recruitEventId:0)}
IPAutoCompleteFindUser.prototype=function(){function a(a,b,e){return{undo:function(){a.deserializeState(b)},redo:function(){a.deserializeState(e)}}}function b(a){a&&(a=a.trim(),","==a.substr(a.length-1)&&(a=a.substr(0,a.length-1)));return a}return juic.set(new ComponentLegacy,{_inputType:"text",_writable:!1,_inputSize:20,setValue:function(a){this.value=a;var b=juic.$(this.id+"_hidden");b&&(!a||0==a.trim().length?b.nodeValue="":b.nodeValue=a)},getValue:function(){return this._writable?juic.$(this.id+
"_hidden").value:this.value},setUserDisplayValue:function(a){this._userDisplayValue=a=b(a);var d=juic.$(this.id+"_a"),e=juic.$(this.id);if(d&&e)!a||0==a.trim().length?(d.innerHTML="["+MSGS.COMMON_Click_to_edit+"]",e.value="",SFDom.removeClass(d.id,"editable"),SFDom.addClass(d.id,"empty")):(d.innerHTML=a,e.value=a,SFDom.removeClass(d.id,"empty"),SFDom.addClass(d.id,"editable"));else if(d=juic.$(this.id))d.innerHTML=a?a.trim():""},getUserDisplayValue:function(){return this._userDisplayValue},getHighLightElemId:function(){return this.id},
renderHtml:function(a){var b=this._userDisplayValue;if(!this.value||0==this.value.length)b="["+MSGS.COMMON_Click_to_edit+"]";if(this._writable){var e=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push("\x3ca href\x3d'javascript:void(0)' id\x3d'"+this.id+"_a' "+e+"\x3d'"+this.fireCode("focus")+"' class\x3d'editable'\x3e"+Util.escapeHTML(b)+"\x3c/a\x3e\x3cspan class\x3d'autocompspan' style\x3d'z-index:998;'\x3e \x3cinput type\x3d'text' id\x3d'"+this.id+"' name\x3d'"+this.id+"' class\x3d'autocompinput' style\x3d'z-index:998; display:none'  onkeypress\x3d'return EventFilterUtil.catchCR(event);'  size\x3d'"+
this._inputSize+"' onfocus\x3d '"+this.fireCode("focus")+"' value\x3d'"+Util.escapeHTML(this._userDisplayValue)+"'/\x3e\x3c/span\x3e\x3cinput type\x3d'hidden' value\x3d'"+this.value+"' id\x3d'"+this.id+"_hidden' name\x3d'"+this.id+"_hidden' /\x3e\x3cdiv id\x3d'"+this.id+"_error' style\x3d'display:none; color: rgb(255, 0, 0);'\x3e\x3c/div\x3e");this._rendered=!0}else this._clickable?a.push("\x3ca href\x3d'javascript:void(0)' id\x3d'"+this.id+"' class\x3d'editTransfer' onclick\x3d'"+this.fireCode("startAction")+
"' title\x3d'"+MSGS.EMPLOYEE_FILES_Icon_Tooltip_Edit_Request_Approval+"'\x3e"+Util.escapeHTML(this._userDisplayValue)+"\x3c/a\x3e"):a.push('\x3cspan id\x3d"'+this.id+'" class\x3d"'+this._readOnlyClass+'"\x3e'+Util.escapeHTML(this._userDisplayValue)+"\x3c/span\x3e")},startAction:function(){this.dispatch("action",{actionCommand:"startWorkflow"})},isValid:function(a){if(this._autoCompleteFindUser)if(0>=this._autoCompleteFindUser.unknownNames.length){if(this._required&&(!a||!/[^ \t\r\n]/.test(a)))return this._lastErrorMessage=
sfMessageFormat.format(MSGS.COMMON_ERR_DATA_REQUIRED,this._labelText),!1}else return this._lastErrorMessage=sfMessageFormat.format(MSGS.COMMON_ERR_INVALID_USERID,this._labelText),!1;return!0},getLastValidationError:function(){return this._lastErrorMessage},blur:function(){var c=juic.$(this.id),d=juic.$(this.id+"_error"),e=juic.$(this.id+"_a"),f=juic.$(this.id+"_hidden"),g=this.serializeState();c.style.display="none";e.style.display="";b(c.value)!=g.defaultValue&&(this.isValid(f.value)?d.style.display=
"none":(e.style.display="none",c.style.display="",d.style.display="",d.innerHTML=this.appendErrorIcon(this.getLastValidationError())),this.isModified()||this.setModified(!0),this.setValue(f.value),this.setUserDisplayValue(c.value),c=this.serializeState(),undoManager.add(a(this,g,c)),this.dispatch("change",{oldvalue:g.value,newvalue:f.value}))},focus:function(){if(this._writable){var a=juic.$(this.id);this._rendered&&(this._autoCompleteFindUser=new AutoCompleteFindUser({textElementId:this.id,maxResultsDisplayed:this._maxDisplayed,
minQueryLength:this._minQueryLength,findtype:"fullname",delimChar:this._delimChar?this._delimChar:"",hideUserName:this._userNameHidden?1:0,enablePhoto:this._usePhoto,enableAutoCompFind:!0,selectedUsersElementId:this.id+"_hidden",errMsg:MSGS.COMMON_AUTOCOMP_FINDUSER_ERR,v10:!1,supressAlert:!0,recruitEventId:this._recruitEventId}),this._autoCompleteFindUser.widget.textboxBlurEvent.subscribe(this.blur,this,!0),this._rendered=!1);juic.$(this.id+"_a").style.display="none";a.style.display="";a.focus();
a.select()}},setModified:function(a){this._modified=a;if(this.isShowModified()){var b=juic.$(this.id+"_a");b&&(a?SFDom.addClass(b.id,"unsaved"):SFDom.removeClass(b.id,"unsaved"))}},isModified:function(){return this._modified},deserializeState:function(a){this.setValue(a.value);this.setUserDisplayValue(a.defaultValue);this.setModified(a.modified)},serializeState:function(){return{value:this.value,defaultValue:this._userDisplayValue,modified:this._modified}}})}();
function IPAutoCompleteDataList(a,b,c,d,e,f){this.register();a&&this.setValue(a);this._findType="userTags";this._forceSelection=!1;this._labelText=e;this._rendered=!1;b&&(this._writable=b);c&&(this._inputSize=c);d&&(this._maxDisplayed=d);this._readOnlyClass=void 0!=f.readOnlyClass?f.readOnlyClass:"readonly";f&&(f.validator&&(this._validator=f.validator,this._validatorActions=[]),f.delimChar&&(this._delimChar=f.delimChar),f.required&&this.setRequired(f.required),f.defaultValue&&(this._defaultValue=
f.defaultValue),f.findType&&(this._findType=f.findType),f.forceSelection&&(this._forceSelection=f.forceSelection))}
IPAutoCompleteDataList.prototype=function(){function a(a,c,d){return{undo:function(){a.deserializeState(c)},redo:function(){a.deserializeState(d)}}}return juic.set(new ComponentLegacy,{_inputType:"text",_writable:!1,_inputSize:20,setValue:function(a){a=a.trim();","==a.substr(a.length-1)&&(a=a.substr(0,a.length-1));this.value=a;var c=juic.$(this.id+"_a");if(c)!a||0==a.trim().length?c.innerHTML="":c.innerHTML=a;else if(c=juic.$(this.id))!a||0==a.trim().length?c.innerHTML="":c.innerHTML=a},getValue:function(){return this.value},
getHighLightElemId:function(){return this.id},stopBlur:!1,stopStateFalse:function(){this.stopBlur=!0;juic.$(this.id).blur()},renderHtml:function(a){var c=this.value;if(!this.value||0==this.value.length)c=this._defaultValue;if(this._writable){var d=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push("\x3ca href\x3d'javascript:void(0)' id\x3d'"+this.id+"_a' "+d+"\x3d'"+this.fireCode("focus")+"' class\x3d'editable'\x3e"+Util.escapeHTML(c)+"\x3c/a\x3e\x3cspan class\x3d'autocompspan' style\x3d'z-index:998;'\x3e\x3cinput type\x3d'text' id\x3d'"+
this.id+"' onblur\x3d'"+this.fireCode("blur")+"' onkeyup\x3d'"+this.fireCode("keypress")+"' name\x3d'"+this.id+"' class\x3d'autocompinput' style\x3d'z-index:998; display:none' size\x3d'"+this._inputSize+"' value\x3d'"+Util.escapeHTML(this.value)+"'/\x3e\x3c/span\x3e\x3cdiv id\x3d'"+this.id+"_error' style\x3d'display:none; color: rgb(255, 0, 0);'\x3e\x3c/div\x3e");this._rendered=!0}else a.push('\x3cspan id\x3d"'+this.id+'" class\x3d "'+this._readOnlyClass+'"\x3e'+Util.escapeHTML(this.value)+"\x3c/span\x3e")},
keypress:function(a){juic.$(this.id);var c;window.event?c=a.keyCode:a.which&&(c=a.which);13==c&&this.stopStateFalse()},blur:function(){if(!this.stopBlur)return this.stopStateFalse(),!0;var b=juic.$(this.id),c=juic.$(this.id+"_error"),d=juic.$(this.id+"_a"),e=this.serializeState();d.style.display="";b.style.display="none";b.value!=e.value&&(this.isValid(b.value)?(this.isModified()||this.setModified(!0),this.setValue(b.value),b=this.serializeState(),this.dispatch("change",{oldvalue:e.value,newvalue:b.value}),
b=this.serializeState(),undoManager.add(a(this,e,b)),c.style.display="none"):(c.style.display="",c.innerHTML=this.appendErrorIcon(sfMessageFormat.format(MSGS.COMMON_ERR_DATA_REQUIRED,this._labelText)),d.style.display="none",b.style.display=""));this.stopBlur=!1},focus:function(){if(this._writable){var a=juic.$(this.id);this._rendered&&(this._autoCompleteFindDataList=new AutoCompleteDataList({textElementId:this.id,maxResultsDisplayed:this._maxDisplayed,minQueryLength:2,delimChar:this._delimChar?this._delimChar:
"",findtype:this._findType,enableAutoCompFind:!0,forceSelection:this._forceSelection,v10:!1,errMsg:MSGS.COMMON_AUTOCOMP_FINDTAGS_ERR}),this._rendered=!1);juic.$(this.id+"_a").style.display="none";a.style.display="";a.focus();a.select()}this.stopBlur=!1},setModified:function(a){this._modified=a;if(this.isShowModified()){var c=juic.$(this.id+"_a");c&&(a?SFDom.addClass(c.id,"unsaved"):SFDom.removeClass(c.id,"unsaved"))}},isModified:function(){return this._modified},deserializeState:function(a){this.setValue(a.value);
this.setModified(a.modified)},serializeState:function(){return{value:this.value,modified:this._modified}}})}();function CalendarField(a,b){this.register();this.setValue(a);this._writable=void 0!=b.editable?b.editable:!0;this._min=b.min?b.min:1901;this._max=b.max?b.max:2099;this._readOnlyClass=void 0!=b.readOnlyClass?b.readOnlyClass:"readonly";b.validator&&(this._validator=b.validator,this._validatorActions=[])}
CalendarField.prototype=function(){return juic.set(new ComponentLegacy,{setValue:function(a){a&&0!=a.trim().length?(a=ISO8601Dateformatter.parse(a),this.value=dateformatter.format(a)):this.value=MSGS.COMMON_DateFormatExample;if(a=juic.$(this.id+"_input"))this._writable?(a.value=this.value,a.previousSibling.firstChild.nodeValue=Util.escapeHTML(this.value)):a.innerHTML=Util.escapeHTML(this.value)},unregister:function(){Calendar.hide();juic.Component.prototype.unregister.apply(this,arguments)},getValue:function(){var a;
a=this._writable?juic.$(this.id+"_input")?juic.$(this.id+"_input").value:this.value:this.value;if(a==MSGS.COMMON_DateFormatExample)return"";a=dateformatter.parse(a);var b=null;a&&(b=ISO8601Dateformatter.format(a));return b},showErrorMessage:function(a){juic.$(this.id+"_input");var b="";juic.$(this.id+"_error")&&(b=juic.$(this.id+"_error"),b.innerHTML="");for(var c=0,d=a.length;c<d;c++)b.innerHTML+="\x3cbr /\x3e"+a[c].msg+"\x3cbr /\x3e";b.style.display=""},hideErrorMessage:function(){var a=juic.$(this.id+
"_error");a&&(a.style.display="none")},getHighLightElemId:function(){return this.id+"_input"},renderHtml:function(a){if(this._writable){var b=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push('\x3ca class\x3d"editable" href\x3d"javascript:void(0);" id\x3d"'+this.id+'_a" '+b+'\x3d"'+this.fireCode("focus")+'" title\x3d"'+MSGS.COMMON_Click_to_edit+'"\x3e'+Util.escapeHTML(this.value)+"\x3c/a\x3e");a.push('\x3cinput id\x3d"'+this.id+'_input" name\x3d"'+this.id+'_input" onfocus\x3d"'+this.fireCode("focusCalendar")+
'" onchange\x3d"'+this.fireCode("change")+'" onmouseover\x3d"Calendar.overIpe(this)" size\x3d"12" style\x3d"display: none" type\x3d"text" value\x3d"'+this.value+'"/\x3e\x3cdiv id\x3d"'+this.id+'_error" style\x3d"display:none; color: rgb(255, 0, 0);"\x3e\x3c/div\x3e')}else a.push('\x3cspan id\x3d"'+(this.id+"_input")+'" class\x3d"'+this._readOnlyClass+'"\x3e'+Util.escapeHTML(this.value)+"\x3c/span\x3e")},focusCalendar:function(){var a=this;Calendar.hook(juic.$(this.id+"_input"),MSGS.COMMON_DateFormatExample,
MSGS.COMMON_DateFormat,"ipe",1,this._min,this._max,null,null,this.id+"_a",function(){a.blur()})},focus:function(){if(this._writable){var a=juic.$(this.id+"_input");a.previousSibling.style.display="none";a.style.display="";a.focus();a.select();this.oldValue=a.value}},blur:function(){var a=juic.$(this.id+"_input"),b=a.previousSibling;juic.$(this.id+"_error");a.style.display="none";b.style.display="";a=a.value;a=Util.escapeHTML(a.trim());b.innerHTML=0<a.length?a:MSGS.COMMON_DateFormatExample;this.change()},
change:function(){var a=juic.$(this.id+"_input").value,b=juic.$(this.id+"_error");a!=this.oldValue&&(this.isValid(a)?(this.setModified(!0),this.dispatch("change",{oldValue:this.oldValue,newValue:a}),delete this.oldValue,b.style.display="none"):(b.style.display="",b.innerHTML=this.appendErrorIcon(this._lastErrorMessage)));this.oldValue=a},isValid:function(a){var b=[],c=[];a==MSGS.COMMON_DateFormatExample&&(a="");this._lastErrorMessage=(out=!this._validator||!this._validator.validate(this.id+"_input",
c,b,""==a?a:null))?"":c[0];return out},getLastValidationError:function(){return this._lastErrorMessage},setModified:function(a){this._modified=a;if(this.isShowModified()){var b=juic.$(this.id+"_input");b&&(this._writable&&(b=b.previousSibling),a?SFDom.addClass(b.id,"unsaved"):SFDom.removeClass(b.id,"unsaved"))}},isModified:function(){return this._modified},serializeState:function(){return{value:this.getValue(),modified:this.isModified()}},deserializeState:function(a){this.setValue(a.value);this.setModified(a.modified)},
bindValidators:function(){if(this._validatorActions)for(var a=0;a<this._validatorActions.length;a++){var b=this._validatorActions[a];this._validator.add(b.name,b.id,b.formater,b.required)}},addToValidatorBindings:function(a,b,c,d){this._validator&&this._writable&&(this._validatorActions[this._validatorActions.length]={name:a,id:b,formater:c,required:d})}})}();
function SelectOneMenu(a,b,c){this.register();this._itemOptions=b;this._valueLabelMap=[];this._editable=!0;this.setValue(a);for(var d in c)d&&(this["_"+d]=c[d])}
SelectOneMenu.prototype=function(){function a(a,c,d){return{undo:function(){a.deserializeState(c)},redo:function(){a.deserializeState(d)}}}return juic.set(new ComponentLegacy,{setValue:function(a){this.value=a;if(a=juic.$(this.id)){for(var c=0,d=0;d<this._itemOptions.length;d++)if(this._itemOptions[d].value==this.value){c=d;break}a.selectedIndex=c}},getValue:function(){return juic.$(this.id)?juic.$(this.id).value:this.value},setLabel:function(a){this._label=a},getLabel:function(){return this._label},
getHighLightElemId:function(){return this.id},renderHtml:function(a){var c=this._editable?"":'disabled\x3d"disabled"',d=this._styleClass?this._styleClass:"",e=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push('\x3cselect category\x3d"'+juic.escapeHTML(this.value)+'" id\x3d"'+this.id+'" name\x3d"'+this.id+'" '+c+' class\x3d"'+d+'" style\x3d"'+(this._hidden?'display:none;" ':'" ')+e+"\x3d"+this.fireCode("focus")+" onblur\x3d"+this.fireCode("blur")+" onchange\x3d"+this.fireCode("change")+"\x3e");
for(c=0;c<this._itemOptions.length;c++)d=this._itemOptions[c],e=d.value==this.value?'selected\x3d"selected"':"",a.push('\x3coption value\x3d"'+juic.escapeHTML(d.value)+'" '+e+"\x3e"+juic.escapeHTML(d.displayLabel)+"\x3c/option\x3e"),this._valueLabelMap[d.value]=d.displayLabel,"selected"==e&&this.setLabel(d.displayLabel);a.push("\x3c/select\x3e");a.push("\x3cdiv id\x3d'"+this.id+"_error' style\x3d'display:none; color: rgb(255, 0, 0);'\x3e\x3c/div\x3e")},focus:function(){this.oldValue=juic.$(this.id).value},
blur:function(){var a=juic.$(this.id).value;this.isValid(a)||(a=juic.$(this.id+"_error"),a.style.display="",a.innerHTML=this.appendErrorIcon(this.getLastValidationError(this._labelText)));this.dispatch("blur",{})},change:function(){var b=juic.$(this.id).value,c={value:this.value,modified:this.isModified(),label:this.getLabel()};if(b!=this.oldValue){this.value=b;""!=b?this.setLabel(this._valueLabelMap[b]):this.setLabel("["+MSGS.COMMON_Click_to_edit+"]");this.isModified()||this.setModified(!0);this.dispatch("change",
{oldValue:this.oldValue,newValue:b,newLabel:this.getLabel()});var d=this.serializeState();undoManager.add(a(this,c,d));this.isValid(b)?(b=juic.$(this.id+"_error"),b.style.display="none"):(b=juic.$(this.id+"_error"),b.style.display="",b.innerHTML=this.appendErrorIcon(this.getLastValidationError(this._labelText)))}delete this.oldValue},setModified:function(a){this._modified=a;this.isShowModified()&&this.id&&(a?SFDom.addClass(this.id,"unsaved"):SFDom.removeClass(this.id,"unsaved"))},isModified:function(){return this._modified},
deserializeState:function(a){this.setValue(a.value);this.setModified(a.modified);this.setLabel(a.label)},serializeState:function(){return{value:this.getValue(),modified:this.isModified(),label:this.getLabel()}}})}();function Table(a,b,c,d){this.register();this._msgObj=d;this._metaData=b;this._styleClassObj=c;this._data=[];this.init(a,this._metaData)}
Table.prototype=function(){function a(a,b){for(var c=0;c<a.length;c++)juic.$(a[c]).style.display="";for(c=0;c<b.length;c++)juic.$(b[c]).style.display="none"}function b(a,b,c){return{undo:function(){a.insertRowAt(b,c)},redo:function(){a.removeRowAt(b)}}}function c(a,b,c){return{undo:function(){a.insertRowAt(b)},redo:function(){a.insertRowAt(b,c)}}}function d(a){var b=[];a.renderHtml(b);a=b.join("");b=document.getElementById("DOM_evaluator");b.innerHTML="\x3ctable\x3e\x3ctbody\x3e"+a+"\x3c/tbody\x3e\x3c/table\x3e";
return b.firstChild.tBodies[0].rows[0]}return juic.set(new ComponentLegacy,{init:function(a,b){for(var c=0;c<a.length;c++){var d=new TableRow(a[c],b,c,this);this._data.push(d)}},setValue:function(a){for(var b=0;b<a.length;b++)this._data[b].setValue(a[b])},getValue:function(){for(var a=[],b=0;b<this._data.length;b++)a.push(this._data[b].getValue());return a},unregister:function(){for(var a=0;a<this._data.length;a++)this._data[a].unregister();juic.Component.prototype.unregister.apply(this,arguments)},
addNewRow:function(){for(var a={},b=0;b<this._metaData.length;b++)a[this._metaData[b].name]=this._metaData[b].defValue;a=new TableRow(a,this._metaData,this._data.length+1,this);this._data=[a].concat(this._data);var b=d(a),c=juic.$(this.id+"_data");0==c.rows.length?c.appendChild(b):c.insertBefore(b,c.rows[0]);a.setModified(!0);this.setModified(!0);this.dispatch("change",{});this.dispatch("adjust_size",{})},addFirstRow:function(){a([this.id+"_header",this.id+"_header_2"],[this.id+"_add_new_btn"]);this.addNewRow()},
deleteRow:function(c){for(var d=0;d<this._data.length;d++)if(this._data[d].id==c){var g=this._data[d].getValue();this._data[d].unregister();this._data.splice(d,1);undoManager.add(b(this,d,g));break}juic.$(c).parentNode.removeChild(juic.$(c));0==this._data.length&&a([this.id+"_add_new_btn"],[this.id+"_header",this.id+"_header_2"]);this.setModified(!0);this.dispatch("change",{});this.dispatch("adjust_size",{})},insertRowAt:function(a,b){this._data.splice(a,0,b);var g=juic.$(this.id+"_data");if(g){var h=
d(b);g.insertBefore(h,a<g.rows.length?g.rows[a]:null)}undoManager.add(c(this,a,b))},removeRowAt:function(a){var c=this._data[a].getValue();this._data[a].unregister();this._data.splice(a,1);var d=juic.$(this.id+"_data");d&&d.removeChild(d.rows[a]);undoManager.add(b(this,a,c))},renderHtml:function(a){a.push('\x3c!-- BEGIN Table--\x3e\x3cdiv class\x3d"'+(this._styleClassObj?this._styleClassObj.styleClass:"")+'" id\x3d"'+this.id+'" style\x3d""\x3e\x3cdiv id\x3d"'+this.id+'_add_new" class\x3d"button_row"\x3e\x3cspan class\x3d"aquabtn mid" id\x3d"'+
this.id+'_add_new_btn" style\x3d"'+(0==this._data.length?"":"display:none")+';"\x3e\x3cspan\x3e\x3cbutton class\x3d"icon_add" onclick\x3d"'+this.fireCode("addFirstRow")+'" type\x3d"button"\x3e'+this._msgObj.addNewObject+'\x3c/button\x3e\x3c/span\x3e\x3c/span\x3e\x3c/div\x3e\x3cdiv id\x3d"'+this.id+'_header" style\x3d"'+(0==this._data.length?"display:none":"")+'"\x3e\x3cdiv class\x3d"table_header_rounded_corner"\x3e\x3cspan class\x3d"leftCorner"\x3e\x3c/span\x3e\x3cspan class\x3d"rightCorner"\x3e\x3c/span\x3e\x3c/div\x3e\x3ctable class\x3d"grid" style\x3d"margin-bottom: 0;" id\x3d"'+
this.id+'_header"\x3e\x3cthead\x3e\x3ctr\x3e\x3cth colspan\x3d"'+(this._metaData.length+1)+'" class\x3d"table_header"\x3e\x3cem\x3e'+MSGS.COMMON_Click_below_to_edit+"\x3c/em\x3e"+this._msgObj.title+':\x3csmall class\x3d"table_header_links"\x3e\x3ca id\x3d"'+this.id+'_add_new_row_link"href\x3d"#"onclick\x3d"'+this.fireCode("addNewRow")+'return false;"style\x3d"" title\x3d"'+MSGS.COMMON_Click_to_add_a_new+'"\x3e'+this._msgObj.add+'\x3c/a\x3e\x3c/small\x3e\x3c/th\x3e\x3c/tr\x3e\x3c/thead\x3e\x3ctbody\x3e\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e\x3cdiv id\x3d"'+
this.id+'_header_2" style\x3d"'+(0==this._data.length?"display:none":"")+'"\x3e\x3ctable class\x3d"grid"\x3e\x3cthead\x3e\x3ctr\x3e');for(var b=0;b<this._metaData.length;b++)a.push('\x3cth class\x3d""\x3e'+this._metaData[b].displayName+"\x3c/th\x3e");a.push('\x3cth class\x3d"col_width1 textright"\x3e\x3c/th\x3e\x3c/tr\x3e\x3c/thead\x3e\x3ctbody id\x3d"'+this.id+'_data"\x3e');for(b=0;b<this._data.length;b++)this._data[b].renderHtml(a);a.push("\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e\x3c/div\x3e\x3c!-- END Table --\x3e")},
setModified:function(a){this._modified=a},isModified:function(){return this._modified},setAllModified:function(a){this.setModified(a);for(var b=0;b<this._data.length;b++)this._data[b].setAllModified(a)},handleEvent:function(a){juic.assert("change"==a.type,"Event is not of type 'change' (Table)!");this.dispatch("change",{})}})}();
function TableRow(a,b,c,d){this.register();this._data=a;this._metaData=b;this._rowIndex=c;this._fields=[];this._parent=d;var e;for(a=0;a<this._metaData.length;a++){b=this._metaData[a];c=this._data[b.name];switch(b.type){case "text":e=new IPEField(c,{writable:b.editable,inputType:b.type,inputSize:20});break;case "percent":case "number":e=new IPEField(c,{writable:b.editable,inputType:b.type,inputSize:20,validator:null,inputMaxLength:null,readOnlyClass:null,valueType:"percent"});break;case "textarea":e=
new IPETextAreaField(c,{writable:b.editable,rows:2,cols:10});break;case "date":e=new CalendarField(c,{editable:b.editable,min:1901,max:2099})}e.setShowModified(this._parent.isShowModified());e.addEventListener("change",this._parent);this._fields.push(e)}}
TableRow.prototype=juic.set(new juic.Component,{setValue:function(a){this._data=a;for(a=0;a<this._metaData.length;a++){var b=this._metaData[a],c=this._data[b.name];switch(b.type){case "text":case "textarea":case "percent":case "date":this._fields[a].setValue(c)}}},getValue:function(){for(var a={},b=0;b<this._metaData.length;b++)a[this._metaData[b].name]=this._fields[b].getValue();return a},unregister:function(){for(var a=0;a<this._fields.length;a++)this._fields[a].unregister();juic.Component.prototype.unregister.apply(this,
arguments)},renderHtml:function(a){a.push('\x3ctr id\x3d"'+this.id+'" class\x3d"'+(0==this._rowIndex%2?"a":"b")+'"\x3e');for(var b=0;b<this._fields.length;b++)a.push('\x3ctd class\x3d"editable_cell"\x3e'),this._fields[b].renderHtml(a),a.push("\x3c/td\x3e");a.push('\x3ctd class\x3d"textright"\x3e\x3ca class\x3d"delete_button"href\x3d"#" id\x3d""onclick\x3d"'+this._parent.fireCode("deleteRow",this.id)+'return false;" title\x3d"'+MSGS.COMMON_Remove+'"\x3e\x3c/a\x3e\x3c/td\x3e\x3c/tr\x3e')},setModified:function(a){this._modified=
a;for(var b=0;b<this._fields.length;b++)this._fields[b].setModified(a)},isModified:function(){return this._modified},setAllModified:function(a){this.setModified(a)}});function FindUserField(a,b,c,d){this.register();this._inputSize=b?b:30;this._maxDisplayed=c?c:5;d&&(this._userNameHidden=d.userNameHidden?d.userNameHidden:!0,this._alwaysLoad=void 0==d.alwaysLoad?!1:d.alwaysLoad);this.init(a)}
FindUserField.prototype=function(){return juic.set(new juic.Component,{init:function(a){this.setValue({userId:a,userDisplayValue:""})},setValue:function(a){this._userId=a.userId;this._userDisplayValue=a.userDisplayValue;if(a=juic.$(this.id+"_hidden"))!this._userId||0==this._userId.trim().length?a.value="":a.value=this._userId;if(a=juic.$(this.id+"_input"))!this._userDisplayValue||0==this._userDisplayValue.trim().length?a.value="":a.value=this._userDisplayValue},getValue:function(){return{userId:this._userId,
userDisplayValue:this._userDisplayValue}},setUserDisplayValue:function(a){this._userDisplayValue=a},getUserDisplayValue:function(){return this._userDisplayValue},renderHtml:function(a){a.push("\x3cspan class\x3d'autocompspan' style\x3d'z-index:998;'\x3e\x3cinput type\x3d'text' id\x3d'"+this.id+"_input' name\x3d'"+this.id+"_input' class\x3d'autocompinput' style\x3d'z-index:998' size\x3d'"+this._inputSize+"' onfocus\x3d '"+this.fireCode("focus")+"' value\x3d'"+Util.escapeHTML(this._userDisplayValue)+
"'/\x3e\x3c/span\x3e\x3cinput type\x3d'hidden' value\x3d'"+this._userId+"' id\x3d'"+this.id+"_hidden' name\x3d'"+this.id+"_hidden'/\x3e")},focus:function(){if(!this._autocompleteFindUserCtrl||this._alwaysLoad){var a=this;this._autocompleteFindUserCtrl=new AutoCompleteFindUser({textElementId:this.id+"_input",maxResultsDisplayed:this._maxDisplayed,minQueryLength:2,findtype:"fullname",hideUserName:0,enablePhoto:!1,enableAutoCompFind:!0,selectedUsersElementId:this.id+"_hidden",onItemSelect:function(){var b=
juic.$(a.id+"_input").value,d=juic.$(a.id+"_hidden").value;a.setValue({userId:d,userDisplayValue:b});a.setUserDisplayValue(b);a.dispatch("select_user",{userId:d,displayName:b})},errMsg:MSGS.COMMON_AUTOCOMP_FINDUSER_ERR,v10:!1,supressAlert:!0})}var b=juic.$(this.id+"_input");b.focus();b.select()},deserializeState:function(a){this.setValue(a)},serializeState:function(){return this.getValue()}})}();function SFLoremIpsum(a){this._numLines=a;this._paragraphs=[];this.register();this.init()}
juic.extend(SFLoremIpsum,juic.Component,{init:function(){this._paragraphs.push("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla vulputate dictum pede. Duis viverra aliquam pede. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed tristique venenatis metus. Cras et est. Mauris ultrices. Nulla interdum. Vivamus fermentum, elit nec dictum malesuada, libero nisi fringilla neque, eu fermentum purus dui eu sapien. Ut laoreet arcu eget augue. Curabitur egestas auctor ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam suscipit semper metus. Curabitur bibendum arcu in est.");
this._paragraphs.push("Proin semper, sapien nec lacinia vehicula, massa orci ornare urna, in cursus libero massa in arcu. Aenean rhoncus eleifend mi. Mauris lacus nunc, fringilla ac, bibendum eget, semper vel, metus. Mauris consequat. Praesent elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam tempor tellus. Praesent ullamcorper cursus enim. Ut magna augue, commodo ac, fermentum sed, adipiscing cursus, erat. Nulla quis quam tempus libero sagittis dictum. Quisque dignissim eros non risus.");
this._paragraphs.push("Mauris bibendum dictum arcu. In mollis, dui vitae interdum ultrices, sem sapien aliquet risus, semper pulvinar urna leo sit amet arcu. Mauris non sapien. Aliquam aliquet mi eu urna. Phasellus ac nibh ac magna gravida malesuada. Ut id dolor. Duis vitae lectus a lectus mollis lacinia. Duis id erat et tortor iaculis viverra. Integer porttitor, eros quis tempor vulputate, lectus erat fermentum lorem, sollicitudin faucibus tortor ante at nisl. Maecenas id risus ut nibh pharetra sollicitudin. Nam arcu lorem, tempus et, dictum at, vulputate vel, nunc. Aliquam ante. Integer aliquet, mi sit amet imperdiet rutrum, lectus felis imperdiet est, nec condimentum lorem arcu in nunc. Suspendisse eleifend dignissim nisi. Aliquam gravida. Aliquam nec leo. Suspendisse laoreet. Donec id urna. Quisque aliquam pulvinar ante.");
this._paragraphs.push("Nunc imperdiet, urna vitae tristique mattis, arcu turpis scelerisque orci, non convallis lorem magna sit amet magna. Quisque turpis lacus, aliquet aliquet, gravida ac, varius in, orci. Duis vel sapien ac elit porttitor faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed odio arcu, malesuada non, tristique eu, facilisis malesuada, nisi. Cras hendrerit lorem vitae augue. Nam at magna sed leo suscipit vulputate. Etiam nisl. Aenean pretium pretium sem. Donec nec tortor sed ligula auctor faucibus. Curabitur tincidunt imperdiet eros.");
this._paragraphs.push("Proin mollis. Phasellus hendrerit lacinia sem. Nullam vestibulum rutrum tellus. Etiam in dui. Vestibulum interdum libero ac orci. Cras a nunc. In tellus nibh, lobortis at, sollicitudin at, dapibus eu, lorem. Donec dapibus. Nulla eget ligula. Nullam ante. Suspendisse vitae urna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quis lectus. Etiam ac purus eu nibh dignissim laoreet. Donec aliquet. Sed arcu lorem, lobortis non, euismod eget, consectetuer eu, leo. Nullam gravida nunc a massa. Nulla nisl ligula, faucibus eu, pulvinar id, cursus in, odio. Sed sed tellus. Pellentesque at dui.");
this._paragraphs.push("Morbi tortor mi, feugiat posuere, dapibus sit amet, viverra ut, turpis. Aliquam hendrerit nisi. Sed lacinia elit eget purus. Maecenas varius neque nec ligula. Curabitur quis est. Suspendisse imperdiet. Mauris nec diam sit amet leo ultrices pharetra. Praesent placerat sodales urna. Donec vel augue porta orci lobortis vehicula. Cras egestas diam sit amet purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas leo. Nulla facilisi. Fusce suscipit interdum elit. Vivamus et diam ac urna gravida suscipit.");
this._paragraphs.push("Sed a nisi. Phasellus fringilla nisl ut erat. Duis adipiscing. Aliquam erat volutpat. In euismod ligula non odio. Phasellus fermentum aliquet mauris. Suspendisse gravida magna vel metus. Nullam vel dui vitae nunc vestibulum feugiat. Curabitur consectetuer. Vestibulum a metus. Nullam sed ipsum quis lectus faucibus porttitor.");this._paragraphs.push("Mauris tempor euismod lacus. Integer porttitor hendrerit dolor. Vivamus dapibus. Quisque in dui vitae purus vestibulum sollicitudin. Donec dui. Maecenas in mi. Vivamus vulputate dui eget sem. Cras sit amet nulla vel eros semper vulputate. Donec nec sapien. Ut augue elit, lobortis nec, ullamcorper aliquam, pharetra sed, velit. Aliquam odio quam, ultrices quis, consequat nec, varius et, orci. Integer tellus. In hac habitasse platea dictumst. Nam at dolor. Praesent lacus. Aenean tortor elit, molestie a, pulvinar et, lacinia at, libero. Integer orci elit, tincidunt sed, luctus consequat, ultricies at, velit. Donec bibendum sagittis sem.");
this._paragraphs.push("Integer vel arcu id orci volutpat dignissim. Pellentesque vel dui a libero sodales rhoncus. Vivamus tempus, orci sed ultrices auctor, tellus mi rutrum ante, nec hendrerit neque nunc sit amet eros. Maecenas dapibus tellus ac neque. Nunc quis justo id sem cursus mollis. Sed faucibus metus at leo. Aenean pellentesque, lorem eu luctus dapibus, odio nunc imperdiet est, eu elementum leo diam id enim. Mauris semper magna eu eros. Nulla iaculis eros eu mauris. Etiam varius.");this._paragraphs.push("Nunc rhoncus volutpat ipsum. Suspendisse commodo tellus vitae turpis. Praesent turpis sapien, molestie non, pharetra non, rhoncus at, mi. Vivamus dignissim, orci quis eleifend scelerisque, neque arcu pulvinar leo, ut posuere neque tellus et purus. Pellentesque est. Mauris dolor dolor, egestas non, sagittis id, consequat eu, dolor. Vestibulum ipsum ligula, sagittis eu, suscipit eu, iaculis quis, ipsum. Duis eu sem. In lobortis volutpat nunc. Aenean imperdiet. Mauris sed eros. Cras vulputate, massa a ullamcorper iaculis, leo lectus pharetra lacus, a hendrerit justo odio sit amet risus.")},
renderHtml:function(a){for(var b=0,c=0;c<this._numLines;c++)9<b&&(b=0),a.push("\x3cp\x3e"+juic.escapeHTML(this._paragraphs[b])+"\x3c/p\x3e"),b++},getLines:function(a){for(var b=[],c=0,d=0;d<a;d++)9<c&&(c=0),b.push("\x3cp\x3e"+juic.escapeHTML(this._paragraphs[c])+"\x3c/p\x3e"),c++;return b.join("")}});
function IPEField(a,b){this.register();b&&(this._writable=!1==b.writable?b.writable:!0,this._inputType=b.inputType?b.inputType:"text",this._inputSize=b.inputSize?b.inputSize:20,this._defaultValue=b.defaultValue?b.defaultValue:"",this._inputMaxLength=b.inputMaxLength?b.inputMaxLength:30,this._valueType=b.valueType?b.valueType:"text",this._minHeight=b.minHeight||0,b.validator&&(this._validator=b.validator,this._validatorActions=[]),this._readOnlyClass=void 0!=b.readOnlyClass?b.readOnlyClass:"readonly");
a&&this.setValue(a)}
IPEField.prototype=function(){function a(a,b,e){return{undo:function(){a.deserializeState(b)},redo:function(){a.deserializeState(e)}}}function b(a,b){if(a.isShowModified()){var e=juic.$(a.id);e&&e.id&&(a._writable&&(e=e.previousSibling),b?SFDom.addClass(e.id,"unsaved"):SFDom.removeClass(e.id,"unsaved"))}}return juic.set(new ComponentLegacy,{setValue:function(a){(this._value=a)&&"text"==this._valueType&&0<a.trim().length?this._escapedValue=Util.escapeHTML(this._value).replace(/\n|\r\n?/g,"\x3cbr/\x3e"):
this._escapedValue=this._value;var b=juic.$(this.id);b&&(b.value=a,this._writable?!a||"text"==this._valueType&&0==a.trim().length?(b.previousSibling.innerHTML="["+MSGS.COMMON_Click_to_edit+"]",SFDom.removeClass(b.previousSibling.id,"editable"),SFDom.addClass(b.previousSibling.id,"empty")):(b.previousSibling.innerHTML=this._escapedValue,SFDom.removeClass(b.previousSibling.id,"empty"),SFDom.addClass(b.previousSibling.id,"editable")):b.innerHTML=this._escapedValue)},getValue:function(){if(this._writable&&
juic.$(this.id)){var a=juic.$(this.id).value;a==this._defaultValue&&(a="");return this._valueType&&("percent"==this._valueType||"number"==this._valueType)?Number(a):a}return this._value},renderHtml:function(a){var b=this._escapedValue;if(!this._value||0==this._value.length)b="["+MSGS.COMMON_Click_to_edit+"]";if(this._writable){var e=isInlineFieldTriggerOnclick()?"onclick":"onfocus";a.push("\x3ca href\x3d'javascript:void(0)' id\x3d'"+this.id+"_a' "+e+"\x3d'"+this.fireCode("focus")+"'  class\x3d'editable'\x3e"+
b+"\x3c/a\x3e\x3ctextarea id\x3d'"+this.id+"'");a.push(" onblur\x3d'"+this.fireCode("blur")+"'");a.push(" style\x3d'display:none;");this._minHeight&&a.push("height:",this._minHeight,"px;");a.push("'\x3e");a.push(Util.escapeHTML(this._value)+"\x3c/textarea\x3e\x3cdiv id\x3d'"+this.id+"_error' style\x3d'display:none; color: rgb(255, 0, 0);'\x3e\x3c/div\x3e")}else a.push('\x3cspan id\x3d"'+this.id+'" class\x3d"'+this._readOnlyClass+'"\x3e'+(this._escapedValue?this._escapedValue:"")+"\x3c/span\x3e")},
focus:function(){if(this._writable){var a=juic.$(this.id),b=a.previousSibling,e=b.offsetHeight;this._minHeight&&e<this._minHeight&&(e=this._minHeight);b.style.display="none";a.style.display="";a.style.height=e+"px";a.focus();a.select();this.oldValue=a.value}},blur:function(){var c=juic.$(this.id),d=c.previousSibling,e=this.serializeState(),f=c.nextSibling;c.style.display="none";d.style.display="";c.value=c.value.trim();this.setValue(c.value);var g=c.value;if(g!=this.oldValue){this.isModified()||this.setModified(!0);
this.dispatch("change",{oldvalue:this.oldValue,newvalue:g});var h=this.serializeState();undoManager.add(a(this,e,h));delete this.oldValue}this.isValid(g)?f.style.display="none":(b(this,!0),d.style.display="",c.style.display="none",f.style.display="",f.innerHTML=this.appendErrorIcon(this._lastErrorMessage))},setModified:function(a){this._modified=a;b(this,a)},isModified:function(){return this._modified},deserializeState:function(a){this.setValue(a.value);this.setModified(a.modified);this._defaultValue=
a.defaultValue},serializeState:function(){return{value:this._value,modified:this._modified,defaultValue:this._defaultValue?this._defaultValue:""}},isValid:function(a){if(this._writable){var b=[],e=[];a==this._defaultValue&&(a="");a=a.toString();if(!this._writable||!this._validator||!this._validator.validate(this.id,b,e,a))return!0;this._lastErrorMessage=b[0];return!1}return!0},getLastValidationError:function(){return this._lastErrorMessage},bindValidators:function(){if(this._validatorActions)for(var a=
0;a<this._validatorActions.length;a++){var b=this._validatorActions[a];-1<b.maxLength?this._validator.add(b.name,b.id,b.formater,b.required,{maxLength:b.maxLength}):this._validator.add(b.name,b.id,b.formater,b.required)}},addToValidatorBindings:function(a,b,e,f,g){this._validator&&this._writable&&(this._validatorActions[this._validatorActions.length]={name:a,id:b,formater:e,required:f,maxLength:g})}})}();
window.SFAbstractItemProvider||(window.SFAbstractItemProvider=function(){},function(){function a(a,b){for(var c=0;c<b.length;c++){var g=a[b[c]];if(null!=g)return g}return a.toString()}var b=["label","displayLabel","value"],c=["value","label","displayLabel"];juic.extend(window.SFAbstractItemProvider,juic.EventTarget,{getItems:function(a){juic.assert(!1,"[SFAbstractItemProvider] Must implement getItems")},getLabel:function(c){return"string"==typeof c?c:null!=c?"function"==typeof c.getLabel?c.getLabel():
a(c,b):""},getValue:function(b){return"string"==typeof b?b:null!=b?"function"==typeof b.getValue?b.getValue():a(b,c):""},toItem:function(a){return a},indexOf:function(a,b){return-1}})}());function SFAbstractPositionable(){juic.assert(!1,"[SFAbstractPositionable] Cannot instantiate")}juic.extend(SFAbstractPositionable,juic.Component,{positionFixed:function(a){juic.assert(!1,"[SFAbstractPositionable] Must implement positionFixed")},handleFullScreenResize:function(a,b){}});
function SFArrayItemProvider(a){juic.assert(a instanceof Array,"[SFArrayItemProvider] items must be an array");this._items=a}
(function(){var a={startsWith:function(a,c){return c?0==a.toLowerCase().indexOf(c.toLowerCase()):!0},contains:function(a,c){return c?0<=a.toLowerCase().indexOf(c.toLowerCase()):!0}};juic.extend(SFArrayItemProvider,SFAbstractItemProvider,{getItems:function(a){var c=this._items.length-1;if(0<=c){a=a||{};var c=this._items.length-1,d=null==a.startIndex?0:a.startIndex,c=null==a.endIndex?c:Math.min(a.endIndex,c);if(0<=d&&d<=c){var e=[],f=0;if(this._filterValue||a.filterValue)for(var g=0;g<this._items.length;g++){var h=
this._items[g];this._isItemVisible(h,a)&&(f>=d&&f<=c&&(e[f-d]=h),f++)}else{for(g=d;g<=c;g++)e[g-d]=this._items[g];f=this._items.length}this._itemsAvailable(e,f,a)}else this.dispatch("itemsError",{message:"Invalid (startIndex, endIndex) ("+d+", "+c+")",pagination:a})}else this._itemsAvailable([],0,a)},indexOf:function(a,c){var d=0;if(this._isItemVisible(a,c))for(var e=this.getValue(a),f=0,g=this._items.length;f<g;f++)if(this._isItemVisible(this._items[f],c)){if(e==this.getValue(this._items[f]))return d;
d++}return-1},toItem:function(a){a=this.indexOf(a);return-1<a?this._items[a]:null},setFilterValue:function(a){this._filterValue=a},_itemsAvailable:function(a,c,d){this.dispatch("itemsAvailable",{items:a,itemCount:c,pagination:d})},_isItemVisible:function(b,c){if(c&&c.filterValue){var d=a[c.filterType||"contains"];juic.assert(d,"[SFAbstractItemProvider] Invalid filterType "+c.filterType);return d?d(this.getLabel(b),c.filterValue):!1}return!0}})})();
function SFDelayedItemProvider(a,b){this._delay=b||100;SFArrayItemProvider.call(this,a)}juic.extend(SFDelayedItemProvider,SFArrayItemProvider,{_itemsAvailable:function(a,b,c){var d=this;setTimeout(function(){d.dispatch("itemsAvailable",{items:a,itemCount:b,pagination:c})},this._delay)}});
"undefined"==typeof SFSessionStorage&&function(){function a(a){return(a=/^\_\_sflocalstorage\_\_([^:]+):(.*)$/.exec(a))&&{sessionId:a[1],key:a[2]}}function b(a){return"__sflocalstorage__"+c+":"+a}var c="string"==typeof ajaxSecKey?ajaxSecKey:null,d={},e=window.sessionStorage&&!!sessionStorage.getItem;window.SFSessionStorage={isSupported:function(){return e},getItem:function(a){return e?sessionStorage.getItem(b(a)):d[a]},setItem:function(a,c){e?sessionStorage.setItem(b(a),c):d[a]=""+c},removeItem:function(a){e?
sessionStorage.removeItem(b(a)):delete d[a]},clear:function(){if(e)for(var b in sessionStorage)a(b)&&sessionStorage.removeItem(b);else d={}},cleanup:function(){if(e)for(var b in sessionStorage){var d=a(b);d&&d.sessionId!=c&&sessionStorage.removeItem(b)}},setSessionId:function(a){c=a},getSessionId:function(){return c}};SFSessionStorage.cleanup()}();