window.dwr||(window.dwr={});dwr.engine||(dwr.engine={});window.DWREngine||(window.DWREngine=dwr.engine);window.AjaxServiceFactory||(window.AjaxServiceFactory={});AjaxServiceFactory.rcmDpcsController=rcmDpcsControllerASProxy;function rcmDpcsControllerASProxy(){}
rcmDpcsControllerASProxy.acceptDPCS=function(d,b,a){var c={};"undefined"!=typeof a&&("function"==typeof a?c.callback=a:c=a);c.headers=AjaxService._preCall();"undefined"!=typeof cid&&(c.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","acceptDPCS",d,b,c)};
rcmDpcsControllerASProxy.declineDPCS=function(d,b,a){var c={};"undefined"!=typeof a&&("function"==typeof a?c.callback=a:c=a);c.headers=AjaxService._preCall();"undefined"!=typeof cid&&(c.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","declineDPCS",d,b,c)};
rcmDpcsControllerASProxy.declineDPCSCandidateRegistration=function(d,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","declineDPCSCandidateRegistration",d,a)};
rcmDpcsControllerASProxy.deleteProfileOrRevokeDpcs=function(d,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","deleteProfileOrRevokeDpcs",d,a)};
rcmDpcsControllerASProxy.getDpcs2Config=function(d,b,a){var c={};"undefined"!=typeof a&&("function"==typeof a?c.callback=a:c=a);c.headers=AjaxService._preCall();"undefined"!=typeof cid&&(c.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","getDpcs2Config",d,b,c)};
rcmDpcsControllerASProxy.getDpscStatementByType=function(d,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","getDpscStatementByType",d,a)};
rcmDpcsControllerASProxy.getDpscStatementByTypeAndCountry=function(d,b,a){var c={};"undefined"!=typeof a&&("function"==typeof a?c.callback=a:c=a);c.headers=AjaxService._preCall();"undefined"!=typeof cid&&(c.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","getDpscStatementByTypeAndCountry",d,b,c)};
rcmDpcsControllerASProxy.getExternalCandidateDpcsStatus=function(d,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","getExternalCandidateDpcsStatus",d,a)};
rcmDpcsControllerASProxy.saveExternalCandidateDpcsStatus=function(d,b,a,c,f){var e={};"undefined"!=typeof f&&("function"==typeof f?e.callback=f:e=f);e.headers=AjaxService._preCall();"undefined"!=typeof cid&&(e.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","rcmDpcsControllerProxy","saveExternalCandidateDpcsStatus",d,b,a,c,e)};