function AddReferralDialog(a){assert(a,"AddReferral Dialog needs config object");this._config=a;this.register();this._init()}
AddReferralDialog.prototype=function(){return set(new Component,{_init:function(){this._addReferralContent=new AddReferralContent(this._config);this._addReferralContent.addEventListener("action",this);this.setDialogTitle(this._config.title?this._config.title:MSGS.RECRUITING_ADD_REFERRAL);this.context=this._config.context?this._config.context:"";this._refocusId=this._config.refocusId?this._config.refocusId:""},setDialogTitle:function(a){this._dialogTitle=a},getDialogTitle:function(){return this._dialogTitle},
_createDlg:function(a){var b=[{label:MSGS.COMMON_Cancel,eventName:"closeAddReferralDlg",active:!1},{label:MSGS.COMMON_Send,eventName:"sendButtonClick",active:!0}];a=a.attachmentEnabled?360:220;this._dialog=new SFDialogBox({title:this.getDialogTitle(),content:this._addReferralContent,buttons:b,width:530,innerHeight:a,scrollable:!0,closeDialogOnEsc:!0});this._dialog.addEventListener("action",this);this._dialog.showDialog(!0,this._refocusId);this._dialog.setShowCloseIcon(!1);SFDom.setFocus("infoDivId",
!0)},renderHtml:function(a){a.push("\x3cdiv class\x3d'addReferralDialog' id\x3d'",this.id,"'\x3e");this._renderInner(a);a.push("\x3c/div\x3e")},rerender:function(){if(juic.$(this.id)){var a=[];this._renderInner(a);juic.$(this.id).innerHTML=a.join("")}},_renderInner:function(a){},showDialog:function(a,b){this._dialog.showDialog(a,b);this._dialog.setShowCloseIcon(!1)},_closeDlg:function(){this._dialog.close()},_cleanup:function(){this._addReferralContent.removeEventListener("action",this);this._addReferralContent.cleanup();
this._dialog.removeEventListener("action",this);this.unregister()},_addReferral:function(){this._addReferralContent.addReferral()},handleEvent:function(a){var b=this;if("action"==a.type)switch(a.actionCommand){case "GetAddReferralInfoCompleted":this._loadingIcon=new SFLoading;SFOverlayMgr.showOverlay(this._loadingIcon,!0);setTimeout(function(){SFOverlayMgr.removeOverlay(b._loadingIcon.id);b._createDlg(a.actionData);b._addReferralContent.setFocus()},1100);break;case "closeAddReferralDlg":this._closeDlg();
break;case "addReferralCompleted":this._dialog.disableButtons();var c=this;setTimeout(function(){c._closeDlg()},3E3);"addReferral"==this.context&&window.location.reload();break;case "sendButtonClick":this._addReferral()}}})}();function ReferralContentScrollBox(a,b){this._addReferralContent=a;this._scrollHeight=b}juic.extend(ReferralContentScrollBox,SFScrollBox,{renderHtml:function(a){this._dialogBox=new SFScrollBox(this._addReferralContent,{height:this._scrollHeight,vertical:!1});this._dialogBox.renderHtml(a)}});
function AddReferralContent(a){this.register();this._config=a;this._jobReqId=this._config.jobReqId?this._config.jobReqId:"";this._init()}
AddReferralContent.prototype=function(){return set(new Component,{_init:function(){this._fieldItems={FIRST_NAME:0,LAST_NAME:1,EMAIL:2};this._fieldLabels=[MSGS.RECRUITING_FIRST_NAME,MSGS.RECRUITING_LAST_NAME,MSGS.COMMON_Email];this._fields=[];this._formLayout=new SFInputFormLayout;for(var a=0;a<this._fieldLabels.length;a++)this._fields[a]=new SFTextField("",{size:40,required:!0,title:this._fieldLabels[a]}),this._formLayout.addField(this._fieldLabels[a],this._fields[a],{required:!0});this._statusMsgDivId=
this.id+"_statusMsg";this._validationMesgDivId=this.id+"_validationMsg";this._configCompleted=!1;this._addReferralVO=this._fileUpload=this._countryValue=this._countryPicklist=this._phone=null;this._actionDAO=new AddReferralsDAO;this._actionDAO.addEventListener("action",this);this._actionDAO.getAddReferralInfo()},renderHtml:function(a){a.push("\x3cdiv class\x3d'addReferralContent' id\x3d'",this.id,"'\x3e");this._renderInner(a);a.push("\x3c/div\x3e")},rerender:function(){if(juic.$(this.id)){var a=[];
this._renderInner(a);juic.$(this.id).innerHTML=a.join("")}},_renderInner:function(a){this._configCompleted&&(a.push("\x3cdiv id\x3d'",this._statusMsgDivId,"' style\x3d'display:none;'\x3e\x3c/div\x3e"),a.push("\x3cdiv class\x3d'addReferralHeading'\x3e\x3cspan id\x3d'infoDivId' tabindex\x3d'0'\x3e",MSGS.RECRUITING_PROVIDE_INFO_BELOW,":\x3c/span\x3e\x3c/div\x3e"),a.push("\x3cdiv id\x3d'",this._validationMesgDivId,"' style\x3d'display:none;'\x3e\x3c/div\x3e"),this._formLayout.renderHtml(a),a.push("\x3cdiv class\x3d'referralFileUpload'\x3e"),
this._fileUpload&&this._fileUpload.renderHtml(a),a.push("\x3c/div\x3e"))},_isEmpty:function(a){return null==a||""==a},cleanup:function(){this._actionDAO.removeEventListener("action",this);this._countryPicklist&&this._countryPicklist.removeEventListener("picklistChanged",this);this._fileUpload&&(this._fileUpload.removeEventListener("uploadSucceeded",this),this._fileUpload.removeEventListener("uploadFailed",this));this.unregister()},_handleGetAddReferralInfoCompleted:function(a){this._addReferralVO=
a.actionData;this._addReferralVO.hasPhoneField&&(this._phone=new SFTextField("",{size:40,title:MSGS.RECRUITING_PHONE}),this._formLayout.addField(MSGS.RECRUITING_PHONE,this._phone,{required:this._addReferralVO.phoneFieldRequired}));this._addReferralVO.hasCountryField?(a=this._addReferralVO.countryPicklist,this._picklistMgr=new SFCascadingPicklistsManager,this._picklistConfig={fieldName:a.fieldId,picklistId:a.picklistFieldId,picklistMgr:this._picklistMgr,childPicklistIds:a.childPicklistFieldIds,defaultOptionList:a.selectList,
parentPicklistId:a.parentPicklistFieldId,validationMsg:a.validationMessage,selectedValue:a.stringValue,unsavedClass:"unsaved",toolTipText:MSGS.COMMON_Country},this._countryPicklist=new SFCascadingPicklist(this._picklistConfig),this._countryPicklist.addEventListener("picklistChanged",this),this._countryPicklist.setAriaRequired(!0),this._formLayout.addField(MSGS.COMMON_Country,this._countryPicklist,{required:!0})):SFMessageBox.alert(MSGS.RECRUITING_ERP_MISSING_COUNTRY_PICKLIST,{title:MSGS.COMMON_Err});
!this._addReferralVO.attachmentEnabled&&1==this._addReferralVO.requireResumeOption?SFMessageBox.alert(MSGS.RECRUITING_ERP_REQUIRE_RESUME_CONFIG_ERR,{title:MSGS.COMMON_Err}):this._addReferralVO.attachmentEnabled&&(this._fileUpload=new SFFileUpload("addReferralAttachmentController",1,!1,null,"\x3cdiv tabindex\x3d'0' role\x3d'note'\x3e"+MSGS.RECRUITING_ADD_RESUME+"\x3cbr\x3e"+MSGS.RECRUITING_FILE_UPLOAD_INSTRUCTION_NO_HTML+"\x3c/div\x3e",{multiUploadMode:!1,size:30,required:1==this._addReferralVO.requireResumeOption}),
this._fileUpload.addEventListener("uploadSucceeded",this),this._fileUpload.addEventListener("uploadFailed",this));this._configCompleted=!0;this.rerender()},setFocus:function(){juic.$(this._fields[0].id+"_txtFld").focus()},_checkFields:function(){for(var a=!1,b=[],c=0;c<this._fieldLabels.length;c++)this._isEmpty(this._fields[c].getValue())&&(this._addMissingField(b,this._fieldLabels[c]),a=!0);if(null!=this._phone&&this._addReferralVO.phoneFieldRequired&&(null==this._phone.getValue()||""==this._phone.getValue()))this._addMissingField(b,
MSGS.RECRUITING_PHONE),a=!0;if(null!=this._countryPicklist&&this._addReferralVO.countryPicklist.required&&(null==this._countryValue||""==this._countryValue))this._addMissingField(b,MSGS.COMMON_Country),a=!0;if(1==this._addReferralVO.requireResumeOption){if(null==this._fileUpload)return this._setValidationMsg(MSGS.RECRUITING_ERP_REQUIRE_RESUME_CONFIG_ERR),!1;c=this._fileUpload.getFileName(0);if(null==c||""==c)this._addMissingField(b,MSGS.RECRUITING_Resume),a=!0}return a?(a=b.join(""),a=-1==a.indexOf(",")?
MSGS.COMMON_Required_Field_Err.replace("{0}",a):MSGS.COMMON_Required_Fields_Err.replace("{0}",a),this._setValidationMsg(a),!1):!Util.isValidEmail(this._fields[this._fieldItems.EMAIL].getValue())?(this._setValidationMsg(MSGS.RECRUITING_INVALID_EMAIL),!1):!0},_setErrMsg:function(a){var b=[];a=new SFSysMsg("error",a);a.renderHtml(b);this._setStatsMsg(b);SFDom.setFocus(a.id+"_sysMsg")},_setValidationMsg:function(a){var b=[];a=new SFSysMsg("error",a);a.renderHtml(b);var c=juic.$(this._validationMesgDivId);
c.innerHTML=b.join("");c.style.display="block";SFDom.setFocus(a.id+"_sysMsg")},_clearValidationMsg:function(){var a=juic.$(this._validationMesgDivId);a.innerHTML="";a.style.display="none"},_setStatsMsg:function(a){var b=juic.$(this._statusMsgDivId);b.innerHTML=a.join("");b.style.display="block"},_clearStatusMsg:function(){this._clearValidationMsg();var a=juic.$(this._statusMsgDivId);a.innerHTML="";a.style.display="none"},_setSuccessMsg:function(a){var b=[];a=new SFSysMsg("confirm",a);a.renderHtml(b);
this._setStatsMsg(b);SFDom.setFocus(a.id+"_sysMsg")},_addMissingField:function(a,b){0<a.length&&a.push(", ");a.push(b)},addReferral:function(){this._clearStatusMsg();this._checkFields()&&(this._addReferralVO.attachmentEnabled?this._addReferralWithResume():this._addReferralNoResume())},_addReferralWithResume:function(){var a={attachmentType:"RESUME",firstName:this._fields[this._fieldItems.FIRST_NAME].getValue(),lastName:this._fields[this._fieldItems.LAST_NAME].getValue(),email:this._fields[this._fieldItems.EMAIL].getValue(),
phone:this._getPhoneValue(),country:this._countryValue,jobReqId:this._jobReqId};this._fileUpload.updateUrlParamsObj(a);a=this._fileUpload.getFileName(0);a=null!=a&&""!=a?new SFSimpleLoading(MSGS.COMMON_Uploading_Text,"#666666"):new SFSimpleLoading(MSGS.RECRUITING_ADDING_REFERRAL,"#666666");this._fileUpload.setUploadMsg(a);this._fileUpload.doUpload()},_addReferralNoResume:function(){this._actionDAO.addReferral(this._fields[this._fieldItems.FIRST_NAME].getValue(),this._fields[this._fieldItems.LAST_NAME].getValue(),
this._fields[this._fieldItems.EMAIL].getValue(),this._getPhoneValue(),this._countryValue,this._jobReqId)},_getPhoneValue:function(){return null==this._phone?"":this._phone.getValue()},handleEvent:function(a){switch(a.type){case "picklistChanged":this._countryValue=a.newValue;break;case "uploadSucceeded":this._setSuccessMsg(a.response.message);this.dispatch("action",{actionCommand:"addReferralCompleted"});break;case "uploadFailed":this._setErrMsg(a.response.message);this.dispatch("action",{actionCommand:"addReferralFailed"});
break;case "action":switch(a.actionCommand){case "GetAddReferralInfoCompleted":this.dispatch("action",{actionCommand:"GetAddReferralInfoCompleted",actionData:a.actionData});this._handleGetAddReferralInfoCompleted(a);break;case "GetAddReferralInfoError":a.actionData&&SFMessageBox.alert(a.actionData,{title:MSGS.COMMON_Err});break;case "AddReferralCompleted":a.actionData&&!a.actionData.success&&a.actionData.message?(SFMessageBox.alert(a.actionData.message,{title:MSGS.COMMON_Err}),this.dispatch("action",
{actionCommand:"closeAddReferralDlg"})):this.dispatch("action",{actionCommand:"addReferralCompleted"});break;case "AddReferralError":a.actionData&&SFMessageBox.alert(a.actionData,{title:MSGS.COMMON_Err}),this.dispatch("action",{actionCommand:"closeAddReferralDlg"})}}}})}();function AddReferralsDAO(){this._init()}
AddReferralsDAO.prototype=function(){return set(new EventTarget,{_init:function(){this._employeeReferralsController=AjaxService.getMBeanInstance("employeeReferralsController")},getAddReferralInfo:function(){try{var a={model:this,callback:function(b){a.model.dispatch("action",{actionCommand:"GetAddReferralInfoCompleted",actionData:b})},errorHandler:function(b,d){a.model.dispatch("action",{actionCommand:"GetAddReferralInfoError",actionData:MSGS.RECRUITING_GET_ADD_REFERRAL_INFO_ERROR+"\nAJAX errorString\x3d"+
b+", exception.javaClassName\x3d"+d.javaClassName+", exception.message\x3d"+d.message})}};this._employeeReferralsController.getAddReferralInfo(a)}catch(b){this.dispatch("action",{actionCommand:"GetAddReferralInfoError",actionData:MSGS.RECRUITING_GET_ADD_REFERRAL_INFO_ERROR+"\x3cbr /\x3eJavaScript Exception\x3d"+b})}},addReferral:function(a,b,c,d,f,g){try{var e={model:this,callback:function(a){e.model.dispatch("action",{actionCommand:"AddReferralCompleted",actionData:a})},errorHandler:function(a,b){e.model.dispatch("action",
{actionCommand:"AddReferralError",actionData:MSGS.RECRUITING_ADD_REFERRAL_FAILED+"\nAJAX errorString\x3d"+a+", exception.javaClassName\x3d"+b.javaClassName+", exception.message\x3d"+b.message})}};this._employeeReferralsController.addReferral(a,b,c,d,f,g,e)}catch(h){this.dispatch("action",{actionCommand:"AddReferralError",actionData:MSGS.RECRUITING_ADD_REFERRAL_FAILED+"\x3cbr /\x3eJavaScript Exception\x3d"+h})}}})}();