function DPCSAckStatementPage(a,b){this.register();this._init(a,b)}
extend(DPCSAckStatementPage,Component,{renderHtml:function(a){a.push("\x3ch3\x3e",MSGS.COMMON_DPCS2_ACK_STMT,"\x3c/h3\x3e");a.push("\x3cp\x3e",MSGS.COMMON_DPCS2_Action_decline_accept,"\x3c/p\x3e");a.push("\x3cdiv\x3e");this.userInput.renderHtml(a);a.push('\x3cdiv style\x3d"margin:10px 0"\x3e');a.push('\x3cbutton type\x3d"button" onclick\x3d"',this.fireCode("_search"),'"\x3e',MSGS.COMMON_Search,"\x3c/button\x3e");a.push("\x3c/div\x3e");a.push("\x3c/div\x3e");a.push('\x3cdiv id\x3d"',this.id,'_result"\x3e');
a.push("\x3c/div\x3e")},_init:function(a){this._model=a;this._config=config;this._initComponents();this._initEventListeners();this._postInit()},_initComponents:function(){this._loadingBox=new SFLoading;this._viewStatementDlg=new ViewStatementDlg;this.button=new SFCommandButton(MSGS.COMMON_Search);this.userInput=new DpcsSearchUsers(this._config);var a=[{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_DPCS2_LBL_STMT+"\x3c/div\x3e"},{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_Type+"\x3c/div\x3e"},
{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_DPCS2_Publish_Date+"\x3c/div\x3e"},{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_DPCS2_Publish_By+"\x3c/div\x3e"},{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_Status+"\x3c/div\x3e"},{label:"\x3cdiv class\x3d'alignleft'\x3e"+MSGS.COMMON_Action+"\x3c/div\x3e"}];this._grid=new SFSimpleDataGridLayout;this._grid.setNbCol(6);this._grid.setAlternateRows(["gray","white"]);this._grid.setColumnDefinitions([{width:"25%"},{width:"10%"},{width:"15%"},
{width:"15%"},{width:"10%"},{width:"25%"}]);this._grid.setHeaders(a)},_initEventListeners:function(){this._model.addEventListener("ackStatementModelUpdated",this);this._model.addEventListener("updateAckStatementDone",this);this._model.addEventListener("statementReady",this);this._model.addEventListener("failedOperation",this);this.button.addEventListener("action",this)},_postInit:function(){this._loadingBox.setMsg(MSGS.COMMON_loading);this.button.setActionCommand("search")},_renderResult:function(){var a=
[];this._grid.renderHtml(a);$(this.id+"_result").innerHTML=a.join("")},_search:function(){this.userInput.getValue()?(SFOverlayMgr.showOverlay(this._loadingBox,!0),this._model.dispatch("retrieveAckStatement",{userInfo:this.userInput.getValue(),searchType:this.userInput.searchType.getValue()})):alert(MSGS.COMMON_DPCS2_WARN_MSG_INPUT_NAME)},_populateGrid:function(){this._grid.resetRows();for(var a=this._model.getStatementList(),b=0;b<a.length;b++){var c=a[b],e,d,f,g,h;e=new SFSpan(c.dpcsName+" ("+c.versionNum+
")");d=new SFSpan(c.type);f=new SFSpan(c.lastModified);g=new SFSpan(c.createdBy);h=new SFSpan(dpcsUtil.mapStatus(c.status));c=this._getAction(c.status,c.dpcsId,c.dpcsVersionId,c.dpcsOrdinal);this._grid.appendRow([e,d,f,g,h,c])}},_getAction:function(a,b,c,e){var d=[];d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_getStatement",c),'"\x3e',MSGS.COMMON_DPCS2_LBL_View_Stmt,"\x3c/a\x3e");a===dpcsUtil.DECLINE?this._isRecruitingDpcs(e)||d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_updateStatus",
b,dpcsUtil.ACCEPT),'"\x3e',MSGS.COMMON_DPCS2_ACCEPT,"\x3c/a\x3e"):a===dpcsUtil.ACCEPT?this._isRecruitingDpcs(e)?d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_openDeclineConfirmDlg",b),'"\x3e',MSGS.COMMON_DPCS2_Decline,"\x3c/a\x3e"):d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_updateStatus",b,dpcsUtil.DECLINE),'"\x3e',MSGS.COMMON_DPCS2_Decline,"\x3c/a\x3e"):this._isRecruitingDpcs(e)?d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_openDeclineConfirmDlg",b),'"\x3e',MSGS.COMMON_DPCS2_Decline,
"\x3c/a\x3e"):(d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_updateStatus",b,dpcsUtil.DECLINE),'"\x3e',MSGS.COMMON_DPCS2_Decline,"\x3c/a\x3e"),d.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_updateStatus",b,dpcsUtil.ACCEPT),'"\x3e',MSGS.COMMON_DPCS2_ACCEPT,"\x3c/a\x3e"));return new ActionWrapper(d.join(""))},_openDlg:function(a,b){this._viewStatementDlg.show(a,b)},_isRecruitingDpcs:function(a){return a==dpcsUtil.RECRUITING_INTERNAL||a==dpcsUtil.RECRUITING_EXTERNAL||a==dpcsUtil.RECRUITING_INTRANET?
!0:!1},_openDeclineConfirmDlg:function(a){var b=new DeclineConfirmDlg(MSGS.COMMON_DPCS2_WARN_MSG_DECLINE_STATEMENT);b.dpcsId=a;b.addEventListener("decline",this);b.show()},_updateStatus:function(a,b){SFOverlayMgr.showOverlay(this._loadingBox,!0);this._model.dispatch("updateAckStatement",{userInfo:this.userInput.getValue(),searchType:this.userInput.searchType.getValue(),dpcsId:a,status:b})},_getStatement:function(a){SFOverlayMgr.showOverlay(this._loadingBox,!0);this._model.dispatch("viewStatement",
{dpcsVersionId:a})},handleEvent:function(a){switch(a.type){case "failedOperation":this._loadingBox.hide();break;case "ackStatementModelUpdated":this._loadingBox.hide();this._populateGrid();this._renderResult();break;case "statementReady":this._loadingBox.hide();this._openDlg(a.data.title,a.data.content);break;case "updateAckStatementDone":this._loadingBox.hide();this._search();break;case "decline":this._updateStatus(a.dpcsId,dpcsUtil.DECLINE)}}});
function ActionWrapper(a){this.register();this._html=a}extend(ActionWrapper,Component,{renderHtml:function(a){a.push('\x3cdiv class\x3d"action_list"\x3e');a.push(this._html);a.push("\x3c/div\x3e")}});