window.dwr||(window.dwr={});dwr.engine||(dwr.engine={});window.DWREngine||(window.DWREngine=dwr.engine);window.AjaxServiceFactory||(window.AjaxServiceFactory={});AjaxServiceFactory.dpcsUserStatusController=dpcsUserStatusControllerASProxy;function dpcsUserStatusControllerASProxy(){}
dpcsUserStatusControllerASProxy.getDpscStatement=function(c,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getDpscStatement",c,a)};
dpcsUserStatusControllerASProxy.getDpscStatementByType=function(c,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getDpscStatementByType",c,a)};
dpcsUserStatusControllerASProxy.getDpscStatementByTypeAndCountry=function(c,b,a){var e={};"undefined"!=typeof a&&("function"==typeof a?e.callback=a:e=a);e.headers=AjaxService._preCall();"undefined"!=typeof cid&&(e.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getDpscStatementByTypeAndCountry",c,b,e)};
dpcsUserStatusControllerASProxy.getDpscStatementByTypes=function(c,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getDpscStatementByTypes",c,a)};
dpcsUserStatusControllerASProxy.getExternalCandidateDpcsStatus=function(c,b,a,e){var d={};"undefined"!=typeof e&&("function"==typeof e?d.callback=e:d=e);d.headers=AjaxService._preCall();"undefined"!=typeof cid&&(d.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getExternalCandidateDpcsStatus",c,b,a,d)};
dpcsUserStatusControllerASProxy.getInternalUserDpcsStatus=function(c,b){var a={};"undefined"!=typeof b&&("function"==typeof b?a.callback=b:a=b);a.headers=AjaxService._preCall();"undefined"!=typeof cid&&(a.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getInternalUserDpcsStatus",c,a)};
dpcsUserStatusControllerASProxy.getInternalUserDpcsStatusWithLoginUser=function(c){var b={};"undefined"!=typeof c&&("function"==typeof c?b.callback=c:b=c);b.headers=AjaxService._preCall();"undefined"!=typeof cid&&(b.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","getInternalUserDpcsStatusWithLoginUser",b)};
dpcsUserStatusControllerASProxy.saveExternalCandidateDpcsStatus=function(c,b,a,e,d){var f={};"undefined"!=typeof d&&("function"==typeof d?f.callback=d:f=d);f.headers=AjaxService._preCall();"undefined"!=typeof cid&&(f.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","saveExternalCandidateDpcsStatus",c,b,a,e,f)};
dpcsUserStatusControllerASProxy.saveInternalUserDpcsStatus=function(c,b,a,e,d){var f={};"undefined"!=typeof d&&("function"==typeof d?f.callback=d:f=d);f.headers=AjaxService._preCall();"undefined"!=typeof cid&&(f.headers.cid=cid);dwr.engine._execute("/xi/ajax/remoting","dpcsUserStatusControllerProxy","saveInternalUserDpcsStatus",c,b,a,e,f)};