function DPCSDraftCell(a,b){this.register();this.text=a;this.dpcsId=b}extend(DPCSDraftCell,Component,{renderHtml:function(a){a.push('\x3cdiv class\x3d"draft_cell"\x3e');a.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_click"),'"\x3e',escapeHTML(this.text),"\x3c/a\x3e\x3clabel\x3e- ",MSGS.COMMON_DPCS2_Draft,"\x3c/label\x3e");a.push("\x3c/div\x3e")},_click:function(){this.dispatch("editDPCS",{objId:this.dpcsId,actionValue:this.actionValue})}});
function DPCSActionCell(a,b){this.register();this.dpcsId=a;this._noDel=b||!1}extend(DPCSActionCell,Component,{renderHtml:function(a){a.push('\x3ca href\x3d"#" onclick\x3d"',this.fireCode("_view"),'"\x3e',MSGS.COMMON_DPCS2_View_History,"\x3c/a\x3e");this._noDel||a.push('\x3ca class\x3d"delete_dpcs" onclick\x3d"',this.fireCode("_delete"),'"\x3e',"\x3c/a\x3e")},_view:function(){this.dispatch("viewHistory",{objId:this.dpcsId})},_delete:function(){this.dispatch("deleteDpcs",{objId:this.dpcsId})}});
function DPCSDetailPane(a){this.register();this._model=a;this.sidePane=new DPCSSidePane(this._model);this.mainPane=new GeneralSettingPane(this._model);this.stmt=new StatementContentPane(this._model);this._model.addEventListener("collapseContents",this);this._model.addEventListener("changeLanguage",this)}
extend(DPCSDetailPane,Component,{renderHtml:function(a){a.push('\x3cdiv id\x3d"dpcs_detail_pane"\x3e');a.push('\x3cdiv id\x3d"',this.id+"side",'" class\x3d"dpcs_pane side_pane"\x3e');this.sidePane.renderHtml(a);a.push("\x3c/div\x3e");a.push('\x3cdiv id\x3d"',this.id+"main",'" class\x3d"dpcs_pane main_pane"\x3e');this.mainPane.renderHtml(a);this.stmt.renderHtml(a);a.push("\x3c/div\x3e");a.push("\x3c/div\x3e")},handleEvent:function(a){"collapseContents"===a.type?(this.mainPane.setVisibility(!0),this.stmt.setVisibility(!1)):
"changeLanguage"===a.type&&(this.mainPane.setVisibility(!1),this.stmt.setVisibility(!0),this.stmt.setContent(this._model.getContent(a.lanId)),this.stmt.updateView())}});function LanguageSelector(a){this.register();this.list=a;jQuery(document.documentElement).bind("mouseup",jQuery.proxy(this._close,this))}
extend(LanguageSelector,Component,{renderHtml:function(a){a.push('\x3cul id\x3d"',this.id,'" class\x3d"list lang_selector"\x3e');for(var b,c=0;c<this.list.length;c++)b=this.id+this.list[c].languageID,a.push('\x3cli onmousedown\x3d"',this.fireCode("_select",this.list[c].languageID),'" onmouseover\x3d"',this.fireCode("_toggle",b),'" onmouseout\x3d"',this.fireCode("_toggle",b),'" '),a.push('id\x3d"',b,'"\x3e',this.list[c].languageDisplayName,"\x3c/li\x3e");a.push("\x3c/ul\x3e")},_select:function(a){this.dispatch("langSelected",
{objId:a})},_close:function(a){var b=$(this.id);b&&a.target!=b&&SFOverlayMgr.removeOverlay(this.id)},_toggle:function(a){a=$(a);a.className=a.className?"":"active"}});function DPCSSidePane(a){this.register();this._model=a;this.langSelector=new LanguageSelector(this._model.dpcsLanguageList);this._confirmDlg=new DeleteConfirmDialog;this.lastActive=this.activeEl=null;this._initEventListeners()}
extend(DPCSSidePane,Component,{renderHtml:function(a){a.push('\x3cdiv id\x3d"detail_side_pane"\x3e');a.push('\x3cdiv class\x3d"navMenu activeMenu" onclick\x3d"',this.fireCode("_collapse"),'"\x3e',MSGS.COMMON_DPCS2_General_setting,"\x3c/div\x3e");a.push('\x3cdiv class\x3d"navMenu close inactive" onclick\x3d"',this.fireCode("_expand"),'"\x3e',MSGS.COMMON_DPCS2_STMT_Message,"\x3c/div\x3e");a.push('\x3cul id\x3d"',this.id+"_contents",'"class\x3d"list languages collapsed"\x3e');this._renderContents(a);
a.push("\x3c/ul\x3e");a.push("\x3c/div\x3e")},_collapse:function(){this._gsMenu=this._gsMenu||jQuery("#detail_side_pane div")[0];this._smMenu=this._smMenu||jQuery("#detail_side_pane div")[1];this.ul=this.ul||jQuery("#detail_side_pane ul")[0];-1===this._gsMenu.className.indexOf("activeMenu")&&(this.ul.className=this.ul.className.replace("expanded","collapsed"),this.activeEl&&(this.activeEl.className=""),this.lastActive&&(this.lastActive.className=""),this.activeEl=this.lastActive=null,this._gsMenu.className=
this._gsMenu.className.replace("inactive","activeMenu"),this._smMenu.className=this._smMenu.className.replace("activeMenu","inactive").replace("open","close"),this._model.dispatch("collapseContents"))},_add:function(){var a=jQuery("#detail_side_pane ul a.arrow_down"),b=a.offset();b.top+=a[0].offsetHeight;SFOverlayMgr.showOverlay(this.langSelector,!1,b)},_renderContents:function(a){for(var b=0;b<this._model.getLangListFromContents().length;b++){var c=this._model.getLangListFromContents()[b];a.push('\x3cli onclick\x3d"',
this.fireCode("_changeLanguage",c.languageID),'" id\x3d"',this.id+c.languageID,'"\x3e');a.push('\x3ca class\x3d"label"\x3e',c.languageDisplayName,"\x3c/a\x3e");"view"!=this._model.mode&&"default"!==c.languageID&&a.push('\x3cspan class\x3d"delete" onclick\x3d"',this.fireCode("_delete",b),'"\x3e\x3c/span\x3e');a.push("\x3c/li\x3e")}"view"!=this._model.mode&&a.push('\x3cli\x3e\x3cdiv class\x3d"plus"\x3e\x3ca href\x3d"#" class\x3d"arrow_down" onclick\x3d"',this.fireCode("_add"),'"\x3e',MSGS.COMMON_DPCS2_Add_Lang,
"\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e")},_delete:function(a){var b=this._model.getLangListFromContents()[a].languageDisplayName;this._confirmDlg.setLang(b);this._confirmDlg.idx=a;this._confirmDlg.show()},_expand:function(){this._gsMenu=this._gsMenu||jQuery("#detail_side_pane div")[0];this._smMenu=this._smMenu||jQuery("#detail_side_pane div")[1];this.ul=this.ul||jQuery("#detail_side_pane ul")[0];-1===this._smMenu.className.indexOf("activeMenu")&&(this.ul.className=this.ul.className.replace("collapsed",
"expanded"),this.activeEl&&(this.activeEl.className=""),this.lastActive&&(this.lastActive.className=""),this.activeEl=this.lastActive=null,this._gsMenu.className=this._gsMenu.className.replace("activeMenu","inactive"),this._smMenu.className=this._smMenu.className.replace("inactive","activeMenu").replace("close","open"),0<this._model.getLangListFromContents().length&&(this._model.activeLang=this._model.getLangListFromContents()[0].languageID,this.currentLang=this.currentLang||this._model.getLangListFromContents()[0].languageID,
this._changeLanguage(this.currentLang)))},_changeLanguage:function(a){var b=$(this.id+a+"");b&&(this.activeEl=b,this.activeEl.className="active",this.lastActive&&(this.lastActive.className=""),this.lastActive=this.activeEl,this._model.dispatch("changeLanguage",{lanId:a}))},_initEventListeners:function(){this.langSelector.addEventListener("langSelected",this);this._model.addEventListener("dpcsDetailUpdated",this);this._model.addEventListener("contentsUpdated",this);this._confirmDlg.addEventListener("deleteLang",
this)},_updateMain:function(){var a=[];this._renderContents(a);$(this.id+"_contents").innerHTML=a.join("")},handleEvent:function(a){"dpcsDetailUpdated"===a.type?"retrieve"===a.action&&this._updateMain():"langSelected"===a.type?(this.currentLang=a.objId,this._model.addContent(a.objId)):"contentsUpdated"===a.type?(this._updateMain(),this._changeLanguage(this.currentLang)):"deleteLang"==a.type&&(this.currentLang=this._model.getLangListFromContents()[0].languageID,this._model.deleteContent(this._confirmDlg.idx))}});
function GeneralSettingPane(a){this.register();this._model=a;this._model.redirect_url=this._model.redirect_url||"";this._type=new SFSingleSelect("select_type",this._getOptions(this._model.dpcsTypeList));if("view"===this._model.mode||"edit"===this._model.mode)this._type.setEnabled(!1),this._type.setValue(this._model.dpcsType);this._ctryTransfer=new MultiSelectTransfer(this._getTransferItems(this._model.getAllCountry()),this._getTransferItems(this._model.assignedCountries),"view"===this._model.mode);
this._initEventListeners()}
extend(GeneralSettingPane,Component,{renderHtml:function(a){a.push('\x3cdiv id\x3d"general_setting_pane"\x3e');a.push("\x3ch3\x3e",MSGS.COMMON_DPCS2_General_setting,"\x3c/h3\x3e");a.push("\x3cfieldset\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e",MSGS.COMMON_Name,"\x3c/label\x3e");a.push('\x3cinput type\x3d"text" class\x3d"long_input" onblur\x3d"',this.fireCode("_dirtyCheck"),'" maxlength\x3d"100" id\x3d"',this.id,'dpcsName" value\x3d"',this._model.dpcsName,'"');("view"===this._model.mode||"edit"===
this._model.mode)&&a.push(" disabled");a.push("/\x3e");a.push('\x3cp class\x3d"name_tips"\x3e',MSGS.COMMON_DPCS2_NOTE_DPCS_NAME,"\x3c/p\x3e");a.push("\x3c/div\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e",MSGS.COMMON_Type,"\x3c/label\x3e");this._type.renderHtml(a);a.push("\x3c/div\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e",MSGS.COMMON_DPCS2_Redirect_URL,"\x3c/label\x3e");a.push('\x3cinput type\x3d"text" class\x3d"long_input" onblur\x3d"',this.fireCode("_dirtyCheck"),'"');a.push(' maxlength\x3d"100" id\x3d"',
this.id,'redirect_url" value\x3d"',this._model.redirect_url,'"');"view"===this._model.mode&&a.push(" disabled");a.push("/\x3e\x3c/div\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e",MSGS.COMMON_DPCS2_Assigned_Country,"\x3c/label\x3e");a.push("\x3cspan\x3e");this._ctryTransfer.renderHtml(a);a.push("\x3c/span\x3e");a.push("\x3c/div\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e","\x26#160;","\x3c/label\x3e",'\x3cinput type\x3d"checkbox" id\x3d"',this.id,'check" onclick\x3d"',this.fireCode("_dirtyCheck"),
'"');this._model.as_default&&a.push(" checked");"view"===this._model.mode&&a.push(" disabled");a.push("/\x3e\x3cspan\x3e",MSGS.COMMON_DPCS2_Set_As_Default,"\x3c/span\x3e");a.push('\x3cp class\x3d"default_tips"\x3e',MSGS.COMMON_DPCS2_MSG_SHOW_STMT,"\x3c/p\x3e");a.push("\x3c/div\x3e");a.push("\x3c/fieldset\x3e");a.push("\x3c/div\x3e")},setVisibility:function(a){this.visibility=a;$("general_setting_pane")&&(this.visibility?($("general_setting_pane").style.display="",this._setDisable()):$("general_setting_pane").style.display=
"none")},_initEventListeners:function(){this._model.addEventListener("dpcsDetailUpdated",this);this._type.addEventListener("change",this);this._ctryTransfer.addEventListener("itemMoved",this)},_getOptions:function(a){for(var b=[],c=0;c<a.length;c++)b.push({key:a[c].dpcsDisplayValue,value:a[c].dpcsTypeId});return b},_getTransferItems:function(a){var b=[];if(a&&0<a.length)for(var c=0;c<a.length;c++){var d={};d.key=a[c].countryId;d.value=a[c].countryName;a[c].dpcs&&(d.dpcs=a[c].dpcs);b.push(d)}return b},
_dirtyCheck:function(){this._model.setGeneralValue(this.getValue());this._model.dispatch("stateChanged")},getValue:function(){return{dpcsName:jQuery.trim($(this.id+"dpcsName").value),dpcsType:this._type.getValue(),redirect_url:jQuery.trim($(this.id+"redirect_url").value),as_default:$(this.id+"check").checked?1:0,assigned_country:this._ctryTransfer.getValue()}},updateValues:function(){$("general_setting_pane")&&($(this.id+"dpcsName").value=this._model.dpcsName,this._type.setValue(this._model.dpcsType),
$(this.id+"check").checked=1==this._model.as_default,$(this.id+"redirect_url").value=this._model.redirect_url,this._ctryTransfer.updateList(this._getTransferItems(this._model.getAllCountry()),this._getTransferItems(this._model.assignedCountries)),this._setDisable(),this._setRedirectUrlInputDisable())},_setDisable:function(){"edit"===this._model.mode&&($(this.id+"dpcsName").disabled=!0,this._type.setEnabled(!1))},_setRedirectUrlInputDisable:function(){this._model.dpcsType.toString()===dpcsUtil.THIRDPARTY.toString()?
($(this.id+"redirect_url").disabled=!0,$(this.id+"redirect_url").value=""):$(this.id+"redirect_url").disabled=!1},handleEvent:function(a){switch(a.type){case "change":this._model.dpcsType=a.newValue;this._ctryTransfer.updateList(this._getTransferItems(this._model.getAllCountry()),this._getTransferItems(this._model.assignedCountries));this._dirtyCheck();this._setRedirectUrlInputDisable();break;case "itemMoved":this._dirtyCheck();break;case "dpcsDetailUpdated":this.updateValues()}}});
function MultiSelectTransfer(a,b,c){this.register();this.fromList=a;this.toList=b;this.setDisabled(c);this.currentFocus=null}
extend(MultiSelectTransfer,Component,{renderHtml:function(a){a.push('\x3cdiv id\x3d"multiple_select_transfer"\x3e');this._renderContent(a);a.push("\x3c/div\x3e")},_renderContent:function(a){a.push("\x3ctable\x3e");a.push("\x3ctr\x3e");a.push("\x3ctd\x3e");a.push('\x3cdiv class\x3d"title"\x3e',MSGS.COMMON_DPCS2_All_Countries,"\x3c/div\x3e");a.push('\x3cul tabindex\x3d"0" id\x3d"',this.id,'from" class\x3d"list multi_transfer" onkeypress\x3d"',this.fireCode("_search"),'"\x3e');for(var b,c=0;c<this.fromList.length;c++){b=
this.fromList[c];a.push('\x3cli onclick\x3d"',this.fireCode("_highlit",b.key+"_from"),'" id\x3d"',b.key+"_from",'"');if(b.dpcs){var d=MSGS.COMMON_DPCS2_assigned_to.replace("{0}",b.dpcs);a.push(" class\x3d'disabled' title\x3d'",d,"'")}a.push("\x3e",b.value,"\x3c/li\x3e")}a.push("\x3c/ul\x3e");a.push("\x3c/td\x3e");a.push("\x3ctd\x3e");a.push('\x3cdiv class\x3d"action"\x3e');a.push('\x3cdiv style\x3d"margin-bottom: 10px"\x3e\x3cbutton type\x3d"button" onclick\x3d"',this.fireCode("_add"),'"',this.disabled,
"\x3e",MSGS.COMMON_Add+" \x3e","\x3c/button\x3e\x3c/div\x3e");a.push('\x3cdiv\x3e\x3cbutton type\x3d"button" onclick\x3d"',this.fireCode("_remove"),'"',this.disabled,"\x3e","\x3c "+MSGS.COMMON_Remove,"\x3c/button\x3e\x3c/div\x3e");a.push("\x3c/div\x3e");a.push("\x3c/td\x3e");a.push("\x3ctd\x3e");a.push('\x3cdiv class\x3d"title"\x3e',MSGS.COMMON_DPCS2_Assigned_Country,"\x3c/div\x3e");a.push('\x3cul tabindex\x3d"0" id\x3d"',this.id,'to" class\x3d"list multi_transfer" onkeypress\x3d"',this.fireCode("_search"),
'"\x3e');for(c=0;c<this.toList.length;c++)b=this.toList[c],a.push('\x3cli onclick\x3d"',this.fireCode("_highlit",b.key+"_to"),'" id\x3d"',b.key+"_to",'"'),a.push("\x3e",b.value,"\x3c/li\x3e");a.push("\x3c/ul\x3e");a.push("\x3c/td\x3e");a.push("\x3c/tr\x3e");a.push("\x3c/table\x3e")},_search:function(a){if(this.currentFocus){for(var b=jQuery(this.currentFocus),c=b[0],d=jQuery(c.parentNode),e=String.fromCharCode(a.keyCode||a.charCode).toLowerCase(),b=b.next();b[0]!=c;){b[0]||(b=d.children().first());
if(0===b[0].innerHTML.toLowerCase().indexOf(e)&&!b.hasClass("disabled"))break;b=b[0]==d.children().last()[0]?d.children().first():b.next()}this._scroll(d[0],b[0]);this._highlit(b[0].id,a)}},_scroll:function(a,b){if(b){var c=b.offsetTop,d=a.scrollTop,e=a.clientHeight,f=c+b.offsetHeight;a.scrollTop=d>c?c:f>d+e?f-e:d}},updateList:function(a,b){this.fromList=a;this.toList=b;this.currentFocus=null;var c=[];this._renderContent(c);$("multiple_select_transfer").innerHTML=c.join("")},_highlit:function(a,b){var c=
jQuery("#"+a);!c.hasClass("disabled")&&!c.hasClass("selected")&&(this.currentFocus=c[0],b.ctrlKey||this._deSelect(c[0].parentNode),c.addClass("selected"))},_deSelect:function(a){jQuery(a).find(".selected").each(function(){jQuery(this).removeClass("selected")})},setDisabled:function(a){a&&(this.disabled=" disabled")},getValue:function(){for(var a=$(this.id+"to").childNodes,b=[],c=0;c<a.length;c++){var d=a[c].id;b.push(d.substring(0,d.indexOf("_")))}return b},_transfer:function(a,b){var c=jQuery(a),
d=jQuery(b);0<c.find(".selected").length&&(c.find(".selected").each(function(a,b){c[0].removeChild(b);d[0].appendChild(b);jQuery(b).removeClass("selected")}),this.dispatch("itemMoved"))},_add:function(){this._transfer($(this.id+"from"),$(this.id+"to"))},_remove:function(){this._transfer($(this.id+"to"),$(this.id+"from"))}});
function StatementContentPane(a){this.register();this._model=a;this.visibility=!1;this.mode=this._model.mode;this.editor=new RTEditor("",{name:"dpcsEditor",height:"240",spellCheck:1==this._model.spellCheckEnabled?!0:!1,legalScan:1==this._model.legalScanEnabled?!0:!1,readOnly:"view"===this.mode,bubbleUpdateEventOnKeyup:!0,textpane:{fontSize:"12px",fontFamily:"Arial,Verdana,sans-serif"}});this._initEventListeners()}
extend(StatementContentPane,Component,{renderHtml:function(a){a.push('\x3cdiv id\x3d"stmt_content_pane" style\x3d"display: none"\x3e');a.push('\x3ch3 id\x3d"',this.id,'instruction"\x3e',this._getInstruction(),"\x3c/h3\x3e");a.push('\x3cp id\x3d"',this.id,'note" style\x3d"padding-right: 20px"\x3e',this._getNote(),"\x3c/p\x3e");a.push("\x3cfieldset\x3e");a.push("\x3cdiv\x3e");a.push("\x3clabel\x3e",MSGS.COMMON_Title,"\x3c/label\x3e");a.push('\x3cinput type\x3d"text" class\x3d"long_input" maxlength\x3d"100" id\x3d"',
this.id+"title",'" onblur\x3d"',this.fireCode("_saveTitle"),'"');this.content&&this.content.title&&a.push(' value\x3d"',this.content.title,'"');"view"===this.mode&&a.push(" disabled");a.push("/\x3e\x3c/div\x3e");a.push("\x3cdiv\x3e");a.push('\x3clabel style\x3d"padding: 6px 0"\x3e',MSGS.COMMON_DPCS2_STMT_Message,"\x3c/label\x3e");a.push('\x3cspan style\x3d"display:inline-block;width:500px"\x3e');this.editor.renderHtml(a);a.push("\x3c/span\x3e");a.push("\x3c/div\x3e");a.push("\x3cdiv\x3e\x3clabel\x3e\x26nbsp;\x3c/label\x3e",
'\x3ca class\x3d"print" href\x3d"#" onclick\x3d"',this.fireCode("_printPreview"),'"\x3e',MSGS.COMMON_DPCS2_Print_preview,"\x3c/a\x3e","\x3c/div\x3e");a.push("\x3c/fieldset\x3e");a.push("\x3c/div\x3e")},_saveTitle:function(){var a=$(this.id+"title");this.content.title=jQuery.trim(a.value);this._model.dispatch("stateChanged")},_getNote:function(){var a="";this.content&&dpcsUtil.DEFAULT_LANG===this.content.languageID&&(a=MSGS.COMMON_DPCS2_MSG_NOTE_Default_STMT);return a},_getInstruction:function(){var a=
MSGS.COMMON_DPCS2_STMT_Message;this.content&&this.content.languageID===dpcsUtil.DEFAULT_LANG&&(a=MSGS.COMMON_DPCS2_Default_STMT);return a},setContent:function(a){this.content=a},updateContent:function(){if(this.content)for(var a=0;a<this._model.contents.length;a++)if(this.content.languageID==this._model.contents[a].languageID){this.content=this._model.contents[a];break}},getTitle:function(){return $(this.id+"title").value},getStatement:function(){return this.editor.getValue()},updateView:function(){$(this.id+
"instruction").innerHTML=this._getInstruction();$(this.id+"note").innerHTML=this._getNote();$(this.id+"title").value=this.content.title||"";this.editor.setValue(this.content.content)},setVisibility:function(a){this.visibility=a;$("stmt_content_pane")&&(this.visibility?$("stmt_content_pane").style.display="":$("stmt_content_pane").style.display="none")},_initEventListeners:function(){this.editor.addEventListener("change",this)},_printPreview:function(){window.open("/xi/ui/dpcs/pages/statement_print.xhtml",
"print_preview","width\x3d"+0.6*window.screen.width+",height\x3d600,location\x3dno,scrollbars\x3dyes")},handleEvent:function(a){switch(a.type){case "change":a=jQuery.trim(this.editor.getValue()),a!=this.content.content&&(this.content.content=a,this._model.dispatch("stateChanged"))}}});
function DeleteConfirmDialog(){this.register();this.isV12()?this._dialog=new SFDialogBox(MSGS.COMMON_DPCS2_Delete_STMT,this,[{label:MSGS.COMMON_Yes,eventName:"done"},{label:MSGS.COMMON_No,eventName:"cancel",active:!0}],500,150):this._dialog=new SFDialog(MSGS.COMMON_DPCS2_Delete_STMT,this,[{label:MSGS.COMMON_Yes,eventName:"done"},{label:MSGS.COMMON_No,eventName:"cancel",active:!0}],500,150);this._dialog.addEventListener("action",this)}
extend(DeleteConfirmDialog,Component,{renderHtml:function(a){var b=MSGS.COMMON_DPCS2_DEL_Confirm;a.push("\x3cp\x3e");a.push(b.replace("{0}",this.lang).replace("{1}",this.lang));a.push("\x3c/p\x3e")},setLang:function(a){this.lang=a},show:function(){this.isV12()?SFOverlayMgr.showOverlay(this._dialog,!0):this._dialog.showDialog()},_cancel:function(a){this.isV12()?SFOverlayMgr.removeOverlay(this._dialog.id):this._dialog.close()},_done:function(){this.isV12()?SFOverlayMgr.removeOverlay(this._dialog.id):
this._dialog.close();this.dispatch("deleteLang")},handleEvent:function(a){"action"==a.type&&("cancel"==a.actionCommand?this._cancel():"done"==a.actionCommand&&this._done())},isV12:function(){var a=UIVersion.getCurrentInstance();return a&&0<=a.compareTo(UIVersion.V12)}});
function DpcsSearchUsers(a){this.register();this.createAutoSearchBox();this._isExternalUserEnabled=a?a.rCMDpcs2EnabledForExternal:!1;this._isIntranetUserEnabled=a?a.rCMDpcs2EnabledForIntranet:!1;this.searchType=new SFSingleSelect("search_type",this._getUserType());this.searchType.addEventListener("change",this);this.searchTypeSelectedValue=1}
extend(DpcsSearchUsers,Component,{renderHtml:function(a){a.push('\x3clabel style\x3d"margin-right:20px"\x3e',MSGS.COMMON_DPCS2_Find_employee,":","\x3c/label\x3e");this.searchType.renderHtml(a);a.push("\x3cspan\x3e\x26#160;\x26#160;\x3c/span\x3e");a.push('\x3cspan id\x3d"',this.id,'"\x3e');this.userInput.renderHtml(a);a.push("\x3c/span\x3e")},_getUserType:function(){var a=[];a[0]={key:MSGS.COMMON_DPCS2_internal_user,value:dpcsUtil.SEARCH_TYPE_USER};"true"==this._isExternalUserEnabled&&(a[1]={key:MSGS.COMMON_DPCS2_external_users,
value:dpcsUtil.SEARCH_TYPE_CANDIDATE});"true"==this._isIntranetUserEnabled&&(a[2]={key:MSGS.COMMON_DPCS2_intranet_users,value:dpcsUtil.SEARCH_TYPE_INTRANET_CANDIDATE});return a},_userInput:function(){var a=[];a.push('\x3cinput type\x3d"text" size\x3d"30" maxlength\x3d"30" id\x3d"',this.id,'_userInput" onfocus\x3d"',this.fireCode("_focus"),'"/\x3e');return a.join("")},getValue:function(){return $(this.id+"_userInput")?$(this.id+"_userInput").value:this.userInput.getValue()},isIntranetUserSelected:function(){return 3==
this.searchTypeSelectedValue},isExternalUserSelected:function(){return 2==this.searchTypeSelectedValue},createAutoSearchBox:function(a,b){this._searchType=a?a:"fullname";this.subType=b?b:"userSearch";this.userInput="userSearch"==this.subType?new SFAutoComplete(this._searchType,{required:!1,inputSize:30,writable:!0,autoComplete:{enablePhoto:!0,hideUserName:0,maxResultsDisplayed:50,params:{subType:b}}}):new SFAutoComplete(this._searchType,{required:!1,inputSize:30,writable:!0,URIParamsArr:"FullName FirstName LastName EmailAddress EmailAddress UserId UserId MiddleInitial Count".split(" "),
autoComplete:{enablePhoto:!0,hideUserName:0,maxResultsDisplayed:50,params:{subType:b}}});this.userInput.addEventListener("action",this)},_focus:function(){this.dispatch("action",{actionCommand:"focus"})},handleEvent:function(a){"change"==a.type?(this.searchTypeSelectedValue=a.newValue,1==a.newValue?(this.createAutoSearchBox(),a=[],this.userInput.renderHtml(a),$(this.id).innerHTML=a.join("")):2==a.newValue?(this.createAutoSearchBox("customUserSearch","externalCandSearch"),a=[],this.userInput.renderHtml(a),
$(this.id).innerHTML=a.join("")):3==a.newValue?(this.createAutoSearchBox("customUserSearch","intranetCandSearch"),a=[],this.userInput.renderHtml(a),$(this.id).innerHTML=a.join("")):$(this.id).innerHTML=this._userInput()):"action"==a.type&&this._focus()}});
function ViewStatementDlg(){this.register();this.isV12()?this._dialog=new SFDialogBox(MSGS.FB_DP_CONSENT_STATEMENT_TITLE,this,[{label:MSGS.COMMON_Close,eventName:"cancel"}],500,250):this._dialog=new SFDialog(MSGS.FB_DP_CONSENT_STATEMENT_TITLE,this,[{label:MSGS.COMMON_Close,eventName:"cancel"}],500,250);this._dialog.addEventListener("action",this)}
extend(ViewStatementDlg,Component,{renderHtml:function(a){a.push('\x3ch3 style\x3d"text-align:center"\x3e',escapeHTML(this._title),"\x3c/h3\x3e");a.push("\x3cp\x3e");a.push(this._content);a.push("\x3c/p\x3e")},show:function(a,b,c){this._title=a;this._content=b;this.isV12()?(a=[],this.renderHtml(a),this._dialog.setContent(a.join("")),this._dialog.showDialog(!0,c)):(this._dialog.setComponent(this),SFOverlayMgr.showOverlay(this._dialog,!0))},_cancel:function(a){this.isV12()?this._dialog.close():SFOverlayMgr.removeOverlay(this._dialog.id)},
handleEvent:function(a){"action"==a.type&&"cancel"==a.actionCommand&&this._cancel()},isV12:function(){var a=UIVersion.getCurrentInstance();return a&&0<=a.compareTo(UIVersion.V12)}});
function DeclineConfirmDlg(a){this.register();this.content=a?a:MSGS.COMMON_DPCS2_Choose_to_accept;this.isV12()?this._dialog=new SFDialogBox(MSGS.COMMON_DPCS2_Decline_STMT,this,[{label:MSGS.COMMON_Yes,eventName:"done"},{label:MSGS.COMMON_No,eventName:"cancel",active:!0}],500,150):this._dialog=new SFDialog(MSGS.COMMON_DPCS2_Decline_STMT,this,[{label:MSGS.COMMON_Yes,eventName:"done"},{label:MSGS.COMMON_No,eventName:"cancel",active:!0}],500,150);this._dialog.addEventListener("action",this)}
extend(DeclineConfirmDlg,Component,{renderHtml:function(a){a.push("\x3cp\x3e");a.push(this.content);a.push("\x3c/p\x3e")},show:function(a){this.isV12()?this._dialog.showDialog(!0,a):SFOverlayMgr.showOverlay(this._dialog,!0)},_cancel:function(a){this.isV12()?this._dialog.close():SFOverlayMgr.removeOverlay(this._dialog.id)},handleEvent:function(a){"action"==a.type&&("cancel"==a.actionCommand?this._cancel():"done"==a.actionCommand&&(this._cancel(),this.dispatch("decline",{dpcsId:this.dpcsId})))},isV12:function(){var a=
UIVersion.getCurrentInstance();return a&&0<=a.compareTo(UIVersion.V12)}});var dpcsUtil={DECLINE:0,ACCEPT:1,REVOKE:2,NOT_PRESENT:3,DEFAULT_LANG:"default",LOGIN:0,THIRDPARTY:4,RECRUITING_INTERNAL:1,RECRUITING_EXTERNAL:2,RECRUITING_INTRANET:3,SEARCH_TYPE_USER:1,SEARCH_TYPE_CANDIDATE:2,SEARCH_TYPE_INTRANET_CANDIDATE:3,mapStatus:function(a){return a===dpcsUtil.DECLINE?MSGS.COMMON_DPCS2_Declined:a===dpcsUtil.ACCEPT?MSGS.COMMON_DPCS2_ACCEPTED:a===dpcsUtil.NOT_PRESENT?MSGS.COMMON_DPCS2_NOT_PRESENTED:MSGS.COMMON_DPCS2_Revoked}};