function picklist(){}picklist.req;picklist.childPicklistObjects=[];picklist.UPDATE_SERVLET_OVERRIDE="";picklist.callAjaxFunction=function(c,b,d){for(var a=b.length,f="",e=0;e<a;e++)f=0==e?b[e]:f+";"+b[e];c=picklist.createAjaxURL(c,f,d);picklist.submitAjaxPickListQuery(c)};
picklist.createAjaxURL=function(c,b,d){var a=(""!=picklist.UPDATE_SERVLET_OVERRIDE?picklist.UPDATE_SERVLET_OVERRIDE:"/jsup")+"?m\x3dpickListQuery\x26";return a=a+("parentOptionId\x3d"+c+"\x26childPicklistIds\x3d"+b)+("\x26parentFieldId\x3d"+(d||""))};
picklist.prepareAjaxRequest=function(){picklist.req=!1;if(window.XMLHttpRequest)try{picklist.req=new XMLHttpRequest}catch(c){picklist.req=!1}else if(window.ActiveXObject)try{picklist.req=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{picklist.req=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){picklist.req=!1}}};
picklist.submitAjaxPickListQuery=function(c){picklist.prepareAjaxRequest();if(picklist.req)try{picklist.req.open("GET",c,!1);picklist.req.send(null);if(200!=picklist.req.status)return alert("Getting Child Picklist process failed, server responded "+picklist.req.statusText),!1;if(-1==picklist.req.getResponseHeader("Content-Type").indexOf("text/plain"))return alert("Getting Child Picklist process failed, your session has timed out"),!1;var b=eval("("+picklist.req.responseText+")");picklist.childPicklistObjects=
b.picklistObjects;var d=b.parentFieldId;if(null==picklist.childPicklistObjects)return;for(c=index=0;c<picklist.childPicklistObjects.length;c++){var a;formElements=document.forms[0].elements;for(var b=0,f=formElements.length;b<f;b++)if(formElements[b].getAttribute("picklistId")==picklist.childPicklistObjects[c].picklistId&&(!formElements[b].getAttribute("parentid")||formElements[b].getAttribute("parentid")==d))a=formElements[b],null!=a&&picklist.addItem(a,picklist.childPicklistObjects[c].value,picklist.childPicklistObjects[c].label)}if(null!=
a&&"true"==a.getAttribute("data-autoselect-single")){d=null;for(c=0;c<a.length;c++)if(a[c].value){if(d){d=null;break}d=a[c]}d&&(d.selected=!0,a.onchange())}}catch(e){return alert("Getting Child Picklist process failed, "+e.message),!1}return!0};picklist.addItem=function(c,b,d){var a=document.createElement("option");c.options.add(a);if(""==b||null==b||0==b)b="";a.value=b;a.text=d};
picklist.getChildpicklists=function(c){for(var b=[],d=[],a=0,b=document.forms[0].elements,f=b.length,e=0;e<f;e++){var g=b[e],h=g.getAttribute("parentId");null!=h&&h==c&&(d[a++]=g.getAttribute("picklistId"))}return d};
picklist.cleanChildren=function(c,b){for(var d=[],d=document.forms[0].elements,a=d.length,f=0;f<a;f++){var e=d[f],g=e.getAttribute("parentId");if(null!=g&&g==c){for(var g=e.options.length,h=0;h<g;h++)e.remove(0);picklist.addItem(e,0,b);picklist.cleanChildren(e.getAttribute("id"),b);e.disabled=!0}}};
picklist.clearChildren=function(c,b,d){for(var a=[],a=document.forms[0].elements,f=a.length,e=0;e<f;e++){var g=a[e],h=g.getAttribute("parentId");if(null!=h&&h==c){for(var h=g.options.length,k=0;k<h;k++)g.remove(0);picklist.addItem(g,0,b);g.disabled=d;picklist.clearChildren(g.getAttribute("id"),b,!0)}}};
picklist.attachBehavior=function(c,b){FCKeditorHack3();var d;formElements=document.forms[0].elements;for(var a=0,f=formElements.length;a<f;a++)if(c==formElements[a].name||c==formElements[a].id){d=formElements[a];break}-1!=d.selectedIndex&&(a=d.value,""==a||"null"==a||a==b?picklist.cleanChildren(d.getAttribute("id"),b):(picklist.clearChildren(d.getAttribute("id"),b,!1),c=d.getAttribute("id"),d=picklist.getChildpicklists(c),0!=d.length&&picklist.callAjaxFunction(a,d,c)))};
picklist.disableChildren=function(){formElements=document.forms[0].elements;for(var c=formElements.length,b=0;b<c;b++){var d=formElements[b];null!=d.getAttribute("parentId")&&(d.disabled=!0)}};
picklist.attachBehaviors=function(){FCKeditorHack3();var c=[];if(document.forms[0])for(var c=document.forms[0],c=c.getElementsByTagName("select"),b=c.length,d=0;d<b;d++){var a=c[d],f=a.getAttribute("parentId");if(null!=f){var e=gebi(f);if(e){var g=e.value,e=a.value;a.getAttribute("id");var h=a.getAttribute("picklistId"),k=a.options.length,k=a.options[0];a.innerHTML="";a.options[0]=k;if(""!=g&&"null"!=g){a.disabled=!1;picklist.callAjaxFunction(g,[h],f);k=a.options.length;for(f=0;f<k;f++)if(a.options[f].value==
e){a.options[f].selected=!0;break}}}}}};function FCKeditorHack3(){};