function SMRF(){}
SMRF={AJAXSERVICE_KEY_LEGACY:"legacy\x3d",_newStylesheetIndex:document.styleSheets.length-1,_loadedStyleNum:0,_downloadRequestedMap:{},_downloadCompletedMap:{},_has31CSSFilesLimitation:!1,load:function(a,c){var b={callbackObj:c,urls:a};if(!window.DEPS_TREE||!window.DEPS_VERSION_MAP)this._dynamicLoadingFinished(b);else{var d=document.getElementsByTagName("link"),e=document.getElementsByTagName("style");SMRF._loadedStyleNum=d.length+e.length;d=navigator.userAgent;e=/MSIE ([0-9]+\.[0-9]+)/.exec(d);this._has31CSSFilesLimitation=
-1==d.indexOf("Opera")&&10>parseFloat(e&&e[1]);SMRF._load(b)}},_findScriptPath:function(a,c,b){juic.assert(a||b,"Module name must be specified when the legacy mode is false (ajaxServiceId\x3d"+c+")");return"/ui/"+(a?"v4":b)+"/js/ajaxservice/"+c+"ASProxy.js"},_isAjaxServiceDirectory:function(a){return-1!=a.indexOf("ajaxservice:")},_normalizeUrl:function(a){if(!this._isAjaxServiceDirectory(a))return a;var c=null,b=a.indexOf(":"),d=Math.max(a.indexOf("."),b),e=a.indexOf("?");if(0<=b&&0<=d&&d>=b){var c=
a.substring(b+1,d==b?b+1:d),b=a.substring(d+1,0<e?e:a.length),f=!1;e>d&&(d=a.indexOf(this.AJAXSERVICE_KEY_LEGACY),d>e&&(e=a.indexOf("\x26",d),0>e&&(e=a.length),f="true"==a.substring(d+this.AJAXSERVICE_KEY_LEGACY.length,e)));c=this._findScriptPath(f,b,c)}return c},_load:function(a){for(var c=a.urls,b=c.length,d=[],e=0;e<b;e++){var f=DEPS_VERSION_MAP[this._normalizeUrl(c[e])];SMRF._populateURLListForDownload(f,d)}if(0<d.length)SMRF._downloadFiles(d,a);else{d=!0;for(e=0;e<b;e++)if(f=DEPS_VERSION_MAP[this._normalizeUrl(c[e])],
0<DEPS_TREE[f].length){d=!1;break}d&&this._dynamicLoadingFinished(a)}},_dynamicLoadingFinished:function(a){a=a.callbackObj;void 0!=a&&("function"==typeof a?(cb=a,cb()):(cb=a.callback,args=a.argument,cb(args)))},_populateURLListForDownload:function(a,c){var b=DEPS_TREE[a];if(1==b.length)this._downloadRequestedMap[b[0]]||(c.push(b[0]),this._downloadRequestedMap[b[0]]=!0);else for(var d=0;d<b.length;d++)b[d]!=a&&SMRF._populateURLListForDownload(b[d],c)},_deleteDownloadedFileRefs:function(a,c){for(var b=
DEPS_TREE[c],d=b.length-1;0<=d;d--)b[d]==a&&b.splice(d,1)},_downloadFiles:function(a,c){for(var b=document.getElementsByTagName("script"),d=document.getElementsByTagName("link"),e=0;e<a.length;e++){var f=a[e];0<f.indexOf(".js")?SMRF._isAlreadyIncluded(f,b,"src")?SMRF._resourceLoadedCallback(f,c):SMRF._appendScriptAndCallCallback(f,c):0<f.indexOf(".css")&&(SMRF._isAlreadyIncluded(f,d,"href")?SMRF._resourceLoadedCallback(f,c):(SMRF._loadedStyleNum++,SMRF._appendStylesheet(f,c),this._newStylesheetIndex++,
!window.opera&&-1==navigator.userAgent.indexOf("MSIE")?SMRF._callCallbackForStylesheet(this._newStylesheetIndex,f,c):this._has31CSSFilesLimitation&&31<SMRF._loadedStyleNum&&SMRF._resourceLoadedCallback(f,c)))}},_isAlreadyIncluded:function(a,c,b){if(document.getElementById(a))return!0;for(var d=c.length,e=0;e<d;e++){var f=c[e],g=f[b];if((g="src"==b?f.src:f.href)&&0<=g.indexOf(a))return f.id=a,!0}return!1},_resourceLoadedCallback:function(a,c){if(!SMRF._downloadCompletedMap[a]){for(var b in DEPS_TREE)SMRF._deleteDownloadedFileRefs(a,
b);SMRF._downloadCompletedMap[a]=!0;SMRF._load(c)}},_appendStylesheet:function(a,c){var b=document.createElement("link");b.id=a;b.href=a;b.rel="stylesheet";b.type="text/css";this._attachLoadHandlers(b,a,c);document.getElementsByTagName("head")[0].appendChild(b)},_appendScriptAndCallCallback:function(a,c){var b=document.createElement("script");b.id=a;b.type="text/javascript";b.src=a;this._attachLoadHandlers(b,a,c);document.getElementsByTagName("head")[0].appendChild(b)},_attachLoadHandlers:function(a,
c,b){a.addEventListener?a.onload=function(){SMRF._resourceLoadedCallback(c,b)}:a.readyState&&(a.onreadystatechange=function(){("loaded"===this.readyState||"complete"===this.readyState)&&SMRF._resourceLoadedCallback(c,b)})},_callCallbackForStylesheet:function(a,c,b){try{document.styleSheets[a].cssRules?SMRF._resourceLoadedCallback(c,b):document.styleSheets[a].rules&&document.styleSheets[a].rules.length?SMRF._resourceLoadedCallback(c,b):setTimeout(function(){SMRF._callCallbackForStylesheet(a,c,b)},
250)}catch(d){setTimeout(function(){SMRF._callCallbackForStylesheet(a,c,b)},250)}}};