(function(){function k(h){for(var e=window,a=h.split(".");a.length;){var b=a.splice(0,1)[0];e[b]||(e[b]=a.length?{}:1<arguments.length?arguments[1]:{});e=e[b]}return e}k("sap.sf.surj");window.surj=sap.sf.surj;window.surj.define=k})();
(function(k){function h(a,b){"string"==typeof a&&(a=document.getElementById(a));return!a?!1:window.jQuery?jQuery(a).hasClass(b):-1<(" "+a.className+" ").indexOf(" "+b+" ")}var e=surj.define("sap.sf.surj.Util",{gotoURL:function(a,b,c){if(!b&&window.ajaxSecKey&&a&&0!=a.indexOf("javascript:")&&0>a.indexOf("_s.crb\x3d")){b=a.indexOf("?");var d=a.indexOf("#");0<=d&&b>d&&(b=-1);var f="";0<=d&&(f=a.substring(d),a=a.substring(0,d));a+=(0>b?"?":"\x26")+"_s.crb\x3d"+window.ajaxSecKey+f}try{c?window.open(a,
c.name||"_new",c.specs,c.replace):window.location.href=a}catch(g){}},isRTL:function(a){return a?h(a,"rtl"):(a=(a=window.pageHeaderJsonData)&&a.langDir)?"rtl"==a:h(document.body,"rtl")},isFioriEnabled:function(){var a=window.pageHeaderJsonData;return(a=a&&a.fioriEnabled)?a:h(document.body,"fiori")},findURLParam:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?\x26]"+a+"\x3d([^\x26#]*)").exec(window.location.href);return null==a?"":a[1]},defineNonEnumPropIfNeeded:function(a,
b,c){a&&(a[b]||e.defineNonEnumProp(a,b,c))},defineNonEnumProp:function(a,b,c){if(a)if("function"==typeof Object.defineProperty)try{Object.defineProperty(a,b,{enumerable:!1,writable:!0,configurable:!0,value:c})}catch(d){a[b]=c}else a[b]=c},getPageContainerId:function(){return window.layoutContainerId||"container"},getOptimizedFontSize:function(a,b,c){function d(a,b,d){b=b||document.body;d=d||"1em";a=a||"M";var c=document.createElement("div");c.style.display="inline-block";c.style.lineHeight="1em";
c.style.fontSize=d;c.style.padding=0;c.style.visibility="hidden";c.appendChild(document.createTextNode(a));b.appendChild(c);a=[Math.max(c.offsetWidth,c.scrollWidth),c.offsetHeight];b.removeChild(c);return a}var f=d(a,b),g=d(null,b);a=d(a,b,c.minFontSize+"px");return a[0]<c.width&&g[1]<f[1]?Math.min(c.maxHeight,Math.max(c.minFontSize,Math.floor(c.minFontSize*(c.width/a[0]))-1))+"px":c.maxHeight&&f[1]>c.maxHeight?Math.min(c.maxHeight,Math.max(c.minFontSize,Math.floor(g[1]*(c.maxHeight/f[1]))-1))+"px":
"1em"},getCssText:function(a){var b=[],c;for(c in a)b.push(c+":"+a[c]);return b.join(";")},getUIMode:function(){var a=document.getElementById("uimode");return a&&a.getAttribute("content")},transBBCodeToHTML:function(a){function b(a){return a.replace(f,d)}function c(a,b){for(var d in b)a=a.replace(RegExp(d,"g"),b[d]);return a}function d(a,d,p,c){c&&-1<c.indexOf("[")&&(c=b(c));switch(d){case "url":case "anchor":case "email":return"\x3ca "+e[d]+(p||c)+'"\x3e'+c+"\x3c/a\x3e";case "img":return a=g.exec(p),
'\x3cimg src\x3d"'+c+'"'+(a?' width\x3d"'+a[1]+'" height\x3d"'+a[2]+'"':"")+' alt\x3d"'+(a?"":p)+'" /\x3e';case "float":return'\x3cspan style\x3d"float: '+p+'"\x3e'+c+"\x3c/span\x3e";case "left":case "right":case "center":case "justify":return'\x3cdiv style\x3d"text-align: '+d+'"\x3e'+c+"\x3c/div\x3e";case "b":case "i":case "u":case "s":case "sup":case "sub":case "h1":case "h2":case "h3":case "h4":case "h5":case "h6":case "table":case "tr":case "th":case "td":return"\x3c"+d+"\x3e"+c+"\x3c/"+d+"\x3e";
case "row":case "r":case "header":case "head":case "h":case "col":case "c":return"\x3c"+h[d]+"\x3e"+c+"\x3c/"+h[d]+"\x3e";case "acronym":case "abbr":return"\x3c"+d+' title\x3d"'+p+'"\x3e'+c+"\x3c/"+d+"\x3e"}return"["+d+(p?"\x3d"+p:"")+"]"+c+"[/"+d+"]"}if(0>a.indexOf("["))return a;var f=RegExp("\\[([a-z][a-z0-9]*)(?:\x3d([^\\]]+))?]((?:.|[\r\n])*?)\\[/\\1]","g"),g=RegExp("^(\\d+)x(\\d+)$",void 0),m={c:"circle",d:"disc",s:"square",1:"decimal",a:"lower-alpha",A:"upper-alpha",i:"lower-roman",I:"upper-roman"},
e={url:'href\x3d"',anchor:'name\x3d"',email:'href\x3d"mailto: '},h={row:"tr",r:"tr",header:"th",head:"th",h:"th",col:"td",c:"td"},k={font:"font-family:$1",size:"font-size:$1px",color:"color:$1"},l={notag:[{"\\[":"\x26#91;","]":"\x26#93;"},"",""],code:[{"\x3c":"\x26lt;"},"\x3ccode\x3e\x3cpre\x3e","\x3c/pre\x3e\x3c/code\x3e"]},p={},n={},r;for(r in l)p["\\[("+r+")]((?:.|[\r\n])*?)\\[/\\1]"]=function(a,d,b){return l[d][1]+c(b,l[d][0])+l[d][2]};for(r in k)n["\\["+r+"\x3d([^\\]]+)]"]='\x3cspan style\x3d"'+
k[r]+'"\x3e',n["\\[/"+r+"]"]="\x3c/span\x3e";n["\\[list]"]="\x3cul\x3e";n["\\[list\x3d(\\w)]"]=function(a,d){return'\x3cul style\x3d"list-style-type: '+(m[d]||"disc")+'"\x3e'};n["\\[/list]"]="\x3c/ul\x3e";n["\\[\\*]"]="\x3cli\x3e";n["\\[quote(?:\x3d([^\\]]+))?]"]=function(a,d){return'\x3cdiv class\x3d"bb-quote"\x3e'+(d?d+" wrote":"Quote")+":\x3cblockquote\x3e"};n["\\[/quote]"]="\x3c/blockquote\x3e\x3c/div\x3e";n["\\[(hr|br)]"]="\x3c$1 /\x3e";n["\\[sp]"]="\x26nbsp;";return b(c(c(a,p),n))}});surj.define("sap.sf.surj.A11yPreferences",
{COLORVISION_UNKNOWN:"unknown",COLORVISION_NORMAL:"type0",LOWVISION_NORMAL:"normal",LOWVISION_DARK:"dark",LOWVISION_LIGHT:"light",isSupported:function(){return!(!window.pageHeaderJsonData||!window.pageHeaderJsonData.accessibilityPreferences)},isBlindnessSupportEnabled:function(){return this.isSupported()?pageHeaderJsonData.accessibilityPreferences.blindnessSupport:!1},isColorVisionEnabled:function(){return this.isSupported()&&null!=window.pageHeaderJsonData.accessibilityPreferences.colorVisionType?
this.getColorVisionType()!=this.COLORVISION_NORMAL:!1},getColorVisionType:function(){if(this.isSupported()){var a=pageHeaderJsonData.accessibilityPreferences.colorVisionType;return this.COLORVISION_UNKNOWN==a?this.COLORVISION_NORMAL:a}return this.COLORVISION_NORMAL},isLowVisionEnabled:function(){return this.isSupported()&&null!=window.pageHeaderJsonData.accessibilityPreferences.lowVisionType?pageHeaderJsonData.accessibilityPreferences.lowVisionType!=this.LOWVISION_NORMAL:!1},getLowVisionType:function(){return this.isSupported()?
pageHeaderJsonData.accessibilityPreferences.lowVisionType:this.LOWVISION_NORMAL},isKeyboardOnlyNavigationEnabled:function(){return this.isSupported()?pageHeaderJsonData.accessibilityPreferences.keyboardOnlyNavigation:!1}});Function.prototype.method=function(a,b){this.prototype[a]=b;return this};RegExp.escape=function(){var a=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\$|\\(|\\)|\\[|\\]|\\{|\\}|\\\\|\\\x26|\\^)","g");return function(b){return b.replace(a,"\\$1")}}();e.defineNonEnumPropIfNeeded(Array.prototype,
"splice",function(a,b){for(var c=[],d=arguments.length-2,f=this.length+d-b,g=0;g<b;++g)c[g]=this[a+g];var m=a+b,e=a+d,h=this.length-m;if(m<e)for(g=h;0<=--g;)this[e+g]=this[m+g];else if(m>e)for(g=0;g<h;++g)this[e+g]=this[m+g];for(g=0;g<d;++g)this[g+a]=arguments[g+2];this.length=f;return c});e.defineNonEnumPropIfNeeded(Array.prototype,"remove",function(a){for(var b=0;b<this.length;b++)a==this[b]&&(this.splice(b,1),b--)});e.defineNonEnumPropIfNeeded(Array.prototype,"contains",function(a){for(var b=this.length,
c=0;c<b;c++)if(this[c]===a)return!0;return!1});(function(){var a=Array.prototype.slice;try{a.call(document.documentElement)}catch(b){e.defineNonEnumProp(Array.prototype,"slice",function(b,d){d="undefined"!==typeof d?d:this.length;if("[object Array]"===Object.prototype.toString.call(this))return a.call(this,b,d);var f,g=[],m;f=this.length;var e=b||0,e=0<=e?e:Math.max(0,f+e);m="number"==typeof d?Math.min(f,d):f;0>d&&(m=f+d);m-=e;if(0<m)if(g=Array(m),this.charAt)for(f=0;f<m;f++)g[f]=this.charAt(e+f);
else for(f=0;f<m;f++)g[f]=this[e+f];return g})}})();e.defineNonEnumPropIfNeeded(Array.prototype,"reduce",function(a){if(null==this)throw new TypeError("Array.prototype.reduce called on null or undefined");if("function"!==typeof a)throw new TypeError(a+" is not a function");var b=Object(this),c=b.length>>>0,d=0,f;if(2==arguments.length)f=arguments[1];else{for(;d<c&&!d in b;)d++;if(d>=c)throw new TypeError("Reduce of empty array with no initial value");f=b[d++]}for(;d<c;d++)d in b&&(f=a(f,b[d],d,b));
return f});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});e.defineNonEnumPropIfNeeded(Array.prototype,"forEach",function(a,b){for(var c=0,d=this.length;c<d;++c)a.call(b,this[c],c,this)});e.defineNonEnumPropIfNeeded(Array.prototype,"every",function(a,b){var c,d;if(null==this)throw new TypeError("this is null or not defined");var f=Object(this),g=f.length>>>0;if("function"!==typeof a)throw new TypeError;1<arguments.length&&(c=b);for(d=0;d<g;){var m;
if(d in f&&(m=f[d],!a.call(c,m,d,f)))return!1;d++}return!0});e.defineNonEnumPropIfNeeded(Array.prototype,"some",function(a){if(null==this)throw new TypeError("Array.prototype.some called on null or undefined");if("function"!==typeof a)throw new TypeError;for(var b=Object(this),c=b.length>>>0,d=2<=arguments.length?arguments[1]:void 0,f=0;f<c;f++)if(f in b&&a.call(d,b[f],f,b))return!0;return!1});e.defineNonEnumPropIfNeeded(Array.prototype,"indexOf",function(a,b){if(void 0===this||null===this)throw new TypeError('"this" is null or not defined');
var c=this.length>>>0;b=+b||0;Infinity===Math.abs(b)&&(b=0);0>b&&(b+=c,0>b&&(b=0));for(;b<c;b++)if(this[b]===a)return b;return-1});e.defineNonEnumPropIfNeeded(Array.prototype,"filter",function(a){if(void 0===this||null===this)throw new TypeError;var b=Object(this),c=b.length>>>0;if("function"!==typeof a)throw new TypeError;for(var d=[],f=2<=arguments.length?arguments[1]:void 0,g=0;g<c;g++)if(g in b){var m=b[g];a.call(f,m,g,b)&&d.push(m)}return d});e.defineNonEnumPropIfNeeded(String.prototype,"quote",
function(){return'"'+this.replace(/(["\\])/g,"\\$1").replace(/\r\n?|\n/g,"\\n")+'"'});e.defineNonEnumPropIfNeeded(String.prototype,"trim",function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});e.defineNonEnumPropIfNeeded(String.prototype,"equalsIgnoreCase",function(a){return this.toLowerCase().toUpperCase()==a.toLowerCase().toUpperCase()});e.defineNonEnumPropIfNeeded(String.prototype,"entityify",function(){return this.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;")});
e.defineNonEnumPropIfNeeded(String.prototype,"truncateByLength",function(a){if(-1<a)return this.length>a?this.substring(0,a)+"...":this});Math.sgn=function(a){return 0==a?0:0<a?1:-1};Math.randSgn=function(){var a=Math.random();return a<1/3?-1:a>=2/3?1:0}})();
"sapui5"==surj.Util.getUIMode()&&function(){if(!Element.prototype.addEventListener){var k=[],h=function(a,b){var c=this,d=function(a){a.target=a.srcElement;a.currentTarget=c;b.handleEvent?b.handleEvent(a):b.call(c,a)};if("DOMContentLoaded"==a){var f=function(a){"complete"==document.readyState&&d(a)};document.attachEvent("onreadystatechange",f);k.push({object:this,type:a,listener:b,wrapper:f});if("complete"==document.readyState){var g=new Event;g.srcElement=window;f(g)}}else this.attachEvent("on"+
a,d),k.push({object:this,type:a,listener:b,wrapper:d})},e=function(a,b){for(var c=0;c<k.length;){var d=k[c];if(d.object==this&&d.type==a&&d.listener==b){"DOMContentLoaded"==a?this.detachEvent("onreadystatechange",d.wrapper):this.detachEvent("on"+a,d.wrapper);k.splice(c,1);break}++c}};Element.prototype.addEventListener=h;Element.prototype.removeEventListener=e;HTMLDocument&&(HTMLDocument.prototype.addEventListener=h,HTMLDocument.prototype.removeEventListener=e);Window&&(Window.prototype.addEventListener=
h,Window.prototype.removeEventListener=e)}}();
"sapui5"==surj.Util.getUIMode()&&!("getComputedStyle"in this)&&(this.getComputedStyle=function(){function k(a,b,c,d){var f=b[c];b=parseFloat(f);f=f.split(/\d/)[0];d=null!=d?d:/%|em/.test(f)&&a.parentElement?k(a.parentElement,a.parentElement.currentStyle,"fontSize",null):16;a="fontSize"==c?d:/width/i.test(c)?a.clientWidth:a.clientHeight;return"em"==f?b*d:"in"==f?96*b:"pt"==f?96*b/72:"%"==f?b/100*a:b}function h(a,b){var c="border"==b?"Width":"",d=b+"Top"+c,f=b+"Right"+c,g=b+"Bottom"+c,c=b+"Left"+c;
a[b]=(a[d]==a[f]==a[g]==a[c]?[a[d]]:a[d]==a[g]&&a[c]==a[f]?[a[d],a[f]]:a[c]==a[f]?[a[d],a[f],a[g]]:[a[d],a[f],a[g],a[c]]).join(" ")}function e(a){var b=a.currentStyle,c=k(a,b,"fontSize",null);for(property in b)if(/width|height|margin.|padding.|border.+W/.test(property)&&"auto"!==this[property])this[property]=k(a,b,property,c)+"px";else if("styleFloat"===property)this["float"]=b[property];else try{this[property]=b[property]}catch(d){}h(this,"margin");h(this,"padding");h(this,"border");this.fontSize=
c+"px";return this}e.prototype={constructor:e,getPropertyPriority:function(){},getPropertyValue:function(a){return this[a]||""},item:function(){},removeProperty:function(){},setProperty:function(){},getPropertyCSSValue:function(){}};return function(a){return new e(a)}}(this));
(function(){function k(b){var c=new Date;h[b]=c;surj&&surj.Logger&&"TRS"!=b&&h.TRS&&surj.Logger.error(b+": "+(((c.getTime()-h[e])/1E3).toFixed(3)+" seconds"));c=new Image;c.src=a+"?perfPhase\x3d"+b;return c}var h={},e="TRS",a=IMAGES["/ui/surj/img/_.gif"];h.TIL=new Date;window.PerfPhase={renderStartLoaded:function(){return k(e)},interactivePageLoaded:function(){return k("TIP")},keyContentLoaded:function(){return this.mainContentLoaded()},mainContentLoaded:function(){return k("TML")},completePageLoaded:function(){return this.supplContentLoaded()},
supplContentLoaded:function(){return k("TSL")}}})();
(function(){function k(a,b){b=b||[];for(var c=0;c<a.length;c++)b.push(a[c]);return b}for(var h=surj.define("sap.sf.surj.Logger",{isEnabled:function(a){return!!b[a]},setEnabled:function(a,c){b[a]=c},enableLoggers:function(){for(var d=0;d<a.length;d++)this.setEnabled(a[d],!0)},addLogListener:function(a,b){this._addEventListener("log",a,b)},removeLogListener:function(a){this._removeEventListener("log",a)},setConsoleEnabled:function(a){a?this.addLogListener(e):this.removeLogListener(e)},getLogger:function(){for(var b=
{isEnabled:function(a){return surj.Logger.isEnabled(a)}},c=k(arguments),g=0;g<a.length;g++)(function(a){b[a.toUpperCase()]=a;b[a]=function(){var b=[c.join(" ")+": "];k(arguments,b);surj.Logger[a].apply(surj.Logger,b)}})(a[g]);return b},_addEventListener:function(a,b,c){var e=this._events||(this._events={});(e[a]||(e[a]=[])).push({handler:b,callback:c?c:null})},_removeEventListener:function(a,b){var c=this._events,e;if(c&&(e=c[a])){for(var h=e.length;0<=--h;)e[h].handler===b&&e.splice(h,1);e.length||
delete c[a]}},dispatch:function(a,b){b.type=a;b.target=this;var c=this._events;if(c&&(c=c[b.type])){for(var c=c.slice(0),e,h=0;h<c.length;++h)try{var k=c[h].handler,q=c[h].callback;if(q)k[q](b);else k.handleEvent(b)}catch(l){e=l}if(e)throw e;}}}),e={handleEvent:function(a){var b=a.level;a=a.messages;for(var c,e,h=0;h<a.length;h++)if(e=a[h],e instanceof Error){c=[h,1];c.push(e);if(e.stack)c.push(" Stack: ",e.stack);else if(e.fileName&&c.push(" File Name: ",e.fileName,"."),e.lineNumber||e.lineNo)c.push(" Line Number: ",
e.lineNumber||e.lineNo,".");a.splice.apply(a,c);h+=c.length-1}"undefined"!=typeof console&&console.log&&(b=["["+b.toUpperCase()+"] "].concat(a),"function"==typeof console.log.apply?console.log.apply(console,b):console.log(b.join("")))}},a=["error","warn","debug","info"],b={error:!0},c=0;c<a.length;c++)(function(a){h[a.toUpperCase()]=a;h[a]=function(){b[a]&&this.dispatch("log",{level:a,messages:k(arguments)})}})(a[c]);h.setConsoleEnabled(!0);c="undefined"!=typeof RESOURCES&&RESOURCES["/ui/surj/js/Logger.js"];
"string"==typeof c&&!/[a-f\d]{32}\.js$/.test(c)&&h.enableLoggers()})();
(function(){function k(a,b){var c=q({},a||{});if(b)for(var d in b)if(!a||"undefined"==typeof a[d])c[d]=b[d];return c}function h(){throw Error("Do not directly instantiate.");}function e(a){if("object"==typeof a&&!Array.isArray(a)){for(var b=[Date],c=0;c<b.length;c++)if(a instanceof b[c])return!1;return!0}return!1}function a(a,b,c){var d=!0;if("object"==typeof a&&null!==a)for(var e in b){var f=c&&[];l.validate(a[e],b[e],f)||(d=!1,c&&f.forEach(function(b){c.push(["[Invalid Object Attribute] Attribute: ",
e,", Object: ",a,": "].concat(b))}))}else d=!1,c&&c.push(["Invalid object, expected: A non-null object, found: ",a]);return d}function b(a,b){if(null===a||void 0===a)return!0;b&&b.push(["Invalid undefined, expected either null or undefined, found: ",a]);return!1}function c(a,b,c){var d=a===b;d||c&&c.push(["Invalid exact, expected: ",b,", value: ",a]);return d}function d(a,b){this.subType=a;this.minCount=b||0}function f(a){this.values=[];for(var b=0;b<a.length;b++)this.values.push(a[b])}function g(a){if("string"==
typeof a)this._regex=RegExp(a);else if(a instanceof RegExp)this._regex=a;else throw Error("RegexType: you must pass a string or a RegExp object");}function m(a){this._args=Array.prototype.slice.call(a,0)}function t(a){this._class=a}function s(a,b,c){function d(){}d.prototype=b.prototype;b=new d;for(var e in c)b[e]=c[e];a.prototype=b}function q(a,b){if(window.juic&&juic.set)return juic.set(a,b);if(window.jQuery)return jQuery.extend(a,b);throw Error("[Config] Requires jQuery or juic");}var l=surj.define("sap.sf.surj.Config",
function(a,b,c){var d=q({},a||{});if(b)for(var e in b)if(!a||"undefined"==typeof a[e])d[e]=b[e];c&&(a=[],l.validate(d,c,a)||(a.forEach(function(a){surj.Logger.error.apply(surj.Logger,a)}),assert(!1,"Config: There was at least one error")));q(this,d)});l.convertArguments=function(a,b,c,d){var f={};b.forEach(function(b,c){f[b]=a[c]});if(1==a.length&&null!=a[0])if(b=a[0],d&&!l.validate(k(f,c),d))f=b;else if(e(b)&&(!d||l.validate(k(b,c),d)))throw Error("configArgs called with one argument, but the validation was not strict enough. Make sure to add at some validation");
return new l(f,c,d)};l.validate=surj.validate=function(d,e,f){var g=!1;switch(typeof e){case "string":switch(e){case "*":null!==d&&void 0!==d?g=!0:(f&&f.push(["Invalid required value, expected anything not null or undefined, found: ",d]),g=!1);break;case "string":case "number":case "object":case "undefined":case "boolean":case "function":typeof d===e?g=!0:(f&&f.push(["Invalid type, expected: ",e,", found: ",typeof d,", value: ",d]),g=!1);break;default:g=c(d,e,f)}break;case "object":switch(!0){case null===
e:g=b(d,f);break;case e instanceof h:g=e.validate(d,f);break;case Array.isArray(e):for(var g=!1,k=0;k<e.length;k++)l.validate(d,e[k],f)&&(g=!0);break;default:g=a(d,e,f)}break;case "function":d instanceof e?g=!0:(f&&f.push(["Invalid value with wrong type, expected an object of type: ",e.name,", but found this value: ",d]),g=void 0);break;case "undefined":g=b(d,f);break;default:g=c(d,e,f)}return g};l.arrayType=function(a,b){return new d(a,b)};l.and=function(){return new m(arguments)};l.classType=function(a){return new t(a)};
l.enumType=function(a){return new f(arguments)};l.htmlElementType=function(a){var b={nodeType:1};"string"==typeof a&&(b.nodeName=a.toUpperCase());return b};l.regexType=function(a){return new g(a)};l.dataType=function(a){if(window.jQuery&&jQuery.sap){jQuery.sap.require("sap.ui.base.DataType");jQuery.sap.declare(a);var b=sap.ui.base.DataType.getType(a);if(b)return a=function(){},a.prototype=h.prototype,a=new a,a.validate=function(a){return!b.isValid||b.isValid(a)},a}throw Error(a+" is not a defined type");
};l.createDataType=function(a,b){if(window.jQuery&&jQuery.sap){jQuery.sap.require("sap.ui.base.DataType");jQuery.sap.declare(a);var c=sap.ui.base.DataType.createType(a,{isValid:function(a){return surj.validate(a,b)}});jQuery.sap.setObject(a,c);return c}throw Error("ui5 not found");};l.createEnum=function(a,b){if(window.jQuery&&jQuery.sap)return jQuery.sap.declare(a),jQuery.sap.require("sap.ui.base.DataType"),sap.ui.base.DataType.createType(a,{isValid:function(a){return"undefined"!=typeof b[a]}}),
jQuery.sap.setObject(a,b),b;throw Error("ui5 not found");};h.prototype.validate=function(a,b){throw Error("A validator must implement the validate function!");};l.ValidatorType=h;s(d,h,{validate:function(a,b){var c=Array.isArray(a);c?(c=a.length>=this.minCount)?void 0!==this.subType&&a.forEach(function(a,d){var e=b&&[];l.validate(a,this.subType,e)||(c=!1,b&&b.push(["Invalid array element at position: ",d,"."]),b&&e.forEach(function(a){b.push(["[Array Element Error] "].concat(a))}))},this):b&&b.push(["Invalid array, expected: at least ",
this.minCount," item(s), found: ",a.length," item(s)"]):b&&b.push(["Invalid array, expected: array, found: ",a]);return c}});s(f,h,{validate:function(a,b){for(var c=!1,d=0;d<this.values.length;d++)if(this.values[d]===a){c=!0;break}c||b&&b.push(["Invalid enum, expected: one of ",this.values,", found: ",a]);return c}});s(g,h,{validate:function(a,b){var c=!1;"string"==typeof a?(c=this._regex.test(a))||b&&b.push(["Invalid regex value, expected: matches ",this._regex,", found: ",a]):b&&b.push(["Invalid regex value, expected: a string, found: ",
a]);return c}});s(m,h,{validate:function(a,b){for(var c=!0,d=0;d<this._args.length;d++)c=l.validate(a,this._args[d],b)&&c;return c}});s(t,h,{validate:function(a,b){var c=!1;a&&a.prototype&&(c=function(){},c.prototype=a.prototype,c=new c instanceof this._class);c||b.push(["Invalid constructor, expected constructor extending: ",this._class,", found: ",a]);return c}})})();