/**
 * XMLHttpRequest.js Copyright (C) 2011 Sergey Ilinsky (http://www.ilinsky.com)
 *
 * This work is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This work is distributed in the hope that it will be useful,
 * but without any warranty; without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
/* Note: Changes have been done for enhancements and perflog requirements in the application */
window.DEF_FLAG_OF_XMLHTTPREQUEST_JS||(window.DEF_FLAG_OF_XMLHTTPREQUEST_JS=!0,function(){function u(){this._object=k&&!w?new k:new window.ActiveXObject("Microsoft.XMLHTTP");this._listeners=[];"withCredentials"in this._object&&(this.withCredentials=this._object.withCredentials);"upload"in this._object&&(this.upload=this._object.upload)}function a(){return new u}function p(e){a.onreadystatechange&&a.onreadystatechange.apply(e);e.dispatchEvent({type:"readystatechange",bubbles:!1,cancelable:!1,timeStamp:new Date+
0});a.postreadystatechange&&a.postreadystatechange.apply(e)}function v(a){try{a.responseText=a._object.responseText}catch(g){}try{var b;var c=a._object,d=c.responseXML,f=c.responseText;m&&f&&d&&!d.documentElement&&c.getResponseHeader("Content-Type").match(/[^\/]+\/[^\+]+\+xml/)&&(d=new window.ActiveXObject("Microsoft.XMLDOM"),d.async=!1,d.validateOnParse=!1,d.loadXML(f));b=d&&(m&&d.parseError&&0!==d.parseError.errorCode||d.documentElement&&"parsererror"==d.documentElement.tagName)?null:d;a.responseXML=
b}catch(g){}try{a.status=a._object.status}catch(g){}try{a.statusText=a._object.statusText}catch(g){}}function q(a){a._object.onreadystatechange=new window.Function}var k=window.XMLHttpRequest,r=!!window.controllers,m=!!window.document.namespaces,w=m&&window.navigator.userAgent.match(/MSIE 7.0/);a.prototype=u.prototype;r&&k.wrapped&&(a.wrapped=k.wrapped);a.UNSENT=0;a.OPENED=1;a.HEADERS_RECEIVED=2;a.LOADING=3;a.DONE=4;a.prototype.UNSENT=a.UNSENT;a.prototype.OPENED=a.OPENED;a.prototype.HEADERS_RECEIVED=
a.HEADERS_RECEIVED;a.prototype.LOADING=a.LOADING;a.prototype.DONE=a.DONE;a.prototype.readyState=a.UNSENT;a.prototype.responseText="";a.prototype.responseXML=null;a.prototype.status=0;a.prototype.statusText="";a.prototype.priority="NORMAL";a.prototype.onreadystatechange=null;a.onreadystatechange=null;a.postreadystatechange=null;a.onopen=null;a.onsend=null;a.onabort=null;a.prototype.open=function(e,b,c,d,f){var g=e.toLowerCase();if("connect"==g||"trace"==g||"track"==g)throw Error(18);delete this._headers;
3>arguments.length&&(c=!0);this._async=c;var h=this,k=this.readyState,t=null;m&&c&&(t=function(){k!=a.DONE&&(q(h),h.abort())},window.attachEvent("onunload",t));a.onopen&&a.onopen.apply(this,arguments);"withCredentials"in this._object&&this._object.withCredentials!=this.withCredentials&&(this._object.withCredentials=this.withCredentials);4<arguments.length?this._object.open(e,b,c,d,f):3<arguments.length?this._object.open(e,b,c,d):this._object.open(e,b,c);if(!this.doesAllowCORS()){var l=b?b.indexOf("//"):
-1;if(0==l||0<l&&":"==b.charAt(l-1)){var n=window.location;(g=n.origin)?0==l&&(g=g.substring(g.indexOf("//"))):(g=(0==l?"":n.protocol)+"//"+n.hostname,(l=n.port)&&(g+=":"+l));0!=b.toLowerCase().indexOf(g.toLowerCase())&&this.setRequestHeader("X-Allow-CORS",!0)}}this.readyState=a.OPENED;p(this);this._object.onreadystatechange=function(){if(!r||c)h.readyState=h._object.readyState,v(h),h._aborted?h.readyState=a.UNSENT:h.readyState==a.DONE&&(delete h._data,q(h),m&&c&&window.detachEvent("onunload",t),
k!=h.readyState&&p(h),k=h.readyState)}};a.prototype.send=function(e){var b="",c=window.pageHeaderJsonData,d;a.onsend&&a.onsend.apply(this,arguments);arguments.length||(e=null);e&&e.nodeType&&(e=window.XMLSerializer?(new window.XMLSerializer).serializeToString(e):e.xml,this._headers["Content-Type"]||this._object.setRequestHeader("Content-Type","application/xml"));if(!this.doesAllowCORS()&&(this._object.setRequestHeader("X-Ajax-Token",String(window.ajaxSecKey)),c)){c.companyId&&(b+="companyId="+encodeURIComponent(c.companyId));
if(d=c.pageInfo)d.moduleId&&(b+="&moduleId="+encodeURIComponent(d.moduleId)),d.pageId&&(b+="&pageId="+encodeURIComponent(d.pageId)),d.pageQualifier&&(b+="&pageQualifier="+encodeURIComponent(d.pageQualifier));c.uiVersion&&(b+="&uiVersion="+encodeURIComponent(c.uiVersion));(c=c.userInfo)&&c.id&&(b+="&userId="+encodeURIComponent(c.id));b&&"&"==b.charAt(0)&&(b=b.substring(1));b&&this._object.setRequestHeader("X-SAP-Page-Info",b)}this._data=e;a:if(this._object.send(this._data),r&&!this._async)for(this.readyState=
a.OPENED,v(this);this.readyState<a.DONE;)if(this.readyState++,p(this),this._aborted)break a};a.prototype.abort=function(){a.onabort&&a.onabort.apply(this,arguments);this.readyState>a.UNSENT&&(this._aborted=!0);this._object.abort();q(this);this.readyState=a.UNSENT;delete this._data};a.prototype.getAllResponseHeaders=function(){return this._object.getAllResponseHeaders()};a.prototype.getResponseHeader=function(a){return this._object.getResponseHeader(a)};a.prototype.setRequestHeader=function(a,b){this._headers||
(this._headers={});this._headers[a]=b;if("X-Allow-CORS"!==a)return this._object.setRequestHeader(a,b)};a.prototype.addEventListener=function(a,b,c){for(var d=0,f;f=this._listeners[d];d++)if(f[0]==a&&f[1]==b&&f[2]==c)return;this._listeners.push([a,b,c])};a.prototype.removeEventListener=function(a,b,c){for(var d=0,f;(f=this._listeners[d])&&(f[0]!=a||f[1]!=b||f[2]!=c);d++);f&&this._listeners.splice(d,1)};a.prototype.dispatchEvent=function(a){a={type:a.type,target:this,currentTarget:this,eventPhase:2,
bubbles:a.bubbles,cancelable:a.cancelable,timeStamp:a.timeStamp,stopPropagation:function(){},preventDefault:function(){},initEvent:function(){}};"readystatechange"==a.type&&this.onreadystatechange&&(this.onreadystatechange.handleEvent||this.onreadystatechange).apply(this,[a]);for(var b=0,c;c=this._listeners[b];b++)c[0]!=a.type||c[2]||(c[1].handleEvent||c[1]).apply(this,[a])};a.prototype.doesAllowCORS=function(){return this._headers&&this._headers["X-Allow-CORS"]};a.prototype.toString=function(){return"[object XMLHttpRequest]"};
a.toString=function(){return"[XMLHttpRequest]"};window.Function.prototype.apply||(window.Function.prototype.apply=function(a,b){b||(b=[]);a.__func=this;a.__func(b[0],b[1],b[2],b[3],b[4]);delete a.__func});window.XMLHttpRequest=a}());
