function RBSummaryTable(a){this.register();this._init(a)}
RBSummaryTable.prototype=function(){return set(new Component,{_init:function(a){this._isGroup=(this._config=a)&&"undefined"!=typeof this._config.isGroup?this._config.isGroup:!1;this._canDelete=this._config&&"undefined"!=typeof this._config.canDelete?this._config.canDelete:!1;this._canDeleteGroup=this._config&&"undefined"!=typeof this._config.canDeleteGroup?this._config.canDeleteGroup:!1;this._allowExpandCollapse=this._config&&"undefined"!=typeof this._config.allowExpandCollapse?this._config.allowExpandCollapse:
!0;this._title=this._config&&"undefined"!=typeof this._config.title?this._config.title:"";this._detailTitle=this._config&&"undefined"!=typeof this._config.detailTitle?this._config.detailTitle:"";this._expanded=this._config&&this._config.expanded?this._config.expanded:!0;this._items=[]},setCanDeleteGroup:function(a){this._canDeleteGroup=a},setCanDelete:function(a){this._canDelete=a},clear:function(){this._items.length=0;this.reRenderMainTable()},removeRow:function(a){this._items.splice(a,1);this.reRenderMainTable();
this.dispatch("deleteRow",{index:a})},addRow:function(a,b,c){b||(b=this._items.length);this._items.splice(b,0,{data:a,removeable:!c});this.reRenderMainTable()},reRender:function(){if($(this.id+"RBSummaryTable")){var a=[];this._getContents(a);$(this.id+"RBSummaryTable").innerHTML=a.join("")}},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'RBSummaryTable" class\x3d"rb_summary_wrapper',this._expanded?" rb_summary_expanded":" rb_summary_collapsed",'"\x3e');this._getContents(a);a.push("\x3c/div\x3e")},
reRenderMainTable:function(){if($(this.id+"RBSummaryTableMain")){var a=[];this._getMainTableContents(a);$(this.id+"RBSummaryTableMain").innerHTML=a.join("")}},_handleDeleteTable:function(){this.dispatch("deleteTable")},_toggleExpand:function(){this._expanded=!this._expanded;var a=juic.$(this.id+"rbSummaryToggle");$(this.id+"RBSummaryTable")&&a&&(this._expanded?(a.innerHTML="\x26#xe1f0",Util.addClass(this.id+"RBSummaryTable","rb_summary_expanded"),Util.removeClass(this.id+"RBSummaryTable","rb_summary_collapsed")):
(a.innerHTML="\x26#xe1ef",Util.addClass(this.id+"RBSummaryTable","rb_summary_collapsed"),Util.removeClass(this.id+"RBSummaryTable","rb_summary_expanded")))},_renderMainTable:function(a){a.push('\x3cdiv id\x3d"',this.id,'RBSummaryTableMain" class\x3d"rb_summary_main_table"\x3e');this._getMainTableContents(a);a.push("\x3c/div\x3e")},_getMainTableContents:function(a){if(this._items){a.push('\x3cul class\x3d"rb_summary_main_list clear_all"\x3e');for(var b=0;b<this._items.length;b++){var c=this._items[b].data;
a.push('\x3cli class\x3d"clear_all ',b%2?"odd":"even",'"\x3e');a.push('\x3cdiv class\x3d"globalPortletLinkTextColor link rb_summary_main_table_header floatleft"\x3e');c[0].renderHtml(a);a.push("\x3c/div\x3e");this._canDelete&&this._items[b].removeable&&(a.push('\x3cdiv class\x3d"sapIcon globalPortletLinkTextColor link floatright" style \x3d "cursor:pointer;padding-top : 10px;font-size : 16px;font-weight : normal;"\x3e'),a.push('\x3ca class\x3d"link" href\x3d"javascript:;" onclick\x3d"',this.fireCode("removeRow",
b),'return false;"\x3e\x26#xe03d\x3c/a\x3e\x3c/div\x3e'));a.push('\x3cdiv class\x3d"globalPortletBodyTextColor rb_summary_main_table_content"\x3e');c[1].renderHtml(a);a.push("\x3c/div\x3e");a.push("\x3c/li\x3e")}a.push("\x3c/ul\x3e")}},_getContents:function(a){this._allowExpandCollapse&&(this._detailTitle?(a.push('\x3cdiv class\x3d"elementBorder globalPortletDimmedTextColor"\x3e\x3cspan\x3e\x3ca id\x3d"',this.id,'rbSummaryToggle" class\x3d"rb_summary_arrow sapIcon" onclick\x3d"',this.fireCode("_toggleExpand"),
'return false;"\x3e',this._expanded?"\x26#xe1f0 ":"\x26#xe1ef ","\x3c/a\x3e\x3c/span\x3e"),a.push('\x3cspan class\x3d"rb_top_title_help_wrap globalPortletDimmedTextColor"\x3e'),this._detailTitle.renderHtml(a),a.push("\x3c/span\x3e")):a.push('\x3cdiv class\x3d"elementBorder globalPortletDimmedTextColor"\x3e\x3cspan\x3e\x3ca id\x3d"',this.id,'rbSummaryToggle" class\x3d"rb_summary_arrow sapIcon" onclick\x3d"',this.fireCode("_toggleExpand"),'return false;"\x3e',this._expanded?"\x26#xe1f0 ":"\x26#xe1ef ",
"\x3c/a\x3e\x3c/span\x3e"));this._title&&a.push('\x3cspan class\x3d"rb_summary_title globalPortletDimmedTextColor"\x3e',this._title,"\x3c/span\x3e");this._canDeleteGroup&&(a.push('\x3cspan class\x3d"globalPortletLinkTextColor"\x3e\x3ca href\x3d"javascript:;" class\x3d"rb_smmary_delete_icon" title\x3d"',MSGS.ANALYTICS_ADHOC_REPORT_BUILDER_FILTERVIEW_DELTEGROUP_LBL,'"'),a.push(' onclick\x3d"',this.fireCode("_handleDeleteTable"),';return false;"\x3e',MSGS.ANALYTICS_ADHOC_REPORT_BUILDER_FILTERVIEW_DELTEGROUP_LBL,
"\x3c/a\x3e\x3c/span\x3e"));this._allowExpandCollapse&&a.push("\x3c/div\x3e");a.push('\x3cdiv class\x3d"clear"\x3e\x3c/div\x3e');this._renderMainTable(a);if(this._bottomLeftComponent||this._bottomRightComponent)a.push('\x3ctable id\x3d"',this.id,'RBSummaryBottomTable" class\x3d"rb_summary_bottom_table"\x3e'),a.push('\x3ctr\x3e\x3ctd\x3e\x3cdiv id\x3d"',this.id,'RBSummaryBottomLeft" class\x3d"globalPortletLinkTextColor"\x3e'),this._bottomLeftComponent&&this._bottomLeftComponent.renderHtml(a),a.push('\x3c/div\x3e\x3c/td\x3e\x3ctd\x3e\x3cdiv id\x3d"',
this.id,'RBSummaryBottomRight"\x3e'),this._bottomRightComponent&&this._bottomRightComponent.renderHtml(a),a.push("\x3c/div\x3e\x3c/td\x3e\x3c/table\x3e")},handleEvent:function(a){},setBottomLeftComponent:function(a){this._bottomLeftComponent=a;$(this.id+"RBSummaryBottomLeft")&&this._bottomLeftComponent.render(this.id+"RBSummaryBottomLeft")},setBottomRightComponent:function(a){this._bottomRightComponent=a;$(this.id+"RBSummaryBottomRight")&&this._bottomRightComponent.render(this.id+"RBSummaryBottomRight")},
setTitle:function(a){this._title=a}})}();function RBSummaryTableLayout(a){this.register();this.init(a)}
RBSummaryTableLayout.prototype=function(){return set(new Component,{init:function(a){this._isGroup=(this._config=a)&&void 0!=this._config.isGroup?this._config.isGroup:!1;this._canDelete=this._config&&void 0!=this._config.canDelete?this._config.canDelete:!0;this._allowExpandCollapse=this._config&&void 0!=this._config.allowExpandCollapse?this._config.allowExpandCollapse:!0;this._canDeleteGroup=this._config&&this._config.canDelete&&(void 0!==this._config.canDeleteGroup?this._config.canDeleteGroup:!0);
this._title=this._config&&this._config.title?this._config.title:"";this._detailTitle=this._config&&"undefined"!=typeof this._config.detailTitle?this._config.detailTitle:"";this._tableNamePrefix="rb_tb_";this._rowNamePrefix="rb_t_r_";this._cellNamePrefix="rb_t_c_";this._lastRowIndex=-1;this._expanded=!0;this._items=[];this._deleteTableLink=new SFSimpleLink("delete group","handleDeleteTable",{},{cssClass:"globalPortletLinkTextColor link"});this._deleteTableLink.addEventListener("action",this);this._nonDeletableItemIndexes=
[]},setItems:function(a){this._items=a},getItems:function(){return this._items},setTitle:function(a){this._title=a},setBottomLeftComponent:function(a){this._bottomLeftComponent=a},setBottomRightComponent:function(a){this._bottomRightComponent=a},setNonDeletableItems:function(a){assert(this._canDelete,"[RBSummaryTableLayout]: Use 'canDelete: false' to disable trash cans on all rows.");for(var b=0;a&&b<a.length;b++)this._nonDeletableItemIndexes.push(a[b])},getRowId:function(a){return this._rowNamePrefix+
a+"_"+this.id},getCellId:function(a,b){return this._cellNamePrefix+a+"_"+b+"_"+this.id},getSize:function(){return this._items.length},setIsGroup:function(a){this._isGroup=a},setAllowExpandCollapse:function(a){this._allowExpandCollapse=a},setCanDelete:function(a){this._canDelete=a},renderHtml:function(a){a.push('\x3cdiv class\x3d"rb_s_bk"\x3e');this._allowExpandCollapse&&(this._detailTitle?(a.push('\x3cdiv class\x3d"elementBorder globalPortletDimmedTextColor"\x3e'),a.push('\x3cspan\x3e\x3ca id\x3d"',
this.id,'Arrow" class\x3d"rb_summary_actionArrow sapIcon" onclick\x3d"',this.fireCode("handleCollapseOrExpand"),'return false;"\x3e',this._getArrowIcon(),"\x3c/a\x3e\x3c/span\x3e"),a.push('\x3cspan class\x3d"rb_top_title_help_wrap globalPortletDimmedTextColor"\x3e'),this._detailTitle.renderHtml(a),a.push("\x3c/span\x3e")):a.push('\x3cdiv class\x3d"elementBorder globalPortletDimmedTextColor"\x3e\x3cspan\x3e\x3ca id\x3d"',this.id,'Arrow" class\x3d"rb_summary_actionArrow sapIcon" onclick\x3d"',this.fireCode("handleCollapseOrExpand"),
'return false;"\x3e',this._getArrowIcon(),"\x3c/a\x3e\x3c/span\x3e"));this._title&&a.push('\x3cspan class\x3d"rb_s_title floatleft"\x3e',this._title,"\x3c/span\x3e");a.push('\x3cdiv id\x3d"rb_del_grp',this.id,'"\x3e');this._renderDeleteGroupLink(a);a.push("\x3c/div\x3e");this._allowExpandCollapse&&a.push("\x3c/div\x3e");a.push('\x3cdiv class\x3d"clear"\x3e\x3c/div\x3e');this._renderMainTableContent(a);a.push("\x3c/div\x3e")},_renderDeleteGroupLink:function(a){this._canDeleteGroup&&this._items&&(a.push('\x3cdiv class\x3d"sapIcon globalPortletLinkTextColor link floatleft" style \x3d "cursor:pointer;padding-top : 10px;font-size : 16px;font-weight : normal;"'),
a.push(' onclick\x3d"',this.fireCode("handleDeleteTable"),'return false;"\x3e\x26#xe03d\x3c/div\x3e'),this._deleteTableLink.renderHtml(a))},_renderMainTableContent:function(a){if(this._items){a.push('\x3ctable id\x3d"'+this._tableNamePrefix+this.id+'"class\x3d"rb_summary" cellspacing\x3d"1" cellpadding\x3d"0" border\x3d"0" style\x3d"width: 100%;"\x3e\x3ctbody\x3e');for(var b=0;b<this._items.length;b++)this._renderRow(a,this._items[b],b),this._lastRowIndex++;a.push("\x3c/tbody\x3e\x3c/table\x3e")}},
_renderTableBottomContent:function(a){a.push('\x3ctable id\x3d"'+this._tableNamePrefix+this.id+':bottom" class\x3d"rb_summary_bottom" cellspacing\x3d"1" cellpadding\x3d"0" border\x3d"0" style\x3d"width: 100%;"\x3e');a.push('\x3ctr\x3e\x3ctd class\x3d"rp_s_b_l"\x3e');this._bottomLeftComponent&&this._bottomLeftComponent.renderHtml(a);a.push('\x3c/td\x3e\x3ctd class\x3d"rp_s_b_e"\x3e');this._bottomRightComponent&&this._bottomRightComponent.renderHtml(a);a.push("\x3c/td\x3e\x3c/table\x3e")},_renderRow:function(a,
b,c){b&&0<b.length&&(a.push('\x3ctr id\x3d"',this.getRowId(c),'"\x3e'),this._renderColumns(a,b,c),a.push("\x3c/tr\x3e"))},_renderColumns:function(a,b,c){if(b&&0<b.length){for(var d=b.length,e=0;e<d;e++){var f=b[e];if(f){var g=this.getCellId(c,e);a.push('\x3ctd id\x3d"',g,'" class\x3d"');a.push(this._getCellClass(c,e,d,this._canDelete));a.push('"\x3e');f.renderHtml(a);a.push("\x3c/td\x3e")}}this._canDelete&&(-1==this._nonDeletableItemIndexes.indexOf(c)?this._renderTrash(a,c,e,d,!1):this._renderTrash(a,
c,e,d,!0))}},_renderTrash:function(a,b,c,d,e){!this._canDeleteGroup&&0===b&&!this._canDelete?(c=this._getCellClass(b,c,d,!0),a.push('\x3ctd class\x3d"',c,'"\x3e')):(c=this._getCellClass(b,c,d,!0),d=0==b&&this._isGroup?"handleDeleteGroup":"handleDelete",a.push('\x3ctd class\x3d"',c,'"\x3e'),e||(assert(this._canDelete,"[RBSummaryTableLayout]: Use 'canDelete: false' to disable trash cans on all rows."),a.push('\x3cdiv class\x3d"sapIcon globalPortletLinkTextColor link" style \x3d "cursor:pointer;padding-left : 10px; font-size : 16px;font-weight : normal;"'),
a.push('onclick\x3d"',this.fireCode(d,b),'return false;"\x3e\x26#xe03d\x3c/div\x3e')));a.push("\x3c/td\x3e")},_getArrowIcon:function(){return this._expanded?"\x26#xe1f0":"\x26#xe1ef"},_getCellClass:function(a,b,c,d){assert(-1<a,"[RBSummaryTableLayout]:Invalid row index");assert(-1<b,"[RBSummaryTableLayout]:Invalid column index");assert(-1<c,"[RBSummaryTableLayout]:Invalid length");var e=b%2,f=b==c-1;b=b==c;return this._isGroup&&0<a?e?d&&b?"rp_s_o_sub_del":f?"rp_s_e_sub_l":"rp_s_e_sub":d&&b?"rp_s_e_sub_del":
f?"rp_s_o_sub_l":"rp_s_o_sub":e?d&&b?"rp_s_o_del":f?"rp_s_e_l":"rp_s_e":d&&b?"rp_s_e_del":"rp_s_o"},addNewRow:function(a,b){if(a&&0<a.length){this._lastRowIndex++;var c=this._lastRowIndex;this._items.push(a);var d=document.getElementById(this._tableNamePrefix+this.id);if(d){var e=document.createElement("tr");e.id=this.getRowId(c);for(var f=0;f<a.length;f++){var g=document.createElement("td"),h=this.getCellId(c,f);g.id=h;g.className=this._getCellClass(c,f,a.length,this._canDelete);h=[];a[f].renderHtml(h);
g.innerHTML=h.join("");e.appendChild(g)}this._canDelete&&(g=document.createElement("td"),g.className=this._getCellClass(c,f,a.length,this._canDelete),h=[],this._renderTrash(h,c,f,a.length,b),g.innerHTML=h.join(""),e.appendChild(g));d.firstChild?d.firstChild.appendChild(e):d.appendChild(e)}}},removeRow:function(a){assert(-1<a&&a<=this._lastRowIndex,"[RBSummaryTableLayout]:rowIdx is invalid");var b=$(this.getRowId(a));b&&b.parentNode.removeChild(b);this._items[a]=void 0},setCell:function(a,b,c){cellId=
this.getCellId(a,b);assert(cellId&&0===cellId.indexOf(this._cellNamePrefix),"[RBSummaryTableLayout]:Cell id is invalid");var d=$(cellId);if(d){var e=[];c.renderHtml(e);d.innerHTML=e.join("")}this._items[a][b]=c},handleEvent:function(a){switch(a.type){case "action":"handleDeleteTable"==a.actionCommand&&this.handleDeleteTable()}},handleDelete:function(a){this.dispatch("delete",{rowIdx:a})},handleDeleteGroup:function(){this.dispatch("deleteGroup")},handleDeleteTable:function(){this.dispatch("deleteTable")},
handleCollapseOrExpand:function(){this._expanded=!this._expanded;var a=juic.$(this.id+"Arrow"),b=$(this._tableNamePrefix+this.id);b&&(b.style.display=this._expanded?"":"none");a&&(a.innerHTML=this._expanded?"\x26#xe1f0":"\x26#xe1ef")},showDeleteGroup:function(){if($(this._canDelete&&"rb_del_grp"+this.id)){var a=[];this._renderDeleteGroupLink(a);$("rb_del_grp"+this.id).innerHTML=a.join("")}},hideDeleteGroup:function(){$("rb_del_grp"+this.id)&&($("rb_del_grp"+this.id).innerHTML="")},cleanup:function(){this._deleteTableLink.cleanup();
this.unregister()}})}();function RBContainerLayout(a,b,c,d,e){this.register();this._init(a,b,c,d,e)}
RBContainerLayout.prototype=function(){return set(new Component,{_init:function(a,b,c,d,e){assert(a,"[RBContainerLayout]: Please specify a title.");assert(b,"[RBContainerLayout]: Please specify a body component.");this._title=a;this._body=b;d&&(this._heading=d);e&&(this._heading2=e);c&&(this._config=c)},renderHtml:function(a){a.push('\x3cdiv class\x3d"rb_container_layout"\x3e','\x3cdiv class\x3d"round bun" style\x3d"background-image:none;"\x3e','\x3cspan class\x3d"ct"\x3e\x3cspan class\x3d"cl"\x3e\x3c/span\x3e\x3c/span\x3e',
'\x3cdiv class\x3d"hd"\x3e');"string"===typeof this._title?a.push(this._title):this._title.renderHtml(a);a.push("\x3c/div\x3e","\x3c/div\x3e");this._heading&&(a.push('\x3cdiv class\x3d"rb_heading_sec"\x3e','\x3cdiv class\x3d"floatleft"\x3e'),this._heading.renderHtml(a),a.push("\x3c/div\x3e","\x3c/div\x3e"));this._heading2&&(a.push('\x3cdiv class\x3d"rb_heading2_sec" tabindex\x3d"0" role\x3d"region" aria-label\x3d"',MSGS.COMMON_Search,'"\x3e'),this._heading2.renderHtml(a),a.push("\x3c/div\x3e"));var b=
' style\x3d"';this._config&&this._config.height&&(b+="height:"+this._config.height+";");!this._heading&&!this._heading2&&(b+="margin-top:-2px;");a.push('\x3cdiv class\x3d"rb_body_sec" ',b+'"',"\x3e");this._body.renderHtml(a);a.push("\x3c/div\x3e");a.push("\x3c/div\x3e")}})}();function RBDataNode(a){this._init(a)}RBDataNode.nodeGen=0;
RBDataNode.prototype=function(){return set(new Component,{_init:function(a){this._nodeId=!a?"node"+ ++RBDataNode.nodeGen:escape(a)},setNodeId:function(a){this._nodeId=a},getNodeId:function(){return this._nodeId},renderHtml:function(a){a.push(this.getNodeId())},cleanup:function(){delete this._nodeId}})}();function RBAbstractListNode(a){this._init(a)}RBAbstractListNode.prototype=function(){return set(new RBDataNode,{_init:function(a){RBDataNode.prototype._init.call(this,a)}})}();
function RBDefaultListNode(a){this._init(a)}RBDefaultListNode.prototype=function(){return set(new RBAbstractListNode,{_init:function(a){RBAbstractListNode.prototype._init.call(this,a)}})}();function RBDefaultTableNode(a){this._init(a)}RBDefaultTableNode.prototype=function(){return set(new RBAbstractListNode,{_init:function(a){RBDefaultListNode.prototype._init.call(this,a)}})}();function RBSelectListNode(a){this._init(a)}
RBSelectListNode.prototype=function(){return set(new RBAbstractListNode,{_init:function(a){RBAbstractListNode.prototype._init.call(this,a);this._selected=!1},isEnabled:function(){return!0},isSelected:function(){return this._selected},setSelected:function(a){this._selected=a},_toggleSelected:function(a){var b=juic.$(this.id)?juic.$(this.id):null;if(this.isSelected()){if(this.deSelect(a),b){b.removeAttribute("aria-checked");a=document.querySelector(".multi_select")?document.querySelector(".multi_select").querySelectorAll("span"):
[];for(i=0;i<a.length;i++)if(a[i].innerHTML==this._text){var c=a[i].parentNode.childNodes[0].id;break}juic.$(c)?juic.$(c).removeAttribute("aria-checked"):null}}else this.select(a),b?b.setAttribute("aria-checked",!0):null},select:function(a,b){this.setSelected(!0);this.dispatch("selectAction",{actionCommand:"selected",nodeId:this.getNodeId(),batched:b,originalEvent:a})},deSelect:function(a,b){this.setSelected(!1);this.dispatch("selectAction",{actionCommand:"deSelected",nodeId:this.getNodeId(),batched:b,
originalEvent:a})},copyNode:function(a){this.setSelected(!0);this.dispatch("selectAction",{actionCommand:"copyNode",nodeId:this.getNodeId(),batched:!1,originalEvent:a})},cleanup:function(){delete this._selected;RBDataNode.prototype.cleanup.call(this,nodeId)}})}();function RBSelectTableNode(a){this._init(a)}RBSelectTableNode.prototype=function(){return set(new RBSelectListNode,{_init:function(a){RBSelectListNode.prototype._init.call(this,a)}})}();function RBMultiSelectListNode(a){this._init(a)}
RBMultiSelectListNode.prototype=function(){return set(new RBSelectListNode,{_init:function(a){this._duplicate=!1;RBSelectListNode.prototype._init.call(this,a)},isDuplicate:function(){return this._duplicate},setDuplicate:function(a){this._duplicate=a},getGeneratedNodeId:function(){assert(!1,"[Subclass must override RBMultiSelectListNode.getGeneratedNodeId method...]")},setGeneratedNodeId:function(a){assert(!1,"[Subclass must override RBMultiSelectListNode.getGeneratedNodeId method...]")},copyNode:function(a){this.dispatch("selectAction",
{actionCommand:"copyNode",nodeId:this.getNodeId(),batched:!1,originalEvent:a})},deSelect:function(a,b){this.setSelected(!1);this.dispatch("selectAction",{actionCommand:"deSelected",nodeId:this.getGeneratedNodeId(),batched:!1,originalEvent:a})}})}();function RBAbstractListModel(){}
RBAbstractListModel.prototype=function(){return set(new EventTarget,{_init:function(a){"undefined"!=typeof a&&(this._dao=a,this._dao.addEventListener("dataAvailable",this),this._dao.addEventListener("listSizeChange",this),this._dao.addEventListener("dataChanged",this));this._numChildren=-1;this._list=[];this._nodeCache={}},getDao:function(){return this._dao},getData:function(a){this.dispatch("loadingData");if(this._dao&&0!=this._numChildren&&"undefined"==typeof this.getList()[a.startIndex])this._dao.fetchChildren(a.startIndex,
a);else{a.endIndex>this._numChildren&&!this._autoGrowListSize&&(a.endIndex=this._numChildren-1);if("undefined"!=typeof a.endIndex){var b=this.dataContigousTill(a.startIndex,a.endIndex);if(this._dao&&"undefined"==typeof this.getList()[b]&&b<a.endIndex){this._dao.fetchChildren(b,a);return}}("undefined"==typeof a.endIndex||b>=a.endIndex)&&this.dispatch("dataAvailable",{startIndex:a.startIndex,endIndex:a.endIndex})}},dataContigousTill:function(a,b){for(var c=a;this._list&&"undefined"!=typeof this._list[c]&&
!(c>=b);)c++;return c},populate:function(a,b,c){var d=a.startIndex,e=a.endIndex;if("undefined"==typeof d&&"undefined"==e)for(var f in a)"undefined"==typeof d&&(d=a[f]),"undefined"==typeof e&&(e=a[f]),a[f]>e&&(e=a[f]),a[f]<d&&(d=a[f]);f=this.dataContigousTill(d,e);f<e?this.getData({deferredStart:d,startIndex:f,endIndex:e,callback:b,scope:c}):(this.dispatch("dataAvailable",{startIndex:a.deferredStart,endIndex:e}),b.apply(c))},getNodeById:function(a){"string"!=typeof a&&(a=a.getNodeId());-1<a.indexOf(" ")&&
(a=escape(a));if(this._nodeCache[a])return this._list[this._nodeCache[a]];a=this.getNodeIndex(a);if(-1<a)return this._list[a]},getNodeIndex:function(a){"string"!=typeof a&&(a=a.getNodeId());if("undefined"==typeof this._nodeCache[a])for(var b=0;b<this._numChildren;b++)"undefined"!=typeof this._list[b]&&(this._nodeCache[this._list[b].getNodeId()]=b);return"undefined"!=typeof this._nodeCache[a]?this._nodeCache[a]:-1},getNumChildren:function(){return this._numChildren},setAutoGrowListSize:function(a){this._autoGrowListSize=
a},setNumChildren:function(a,b){a!=this._numChildren&&(this._numChildren=a,b||this.dispatch("listSizeChange",{newSize:a}))},getList:function(){return this._list},addItem:function(a,b,c){if("undefined"==typeof b||null==b)b=this._numChildren;!0==this._autoGrowListSize&&b>=this._numChildren&&this.setNumChildren(b+1);"undefined"==typeof b||b>=this._numChildren?assert(!1,"[RBAbstractListModel]:invalid position for data"):(this._list[b]?(this.removeItem(this._list[b],!0,!0),this.setNumChildren(this._numChildren+
1,c),this._list.splice(b,0,a)):this._list[b]=a,this._nodeCache[a.getNodeId()]=b,!0!=c&&this.dispatch("dataAvailable",{startIndex:b,endIndex:b}))},removeItem:function(a,b,c){var d=this.getNodeIndex(a);if(-1<d){this._list.splice(d,1);this.setNumChildren(this._numChildren-1,b);delete this._nodeCache[a];if(!c)for(a=d;a<this._list.length;a++)this._list[a]&&(this._nodeCache[this._list[a].getNodeId()]=a);!0!=b&&this.dispatch("dataRefreshed")}else assert(!1,"[RBAbstractListModel]:cannot remove node as it does not exist in currentg list")},
removeAll:function(){this._list=[];delete this._nodeCache;this._nodeCache={};this.setNumChildren(0);this.dispatch("dataRefreshed")},handleEvent:function(a){try{switch(a.type){case "dataAvailable":var b=a.endIndex;!0==this._autoGrowListSize&&b>=this._numChildren&&this.setNumChildren(b+1);for(var c=a.startIndex,d=0;c<=b;c++,d++)this.addItem(a.data[d],c,!0);"undefined"!=typeof a.referenceObj&&("undefined"==typeof a.referenceObj.deferredStart?this.dispatch("dataAvailable",{startIndex:a.startIndex,endIndex:b}):
this.populate({startIndex:a.referenceObj.deferredStart,endIndex:a.referenceObj.endIndex},a.referenceObj.callback,a.referenceObj.scope));break;case "listSizeChange":this.setNumChildren(a.listSize);break;case "dataChanged":this.removeAll()}}catch(e){assert(!1,"[RBAbstractListModel]: caught exception : "+e)}},cleanup:function(){this._dao&&(this._dao.removeEventListener("dataAvailable",this),this._dao.removeEventListener("listSizeChange",this));delete this._numChildren;for(var a=0;a<this._list.length;a++)delete this._list[a];
delete this._list;delete this._nodeCache}})}();function RBListModel(a){this._init(a)}RBListModel.prototype=function(){return set(new RBAbstractListModel,{_init:function(a){RBAbstractListModel.prototype._init.call(this,a)}})}();function RBSelectListModel(a){this._init(a)}
RBSelectListModel.prototype=function(){return set(new RBAbstractListModel,{_init:function(a){this._selectedIndices={};this._shiftSelect=!0;RBAbstractListModel.prototype._init.call(this,a)},selectAll:function(a){if(0<this._numChildren&&this._numChildren!=this.dataContigousTill(0,this._numChildren))this.populate({startIndex:0,endIndex:this._numChildren},this.selectAll,this);else{this._selectAll=!0;for(var b=0,c=0,d=0;d<this._numChildren;d++)"undefined"!=typeof this._list[d]&&this._list[d].isEnabled()?
(this._list[d].select(a,!0),this._selectedIndices[d]=!0,c++):b<c?(this.dispatch("selectAction",{actionCommand:"selected",startNodeIndex:b,endNodeIndex:c-1}),c++,b=c):(b++,c++);b<c&&this.dispatch("selectAction",{actionCommand:"selected",startNodeIndex:b,endNodeIndex:c-1})}},getActiveNodeId:function(){return this._last},getSelectedNodes:function(){for(var a=[],b=0;b<this._numChildren;b++)if("undefined"!=typeof this._list[b]&&this._list[b].isSelected()&&(a.push(this._list[b]),this._selectedIndices&&
(!this._selectedIndices.length||0==this._selectedIndices.length)))this._selectedIndices[b]=!0;return a},selectNone:function(a){if(0<this._numChildren&&this._numChildren!=this.dataContigousTill(0,this._numChildren))this.populate({startIndex:0,endIndex:this._numChildren},this.selectNone,this);else{this._selectAll=!1;for(var b=0;b<this._numChildren;b++)"undefined"!=typeof this._list[b]&&this._list[b].deSelect(a,!0),delete this._selectedIndices[b];0<this._numChildren&&this.dispatch("selectAction",{actionCommand:"deSelected",
startNodeIndex:0,endNodeIndex:this._numChildren-1})}},addItem:function(a,b,c){(!0==this._selectedIndices[b]||this._selectAll)&&a.select(!0);RBAbstractListModel.prototype.addItem.call(this,a,b,c);a.addEventListener("selectAction",this);a.addEventListener("change",this)},removeItem:function(a,b,c){this.getNodeById(a).removeEventListener("selectAction",this);this.getNodeById(a).removeEventListener("change",this);RBAbstractListModel.prototype.removeItem.call(this,a,b,c)},removeAll:function(){for(var a=
0;a<this._numChildren;a++)this._list[a]&&(this._list[a].removeEventListener("selectAction",this),this._list[a].removeEventListener("change",this));RBAbstractListModel.prototype.removeAll.call(this)},setShiftSelect:function(a){this._shiftSelect=!!a},refreshIndicesAfterBatchSelect:function(){if(this._list)for(var a=0;a<=this._list.length;a++)this._list[a]&&this._list[a].isSelected()&&(this._selectedIndices[a]=!0)},handleEvent:function(a){switch(a.type){case "selectAction":if("undefined"==typeof this.getNodeById(a.nodeId))assert(!1,
"[RBSelectListModel]:node["+a.nodeId+"] does not exist in list");else{if(this._shiftSelect&&a.originalEvent&&a.originalEvent.shiftKey){var b=this.getNodeIndex(this._last),c=this.getNodeIndex(a.nodeId);if(c<b)var d=c,c=b,b=d;if("selected"==a.actionCommand)for(d=b;d<=c;d++)this._list[d]&&this._list[d].isEnabled()&&(this._list[d].select(null,!0),this._selectedIndices[d]=!0);else if("deSelected"==a.actionCommand)for(d=b;d<=c;d++)this._list[d]&&this._list[d].deSelect(null,!0),delete this._selectedIndices[d];
a.batched||this.dispatch("selectAction",{actionCommand:a.actionCommand,startNodeIndex:b,endNodeIndex:c});a.originalEvent.stopPropagation&&a.originalEvent.stopPropagation()}else this._selectAll?"deSelected"==a.actionCommand&&delete this._selectedIndices[this.getNodeIndex(a.nodeId)]:"selected"==a.actionCommand?this._selectedIndices[this.getNodeIndex(a.nodeId)]=!0:"deSelected"==a.actionCommand&&delete this._selectedIndices[this.getNodeIndex(a.nodeId)],a.batched||this.dispatch("selectAction",{actionCommand:a.actionCommand,
nodeId:a.nodeId});this._last=a.nodeId}}RBAbstractListModel.prototype.handleEvent.call(this,a)},cleanup:function(){delete this._selectedIndices;for(var a=this._list.length,b=0;b<this._numChildren||b<a;b++)this._list[b]&&(this._list[b].removeEventListener("selectAction",this),this._list[b].removeEventListener("change",this));RBAbstractListModel.prototype.cleanup.call(this)}})}();function RBSingleSelectListModel(a){this.init(a)}
RBSingleSelectListModel.prototype=function(){return set(new RBSelectListModel,{init:function(a){RBSelectListModel.prototype._init.call(this,a);this._shiftSelect=!1},setShiftSelect:function(){assert(!1,"[RBSingleSelectListModel]:cannot set shift select for single selection type")},getSelectedNodes:function(){return[]},getSelectedNode:function(){if(this._selectedNodeId)return this.getNodeById(this._selectedNodeId)},handleEvent:function(a){switch(a.type){case "selectAction":switch(a.actionCommand){case "selected":if(a.nodeId){if(this._selectedNodeId){var b=
this.getNodeById(this._selectedNodeId);b&&b.deSelect(a)}this._selectedNodeId=a.nodeId}else return;break;case "deSelected":delete this._selectedNodeId}break;case "change":switch(a.actionCommand){case "selected":if(a.value){if(this._selectedNodeId&&(b=this.getNodeById(this._selectedNodeId)))b.deSelect(a),b._buttonGroup.getRadioFieldByIndex(0).setChecked(!1);this._selectedNodeId=a.value}else return;break;case "deSelected":delete this._selectedNodeId}}RBSelectListModel.prototype.handleEvent.call(this,
a)}})}();function RBMultiSelectListModel(a){this.init(a)}
RBMultiSelectListModel.prototype=function(){return set(new RBSelectListModel,{init:function(a){RBSelectListModel.prototype._init.call(this,a);this._shiftSelect=!0;this._cacheMap={};this._nodeGen={}},generateNodeId:function(a){var b=/(.*)(\d+)$/,c;do a=c=(c=a.match(b))&&c[2]?c[1]+ ++c[2]:a+"-1";while(this._nodeGen[c]);return c},addItem:function(a,b,c){var d=a.getNodeId();if(this._nodeGen[d]){var e=this.generateNodeId(d),d=e;a.gId=e;this._nodeGen[e]=a}else this._nodeGen[d]=a,a.gId=d;(!0==this._selectedIndices[b]||
this._selectAll)&&a.select(!0);if("undefined"==typeof b||null==b)b=this._numChildren;!0==this._autoGrowListSize&&b>=this._numChildren&&this.setNumChildren(b+1);"undefined"==typeof b||b>=this._numChildren?assert(!1,"[RBAbstractListModel]:invalid position for data"):(this._list[b]?(this.removeItem(this._list[b],!0,!0),this.setNumChildren(this._numChildren+1,c),this._list.splice(b,0,a)):this._list[b]=a,this._nodeCache[d]=b,!0!=c&&this.dispatch("dataAvailable",{startIndex:b,endIndex:b}),a.addEventListener("selectAction",
this),a.addEventListener("change",this))},removeItem:function(a,b,c){if(this.getNodeById(a)){this.getNodeById(a).removeEventListener("selectAction",this);this.getNodeById(a).removeEventListener("change",this);var d=this.getNodeIndex(a);if(-1<d){this._list.splice(d,1);this.setNumChildren(this._numChildren-1,b);delete this._nodeCache[a];if(!c)for(a=d;a<this._list.length;a++)this._list[a]&&(this._nodeCache[this._list[a].getNodeId()]=a);!0!=b&&this.dispatch("dataRefreshed")}else assert(!1,"[RBAbstractListModel]:cannot remove node as it does not exist in currentg list")}},
handleEvent:function(a){switch(a.type){case "selectAction":"selected"==a.actionCommand?(this._selectedIndices[this.getNodeIndex(a.nodeId)]=!0,a.batched||this.dispatch("selectAction",{actionCommand:a.actionCommand,nodeId:a.nodeId})):"deSelected"==a.actionCommand?(delete this._selectedIndices[this.getNodeIndex(a.nodeId)],a.batched||this.dispatch("selectAction",{actionCommand:a.actionCommand,nodeId:a.nodeId,gid:a.target.gId})):"copyNode"==a.actionCommand&&(a.batched||this.dispatch("selectAction",{actionCommand:a.actionCommand,
nodeId:a.nodeId,gid:a.target.gId}));return}RBSelectListModel.prototype.handleEvent.call(this,a)},selectAll:function(){RBSelectListModel.prototype.selectAll.call(this)},removeAll:function(){RBSelectListModel.prototype.removeAll.call(this)},clearAll:function(){}})}();function RBAbstractListView(){}RBAbstractListView.DEFAULT_PAGE_SIZE=100;
RBAbstractListView.prototype=function(){return set(new Component,{_init:function(a,b){"undefined"!=typeof a&&this.setModel(a);this._options=set({NO_RESULTS_MESSAGE:MSGS.COMMON_no_items},b)},setOption:function(a,b){this._options[a]=b},setModel:function(a){this._model&&(this.getModel().removeEventListener("dataAvailable",this),this.getModel().removeEventListener("dataRefreshed",this),this.getModel().removeEventListener("listSizeChange",this),this.getModel().removeEventListener("loadingData",this));
(this._model=a)?(this.getModel().addEventListener("dataAvailable",this),this.getModel().addEventListener("dataRefreshed",this),this.getModel().addEventListener("listSizeChange",this),this.getModel().addEventListener("loadingData",this),a=RBAbstractListView.DEFAULT_PAGE_SIZE,this._paginator&&(a=this._paginator.getPagingModel().getExtent(),this._paginator.getPagingModel().setRangeProperties(this._paginator.getPagingModel().getMinimum(),this.getModel().getNumChildren()-1,0,a)),this.getModel().getData({startIndex:0,
endIndex:a-1}),this.getModel().dispatch("listSizeChange",{newSize:this.getModel().getNumChildren()})):(this._paginator&&(this._paginator.getPagingModel().getExtent(),this._paginator.getPagingModel().setRangeProperties(this._paginator.getPagingModel().getMinimum(),0,0,this._paginator.getPagingModel().getExtent())),this.reRender())},getModel:function(){return this._model},setAutoFetchPagedDataInView:function(a){this._autoFetchPagedDataInView=a},setPaginator:function(a){this._paginator&&(this._paginator.removeEventListener("action",
this),this._paginator.cleanup());this._paginator=a;this.getModel()&&this._paginator.getPagingModel().setRangeProperties(this._paginator.getPagingModel().getMinimum(),this.getModel().getNumChildren()-1,0,this._paginator.getPagingModel().getExtent());this._paginator.addEventListener("action",this)},renderHtml:function(a){a.push('\x3cdiv class\x3d"listview_wrapper clear_all" id\x3d"',this.id,'"');!0==this._autoFetchPagedDataInView&&a.push(' onscroll\x3d"',this.fireCode("_checkMoreMarkers"),'"');a.push("\x3e");
a.push('\x3cdiv class\x3d"listview_items" id\x3d"',this.id,'list" \x3e');if(null!=this.getModel()){var b=this.getModel();null!=b.getList()&&0<b.getList().length?this._getListHtml(a):a.push('\x3cdiv id\x3d"rbListNoFilterCriteria" tabindex\x3d0 class\x3d"instructionalText rb_help_txt"\x3e',MSGS.COMMON_no_items,"\x3c/div\x3e")}a.push("\x3c/div\x3e");a.push("\x3c/div\x3e")},_getListHtml:function(a){delete this._moreMarker;var b="";this.getModel()instanceof RBSingleSelectListModel?b="single_select":this.getModel()instanceof
RBSelectListModel||this.getModel()instanceof RBMultiSelectListModel?b="multi_select":this.getModel()instanceof RBListModel&&(b="no_select");if(this.getModel()&&this.getModel().getList()&&0<this.getModel().getList().length){a.push('\x3cul id\x3d"',this.id,":childNodes",'" class\x3d"',b,'"\x3e');var c=this.getModel().getList(),d=0,e=this.getModel().getNumChildren()-1;this._paginator&&(d=(this._paginator.getCurrentPageNumber()-1)*this._paginator.getExtent(),d=0<d?d:0,e=e<d+this._paginator.getExtent()?
e:d+this._paginator.getExtent());var f=0,g=e;"undefined"!=typeof rbsd&&null!=rbsd&&"LaunchForm"===rbsd._source&&parseInt(e)-parseInt(d)>=this._paginator.getExtent()&&(g=e-1);for(f=d;f<=g&&"undefined"!=typeof c[f];f++)this._getListItemHtml(c[f],f,a,b);f<e?(this._moreMarker=!0,a.push('\x3cli id\x3d"',this.id,':more" class\x3d"more_items"\x3e'),a.push('\x3ca id\x3d"',this.id,':more_text" href\x3d"javascript:;" onclick\x3d"',this.fireCode("_handleMore",{index:f}),';return false;"\x3e',MSGS.COMMON_More,
"\x3c/a\x3e"),a.push("\x3c/li\x3e")):delete this._moreMarker;a.push("\x3c/ul\x3e");"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&enableDeselectAllLaunchForms()}else a.push('\x3cdiv id\x3d"rbListNoResults" tabindex\x3d0 class\x3d"instructionalText rb_help_txt"\x3e',this._options.NO_RESULTS_MESSAGE,"\x3c/div\x3e"),"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&(disableDeselectAllLaunchForms("selectnone"),disableDeselectAllLaunchForms("clearall"))},_getListItemHtml:function(a,
b,c){c.push('\x3cli id\x3d"',this.id,a.getNodeId(),':wrapper" class\x3d"item" \x3e');a.renderHtml(c);c.push("\x3c/li\x3e")},_pageAdjust:function(a){var b=this._paginator.getPagingModel(),c="undefined"==typeof a.newPageSize?b.getExtent():a.newPageSize,c=parseInt(c),d="undefined"==typeof a.newPageSize?a.newPage:1,d=parseInt(d);b.setRangeProperties(b.getMinimum(),b.getMaximum(),c*(d-1)+1,c);"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&(typeCheckbox=(document.querySelector(".rbSelectionSection",
"div.sfPaginator")&&document.querySelector(".rbSelectionSection").querySelector("div.sfPaginator")?document.querySelector(".rbSelectionSection").querySelector("div.sfPaginator").id:null)==a.target.id?!0:!1);this.reRender()},_checkMoreMarkers:function(){if(this._moreMarker){var a=juic.$(this.id).getBoundingClientRect(),b=juic.$(this.id+":more").getBoundingClientRect();b.top<=a.bottom&&b.bottom>=a.top&&(b.left<=a.right&&b.right>=a.left)&&(a=juic.$(this.id+":more_text"),a.onclick.call(a))}},_handleMore:function(a,
b){!0==this._moreMarker&&(delete this._moreMarker,this.getModel().getData({startIndex:a.index}))},reRender:function(){var a=[];juic.$(this.id+"list")&&(this._getListHtml(a),juic.$(this.id+"list").innerHTML=a.join(""),!0==this._autoFetchPagedDataInView&&this._checkMoreMarkers());"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&enableDeselectAllLaunchForms()},handleEvent:function(a){try{switch(a.type){case "dataAvailable":case "dataRefreshed":if(this._paginator){var b=this._paginator.getPagingModel();
b.getValue()>this.getModel().getNumChildren()&&b.setValue(this.getModel().getNumChildren()-this.getModel().getNumChildren()%b.getExtent());b.setRangeProperties(b.getMinimum(),this.getModel().getNumChildren(),b.getValue(),b.getExtent())}juic.$(this.id)&&this.reRender();break;case "listSizeChange":this._paginator&&(b=this._paginator.getPagingModel(),b.setRangeProperties(b.getMinimum(),a.newSize-1,b.getValue(),b.getExtent()));break;case "action":"pageAdjust"===a.actionCommand&&("undefined"!=typeof event&&
(event.returnValue=!1),this._pageAdjust(a));break;case "loadingData":juic.$(this.id+"list")&&(juic.$(this.id+"list").innerHTML=MSGS.COMMON_loading);break;case "change":this._buttonGroup?this.getModel()&&this.getModel().getDao()instanceof FilterColumnValuesListDAO?(this.inlineSelectContent=new RBInlineSelectListContent({dao:this.getModel().getDao(),freeForm:!0}),this.inlineSelectContent._model.setNumChildren(this.getModel().getList().length),this.inlineSelectContent._model._list=this.getModel().getList(),
this.inlineSelectContent.addEventListener("selectAction",this.inlineSelectContent),this.inlineSelectContent.dispatch("selectAction",{actionCommand:"selected",nodeId:escape(a.value)})):(this._model.addEventListener("radioSelectAction",this._model),this._model.dispatch("radioSelectAction",{actionCommand:"selected",nodeId:escape(a.value)})):a.target&&this._model.dispatch("selectAction",{actionCommand:a.checked?"selected":"deSelected",nodeId:escape(a.value)})}}catch(c){assert(!1,"[RBAbstractListView]"+
c)}},cleanup:function(){this.getModel().removeEventListener("dataAvailable",this)}})}();function RBDefaultListView(a,b){this.register();this._init(a,b)}RBDefaultListView.prototype=function(){return set(new RBAbstractListView,{_init:function(a,b){RBAbstractListView.prototype._init.call(this,a,b)}})}();function RBSelectListView(a,b){this.register();this._init(a,b)}
RBSelectListView.prototype=function(){return set(new RBAbstractListView,{_init:function(a,b){RBAbstractListView.prototype._init.call(this,a,b)},setModel:function(a){this._model&&this.getModel().removeEventListener("selectAction",this);RBAbstractListView.prototype.setModel.call(this,a);this.getModel()&&this.getModel().addEventListener("selectAction",this)},_getListItemHtml:function(a,b,c,d){c.push('\x3cli id\x3d"',this.id,a.getNodeId(),':wrapper"');c.push('class\x3d"clear_all item',a.isSelected()?
" selected":"");c.push(a.getNodeId()==this.getModel().getActiveNodeId()?" current":"");c.push(b%2?" even":" odd",'" \x3e');a.renderHtml(c,d);c.push("\x3c/li\x3e")},setActiveNode:function(a){this.getModel().getActiveNodeId()&&juic.$(this.id+this.getModel().getActiveNodeId()+":wrapper")&&Util.removeClass(this.id+this.getModel().getActiveNodeId()+":wrapper","current");Util.gebi(this.id+a)&&Util.addClass(this.id+a+":wrapper","current")},handleEvent:function(a){switch(a.type){case "selectAction":switch(a.actionCommand){case "selected":if(0<=
a.startNodeIndex&&a.endNodeIndex<=this.getModel().getNumChildren()){for(var b=a.startNodeIndex;b<=a.endNodeIndex;b++)Util.gebi(this.id+this.getModel().getList()[b].getNodeId()+":wrapper")&&Util.addClass(this.id+this.getModel().getList()[b].getNodeId()+":wrapper","selected");this.dispatch("selected",{startNodeIndex:a.startNodeIndex,endNodeIndex:a.endNodeIndex});this.reRender()}else b=this.getModel().getNodeIndex(a.nodeId),this.setActiveNode(a.nodeId),Util.gebi(this.id+a.nodeId+":wrapper")&&Util.addClass(this.id+
a.nodeId+":wrapper","selected"),this.dispatch("selected",{nodeId:a.nodeId,nodeIndex:b});break;case "deSelected":if(0<=a.startNodeIndex&&a.endNodeIndex<=this.getModel().getNumChildren()){for(b=a.startNodeIndex;b<=a.endNodeIndex;b++)this.getModel().getList()[b]&&Util.gebi(this.id+this.getModel().getList()[b].getNodeId()+":wrapper")&&Util.removeClass(this.id+this.getModel().getList()[b].getNodeId()+":wrapper","selected");this.dispatch("deSelected",{startNodeIndex:a.startNodeIndex,endNodeIndex:a.endNodeIndex});
this.reRender()}else b=this.getModel().getNodeIndex(a.nodeId),null!=Util.gebi(this.id+a.nodeId+":wrapper")&&Util.removeClass(this.id+a.nodeId+":wrapper","selected"),this.dispatch("deSelected",{nodeId:a.nodeId,nodeIndex:b})}}RBAbstractListView.prototype.handleEvent.call(this,a)}})}();function RBMultiSelectListView(a,b){this._init(a,b)}
RBMultiSelectListView.prototype=function(){return set(new RBSelectListView,{_init:function(a,b){RBSelectListView.prototype._init.call(this,a,b)},handleEvent:function(a){RBSelectListView.prototype.handleEvent.call(this,a)},_getListItemHtml:function(a,b,c){var d=a.getNodeId();a instanceof RBMultiSelectListNode&&(d=a.isDuplicate()?a.getGeneratedNodeId():a.getNodeId());c.push('\x3cli id\x3d"',this.id,d,':wrapper"');c.push('class\x3d"clear_all item',a.isSelected()?" selected":"");c.push(a.getNodeId()==
this.getModel().getActiveNodeId()?" current":"");c.push(b%2?" even":" odd",'" \x3e');a.renderHtml(c);c.push("\x3c/li\x3e")}})}();function enableDeselectAllLaunchForms(){rbsd.reRenderSelectedMassButtons();rbsd.reRenderSelectionMassButtons()}
function disableDeselectAllLaunchForms(a){var b=document.querySelectorAll(".multi_select")!=[]?document.querySelectorAll(".multi_select").length:0;a=document.getElementById(a);if((1===b||document.getElementById("rbListNoResults"))&&a){a.disabled=!0;a.tabIndex="-1";b=a.getElementsByTagName("div");for(a=0;a<b.length;a++)if("pointer"===b[a].style.cursor){b[a].disabled=!0;b[a].style.cursor="default";b[a].style.filter="alpha(opacity\x3d30)";b[a].style.opacity="0.7";b[a].onclick="return false";b[a].tabIndex=
"-1";break}}}function RBAbstractTreeNode(a){this._init(a)}
RBAbstractTreeNode.prototype=function(){return set(new RBDataNode,{_init:function(a){RBDataNode.prototype._init.call(this,a);this.setLeaf(!0)},isLeaf:function(){return 0==this._numChildren},setLeaf:function(a){a?(RBAbstractTreeNode.prototype.cleanup.call(this),this._children=void 0,this._numPopulatedChildren=this._numChildren=0):"undefined"==typeof this._children&&(this._children={},this._numPopulatedChildren=0)},isDataPopulated:function(){return 0==this._numChildren||this._numPopulatedChildren==
this._numChildren},addChild:function(a){this.setLeaf(!1);this._children[a.getNodeId()]=a;this._numPopulatedChildren++;assert(this._numPopulatedChildren<=this._numChildren,"[RBAbstractTreeNode]:Number of children ("+this._numPopulatedChildren+") for node "+this.getNodeId()+" exceeds the declared number ("+this._numChildren+")")},getChildren:function(){return this._children},getChild:function(a){return this._children[a]},getNumChildren:function(){return this._numChildren},getNumPopulatedChildren:function(){return this._numPopulatedChildren},
setNumChildren:function(a){this._numChildren=a},cleanup:function(){if("undefined"!=typeof this._children)for(var a in this._children)this.getChild(a).cleanup()}})}();function RBDefaultTreeNode(a){this._init(a)}RBDefaultTreeNode.prototype=function(){return set(new RBAbstractTreeNode,{_init:function(a){RBAbstractTreeNode.prototype._init.call(this,a)},cleanup:function(){RBAbstractTreeNode.prototype.cleanup.call(this)}})}();function RBDefaultTreeSelectNode(a){this._init(a)}
RBDefaultTreeSelectNode.prototype=function(){return set(new RBAbstractTreeNode,{_init:function(a){this._selected=!1;this._numSelectedChildren=0;this._selectedChildren={};RBAbstractTreeNode.prototype._init.call(this,a)},addChild:function(a){RBAbstractTreeNode.prototype.addChild.call(this,a);this._showChildSelected&&a.addEventListener("selectAction",this)},setShowChildSelected:function(a){this._showChildSelected=a},isSelected:function(){return this._selected},setSelected:function(a){this._selected=
a},hasSelectedChildren:function(){return 0<this._numSelectedChildren},_toggleSelected:function(){this.isSelected()?this.deSelect():this.select()},select:function(){this.setSelected(!0);this.dispatch("selectAction",{actionCommand:"selected",nodeId:this.getNodeId()})},deSelect:function(){this.setSelected(!1);this.dispatch("selectAction",{actionCommand:"deSelected",nodeId:this.getNodeId()})},renderHtml:function(a){a.push('\x3ca href\x3d"javascript:;" onclick\x3d"',this.fireCode("_toggleSelected",this.getNodeId()),
';return false;"\x3e');a.push("\x3cspan\x3e"+escapeHTML(this.getNodeId())+"\x3c/span\x3e");a.push("\x3c/a\x3e")},handleEvent:function(a){switch(a.type){case "selectAction":switch(a.actionCommand){case "childSelected":case "selected":"undefined"!=typeof this._children[a.nodeId]&&(this._selectedChildren[a.nodeId]=!0,this._numSelectedChildren++,this.dispatch("selectAction",{actionCommand:"childSelected",nodeId:this.getNodeId()}));break;case "childDeSelected":case "deSelected":"undefined"!=typeof this._children[a.nodeId]&&
(delete this._selectedChildren[a.nodeId],this._numSelectedChildren--,this.dispatch("selectAction",{actionCommand:"childDeSelected",nodeId:this.getNodeId()}))}}},cleanup:function(){for(var a in this.getChildren())this.getChild(a).removeEventListener("selectAction",this);RBAbstractTreeNode.prototype.cleanup.call(this)}})}();function RBAbstractTreeModel(){}
RBAbstractTreeModel.prototype=function(){return set(new EventTarget,{_init:function(a){this._rootNode=new RBDefaultTreeNode;this._rootNode.register();this._rootNode.setNumChildren(1);this._dao=a;this._dao.addEventListener("dataAvailable",this);this._dao.setRootNodeId(this.getRootNode().getNodeId());this._nodeIdMap={};this._nodeOrderMap={};this._nodeIdMap[this._rootNode.getNodeId()]=this._rootNode;this.getNodeData(this.getRootNode().getNodeId())},getNodeData:function(a,b){this._nodeIdMap[a].isDataPopulated()?
this.dispatch("dataAvailable",{nodeId:a,startIndex:0,endIndex:this.getNodeById(a).getNumChildren()}):this._dao.fetchChildren(a,b)},getRootNode:function(){return this._rootNode},getNodeById:function(a){return this._nodeIdMap[a]},getChildNodeOrder:function(a){"undefined"==typeof this._nodeOrderMap[a]&&(this._nodeOrderMap[a]={});return this._nodeOrderMap[a]},handleEvent:function(a){switch(a.type){case "dataAvailable":var b=a.parentNode;a.parentNode==this._rootNode.getNodeId()&&this._rootNode.setNumChildren(a.endIndex+
1);var c=0;"undefined"==typeof this._nodeOrderMap[b]&&(this._nodeOrderMap[b]=[]);for(var d=a.startIndex;d<=a.endIndex;d++,c++)this._nodeIdMap[a.data[c].getNodeId()]=a.data[c],this._nodeOrderMap[b][d]=a.data[c].getNodeId(),this.getNodeById(b).addChild(a.data[c]);this.dispatch("dataAvailable",{nodeId:b,startIndex:a.startIndex,endIndex:a.endIndex})}},cleanup:function(){this._dao.removeEventListener("dataAvailable",this);this._rootNode.cleanup()}})}();function RBDefaultTreeModel(a){a&&this._init(a)}
RBDefaultTreeModel.prototype=function(){return set(new RBAbstractTreeModel,{_init:function(a){RBAbstractTreeModel.prototype._init.call(this,a)}})}();function RBMultiSelectTreeModel(a){a&&this._init(a)}
RBMultiSelectTreeModel.prototype=function(){return set(new RBAbstractTreeModel,{_init:function(a){this._selectedNodes={};RBAbstractTreeModel.prototype._init.call(this,a)},setShowChildSelected:function(a){this._showChildSelected=a},getSelectedNodes:function(){return this._selectedNodes},isNodeSelected:function(a){return!0==this._selectedNodes[a]},handleEvent:function(a){switch(a.type){case "dataAvailable":for(var b=0,c=a.startIndex;c<=a.endIndex;c++,b++)a.data[b].addEventListener("selectAction",this),
a.data[b].setShowChildSelected(this._showChildSelected);break;case "selectAction":"selected"==a.actionCommand?this._selectedNodes[a.nodeId]=!0:"deSelected"==a.actionCommand&&delete this._selectedNodes[a.nodeId],this.dispatch("selectAction",{actionCommand:a.actionCommand,nodeId:a.nodeId})}RBAbstractTreeModel.prototype.handleEvent.call(this,a)},cleanup:function(){for(var a in this._nodeIdMap)this.getNodeById(a).removeEventListener("selectAction",this);RBAbstractTreeModel.prototype.cleanup.call(this)}})}();
function RBSingleSelectTreeModel(a){this._init(a)}
RBSingleSelectTreeModel.prototype=function(){return set(new RBMultiSelectTreeModel,{_init:function(a){RBMultiSelectTreeModel.prototype._init.call(this,a);delete this.getSelectedNodes},getSelectedNode:function(){return this._selectedNode},handleEvent:function(a){switch(a.type){case "selectAction":"selected"==a.actionCommand&&("undefined"!=typeof this.getNodeById(this._selectedNode)&&this.getNodeById(this._selectedNode).deSelect(),this._selectedNode=a.nodeId)}RBMultiSelectTreeModel.prototype.handleEvent.call(this,
a)}})}();function RBAbstractTreeView(){}
RBAbstractTreeView.prototype=function(){return set(new Component,{_init:function(a){this._expandedNodes={};this._moreMarkers={};this.setMsg(MSGS);"undefined"!=typeof a&&this.setModel(a)},setModel:function(a){this._model&&this._model.removeEventListener("dataAvailable",this);this._model=a;this._model.addEventListener("dataAvailable",this);this.reRender()},getModel:function(){return this._model},setMsg:function(a){this._msgs=a},_getHtmlContent:function(a){a.push('\x3cdiv id\x3d"',this.id,this.getModel().getRootNode().getNodeId(),
':childTree"\x3e');this._getNodeChildrenListHtml(this.getModel().getRootNode().getNodeId(),a);a.push("\x3c/div\x3e")},reRender:function(){if($(this.id+":treeView")){var a=[];this._getHtmlContent(a);$(this.id+":treeView").innerHTML=a.join("");!0==this._autoFetchPagedDataInView&&this._checkMoreMarkers()}},renderHtml:function(a){a.push('\x3cdiv class\x3d"treeview_wrapper" id\x3d"',this.id,':treeView"');!0==this._autoFetchPagedDataInView&&a.push(' onscroll\x3d"',this.fireCode("_checkMoreMarkers"),'"');
a.push("\x3e");this._getHtmlContent(a);a.push("\x3c/div\x3e")},setAutoFetchPagedDataInView:function(a){this._autoFetchPagedDataInView=a},setExpandedNodes:function(a){this._expandedNodes=a;this._reRenderTree(this.getModel().getRootNode().getNodeId());for(var b in this._expandedNodes)!0==this._expandedNodes[b]&&this.getModel().getNodeData(b)},_reRenderTree:function(a){if(a&&$(this.id+a+":childTree")){var b=[];this._getNodeChildrenListHtml(a,b);$(this.id+a+":childTree").innerHTML=b.join("")}},_checkMoreMarkers:function(){var a=
$(this.id+":treeView").getBoundingClientRect(),b;for(b in this._moreMarkers){var c=$(this.id+b+":more").getBoundingClientRect();if(c.top<=a.bottom&&c.bottom>=a.top&&c.left<=a.right&&c.right>=a.left)for(var c=this.getModel().getNodeById(b).getNumChildren(),d=0;d<c;d++)if("undefined"==typeof this.getModel().getChildNodeOrder(b)[d]){delete this._moreMarkers[b];Util.addClass(this.id+b+":more","loading");$(this.id+b+":more_text").innerHTML=this._msgs.COMMON_loading;this.getModel().getNodeData(b,d);return}}},
_getNodeChildrenListHtml:function(a,b){b.push('\x3cul id\x3d"',this.id,a,":childNodes",'"\x3e');if("undefined"!=typeof this.getModel().getNodeById(a))for(var c=this.getModel().getChildNodeOrder(a),d=0;d<this.getModel().getNodeById(a).getNumChildren();d++)"undefined"!=typeof c[d]&&this.getModel().getNodeById(c[d])&&this._getNodeChildElementHtml(c[d],b);this.getModel().getNodeById(a).isDataPopulated()?delete this._moreMarkers[a]:this._getNodeMoreChildrenHtml(a,b);b.push("\x3c/ul\x3e")},_getNodeMoreChildrenHtml:function(a,
b){this._moreMarkers[a]=!0;b.push('\x3cli id\x3d"',this.id,a,':more" class\x3d"more_items"\x3e');b.push('\x3ca id\x3d"',this.id,a,':more_text" href\x3d"javascript:;" onclick\x3d"',this.fireCode("_handleMore",a),';return false;"\x3e',this._msgs.COMMON_More,"\x3c/a\x3e");b.push("\x3c/li\x3e")},_getNodeChildElementHtml:function(a,b){b.push('\x3cli id\x3d"',this.id,a,':wrapper" class\x3d"item ',!0!=this._expandedNodes[a]?"collapsed":"",this.getModel().getNodeById(a).isLeaf()?" leaf":"",'" \x3e');this._getNodeToggleSwitchHtml(a,
b);this._getNodeChildrenHtml(a,b);b.push("\x3c/li\x3e")},_getNodeContentHtml:function(a,b){b.push('\x3cdiv id\x3d"',this.id,a,':content" class\x3d"nodeContent"\x3e');this.getModel().getNodeById(a).renderHtml(b);b.push("\x3c/div\x3e")},_getNodeToggleSwitchHtml:function(a,b){b.push('\x3cdiv id\x3d"',this.id,a,':toggle_wrapper" class\x3d"expand_switch"\x3e');this.getModel().getNodeById(a).isLeaf()||b.push('\x3ca href\x3d"javascript:;" id\x3d"',this.id,a,':toggle" onclick\x3d"',this.fireCode("_handleClick",
a),';return false;" class\x3d"expand_switch_link"\x3e\x3c/a\x3e');this._getNodeContentHtml(a,b);b.push("\x3c/div\x3e")},_getNodeChildrenHtml:function(a,b){b.push('\x3cdiv id\x3d"',this.id,a,":childTree",'" class\x3d"childTree"\x3e');0<this.getModel().getNodeById(a).getNumChildren()&&this._expandedNodes[a]&&this._getNodeChildrenListHtml(a,b);b.push("\x3c/div\x3e")},_handleClick:function(a,b){!0==this._expandedNodes[a]?(delete this._expandedNodes[a],Util.addClass(this.id+a+":wrapper","collapsed")):
(0==this.getModel().getNodeById(a).getNumPopulatedChildren()?this.getModel().getNodeData(a):this._reRenderTree(a),this._expandedNodes[a]=!0,Util.removeClass(this.id+a+":wrapper","collapsed"),this._checkMoreMarkers())},_handleMore:function(a,b){if(!0==this._moreMarkers[a])for(var c=this.getModel().getNodeById(a).getNumChildren(),d=0;d<c;d++)if("undefined"==typeof this.getModel().getChildNodeOrder(a)[d]){delete this._moreMarkers[a];Util.addClass(this.id+a+":more","loading");$(this.id+a+":more_text").innerHTML=
this._msgs.COMMON_loading;this.getModel().getNodeData(a,d);break}},handleEvent:function(a){switch(a.type){case "dataAvailable":if($(this.id+a.nodeId+":childTree")){this._expandedNodes[a.nodeId]=!0;var b=[];this._getNodeChildrenListHtml(a.nodeId,b);$(this.id+a.nodeId+":childTree").innerHTML=b.join("");(!0==this._autoFetchPagedDataInView||this._expandedNodes[a.nodeId])&&this._checkMoreMarkers()}}},cleanup:function(){this.getModel()&&this.getModel().removeEventListener("dataAvailable",this)}})}();
function RBDefaultTreeView(a){this.register();this._init(a)}RBDefaultTreeView.prototype=function(){return set(new RBAbstractTreeView,{_init:function(a){RBAbstractTreeView.prototype._init.call(this,a)}})}();function RBSelectTreeView(a){this.register();this._init(a)}
RBSelectTreeView.prototype=function(){return set(new RBAbstractTreeView,{_init:function(a){RBAbstractTreeView.prototype._init.call(this,a);this.getModel().addEventListener("selectAction",this)},_getNodeToggleSwitchHtml:function(a,b){var c=this.getModel().getNodeById(a);b.push('\x3cdiv id\x3d"',this.id,a,':toggle_wrapper" class\x3d"expand_switch');b.push(c.isSelected()?" selected":"",c.hasSelectedChildren()?" hasSelectedChildren":"",'"\x3e');this.getModel().getNodeById(a).isLeaf()||b.push('\x3ca href\x3d"javascript:;" id\x3d"',
this.id,a,':toggle" onclick\x3d"',this.fireCode("_handleClick",a),';return false;" class\x3d"expand_switch_link"\x3e\x3c/a\x3e');this._getNodeContentHtml(a,b);b.push("\x3c/div\x3e")},setModel:function(a){this._model&&this.getModel().removeEventListener("selectAction",this);RBAbstractTreeView.prototype.setModel.call(this,a);this.getModel()&&this.getModel().addEventListener("selectAction",this)},handleEvent:function(a){RBAbstractTreeView.prototype.handleEvent.call(this,a);switch(a.type){case "selectAction":switch(a.actionCommand){case "selected":$(a.nodeId+
"_selectDialogTreeNode")&&Util.addClass(a.nodeId+"_selectDialogTreeNode","selected highlightColumnColor");this.dispatch("selected",{nodeId:a.nodeId});break;case "childSelected":!0==this.getModel().getNodeById(a.nodeId).hasSelectedChildren()&&$(this.id+a.nodeId+":toggle_wrapper")&&Util.addClass(this.id+a.nodeId+":toggle_wrapper","childSelected");break;case "deSelected":$(this.id+a.nodeId+":toggle_wrapper")&&Util.removeClass(this.id+a.nodeId+":toggle_wrapper","selected");$(a.nodeId+"_selectDialogTreeNode")&&
Util.removeClass(a.nodeId+"_selectDialogTreeNode","selected highlightColumnColor");this.dispatch("deSelected",{nodeId:a.nodeId});break;case "childDeSelected":!1==this.getModel().getNodeById(a.nodeId).hasSelectedChildren()&&$(this.id+a.nodeId+":toggle_wrapper")&&Util.removeClass(this.id+a.nodeId+":toggle_wrapper","childSelected")}}}})}();function RBSelectDialog(a){this.register();this._init(a)}RBSelectDialog.MAX_SELECTION=1E3;var rbsd=null,typeCheckbox=null;
RBSelectDialog.prototype=function(){return set(new Component,{_init:function(a,b){this._enableCopyNodes=a&&a.enableCopyNode?!0:!1;this._rbSelDlgEnhanced=a&&a.rbSelDlgEnhanced?!0:!1;this._source=a&&a.source?a.source:"";this._rbSelDlgEnhanced&&(this._selectedFilter=new SFAutoComplete("department",{writable:!0,inputSize:26,autoComplete:{forceSelection:!1,maxResultsDisplayed:30,resetButton:{label:MSGS.COMMON_AutoComplete_Clear,enabled:!0}}}),this._selectedFilter.addEventListener("action",this),this._filterType=
"dept");this._listView=new RBSelectListView;this._selectedListView=this._enableCopyNodes?new RBMultiSelectListView:new RBSelectListView;"undefined"==typeof a?this.demo():this._config=a;this._config.msgs=set({NO_SELECTED_RESULTS_MESSAGE:MSGS.TRY_DIFFERENT_SEARCH,SELECT_HEADING_MESSAGE:MSGS.Select,SELECTED_HEADING_MESSAGE:MSGS.Use_Selected,SELECT_UNKNOWN_LENGTH:MSGS.ANALYTICS_ADHOC_REPORT_BUILDER_COLUMNS_ELLIPSIS,SELECTED_UNKNOWN_LENGTH:MSGS.ANALYTICS_ADHOC_REPORT_BUILDER_COLUMNS_ELLIPSIS},this._config.msgs);
this._listView.setOption("NO_RESULTS_MESSAGE",this._config.msgs.NO_SELECTED_RESULTS_MESSAGE);this._config.selectionPaginator&&(this._config.selectionPaginator=new SFPagination({model:new SFBoundedRangeModel(0,500,0,10)}),this._config.selectionPaginatorPerPage||this._config.selectionPaginator.setHideItemsPerPage(!0));this._config.selectedPaginator&&(this._config.selectedPaginator=new SFPagination({model:new SFBoundedRangeModel(0,500,0,10)}),this._config.selectedPaginatorPerPage||this._config.selectedPaginator.setHideItemsPerPage(!0));
this._config.leftComponent&&(this._config.leftComponent.addEventListener("switchListDataDao",this),this._config.leftComponent.addEventListener("switchSingleListDataDao",this),this._config.leftComponent.addEventListener("enableSelectionMassSelect",this));this._config.topComponent&&(this._config.topComponent.addEventListener("switchListDataDao",this),this._config.topComponent.addEventListener("enableSelectionMassSelect",this));this._config.bottomComponent&&(this._config.bottomComponent.addEventListener("switchListDataDao",
this),this._config.bottomComponent.addEventListener("enableSelectionMassSelect",this));this._config.selectedExtraComponent&&(this._config.selectedExtraComponent.addEventListener("switchListDataDao",this),this._config.selectedExtraComponent.addEventListener("enableSelectionMassSelect",this));this._config.selectionExtraComponent&&(this._config.selectionExtraComponent.addEventListener("switchListDataDao",this),this._config.selectionExtraComponent.addEventListener("enableSelectionMassSelect",this));this._config.selectionPaginator&&
(this._config.selectionPaginator.addEventListener("action",this),this._listView.setPaginator(this._config.selectionPaginator),this._listView.setAutoFetchPagedDataInView(!0));this._listSelectAll=new SFButton(MSGS.Select_All,{leftCss:"aquabtn active sml floatleft",rightCss:"span floatleft",onClick:"selectAll"});this._listSelectAll.addEventListener("selectAll",this);this._listSelectNone=new SFButton(MSGS.Deselect_All,{leftCss:"aquabtn active sml floatleft",rightCss:"span floatleft",onClick:"selectNone"});
this._listSelectNone.addEventListener("selectNone",this);this._listClearAll=new SFButton(MSGS.Deselect_All,{leftCss:"aquabtn active sml",rightCss:"span",onClick:"clearAll"});this._listClearAll.addEventListener("clearAll",this);this._listSelectall_none=new SFCheckBoxInput("selectAll",MSGS.Select_All,!1);this._listSelectall_none.addEventListener("change",this);this._config.selectedPaginator&&(this._config.selectedPaginator.addEventListener("action",this),this._selectedListView.setPaginator(this._config.selectedPaginator));
rbsd=this},setSelectedFilter:function(a){this._defaultText=(this._selectedFilter=a)?a.getValue():""},setFilterType:function(a){this._filterType=a},isCopyEnabled:function(){return this._enableCopyNodes},getSelectedListModel:function(a){return this.isCopyEnabled()?new RBMultiSelectListModel(a):new RBSelectListModel(a)},demo:function(){this._demoObj=new RBSelectDialogDummyWiring(this)},getLeftComponent:function(){return this._config.leftComponent},getSelectedNodes:function(){return this._selectedListView.getModel().getList()},
getSelectListModel:function(){return this._listView.getModel()},enableSelectionMassChange:function(a){this._config.allowSelectionMassChange=!!a;this.reRenderSelectionMassButtons()},enableSelectedMassChange:function(a){this._config.allowSelectedMassChange=!!a;this.reRenderSelectedMassButtons()},setSelectedDao:function(a){this._selectedListView.getModel()&&(this._selectedListView.getModel().removeEventListener("selectAction",this),this._selectedListView.getModel().removeEventListener("listSizeChange",
this),this._selectedListView.getModel().cleanup());a=this.getSelectedListModel(a);a.addEventListener("selectAction",this);a.addEventListener("listSizeChange",this);a.selectAll();a.setAutoGrowListSize(!0);this._selectedListView.setModel(a);this.switchListDataDao()},switchListDataDao:function(a){this._listView.getModel()&&(this._listView.getModel().removeEventListener("dataAvailable",this),this._listView.getModel().removeEventListener("selectAction",this),this._listView.getModel().removeEventListener("listSizeChange",
this),this._listView.getModel().selectNone(),this._listView.getModel().cleanup());a?(a=new RBSelectListModel(a),a.selectNone(),this._selectedListView.getModel()&&(this._selectedListView.getModel().selectAll(),this.selectOverLap(this._selectedListView.getModel(),a)),a.refreshIndicesAfterBatchSelect(),a.addEventListener("dataAvailable",this),a.addEventListener("selectAction",this),a.addEventListener("listSizeChange",this),this._listView.setModel(a)):(this._listView.setModel(),this.refreshSelectListCount(0))},
switchSingleListDataDao:function(a){this._listView.getModel()&&(this._listView.getModel().removeEventListener("dataAvailable",this),this._listView.getModel().removeEventListener("selectAction",this),this._listView.getModel().removeEventListener("listSizeChange",this),this._listView.getModel().selectNone(),this._listView.getModel().cleanup());a?(a=new RBSingleSelectListModel(a),a.selectNone(),this._selectedListView.getModel()&&(this._selectedListView.getModel().selectAll(),this.selectOverLap(this._selectedListView.getModel(),
a)),a.refreshIndicesAfterBatchSelect(),a.addEventListener("dataAvailable",this),a.addEventListener("selectAction",this),a.addEventListener("listSizeChange",this),this._listView.setModel(a)):(this._listView.setModel(),this.refreshSelectListCount(0))},handleEvent:function(a){switch(a.type){case "change":this._listViewModel=this._listView.getModel()||this._selectedListView.getModel();if("clearAll"==a.value||!1==a.checked){if(this._listViewModel&&(!(this._listViewModel.getSelectedNodes().length>RBSelectDialog.MAX_SELECTION)||
confirm(sfMessageFormat.format(MSGS.ANALYTICS_SELECT_DIALOG_TOO_MANY_DESELECTIONS,RBSelectDialog.MAX_SELECTION))))if(typeCheckbox=!0,this._listViewModel.selectNone(a),typeCheckbox=!1,this._selectedListView.getModel().dispatch("dataRefreshed"),this.refreshSelectedListCount(this._selectedListView.getModel().getSelectedNodes().length),"clearAll"==a.value){if(this._selectedListView.getModel()&&this._selectedListView.getModel()._list)for(var b=this._selectedListView.getModel()._list.length;b;){var c=this._selectedListView.getModel().getNodeById(this._selectedListView.getModel()._list[0]._nodeId);
c&&c.deSelect();b--}this._listView.reRender();a.type="selectNone";this.dispatchEvent(a)}}else if("selectAll"==a.value&&this._listViewModel&&this._listViewModel.getSelectedNodes().length<this._listViewModel._numChildren&&(!(this._listViewModel._numChildren>RBSelectDialog.MAX_SELECTION)||confirm(sfMessageFormat.format(MSGS.ANALYTICS_SELECT_DIALOG_TOO_MANY_SELECTIONS,RBSelectDialog.MAX_SELECTION))))typeCheckbox=!0,this._listViewModel.selectAll(a),typeCheckbox=!1,this._selectedListView.getModel().dispatch("dataRefreshed"),
this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked"),a.type="selectAll",this.dispatchEvent(a);break;case "selectAll":if((this._listViewModel=this._listView.getModel())&&this._listViewModel.getSelectedNodes().length<this._listViewModel._numChildren&&(!(this._listViewModel._numChildren>RBSelectDialog.MAX_SELECTION)||confirm(sfMessageFormat.format(MSGS.ANALYTICS_SELECT_DIALOG_TOO_MANY_SELECTIONS,RBSelectDialog.MAX_SELECTION))))typeCheckbox=!0,this._listView.getModel().selectAll(a),
typeCheckbox=!1,this._selectedListView.getModel().dispatch("dataRefreshed");this.dispatchEvent(a);break;case "clearAll":this._listViewModel=this._listView.getModel();if(!(this._selectedListView.getModel().getSelectedNodes().length>RBSelectDialog.MAX_SELECTION)||confirm(sfMessageFormat.format(MSGS.ANALYTICS_SELECT_DIALOG_TOO_MANY_DESELECTIONS,RBSelectDialog.MAX_SELECTION)))typeCheckbox=!1,this._selectedListView.getModel().removeAll(a),this._listViewModel&&(typeCheckbox=!0,this._listViewModel.selectNone(a)),
typeCheckbox=!1,this._selectedListView.getModel().dispatch("dataRefreshed"),this._rbSelDlgEnhanced&&"LaunchForm"===this._source&&this._resetFilterCount(this._filterType,this._selectedListView.getModel());this.dispatchEvent(a);break;case "selectNone":this._listViewModel=this._listView.getModel();if(!(this._listViewModel.getSelectedNodes().length>RBSelectDialog.MAX_SELECTION)||confirm(sfMessageFormat.format(MSGS.ANALYTICS_SELECT_DIALOG_TOO_MANY_DESELECTIONS,RBSelectDialog.MAX_SELECTION)))typeCheckbox=
!0,this._listView.getModel().selectNone(a),typeCheckbox=!1,this._selectedListView.getModel().dispatch("dataRefreshed"),this.refreshSelectedListCount(this._selectedListView.getModel().getSelectedNodes().length);this.dispatchEvent(a);break;case "selectAction":switch(a.actionCommand){case "selected":if(a.target==this._listView.getModel()){if(a.nodeId){if(this._rbSelDlgEnhanced){var d=!1;if(this._selectedListView.getModel()){var e=this._selectedListView.getModel().getList();if(e&&0==e.length)d=!0;else for(b=
0;b<e.length;b++)d=(d=e[b])&&d._nodeId===a.nodeId?!1:!0}}if(!this._rbSelDlgEnhanced||this._rbSelDlgEnhanced&&d)c=this._listView.getModel().getNodeById(a.nodeId),c.setSelected(!0),e=this._selectedListView.getModel().getDao().getNewItem(c),typeCheckbox=!1,this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked"),this._selectedListView.getModel().addItem(e)}else if("undefined"!=typeof a.startNodeIndex&&null!=a.startNodeIndex&&"undefined"!=typeof a.endNodeIndex&&null!=a.endNodeIndex){d=
this._listView.getModel().getList();for(b=a.startNodeIndex;b<=a.endNodeIndex;b++)!this._selectedListView.getModel().getNodeById(d[b].getNodeId())&&d[b].isEnabled()&&(e=this._selectedListView.getModel().getDao().getNewItem(d[b]),this._selectedListView.getModel().addItem(e,void 0,!0));this._selectedListView.getModel().dispatch("dataRefreshed")}this._rbSelDlgEnhanced&&"LaunchForm"===this._source&&this._resetFilterCount(this._filterType,this._selectedListView.getModel())}break;case "copyNode":a.target==
this._selectedListView.getModel()&&a.nodeId&&(c=this._selectedListView.getModel().getNodeById(a.nodeId),e=this._selectedListView.getModel().getDao().getNewItem(c),this._selectedListView.getModel().copyNode(e));break;case "deSelected":if(a.target==this._listView.getModel()||a.target==this._selectedListView.getModel()){if(a.nodeId){if(b="",c=this._selectedListView.getModel().getNodeById(a.nodeId))if(b=c._text,this._selectedListView.getModel().removeItem(a.nodeId),this._rbSelDlgEnhanced&&"LaunchForm"===
this._source){if(this._listView.getModel().getList()&&0<this._listView.getModel().getList().length){c=this._listView.getModel().getList();for(e=0;e<c.length;e++)if(c[e]._text===b&&(d=c[e])&&d.isSelected()){d.deSelect();break}}}else if(this._listView.getModel()&&(c=this._listView.getModel().getNodeById(a.nodeId))&&c.isSelected())c.deSelect(),this._listView.reRender()}else if(a.target==this._listView.getModel()&&"undefined"!=typeof a.startNodeIndex&&"undefined"!=typeof a.endNodeIndex){d=this._listView.getModel().getList();
for(b=a.startNodeIndex;b<=a.endNodeIndex;b++)(c=this._selectedListView.getModel().getNodeById(d[b].getNodeId()))&&this._selectedListView.getModel().removeItem(c.getNodeId(),!0);this._selectedListView.getModel().dispatch("dataRefreshed")}this._resetFilterCount(this._filterType,this._selectedListView.getModel());this._listSelectall_none&&this._listSelectall_none.setState("unchecked")}}this.dispatchEvent(a);break;case "dataAvailable":if(this._rbSelDlgEnhanced&&"LaunchForm"===this._source){if(this._selectedListView.getModel().getList()&&
0<this._selectedListView.getModel().getList().length){c=this._selectedListView.getModel().getList();for(b=a.startIndex;b<=a.endIndex;b++){e=a.target.getList()[b]?a.target.getList()[b]._text:"";for(d=0;d<c.length;d++)if(c[d]&&e===c[d]._text){a.target.getList()[b].select(a,!0);break}}}}else for(b=a.startIndex;b<=a.endIndex;b++)-1<this._selectedListView.getModel().getNodeIndex(a.target.getList()[b].getNodeId())&&a.target.getList()[b].select(a,!0);typeCheckbox=!0;(this._listViewModel=this._listView.getModel())&&
0==this._listViewModel.getSelectedNodes().length?(this._listSelectall_none&&this._listSelectall_none.setState("unchecked"),this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked")):this._listViewModel&&this._listViewModel.getSelectedNodes().length==this._listViewModel._numChildren?(this._listSelectall_none&&this._listSelectall_none.setState("checked"),this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked")):this._listSelectall_none&&this._listSelectall_none.setState("unchecked");
this._listView.reRender();this.refreshSelectListCount(this._listView.getModel().getNumChildren());break;case "switchListDataDao":this.switchListDataDao(a.dao);break;case "switchSingleListDataDao":this.switchSingleListDataDao(a.dao);break;case "enableSelectionMassSelect":this.enableSelectionMassChange(a.enable);break;case "listSizeChange":b=a.newSize;a.target==this._listView.getModel()&&juic.$(this.id+"select_heading")?this.refreshSelectListCount(b):a.target==this._selectedListView.getModel()&&juic.$(this.id+
"selected_heading")&&this.refreshSelectedListCount(b);break;case "action":switch(a.actionCommand){case "itemSelect":if(this._rbSelDlgEnhanced&&(this._selectedFilter&&this._selectedFilter._selectedObj)&&(a=this._selectedFilter._selectedObj.name,this._listView.getModel()&&this._listView.getModel().getList())){e=this._listView.getModel().getList();for(b=0;b<=e.length;b++)if((d=e[b])&&d._text===a){c=d._nodeId;break}if(c&&this._selectedListView.getModel()&&this._selectedListView.getModel().getList()){d=
!1;if(e=this._selectedListView.getModel().getList())if(0==e.length)d=!0;else for(b=0;b<e.length;b++)if((d=e[b])&&d._nodeId===c){d=!1;break}else d=!0;d&&(c=this._listView.getModel().getNodeById(c),e=this._selectedListView.getModel().getDao().getNewItem(c),this._selectedListView.getModel().addItem(e),c&&c.select(),"LaunchForm"===this._source&&this._resetFilterCount(this._filterType,this._selectedListView.getModel()))}}break;case "change":if(this._rbSelDlgEnhanced&&this._selectedFilter&&(juic.$(this._selectedFilter.id+
"_clear").style.display="block",SFDom.addClass(juic.$(this._selectedFilter.id+"_clear"),"render_clear_button"),this._listView.getModel()&&(b=this._listView.getModel().getDao())))b._nodes=[],a=a.target?a.target.getValue():null,null!=a&&(a=a.trim(),0>=a.length&&(a=null)),b._searchKey=a,this.switchListDataDao(b);break;case "focus":this._rbSelDlgEnhanced&&this._selectedFilter&&(this.focus_text=this._selectedFilter.getValue(),this.focus_text==this._defaultText&&(this._selectedFilter.setValue(""),juic.$(this._selectedFilter.id).style.color=
"black"));break;case "blur":this._rbSelDlgEnhanced&&this._selectedFilter&&(this._currentvalue=this._selectedFilter.getValue(),""==this._currentvalue&&(this._selectedFilter.setValue(this._defaultText),juic.$(this._selectedFilter.id).style.color="grey"))}}},_handleSelectButtonsEnter:function(a){var b=a.which||a.keyCode;13===b?(a=a.target||a.srcElement,(b=a.childNodes[0].id.split("_")[0])&&null!=a.querySelector("li.aquabtn")&&(juic.$(b)?juic.$(b).click():null)):27==b&&this.dispatch("action",{actionCommand:"cancel"})},
_resetFilterCount:function(a,b){b&&b.getList()&&this.dispatch("filtersModified",{filterType:a,count:b.getList().length})},selectOverLap:function(a,b){var c=a.getList();if(c)for(var d=0;d<c.length&&c[d];d++){var e=b.getNodeById(c[d].getNodeId());e&&e.select(null,!0)}},refreshSelectedListCount:function(a){juic.$(this.id+"selected_heading")&&a==parseInt(a)&&(-1==a?juic.$(this.id+"selected_heading").innerHTML=sfMessageFormat.format(this._config.msgs.SELECTED_HEADING_MESSAGE,this._config.msgs.SELECTED_UNKNOWN_LENGTH):
juic.$(this.id+"selected_heading").innerHTML=sfMessageFormat.format(this._config.msgs.SELECTED_HEADING_MESSAGE,a))},refreshSelectListCount:function(a){a==parseInt(a)&&juic.$(this.id+"select_heading")&&(-1==a?juic.$(this.id+"select_heading").innerHTML=sfMessageFormat.format(this._config.msgs.SELECT_HEADING_MESSAGE,this._config.msgs.SELECT_UNKNOWN_LENGTH):juic.$(this.id+"select_heading").innerHTML=sfMessageFormat.format(this._config.msgs.SELECT_HEADING_MESSAGE,a),this._rbSelDlgEnhanced&&("LaunchForm"===
this._source&&0==a)&&juic.$("rbListNoResults")&&(juic.$("rbListNoResults").innerHTML=sfMessageFormat.format(MSGS.COMMON_No_Result)))},reRenderSelectedMassButtons:function(){if(juic.$(this.id+"selectedMassButtons")){var a=[];this.renderSelectedMassButtons(a);juic.$(this.id+"selectedMassButtons").innerHTML=a.join("")}"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&disableDeselectAllLaunchForms("clearall")},renderSelectedMassButtons:function(a){if(this._config.allowMassChange||this._config.allowSelectedMassChange)a.push('  \x3cdiv class\x3d"rbSelectedSection_header clear_all"\x3e\x3cdiv class\x3d"rb_massSelection globalPortletDimmedTextColor"\x3e'),
this._deselectAllCheckBox=new SFCheckBoxInput("clearAll",MSGS.Deselect_All,this._deselectAllCheckBox?this._deselectAllCheckBox._checked:!1,!0),this._deselectAllCheckBox.addEventListener("change",this),this._selectedListView&&0<=this._selectedListView.getModel().getSelectedNodes().length&&this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked"),this._deselectAllCheckBox.renderHtml(a),a.push("\x3c/div\x3e\x3c/div\x3e")},reRenderSelectionMassButtons:function(){if(juic.$(this.id+"selectionMassButtons")){var a=
[];this.renderSelectionMassButtons(a);juic.$(this.id+"selectionMassButtons").innerHTML=a.join("");"undefined"!=typeof rbsd&&(null!=rbsd&&"LaunchForm"===rbsd._source)&&disableDeselectAllLaunchForms("selectnone")}},renderSelectionMassButtons:function(a){if(this._config.allowMassChange||this._config.allowSelectionMassChange)a.push('  \x3cdiv class\x3d"rbSelectionSection_header clear_all"\x3e\x3cdiv class\x3d"rb_massSelection"\x3e\x3cdiv class\x3d"globalPortletDimmedTextColor floatleft" tabindex\x3d0 role\x3d"checkbox" id\x3d"'+
this.id+'"\x3e'),this._selectedListView&&0==this._selectedListView.getModel().getSelectedNodes().length&&(this._listSelectall_none&&this._listSelectall_none.setState("unchecked"),this._deselectAllCheckBox&&this._deselectAllCheckBox.setState("unchecked")),this._listSelectall_none.renderHtml(a),a.push("\x3c/div\x3e"),this._rbSelDlgEnhanced&&this._selectedFilter&&(a.push('\x3cdiv id\x3d"'+this.id+'_autoComp" class\x3d"floatleft" style\x3d"padding-left:10px;"\x3e'),this._selectedFilter.renderHtml(a),
a.push("\x3c/div\x3e")),a.push("\x3c/div\x3e\x3c/div\x3e")},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'rbSelectDialog" class\x3d"rbSelectDialog ',this._config.cssClass?this._config.cssClass:"",'"\x3e');a.push('\x3cdiv class\x3d"');this.getLeftComponent()?a.push("rb3pane"):a.push("rb2pane");a.push('"\x3e');this._config.topComponent&&(a.push('  \x3cdiv class\x3d"globalPortletDimmedTextColor rbTopSection" style \x3d"padding-left:10px;"\x3e'),this._config.topComponent.renderHtml(a),a.push("\x3c/div\x3e"));
a.push('\x3cdiv class\x3d"rbwhole"\x3e');this.getLeftComponent()&&(a.push('  \x3cdiv class\x3d"rbLeftSection"\x3e'),a.push("\x3cdiv\x3e"),a.push('\x3cdiv class\x3d"leftSection_wrapper"\x3e'),this._config.leftComponent.renderHtml(a),a.push('\x3c/div\x3e\x3cspan class\x3d"cb" style\x3d"background-image: none;"\x3e\x3cspan class\x3d"cl"\x3e\x3c/span\x3e\x3c/span\x3e\x3c/div\x3e'),a.push("  \x3c/div\x3e"));a.push('\x3cdiv class\x3d"rbcentral_right"\x3e');a.push('\x3cdiv class\x3d"rbSelectionSection globalPortletDimmedTextColor"\x3e');
a.push('\x3cdiv style\x3d"padding-left:10px;"\x3e','\x3cdiv class\x3d"hd" tabindex\x3d0\x3e\x3cdiv class\x3d" floatleft" \x3e');this._rbSelDlgEnhanced?(a.push('\x3cspan style\x3d"font-weight:bold; font-size:15px;" id\x3d"',this.id,'select_heading"\x3e'),a.push(sfMessageFormat.format(this._config.msgs.SELECT_HEADING_MESSAGE,this._listView.getModel()?this._listView.getModel().getNumChildren():0)),a.push("\x3c/span\x3e")):(a.push('\x3ch2 class\x3d"bold" id\x3d"',this.id,'select_heading"\x3e'),a.push(sfMessageFormat.format(this._config.msgs.SELECT_HEADING_MESSAGE,
this._listView.getModel()?this._listView.getModel().getNumChildren():0)),a.push("\x3c/h2\x3e"));a.push("\x3c/div\x3e");a.push('\x3cdiv class\x3d" floatright"\x3e');this._config.selectionPaginator&&(a.push('\x3cdiv class\x3d"rb_paginator"\x3e'),this._config.selectionPaginator.renderHtml(a),a.push("\x3c/div\x3e"));a.push("\x3c/div\x3e");a.push("\x3c/div\x3e\x3c/div\x3e");a.push('\x3cdiv id\x3d"',this.id,'selectionMassButtons"\x3e');this.renderSelectionMassButtons(a);a.push("\x3c/div\x3e");this._config.selectionExtraComponent&&
(a.push('  \x3cdiv class\x3d"rbSelectionSection_extra_component clear_all"\x3e'),this._config.selectionExtraComponent.renderHtml(a),a.push("\x3c/div\x3e"));typeCheckbox=!0;this._listView.renderHtml(a);a.push("  \x3c/div\x3e");a.push('  \x3cdiv class\x3d"rbSelectedSection globalPortletDimmedTextColor"\x3e');a.push('\x3cdiv style\x3d"padding-left:10px;"\x3e','\x3cdiv class\x3d"hd" tabindex\x3d0\x3e\x3cdiv class\x3d"floatleft"\x3e');this._rbSelDlgEnhanced?(a.push('\x3cspan style\x3d"font-weight:bold; font-size:15px;" id\x3d"',
this.id,'selected_heading"\x3e'),a.push(sfMessageFormat.format(this._config.msgs.SELECTED_HEADING_MESSAGE,this._config.msgs.SELECTED_UNKNOWN_LENGTH)),a.push("\x3c/span\x3e")):(a.push('\x3ch2 class\x3d"bold" id\x3d"',this.id,'selected_heading"\x3e'),a.push(sfMessageFormat.format(this._config.msgs.SELECTED_HEADING_MESSAGE,this._config.msgs.SELECTED_UNKNOWN_LENGTH)),a.push("\x3c/h2\x3e"));a.push("\x3c/div\x3e");a.push('\x3cdiv class\x3d"floatright"\x3e');this._config.selectedPaginator&&(a.push('\x3cdiv class\x3d"rb_paginator"\x3e'),
this._config.selectedPaginator.renderHtml(a),a.push("\x3c/div\x3e"));a.push("\x3c/div\x3e");a.push("\x3c/div\x3e\x3c/div\x3e");a.push('\x3cdiv id\x3d"',this.id,'selectedMassButtons"\x3e');this.renderSelectedMassButtons(a);a.push("\x3c/div\x3e");this._config.selectedExtraComponent&&(a.push('  \x3cdiv class\x3d"rbSelectedSection_extra_component clear_all"\x3e'),this._config.selectedExtraComponent.renderHtml(a),a.push("\x3c/div\x3e"));typeCheckbox=!1;this._selectedListView.renderHtml(a);a.push("\x3c/div\x3e");
a.push("\x3c/div\x3e");a.push("\x3c/div\x3e");this._config.bottomComponent&&(a.push('  \x3cdiv class\x3d"rbBottomSection"\x3e'),this._config.bottomComponent.renderHtml(a),a.push("\x3c/div\x3e"));a.push("\x3c/div\x3e\x3c/div\x3e")},setSelectColumnHeading:function(a){this._config.msgs.SELECT_HEADING_MESSAGE=a},setSelectedColumnHeading:function(a){this._config.msgs.SELECTED_HEADING_MESSAGE=a},cleanup:function(){this._config.topComponent&&this._config.topComponent.removeEventListener("switchListDataDao",
this);this._config.bottomComponent&&this._config.bottomComponent.removeEventListener("switchListDataDao",this)}})}();function RBSelectDialogTreeNode(a,b,c){this.register();this._init(a,b,c)}
RBSelectDialogTreeNode.prototype=function(){return set(new RBDefaultTreeSelectNode,{_init:function(a,b,c){RBDefaultTreeSelectNode.prototype._init.call(this,a);this._text=b;this._id=c},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'"\x3e');a.push('\x3ca id\x3d"',this._nodeId,'_selectDialogTreeNode" href\x3d"javascript:;" onclick\x3d"',this.fireCode("_toggleSelected",this.getNodeId()),';return false;"\x3e');a.push("\x3cspan\x3e"+escapeHTML(this._text)+"\x3c/span\x3e");a.push("\x3c/a\x3e");
a.push("\x3c/div\x3e")}})}();function RBSelectDialogListNode(a,b,c){this.register();this._init(a,b,c)}
RBSelectDialogListNode.prototype=function(){return set(new RBSelectListNode,{_init:function(a,b,c){this._id=a;this._text=b;c&&(this._options=c,this._calloutInfo=c.calloutInfo,this._type=c.type);RBSelectListNode.prototype._init.call(this,this._id)},getId:function(){return this._id},getText:function(){return this._text},getType:function(){return this._type},getOptions:function(){return this._options},renderHtml:function(a,b){if("single_select"==b){this.radioItems=[];var c=this._nodeId,d=escapeHTML(this._text);
this.radioItems.push({value:c,label:d});this._buttonGroup=new SFRadioInput({options:this.radioItems});this._selected&&this._buttonGroup.setValue(this._nodeId);a.push('\x3cdiv style\x3d"padding-bottom:10px;"\x3e');this._buttonGroup.renderHtml(a);a.push("\x3c/div\x3e");this._buttonGroup.addEventListener("change",this)}else{a.push('\x3cdiv id\x3d"',this.id,'_singleSelectDialogListItem" class\x3d"globalPortletDimmedTextColor" style\x3d"padding-top:10px;padding-left:10px;"');this._calloutInfo&&a.push(' onmouseover\x3d"',
this.fireCode("_showPopup"),';return false;"');a.push("\x3e");var c=this._selected,d=this._nodeId,e=escapeHTML(this._text);this._checkBoxItem=new SFCheckBoxInput(d,e,c,!0);this._checkBoxItem.addEventListener("change",this);this._calloutInfo&&(this._callOutItemId=this._checkBoxItem.id+"_wrapper");this._checkBoxItem.renderHtml(a);a.push("\x3c/div\x3e")}},_showPopup:function(a){this.dispatch("showCalloutPopup",{actionCommand:"showCalloutInfo",id:this._callOutItemId,data:this._calloutInfo})},cleanup:function(){RBSelectListNode.prototype.cleanup.call(this);
this.unregister()},handleEvent:function(a){"change"===a.type&&(this._buttonGroup?(a.actionCommand=a.target.getRadioFieldByIndex(0).checked?"selected":"deSelected",this.dispatchEvent(a)):a.target&&this.dispatch("selectAction",{actionCommand:a.checked?"selected":"deSelected",nodeId:a.value}))}})}();function RBSelectDialogDummyWiring(a){this._init(a)}
RBSelectDialogDummyWiring.prototype=function(){return set(new EventTarget,{_init:function(a){this.leftComponent=new RBSelectTreeView(new RBSingleSelectTreeModel(new RBTreeMockDao));this.leftComponent.setAutoFetchPagedDataInView(!0);this.leftComponent.addEventListener("selected",this);this.leftComponent.addEventListener("deSelected",this);this.modelCache={};a._config={leftComponent:this.leftComponent,allowMassChange:!0,selectedPaginator:!0,selectionPaginator:!0,selectionExtraComponent:new SFLabel("label1"),
selectedExtraComponent:new SFLabel("label2"),msgs:{NO_SELECTED_RESULTS_MESSAGE:"please select from the leftComponent on the right or the drop down on the top"},topComponent:new SFLabel("Top Component"),bottomComponent:new SFLabel("Bottom Component")};a.setSelectedDao(new RBSelectDialogSelectedMockDao)},handleEvent:function(a){switch(a.type){case "selected":a.target==this.leftComponent&&(this.modelCache[a.nodeId]||(this.modelCache[a.nodeId]=new RBSelectDialogMockDao(a.nodeId)),this.leftComponent.dispatch("switchListDataDao",
{dao:this.modelCache[a.nodeId],evt:a}))}}})}();function RBTreeMockDao(){this._init()}RBTreeMockDao.prototype=function(){return set(new EventTarget,{_init:function(){},setRootNodeId:function(a){this._rootNodeId=a},fetchChildren:function(a,b){b=b?b:0;var c=[],d=new RBSelectDialogTreeNode;d.setNumChildren(3);c.push(d);d=new RBSelectDialogTreeNode;c.push(d);d=new RBSelectDialogTreeNode;d.setNumChildren(6);c.push(d);this.dispatch("dataAvailable",{data:c,parentNode:a,startIndex:b,endIndex:b+c.length-1})}})}();
function RBSelectDialogMockDao(a){this._init(a)}RBSelectDialogMockDao.prototype=function(){return set(new EventTarget,{_init:function(a){this._parentInfo=a},fetchChildren:function(a,b){var c=[];this.dispatch("listSizeChange",{listSize:a+20});for(var d=a;d<a+20;d++)c.push(new RBSelectDialogListNode("id"+d,this._parentInfo+" : "+d));this.dispatch("dataAvailable",{data:c,startIndex:a,endIndex:a+c.length-1,referenceObj:b})}})}();function RBSelectDialogSelectedMockDao(){}
RBSelectDialogSelectedMockDao.prototype=function(){return set(new EventTarget,{getNewItem:function(a){return new RBSelectDialogSelectedListMockNode(a.getId(),"text "+a.getId())},fetchChildren:function(a,b){var c=[];this.dispatch("listSizeChange",{listSize:a+20});for(var d=a;d<a+20;d++)c.push(new RBSelectDialogSelectedListMockNode("id"+d,"text"+d));this.dispatch("dataAvailable",{data:c,startIndex:a,endIndex:a+c.length-1,referenceObj:b})}})}();
function RBSelectDialogSelectedListMockNode(a,b){this.register();this._init(a,b)}
RBSelectDialogSelectedListMockNode.prototype=function(){return set(new RBSelectListNode,{_init:function(a,b){this._id=a;this._text=b;RBSelectListNode.prototype._init.call(this,this._id)},renderHtml:function(a){a.push("\x3cdiv\x3e");a.push('\x3ca class\x3d"checkbox_link" href\x3d"javascript:;" onclick\x3d"');a.push(this.fireCode("_toggleSelected"),'; return false;"\x3e\x26nbsp;\x3c/a\x3e');a.push("\x3cspan\x3eSelected Node ",this._text,"\x3c/span\x3e");a.push("\x3c/div\x3e")},cleanup:function(){RBSelectListNode.prototype.cleanup.call(this);
this.unregister()}})}();function RBHelpInfoWrapper(a){this.register();assert("undefined"!==typeof a,"[RBHelpInfoWrapper] Main help text is required");this.setMainHelpText(a)}
RBHelpInfoWrapper.prototype=function(){return set(new Component,{setComponent:function(a){this._component=a},setMainHelpText:function(a){this._mainHelpTxt=a;$("rb_help_s"+this.id)&&($("rb_help_s"+this.id).innerHTML=this._mainHelpTxt)},setHelpTextBelowObject:function(a){this._helpTxtBelow=a},renderHtml:function(a){this._component&&(a.push("\x3ctable\x3e\x3ctr\x3e\x3ctd"),this._component instanceof SFDropDown&&a.push(' class\x3d"globalPortletDimmedTextColor"'),a.push("\x3e"),this._component.renderHtml(a),
a.push("\x3c/td\x3e\x3ctd\x3e"));this._title=this._helpTxtBelow?this._mainHelpTxt+"("+this._helpTxtBelow+" )":this._mainHelpTxt;a.push('\x3cdiv title\x3d"',this._title,'" id\x3d"rb_help_m',this.id,'" class\x3d"sapIcon globalPortletDimmedTextColor floatleft"');a.push(' tabindex\x3d"0" style \x3d "padding-left : 10px; font-size : 16px;font-weight : normal;"\x3e\x26#xE1C4\x3c/div\x3e');this._component&&(a.push("\x3c/td\x3e\x3c/tr\x3e"),a.push("\x3c/table\x3e"))}})}();