window.Util&&window.Util.defineNonEnumPropIfNeeded?Util.defineNonEnumPropIfNeeded(Array.prototype,"______array","______array"):Array.prototype.______array="______array";
var JSON={org:"http://www.JSON.org",copyright:"(c)2005 JSON.org",license:"http://www.crockford.com/JSON/license.html",stringify:function(a){var e,b,f,c="";switch(typeof a){case "object":if(a){if("______array"==a.______array){for(b=0;b<a.length;++b)e=this.stringify(a[b]),c&&(c+=","),c+=e;return"["+c+"]"}if("undefined"!=typeof a.toString){for(b in a)e=a[b],"undefined"!=typeof e&&"function"!=typeof e&&(e=this.stringify(e),c&&(c+=","),c+=this.stringify(b)+":"+e);return"{"+c+"}"}}return"null";case "number":return isFinite(a)?
String(a):"null";case "string":f=a.length;c='"';for(b=0;b<f;b+=1)if(e=a.charAt(b)," "<=e){if("\\"==e||'"'==e)c+="\\";c+=e}else switch(e){case "\b":c+="\\b";break;case "\f":c+="\\f";break;case "\n":c+="\\n";break;case "\r":c+="\\r";break;case "\t":c+="\\t";break;default:e=e.charCodeAt(),c+="\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}return c+'"';case "boolean":return String(a);default:return"null"}},parse:function(a){function e(b){throw{name:"JSONError",message:b,at:h-1,text:a};}function b(){d=
a.charAt(h);h+=1;return d}function f(){for(;""!=d&&" ">=d;)b()}function c(){var c,a="",f,g;if('"'==d)a:for(;b();){if('"'==d)return b(),a;if("\\"==d)switch(b()){case "b":a+="\b";break;case "f":a+="\f";break;case "n":a+="\n";break;case "r":a+="\r";break;case "t":a+="\t";break;case "u":for(c=g=0;4>c;c+=1){f=parseInt(b(),16);if(!isFinite(f))break a;g=16*g+f}a+=String.fromCharCode(g);break;default:a+=d}else a+=d}e("Bad string")}function g(){var a="";"-"==d&&(a="-",b());for(;"0"<=d&&"9">=d;)a+=d,b();if("."==
d)for(a+=".";b()&&"0"<=d&&"9">=d;)a+=d;if("e"==d||"E"==d){a+="e";b();if("-"==d||"+"==d)a+=d,b();for(;"0"<=d&&"9">=d;)a+=d,b()}a=+a;if(isFinite(a))return a;e("Bad number")}function k(){switch(d){case "t":if("r"==b()&&"u"==b()&&"e"==b())return b(),!0;break;case "f":if("a"==b()&&"l"==b()&&"s"==b()&&"e"==b())return b(),!1;break;case "n":if("u"==b()&&"l"==b()&&"l"==b())return b(),null}e("Syntax error")}function l(){f();switch(d){case "{":var a;a:{var h={};if("{"==d){b();f();if("}"==d){b();a=h;break a}for(;d;){a=
c();f();if(":"!=d)break;b();h[a]=l();f();if("}"==d){b();a=h;break a}else if(","!=d)break;b();f()}}e("Bad object");a=void 0}return a;case "[":a:{a=[];if("["==d){b();f();if("]"==d){b();break a}for(;d;){a.push(l());f();if("]"==d){b();break a}else if(","!=d)break;b();f()}}e("Bad array");a=void 0}return a;case '"':return c();case "-":return g();default:return"0"<=d&&"9">=d?g():k()}}var h=0,d=" ";return l()}},req;
function prepareAjaxRequest(){req=!1;try{req=new XMLHttpRequest}catch(a){try{req=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{req=new ActiveXObject("Microsoft.XMLHTTP")}catch(b){try{req=new ActiveXObject("Msxml2.XMLHTTP.4.0")}catch(f){return alert(MSGS.TOM_UNSUPPORTED),null}}}}}
function submitAjaxQuery(a){prepareAjaxRequest();if(req)try{req.open("GET",a,!1);req.send(null);if(200!=req.status)return alert("Status "+req.status),error_text=req.statusText,!1;if(-1==req.getResponseHeader("Content-Type").indexOf("text/plain"))return error_text="Your session has timed out",alert(error_text),!1;var e=JSON.parse(req.responseText);queried_items=e.queried_items;total_items=e.total_items;items=e.items;error=e.error}catch(b){return error_text=b.message,!1}return!0}
function submitAjaxQueryIgnoreResponse(a){prepareAjaxRequest();if(req)try{req.open("GET",a,!1),req.send(null)}catch(e){return error_text=e.message,!1}return!0}function submitAsyncAjaxQuery(a,e){return submitAsyncAjaxQueryAdv(a,"GET",null,e)}function submitAsyncAjaxQueryAdv(a,e,b,f,c){return submitAjaxQueryAdv(a,e,b,!0,f,c)}
function submitAjaxQueryAdv(a,e,b,f,c,g){prepareAjaxRequest();if(req)try{req.onreadystatechange=c,req.open(e,a,f),g&&g(req),req.send(b)}catch(k){return error_text=k.message,!1}return!0};