function SFAbstractAdjustableHeight(){juic.assert(!1,"[SFAbstractAdjustableHeight] Please do not instantiate")}juic.extend(SFAbstractAdjustableHeight,juic.Component,{setHeight:function(b){juic.assert(!1,"[SFAbstractAdjustableHeight] Must implement setHeight")}});function SFButtonLayout(b,c){this._baseButtonWrapperClass=c;this._super(b,{styleClass:"buttonLayout",innerClass:"buttonWrapper",outerBlock:!0,innerBlock:!1})}
(function(){SFButtons={OK:{actionCommand:"ok",label:MSGS.COMMON_Ok,active:!0},CANCEL:{actionCommand:"cancel",label:MSGS.COMMON_Cancel},PREVIOUS:{actionCommand:"previous",label:MSGS.COMMON_Previous},NEXT:{actionCommand:"next",label:MSGS.COMMON_Next,active:!0},DONE:{actionCommand:"done",label:MSGS.COMMON_Done,active:!0},OK_CANCEL:["CANCEL","OK"],PREVIOUS_NEXT_CANCEL:["CANCEL","PREVIOUS","NEXT"],PREVIOUS_NEXT:["PREVIOUS","NEXT"],normalize:function(b){if(b){var c=SFButtons[b];c&&!Array.isArray(c)&&(b=
c);return{label:b.label||b.text||b.toString(),active:b.active,actionCommand:b.eventName||b.actionCommand||b.command||("string"==typeof b?b:null),size:b.size,enabled:null==b.enabled?null==b.disabled?!0:!b.disabled:b.enabled,data:b.data,ariaLabel:b.ariaLabel,baseButtonWrapperClass:b.baseButtonWrapperClass}}return null},normalizeSet:function(b){"string"==typeof b&&SFButtons[b]&&(b=SFButtons[b]);var c=[];b&&(Array.isArray(b)||(b=[b]),b.forEach(function(b){c.push(SFButtons.normalize(b))},this));return c}};
juic.extend(SFButtonLayout,SFListContainer,{setModel:function(b){b=SFButtons.normalizeSet(b);Array.isArray(b)&&(b=new SFDefaultListModel(b));assert(b instanceof SFDefaultListModel,"SFButtonLayout: invalid model");this._buttonModel=b;this._super(new SFFactoryListModel(this._buttonModel,this._createButton,this))},getModel:function(){return this._buttonModel},getButtonDefinitions:function(){return this._buttonModel.getItems()},setButtonDefinitions:function(b){this._buttonModel.setItems(SFButtons.normalizeSet(b))},
getButtonDefinition:function(b){return this._buttonModel.get(b)},setButtonDefinition:function(b,c){this._buttonModel.set(b,SFButtons.normalize(c))},insertButton:function(b,c){this._buttonModel.insertItemAt(b,SFButtons.normalize(c))},appendButton:function(b){this._buttonModel.add(SFButtons.normalize(b))},removeButton:function(b){this._buttonModel.removeItemAt(b)},setButtonsEnabled:function(b){this.broadcast(function(c,d){c.setEnabled(b);this._buttonModel.get(d).enabled=b})},setButtonEnabled:function(b,
c){var d=this.get(b);d&&(this._buttonModel.get(b).enabled=c,d.setEnabled(c))},setButtonLabel:function(b,c){var d=this.get(b);d&&(this._buttonModel.get(b).label=c,d.setLabel(c))},setButtonActionCommand:function(b,c){var d=this.get(b);d&&(this._buttonModel.get(b).actionCommand=c,d.setActionCommand(c))},setButtonVisible:function(b,c){var d=this.get(b);d&&(this._buttonModel.get(b).visible=c,d.setVisible(c))},_createButton:function(b){b=SFButtons.normalize(b);juic.assert(b,"SFButtonLayout: You cannot pass null for the button definition");
if(b){var c=new SFCommandButton(b.label,b.active,b.enabled,!0,{baseButtonWrapperClass:this._baseButtonWrapperClass||b.baseButtonWrapperClass,ariaLabel:b.ariaLabel});c.setActionCommand(b.actionCommand);c.setData(b.data);b.size&&c.setSize(b.size);c.addEventListener("action",this,"dispatchEvent");return c}}})})();function SFFocusMarker(b){this.register();this._init(b)}
(function(){juic.extend(SFFocusMarker,juic.Component,{_init:function(b){this._disabled=b&&b.disabled},renderHtml:function(b){b.push('\x3cbutton id\x3d"',this.getId(),'" class\x3d"sfFocusMarker hiddenAriaContent"');this._disabled&&b.push(' style\x3d"display:none;"');b.push(' onfocus\x3d"',this.fireCode("_onEventDispatch","focus"),'"',' onblur\x3d"',this.fireCode("_onEventDispatch","blur"),'"',' title\x3d"',MSGS.COMMON_HIDDEN_FOCUS_MARKER_TITLE,'"',"\x3e\x3c/button\x3e")},_onEventDispatch:function(b,
c){this.dispatch(b,{userEvent:c})},getId:function(){return this.id},disableMarker:function(){this._disabled=!0;SFDom.setStyle(this.getId(),"display","none")},enableMarker:function(){this._disabled=!1;SFDom.setStyle(this.getId(),"display","inline")},focus:function(){var b=juic.$(this.getId());b&&b.focus&&b.focus()}})})();function SFFocusLoop(b){this._parentElementId=b}
SFFocusLoop.prototype=function(){function b(b,d){juic.assert(null!=d,"SFFocusLoop: Parent is not rendered");if(d){var a=SFDom.walk(d[b?"lastChild":"firstChild"],d,function(a){return!SFDom.hasClass(a,"sfFocusMarker")&&SFDom.isFocusable(a,!0)?a:!1},null,b);SFDom.setFocus(a)}}return juic.set(new juic.EventTarget,{_parentElementId:null,cleanup:function(){this.startMarker.cleanup();this.endMarker.cleanup()},setFocus:function(c){b(c,this._getParentElement())},getMarkers:function(b){this.startMarker=new SFFocusMarker(b);
this.startMarker.addEventListener("focus",this,"_loopMarkers");this.endMarker=new SFFocusMarker(b);this.endMarker.addEventListener("focus",this,"_loopMarkers");return[this.startMarker,this.endMarker]},disableMarkers:function(){this.startMarker&&this.startMarker.disableMarker();this.endMarker&&this.endMarker.disableMarker()},enableMarkers:function(){this.startMarker&&this.startMarker.enableMarker();this.endMarker&&this.endMarker.enableMarker()},_getParentElement:function(){juic.assert(this._parentElementId,
"Parent Element Id Not Set");return juic.$(this._parentElementId)},_loopMarkers:function(c){var d=this;window.setTimeout(function(){b(c.target.id===d.startMarker.id,d._getParentElement())},1)}})}();function SFPanel(b){this.register();this._init(b)}
(function(){var b=["header","content","buttonLayout","footer"],c={header:"panelHeader globalPortletHeader",content:"panelContent globalPortletBody",buttonLayout:"panelButtonLayout",footer:"panelFooter"},d=document.createElement("div");juic.extend(SFPanel,SFAbstractAdjustableHeight,{_init:function(a){if(a){if("undefined"!=typeof a.titleHeaderTagLevel&&(juic.assert("number"==typeof a.titleHeaderTagLevel,"[SFPanel] : titleHeaderTagLevel must be a number."),juic.assert(-1<a.titleHeaderTagLevel&&7>a.titleHeaderTagLevel,
"[SFPanel] : titleHeaderTagLevel must be a number between 0 and 6.")),this._header=a.header,this._title=a.title,this._titleHeaderTagLevel=a.titleHeaderTagLevel,this._useNameAnchor=a.useNameAnchor,this._showCloseIcon=a.showCloseIcon,this._closeDialogOnEsc=a.closeDialogOnEsc,this._headerTag=!0===this._useNameAnchor?"a":"span",this._content=a.content,this._footer=a.footer,this._type=a.type,this._width=a.width,this._height=a.height,this._scrollable=null!=a.scrollable?a.scrollable:!1,this._escapeHtml=
null!=a.escapeHtml?a.escapeHtml:!0,this._ownChildren=!1!==a.ownChildren,this._baseButtonWrapperClass=a.baseButtonWrapperClass,this._ignoreAccessibility=a.ignoreAccessibility,this._focusable=a.focusable,this._ariaLabel=a.ariaLabel,this._panelRole=a.panelRole,(a=a.buttonDefinitions||a.buttons)&&0<a.length)this._buttonLayout=new SFButtonLayout(a,this._baseButtonWrapperClass),this._buttonLayout.addEventListener("action",this,"handleButton")}else this._scrollable=!1,this._ownChildren=!0},renderHtml:function(a){a.push('\x3cdiv id\x3d"',
this.id,'" class\x3d"',this._getSectionClassName(),'"');SFDom.renderStyle(a,this._getStyle());this._ignoreAccessibility?(this._ariaLabel&&a.push(" aria-label\x3d'",this._ariaLabel,"'"),this._panelRole&&a.push(" role\x3d'",this._panelRole,"'")):(this.renderAriaAttributes(a),a.push(' role\x3d"group"'));this._focusable&&a.push(" tabindex\x3d'0'");a.push("\x3e");for(var b=this._getSectionOrder(),c=0;c<b.length;c++){var f=b[c];this._renderSection(a,f,this["_"+f])}a.push("\x3c/div\x3e")},renderAriaAttributes:function(a){null!=
this._title&&a.push(' aria-labelledby\x3d"',this.id,'_panelTitle"');null!=this._content&&a.push(' aria-describedby\x3d"',this.id,'content"')},handleButton:function(a){this.dispatchEvent(a)},_renderSection:function(a,b,c){if(this._isSectionRendered(b,c)){var f=this._getSectionClassName(b);a.push('\x3cdiv id\x3d"',this.id,b,'"');f&&a.push(' class\x3d"',f,'"');SFDom.renderStyle(a,this._getStyle(b));a.push("\x3e");this._renderContent(a,b,c);a.push("\x3c/div\x3e")}},_renderContent:function(a,b,c){null!=
c&&(a=(b=Array.isArray(a)?a:null)?juic.createRenderContext():a,this._escapeHtml&&!(c instanceof juic.Component)?a.push(juic.escapeHTML(c.toString())):a.push(c),b&&b.push(a.join("")))},_renderStandardHeader:function(a){a.push('\x3cspan id\x3d"',this.id,'headerContainer", class\x3d"sfPanelHeaderContainer"\x3e');this._renderStandardHeaderContent(a);a.push("\x3c/span\x3e")},_renderStandardHeaderContent:function(a){this._renderTitle(a);this._showCloseIcon&&(a.push("\x26nbsp;"),a.push('\x3cbutton id\x3d"',
this.id,'closeIcon" class\x3d"closeDialog globalPortletCloseIcon globalIconFont1Support" title\x3d"',MSGS.COMMON_Close,'"  onclick\x3d"',this.fireCode("_handleClose"),'return false;" style\x3d"display:',this._showCloseIcon?"block":"none",'"\x3e\x3cspan class\x3d"legacyFont1Icon"\x3e\x3c/span\x3e\x3c/button\x3e'))},_usesStandardHeader:function(){return!1},setShowCloseIcon:function(a){this._showCloseIcon=a;var b=juic.$(this.id+"closeIcon");b&&(b.style.display=a?"":"none")},isShowCloseIcon:function(){return this._showCloseIcon},
_handleClose:function(){},_renderTitle:function(a){this._closeDialogOnEsc&&a.push('\x3cspan class\x3d"hiddenAriaContent"\x3e',MSGS.COMMON_PRESS_ESC_KEY,"\x3c/span\x3e");if(this._title||this._useNameAnchor)this._titleHeaderTagLevel&&a.push("\x3ch",this._titleHeaderTagLevel,"\x3e"),a.push("\x3c",this._headerTag,' id\x3d"',this.id,'_panelTitle"',this._ignoreAccessibility?' aria-hidden\x3d"true"':' role\x3d"heading" style\x3d"display: block;width: 90%;" class\x3d"'),!0===this._useNameAnchor?(a.push("namedAnchor"),
this._title||a.push(" hiddenAriaContent"),a.push(' panelHeaderTitle" tabindex\x3d"-1" name\x3d"',this._getAnchorName(),'"\x3e')):a.push('"\x3e'),this._title&&"string"==typeof this._title?a.push(juic.escapeHTML(this._title)):a.push(this._title||"\x26nbsp;"),a.push("\x3c/",this._headerTag,"\x3e"),this._titleHeaderTagLevel&&a.push("\x3c/h",this._titleHeaderTagLevel,"\x3e")},getTitle:function(){return this._title},setTitle:function(a){this._title=a;this._usesStandardHeader()&&this._setSectionContent("header",
"\x26nbsp;")},setFocusNamedAnchor:function(){location.hash="#"+this._getAnchorName()},setFocus:function(a){this.isShown()&&(this._useNameAnchor&&!a)&&this.setFocusNamedAnchor()},_handleRefocus:function(){var a=this._refocusRef;a&&setTimeout(function(){a.setFocus?a.setFocus():a.focus?a.focus():SFDom.setFocus(a)},0)},isShown:function(){},_getAnchorName:function(){return Util.createAnchorName("sfPanelHeaderAnchor_"+this.id)},adjustDOM:function(){this._updateStyles()},setWidth:function(a){this._width=
a;this._updateStyles()},setHeight:function(a){this._height=a;this._updateStyles()},getWidth:function(){return this._width},getHeight:function(){var a=juic.$(this.id);return"auto"===this._height&&a?a.offsetHeight:this._height},setType:function(a){this._type=a;this._updateClassName()},getType:function(){return this._type},setHeader:function(a){this._setSectionContent("header",a)},getHeader:function(){return this._header},setContent:function(a){this._setSectionContent("content",a)},getContent:function(){return this._content},
setFooter:function(a){this._setSectionContent("footer",a)},getFooter:function(){return this._footer},getButtonLayout:function(){this._buttonLayout||(this._buttonLayout=new SFButtonLayout([],this._baseButtonWrapperClass),this._buttonLayout.addEventListener("action",this,"handleButton"),this._setSectionContent("buttonLayout",this._buttonLayout));return this._buttonLayout},getButtonModel:function(){return this._buttonLayout&&this._buttonLayout.getModel()},setScrollable:function(a){this._scrollable=a;
this._updateStyles()},isScrollable:function(){return this._scrollable},cleanup:function(){this._ownChildren&&(this._header instanceof juic.Component&&this._header.cleanup(),this._content instanceof juic.Component&&this._content.cleanup(),this._footer instanceof juic.Component&&this._footer.cleanup());this._buttonLayout&&this._buttonLayout.cleanup();this._super()},_setSectionContent:function(a,b){this["_"+a]=b;var c=juic.$(this.id+a),f=this._isSectionRendered(a,b);if(c)if(f){var h=juic.createRenderContext();
this._renderContent(h,a,b);h.renderInto(c)}else{for(f=juic.$(this.id);c.parentNode!==f;)c=c.parentNode;f.removeChild(c)}else if(f&&(f=juic.$(this.id))){h=juic.createRenderContext();this._renderSection(h,a,b);d.innerHTML=h.join("");for(var c=d.firstChild,h=this._getSectionOrder(),s,l=0;l<h.length;l++)if(h[l]==a){s=l;break}for(var q=null,l=s+1;!q&&l<h.length;l++)q=juic.$(this.id+h[l]);q?f.insertBefore(c,q):f.appendChild(c)}this._margins=null;this._updateStyles()},_isSectionRendered:function(a,b){return b||
"content"==a},_getStyle:function(a){var b={};switch(a){case void 0:this._width&&(b.width="number"==typeof this._width?this._width+"px":this._width);break;case "content":b={},this._scrollable&&(b.overflow="auto"),a=this._getInnerHeight(),b.height=a?a+"px":""}return b},_updateClassName:function(a){var b;if(b=a?juic.$(this.id+a):juic.$(this.id))b.className=this._getSectionClassName(a)},_updateStyles:function(a){var b=juic.$(this.id+(a?a:""));if(b&&(SFDom.updateStyle(b,this._getStyle(a)),null==a)){a=
this._getSectionOrder();for(b=0;b<a.length;b++)this._updateStyles(a[b]);a=this._getInnerHeight();null!=a&&this._content instanceof SFAbstractAdjustableHeight&&this._content.setHeight(a)}},_getInnerHeight:function(){var a=null;null!=this._height&&(a=this._getMarginToFitContent(),a=null!=a?Math.max(0,this._height-a):this._height);return a},_getMarginToFitContent:function(a){this._margins=this._margins||{};a=a||"y";var b=this._margins[a];if(null==b){var c=juic.$(this.id);if(c){var b=juic.$(this.id+"content"),
f="x"==a?"width":"height",h=c.style[f];c.style[f]="";b=SFDom.getMarginToFitDescendant(c,b,a);c.style[f]=h;this._margins[a]=b}}return b},_getSectionClassName:function(a){if(a){var b=c[a];"header"==a&&(this._usesStandardHeader()&&!this._title&&!this._showCloseIcon)&&(b+=" hiddenAriaContent");return b}a=["sfPanelComponent"];this._type&&a.push(this._type);(this._title||this._header)&&a.push("hasTitle");return a.join(" ")},_getSectionOrder:function(){return b}})})();
function SFRevolutionPanel(b){this._super(b)}juic.extend(SFRevolutionPanel,SFPanel,{_init:function(b){var c="globalContainer globalPortletBodyBackground globalRoundedCorners revolutionPanel";b.type&&(c+=" "+b.type);this._super(juic.set(b,{type:c}))},_getSectionClassName:function(b){var c=this._super(b);"header"==b&&(c+=" globalRoundedCornersHeader globalModernStyleSupport");return c}});function SFCalloutPanel(b){this._super(b)}
(function(){var b="startMarker header content buttonLayout footer pointerContainer pointer endMarker".split(" "),c={direction:"top",offset:"middle"};juic.extend(SFCalloutPanel,SFPanel,{_init:function(b){b=b?juic.set({},b):{};var a=b.pointerOptions;if(a){var e=a.direction,g=a.offset,a=!!a.flipOffset;["top","right","bottom","left"].contains(e)||(e=c.direction);if("middle"!=g)if(isNaN(g))g=c.offset;else var f=["top","bottom"].contains(e)?30:50,g=Math.max(parseInt(g),f);a={direction:e,offset:g,flipOffset:a}}else a=
juic.set({},c);e=b.type;b.type="globalRoundedCorners revolutionPanel revolutionCallout"+(e?" "+e:"");b.pointerOptions=a;this._super(b);this._pointerOptions=b.pointerOptions;this._clickOutsideClosesPopup=b&&b.clickOutsideClosesPopup;juic.assert(this._pointerOptions,"SFCalloutPanel: Invalid pointer options.")},_getStyle:function(b){if("pointer"==b||"pointerContainer"==b){var a=this._pointerOptions,e={};if(a){var c=a.direction,f=a.offset,f="middle"==f?"50%":f+"px";switch(c){case "top":case "bottom":e[a.flipOffset?
"right":"left"]=f;e[a.flipOffset?"left":"right"]="auto";break;case "left":case "right":e[a.flipOffset?"bottom":"top"]=f,e[a.flipOffset?"top":"bottom"]="auto"}"pointerContainer"==b&&Util.browserInfo.ie&&9>=Util.ieVersion()?e[c]="-1px":e[c]=0;switch(c){case "top":e.bottom="auto";break;case "bottom":e.top="auto";break;case "left":e.right="auto";break;case "right":e.left="auto"}}return e}return this._super(b)},_getSectionClassName:function(b){var a=this._super(b);switch(b){case void 0:if(!this._header)return a+
" globalContentBackground globalContentForeground noTitle";break;case "pointer":a="globalCalloutPointer calloutPointer";this._pointerOptions&&this._pointerOptions.direction&&(a+=" calloutDirection-"+this._pointerOptions.direction);break;case "pointerContainer":a="globalCalloutPointerContainer calloutPointer";this._pointerOptions&&this._pointerOptions.direction&&(a+=" calloutDirection-container-"+this._pointerOptions.direction);break;case "header":"header"==b&&(a+=" globalRoundedCornersHeader")}return a},
_isSectionRendered:function(b,a){return"pointer"==b||"pointerContainer"==b?!0:this._super(b,a)},_getSectionOrder:function(){return b}})})();function SFContextPopup(b,c){this.register();this._init(b,c)}
(function(){function b(a,b){var f=Util.isRTL()?"right":"left",f={origin:a.origin?juic.set({},a.origin):{vertical:"bottom",horizontal:f},menu:a.menu?juic.set({},a.menu):{vertical:"top",horizontal:f},offset:a.offset?juic.set({},a.offset):void 0};if(b){if(f.offset){if(f.origin.vertical!=b.origin.vertical||f.menu.vertical!=b.menu.vertical)f.offset.vertical*=-1;if(f.origin.horizontal!=b.origin.horizontal||f.menu.horizontal!=b.menu.horizontal)f.offset.horizontal*=-1}f.origin=b.origin;f.menu=b.menu}return f}
var c=Util.browserInfo.android||Util.browserInfo.ios,d={context:SFPositionManager,originId:null,refocusRef:null,visibleOverflow:!1,preventRedisplay:!0,loopFocus:!1,setFocusOnSelf:!1,closeOnEscape:!1,closeOnClick:!1,closeOnMouseout:!1,hideLatency:0.5},a={context:SFAbstractPositionManager};juic.extend(SFContextPopup,juic.Component,{_init:function(b,c){c=new juic.Config(c,d,a);this._originalPoint={offset:c&&c.offset,menu:c&&c.menu,origin:c&&c.origin};this.setChild(b);this._context=c.context;this._originId=
c.originId;this._visibleOverflow=c.visibleOverflow;this._preventRedisplay=c.preventRedisplay;this._lastHiddenTimeStamp=0;this._loopFocus=c.loopFocus;this._setFocusOnSelf=c.setFocusOnSelf;this._closeOnEscape=c.closeOnEscape;this._closeOnClick=c.closeOnClick;this._refocusRef=c.refocusRef;this._closeOnMouseout=c.closeOnMouseout;this._hideLatency=c.hideLatency;this._fullScreen=c.fullScreen;this._fullScreenThreshold=c.fullScreenThreshold;this._showRelativeToViewport=c.showRelativeToViewport;this._stopTouchMove=
c.stopTouchMove;this._loopFocus&&(this._focusLoop=new SFFocusLoop(this.id),this._focusMarkers=this._focusLoop.getMarkers())},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'" onmousedown\x3d"',this.fireCode("_onMouseDown"),'" ontouchstart\x3d"',this.fireCode("_onMouseDown"),'" style\x3d"max-height: ',SFDom.getViewportHeight()-20,"px; max-width: ",SFDom.getViewportWidth()-20,"px");this._visibleOverflow||a.push("; overflow: hidden");this._stopTouchMove&&a.push('" ontouchmove\x3d"SFDOMEvent.stopPropagation(event)');
a.push('"\x3e');this._focusMarkers&&a.push(this._focusMarkers[0]);this._child.renderHtml(a);this._focusMarkers&&a.push(this._focusMarkers[1]);a.push("\x3c/div\x3e")},show:function(a,d){var f=this._showRelativeToViewport;d=d||{};d.refocusRef&&(this._refocusRef=d.refocusRef);null!=d.setFocusOnSelf&&(this._setFocusOnSelf=d.setFocusOnSelf);"boolean"==typeof d.showRelativeToViewport&&(f=d.showRelativeToViewport);var h=a==this._currentOriginId;this._currentOriginId=a||this._originId;this._allowShow()?(this._shown=
!0,this._isFullScreen=this._fullScreen,!this._isFullScreen&&null!=this._fullScreenThreshold&&(this._isFullScreen=SFDom.getViewportWidth()<=this._fullScreenThreshold),this._isFullScreen?(SFOverlayMgr.addEventListener("overlayRendered",this,"_onFullScreenRendered"),SFOverlayMgr.show(this,{fullScreen:!0,viewport:!0,modal:!0,centered:!1,css:{top:0,left:0}})):(this._context.addEventListener("positionFixed",this,"_onPositionFixed"),this._context.show({component:this,originId:this._currentOriginId,fixPoint:b(this._originalPoint,
this._currentPoint),alwaysInViewport:!0,showRelativeToViewport:f})),c?(SFDOMEvent.addListener(window.document,"touchstart",this._onWindowMouseDown,this),SFDOMEvent.addStopPropagationListener("touchstart",this,"_onNotifyClick")):(SFDOMEvent.addListener(window.document,"mousedown",this._onWindowMouseDown,this),SFDOMEvent.addStopPropagationListener("mousedown",this,"_onNotifyClick")),this._closeOnEscape&&SFDOMEvent.addListener(window.document,"keydown",this._onWindowKeyDown,this),this._closeOnMouseout&&
this._bindMouseOutAndOver()):h||this._isFullScreen||this._context.moveTo(this.id,b(this._originalPoint,this._currentPoint),this._currentOriginId,!0)},hide:function(){this._shown&&(this._shown=!1,this.dispatch("hide"),this._isFullScreen?SFBodyEventDispatcher.removeResizeListener(null,this):this._context.removeEventListener("positionFixed",this),c?(SFDOMEvent.removeListener(window.document,"touchstart",this._onWindowMouseDown,this),SFDOMEvent.removeStopPropagationListener("touchstart",this)):(SFDOMEvent.removeListener(window.document,
"mousedown",this._onWindowMouseDown,this),SFDOMEvent.removeStopPropagationListener("mousedown",this)),this._closeOnEscape&&SFDOMEvent.removeListener(window.document,"keydown",this._onWindowKeyDown,this),this._refocusRef&&this._handleRefocus(),this._closeOnMouseout&&(this._unBindMouseOutAndOver(),this._cleanHidePopupTimeout()))},setChild:function(a){this._child&&(this._child.removeEventListener("changeDimensions",this),this._child.removeEventListener("hide",this),this._child.removeEventListener("action",
this));if(this._child=a)this._child.addEventListener("changeDimensions",this,"_onChangeDimension"),this._child.addEventListener("hide",this,"hide"),this._child.addEventListener("action",this,"_onChildAction")},setFocus:function(a){this._focusLoop&&this._focusLoop.setFocus(a)},isFullScreen:function(){return this._isFullScreen},_onFullScreenRendered:function(a){SFOverlayMgr.removeEventListener("overlayRendered",this);SFBodyEventDispatcher.addResizeListener(this,"_onFullScreenResize");this._child instanceof
SFAbstractPositionable&&this._child.handleFullScreenResize(this._getViewportDims(),!0);this._setFocusOnSelf&&this.setFocus()},_onFullScreenResize:function(a){this._child instanceof SFAbstractPositionable&&this._child.handleFullScreenResize(this._getViewportDims(),!1)},_getViewportDims:function(){return{width:SFDom.getViewportWidth(),height:SFDom.getViewportHeight()}},_handleRefocus:function(){var a=this._refocusRef;a&&setTimeout(function(){a.setFocus?a.setFocus():a.focus?a.focus():SFDom.setFocus(a)},
0)},isShown:function(){return this._shown},cleanup:function(a){!1!==a&&this._child.cleanup();this._focusLoop&&this._focusLoop.cleanup();this.unregister()},resetCurrentPosition:function(){this._currentPoint=null},preventClose:function(){this._clickedInsidePopup=!0;var a=this;setTimeout(function(){a._clickedInsidePopup=!1},0)},_updateClassName:function(){var a=juic.$(this.id);a&&(a.className="popupAligned-"+this._currentPoint.menu.horizontal+" popupAligned-"+this._currentPoint.menu.vertical)},_onChildAction:function(a){"hide"==
a.actionCommand&&this.dispatch("hide")},_allowShow:function(){var a=!this._shown;a&&this._preventRedisplay&&250>=(new Date).getTime()-this._lastHiddenTimeStamp&&(a=!1);return a},_onPositionFixed:function(a){a.componentId==this.id&&(this._childChangedDimension||(this._currentPoint=a.positionInfo.fixPoint,this._updateClassName(),"undefined"!=typeof SFAbstractPositionable&&this._child instanceof SFAbstractPositionable?this._child.positionFixed(a):"undefined"!=typeof SFAbstractResizable&&this._child instanceof
SFAbstractResizable?(a.newComponentWidth||a.newComponentHeight)&&this._child.setDimension({width:a.newComponentWidth,height:a.newComponentHeight}):"undefined"!=typeof SFAbstractAdjustableHeight&&this._child instanceof SFAbstractAdjustableHeight&&a.newComponentHeight&&this._child.setHeight(a.newComponentHeight)),this._loopFocus&&this._setFocusOnSelf&&this.setFocus(),this.dispatch("positionFixed"))},_bindMouseOutAndOver:function(){var a=juic.$(this._currentOriginId);a&&(SFDOMEvent.addListener(a,"mouseover",
this._handleMouseOver,this),SFDOMEvent.addListener(a,"mouseout",this._handleMouseOut,this));if(a=juic.$(this.id))SFDOMEvent.addListener(a,"mouseover",this._handleMouseOver,this),SFDOMEvent.addListener(a,"mouseout",this._handleMouseOut,this)},_unBindMouseOutAndOver:function(){var a=juic.$(this._currentOriginId);a&&(SFDOMEvent.removeListener(a,"mouseover",this._handleMouseOver,this),SFDOMEvent.removeListener(a,"mouseout",this._handleMouseOut,this));if(a=juic.$(this.id))SFDOMEvent.removeListener(a,"mouseover",
this._handleMouseOver,this),SFDOMEvent.removeListener(a,"mouseout",this._handleMouseOut,this)},_handleMouseOver:function(a){this._cleanHidePopupTimeout()},_handleMouseOut:function(a){var b=juic.$(this._currentOriginId),f=juic.$(this.id),h=this,c=SFDOMEvent.getRelatedTarget(a);this._cleanHidePopupTimeout();0<this._hideLatency&&(this._hidePopupTimeout=setTimeout(function(){f&&(!SFDom.isAncestor(b,c)&&!SFDom.isAncestor(f,c))&&h.hide()},1E3*this._hideLatency))},_cleanHidePopupTimeout:function(){this._hidePopupTimeout&&
clearTimeout(this._hidePopupTimeout)},_onNotifyClick:function(a){this._onWindowMouseDown(a.userEvent)},_onWindowMouseDown:function(a){a||(a=window.event);if(!this._clickedInsidePopup){var b=a&&SFDOMEvent.getTarget(a);SFDom.isAncestor(this.id,b)?this._onMouseDown(a):(this.dispatch("clickedOutsidePopup",{userEvent:a}),this._closeOnClick&&this.hide(),this._lastHiddenTimeStamp=(new Date).getTime())}},_onMouseDown:function(a){this.preventClose();this.dispatch("preventBlur",{mouseEvent:a})},_onWindowKeyDown:function(a){switch(SFDOMEvent.getKeyName(a)){case "ESCAPE":this.hide()}},
_onChangeDimension:function(){if(this._shown){var a=juic.$(this.id);this.dispatch("changeDimensions",{width:a.offsetWidth,height:a.offsetHeight});this._childChangedDimension=!0;this.reposition();this._childChangedDimension=!1}},reposition:function(){this._isFullScreen||this._context.moveTo(this.id,b(this._originalPoint,this._currentPoint),this._currentOriginId,!0)},setCloseOnClick:function(a){this._closeOnClick=a},setRefocusId:function(a){this._refocusRef=a}})})();
function SFAbstractDropComponent(b){this.register();this._init(b)}
(function(){var b={useButton:!1},c={};juic.extend(SFAbstractDropComponent,juic.Component,{_init:function(d){d=new juic.Config(d,b,c);this._useButton=d.useButton;this._popup=new SFContextPopup(this._createPopupContents(),this._getPopupOptions());this._popup.addEventListener("hide",this,"_onPopupHidden")},cleanup:function(){this.hide();this._popup.cleanup();this._super()},renderHtml:function(b){this._useButton?b.push("\x3cbutton"):b.push('\x3ca href\x3d"javascript:void(0)"');b.push(' id\x3d"',this.getReferenceId(),
'" class\x3d"',this._getClassName(),'" aria-haspopup\x3d"true" role\x3d"menu" onclick\x3d"',this.fireCode("show"),'return false;" aria-owns\x3d"',this._popup.getReferenceId(),'"\x3e');this._renderButtonContents(b);this._useButton?b.push("\x3c/button\x3e"):b.push("\x3c/a\x3e")},_renderButtonContents:function(b){throw Error("SFAbstractDropComponent: Must implement _renderButtonContents");},_createPopupContents:function(){throw Error("SFAbstractDropComponent: Must implement _createPopupContents");},
_getClassName:function(){return"sfDropComponent"},_getPopupOptions:function(){return{visibleOverflow:!0,originId:this.getReferenceId(),refocusRef:this,loopFocus:!0,closeOnEscape:!0,closeOnClick:!0,setFocusOnSelf:!0}},_onPopupHidden:function(){},focus:function(){SFDom.setFocus(this.getReferenceId())},isPopupShown:function(){return this._popup.isShown()},show:function(){this._popup.show()},hide:function(){this._popup.hide()},updateClassName:function(){var b=juic.$(this.id);b&&(b.className=this._getClassName())},
updateContent:function(){var b=juic.$(this.id);if(b){b.className=this._getClassName();var a=juic.createRenderContext();this._renderButtonContents(a);a.renderInto(b)}}})})();function SFDropComponentContents(b){this.register();this._init(b)}
(function(){var b={contents:["string",juic.Component],className:["string",null]},c={};juic.extend(SFDropComponentContents,SFAbstractAdjustableHeight,{_init:function(d){d=new juic.Config(d,c,b);this._contents=d.contents;this._className=d.className;this._contents instanceof juic.Component&&this._contents.addEventListener("hide",this,"dispatchEvent")},cleanup:function(){this._contents instanceof juic.Component&&this._contents.cleanup();this._super()},renderHtml:function(b){b.push('\x3cdiv id\x3d"',this.id,
'" class\x3d"',this.getClassName(),'"\x3e',this._contents,"\x3c/div\x3e")},getClassName:function(){return this._className?this._className:"sfDropComponentContents"},setHeight:function(b){var a=juic.$(this.id);a&&(this._offsets||(this._offsets=SFDom.getOffsets(a)),b=Math.max(0,b-this._offsets),this._contents instanceof SFAbstractAdjustableHeight?this._contents.setHeight(b):(SFDom.updateStyle(a,{overflow:"auto",height:b+"px"}),this.dispatch("changeDimensions")))}})})();
function SFCalloutPopup(b){this._super(b)}
(function(){function b(a){this._panel=a;this._panel.addEventListener("action",this,"dispatchEvent");this._panel.addEventListener("changeDimensions",this,"dispatchEvent")}function c(b,h,c,e){b=b[h];if(null!=b&&(!e||"middle"!=b))b=isNaN(b)?null:Math.max(c,parseInt(b));return null==b?a[h]:b}function d(a){var b=g[a.direction],c={menu:{},origin:{},offset:{}};c.menu[b.directionType]=b.opposite;c.origin[b.directionType]=b.direction;c.menu[b.oppositeType]="middle"==a.pointerOffset?"middle":a.flipPointerOffset?
b.oppositeAnchor:b.anchor;c.origin[b.oppositeType]="middle"==a.originOffset?"middle":a.flipOriginOffset?b.oppositeAnchor:b.anchor;c.offset[b.directionType]=(b.flipped?1:-1)*a.margin;var l=0,d=a.flipPointerOffset?-1:1,n=a.flipOriginOffset?-1:1;"middle"!=a.pointerOffset&&(l-=d*(a.pointerOffset+e));"middle"!=a.originOffset&&(l+=n*a.originOffset);c.offset[b.oppositeType]=l;return c}var a={direction:"bottom",originOffset:"middle",flipOriginOffset:!1,pointerOffset:"middle",flipPointerOffset:!1,margin:0},
e=10;juic.extend(SFCalloutPopup,SFCalloutPanel,{_init:function(b){b=b?juic.set({},b):{};var h=b.originOptions;if(h){var e=h.direction;g[e]||(e=a.direction);var l="vertical"==g[e].directionType?30:50,h={direction:e,originOffset:c(h,"originOffset",0,!0),flipOriginOffset:!!h.flipOriginOffset,pointerOffset:c(h,"pointerOffset",l,!0),flipPointerOffset:!!h.flipPointerOffset,margin:c(h,"margin",0,!1)}}else h=juic.set({},a);b.originOptions=h;b.pointerOptions={direction:g[h.direction].opposite,offset:h.pointerOffset,
flipOffset:h.flipPointerOffset};this._super(b);this._originOptions=b.originOptions;this._originId=b.originId;this._closeOnClick=null==b.closeOnClick?!0:b.closeOnClick;this._closeOnMouseout=null==b.closeOnMouseout?!0:b.closeOnMouseout;this._hideLatency=null==b.hideLatency?0.5:b.hideLatency;this._role=b.role;this._refocusRef=b.refocusRef;this._showRelativeToViewport=b.showRelativeToViewport},show:function(a,h){var c=new juic.Config(h);"boolean"!=typeof c.showRelativeToViewport&&(c.showRelativeToViewport=
this._showRelativeToViewport);this._currentOriginId=a||this._originId;if(!this._popup){var e=d(this._originOptions);this._popup=new SFContextPopup(new b(this),juic.set({originId:this._originId,closeOnClick:this._closeOnClick,closeOnMouseout:this._closeOnMouseout,hideLatency:this._hideLatency,loopFocus:!0,closeOnEscape:!0,refocusRef:this._refocusRef},e));this._popup.addEventListener("clickedOutsidePopup",this,"dispatchEvent");this._popup.addEventListener("positionFixed",this,"_onPositionFixed")}this._setFocusOnSelf=
c.setFocusOnSelf;c.setFocusOnSelf=!1;this._popup.show(this._currentOriginId,c);SFBodyEventDispatcher.addResizeListener(this,"reposition")},_onPositionFixed:function(){this._setFocusOnSelf&&this.setFocus()},exclusiveShow:function(a,b){this.isShown()&&this._currentOriginId!==a&&this.hide();if(!this.isShown()||this.isShown()&&this._currentOriginId!==a)b&&(b.header&&(this._usesStandardHeader()?this.setTitle(b.header):this.setHeader(b.header)),b.title&&this.setTitle(b.title),b.content&&this.setContent(b.content)),
this.show(a,b)},hide:function(){this._popup&&this._popup.hide();this.dispatch("hide");this._currentOriginId=null;SFBodyEventDispatcher.removeResizeListener(null,this)},setFocus:function(a){this._popup&&this._popup.setFocus(a);this._super(a)},_handleClose:function(){this.hide.apply(this,arguments)},_isSectionRendered:function(a,b){switch(a){case "header":return!0}return this._super(a,b)},_renderContent:function(a,b){switch(b){case "header":this._renderStandardHeader(a);break;default:this._super.apply(this,
arguments)}},_usesStandardHeader:function(){return!0},reposition:function(){this._popup.reposition()},isShown:function(){return this._popup&&this._popup.isShown()},positionFixed:function(a){var b=this._originOptions,c=a.positionInfo.fixPoint,e=g[b.direction],q=d(b);this._pointerOptions={direction:c.menu[e.directionType]!=q.menu[e.directionType]?e.direction:e.opposite,offset:b.pointerOffset,flipOffset:c.menu[e.oppositeType]!=q.menu[e.oppositeType]?!b.flipPointerOffset:b.flipPointerOffset};c=g[this._pointerOptions.direction];
e=a[c.offsetNewDimension];0<e&&(b=a.positionInfo.overlay[c.offsetDimension],e=b-e,10>parseInt(SFDom.getStyle(juic.$(a.positionInfo.overlay.overlayId),c.offsetOverlayPosition))&&(e*=-1),this._pointerOptions.flipOffset&&(e*=-1),a=this._pointerOptions.offset,"middle"==a&&(a=juic.$(this.id),c=this._pointerOptions.flipOffset?c.offsetMarginEnd:c.offsetMarginStart,a=b/2-parseInt(SFDom.getStyle(a,c))),a+=e,this._pointerOptions.offset=a);this._updateStyles("pointerContainer");this._updateClassName("pointerContainer");
this._updateStyles("pointer");this._updateClassName("pointer")},setCloseOnClick:function(a){this._popup.setCloseOnClick(a)},getRole:function(){return this._role},cleanup:function(){this._popup&&(this._popup.cleanup(!1),delete this._popup);this._focusMarkers&&(this._focusMarkers[0].cleanup(),this._focusMarkers[1].cleanup());this._super()}});juic.extend(b,SFAbstractPositionable,{renderHtml:function(a){var b=this._panel.getRole();a.push('\x3cdiv id\x3d"',this._panel.getReferenceId(),'wrapper" ');b&&
a.push('role\x3d"',b,'" ');a.push('class\x3d"globalCallout calloutPopupWrapper"\x3e');this._panel.renderHtml(a);a.push("\x3c/div\x3e")},positionFixed:function(a){this._panel.positionFixed(a)}});var g={top:{flipped:!1,direction:"top",opposite:"bottom",directionType:"vertical",oppositeType:"horizontal",offsetMarginStart:"margin-left",offsetMarginEnd:"margin-right",offsetDimension:"width",offsetNewDimension:"newComponentWidth",offsetOverlayPosition:"left",anchor:"left",oppositeAnchor:"right"},bottom:{flipped:!0,
direction:"bottom",opposite:"top",directionType:"vertical",oppositeType:"horizontal",offsetMarginStart:"margin-left",offsetMarginEnd:"margin-right",offsetDimension:"width",offsetNewDimension:"newComponentWidth",offsetOverlayPosition:"left",anchor:"left",oppositeAnchor:"right"},left:{flipped:!1,direction:"left",opposite:"right",directionType:"horizontal",oppositeType:"vertical",offsetMarginStart:"margin-top",offsetMarginEnd:"margin-bottom",offsetDimension:"height",offsetNewDimension:"newComponentHeight",
offsetOverlayPosition:"top",anchor:"top",oppositeAnchor:"bottom"},right:{flipped:!0,direction:"right",opposite:"left",directionType:"horizontal",oppositeType:"vertical",offsetMarginStart:"margin-top",offsetMarginEnd:"margin-bottom",offsetDimension:"height",offsetNewDimension:"newComponentHeight",offsetOverlayPosition:"top",anchor:"top",oppositeAnchor:"bottom"}}})();function SFTriangle(b){this.register();this._init(b)}
(function(){var b={top:"top",bottom:"bottom",left:"left",right:"right"},c=[[0,3,2,1],[1,0,3,2],[2,1,0,3],[3,2,1,0]],d={top:2,bottom:0,left:1,right:3},a=["bottom","left","top","right"],e={size:20,direction:b.top,cssClass:"",inherit:void 0},g={color:["string",null],size:["number",null],direction:["string",null],cssClass:["string",null],inherit:["boolean",null]};juic.extend(SFTriangle,juic.Component,{_init:function(a){this._options=new juic.Config(a,e,g);this._originalDirection=this._options.direction},
renderHtml:function(a){this._renderTriangle(a)},pivot:function(a){var h=juic.$(this._getDomId());this._clearDirections(h);switch(this._getRotationDirection(a)){case b.top:Util.addClass(h,"directionTop");break;case b.bottom:Util.addClass(h,"directionBottom");break;case b.left:Util.addClass(h,"directionLeft");break;case b.right:Util.addClass(h,"directionRight")}this._options.direction=b[a]||this._options.direction},_getRotationDirection:function(b){var h=d[this.getDirection()];return a[c[d[b]][h]]},
_renderTriangle:function(a){this._options.cssClass+=" "+this._options.direction;a.push('\x3cspan class\x3d"globalArrowColor sfTriangle globalIconFont1Support',this._options.cssClass,'"',' id\x3d"triangle_',this.id,'"');a.push(' onclick\x3d"',this.fireCode("_click"),'" style\x3d"');this._options.inherit||a.push("border-width:",this._options.size,"px;");switch(this._options.direction){case b.top:a.push("border-top-width:0;");a.push("border-left-color:transparent;");a.push("border-right-color:transparent;");
this._options.color&&!this._options.inherit&&(a.push("border-bottom-color:"),a.push(this._options.color));a.push('"\x3e\x3cspan class\x3d"legacyFont1Icon up"\x3e\x26#xe1f0;\x3c/span\x3e');a.push("\x3c/span\x3e");break;case b.bottom:a.push("border-bottom-width:0;");a.push("border-left-color:transparent;");a.push("border-right-color:transparent;");this._options.color&&!this._options.inherit&&(a.push("border-top-color:"),a.push(this._options.color));a.push('"\x3e\x3cspan class\x3d"legacyFont1Icon down"\x3e\x26#xe1ef;\x3c/span\x3e');
a.push("\x3c/span\x3e");break;case b.left:a.push("border-left-width:0;");a.push("border-top-color:transparent;");a.push("border-bottom-color:transparent;");this._options.color&&!this._options.inherit&&(a.push("border-right-color:"),a.push(this._options.color));a.push('"\x3e\x3cspan class\x3d"legacyFont1Icon left"\x3e\x26#xe1ee;\x3c/span\x3e');a.push("\x3c/span\x3e");break;case b.right:a.push("border-right-width:0;");a.push("border-top-color:transparent;");a.push("border-bottom-color:transparent;");
this._options.color&&!this._options.inherit&&(a.push("border-left-color:"),a.push(this._options.color));a.push('"\x3e\x3cspan class\x3d"legacyFont1Icon right"\x3e\x26#xe1ed;\x3c/span\x3e');a.push("\x3c/span\x3e");break;default:a.push("border-bottom-width:0;"),a.push("border-left-color:transparent;"),a.push("border-right-color:transparent;"),this._options.color&&!this._options.inherit&&(a.push("border-top-color:"),a.push(this._options.color)),a.push('"\x3e\x3cspan class\x3d"legacyFont1Icon"\x3e\x26#xe1ef;\x3c/span\x3e'),
a.push("\x3c/span\x3e")}},_getDomId:function(){return"triangle_"+this.id},_click:function(){this.dispatch("triangleClickEvent")},getDirection:function(){return this._options.direction},_clearDirections:function(a){Util.removeClass(a,"directionTop");Util.removeClass(a,"directionBottom");Util.removeClass(a,"directionLeft");Util.removeClass(a,"directionRight");this._options.direction=this._originalDirection}})})();function SFDropMenuPopup(b,c){this.register();this._init(b,c)}
(function(){function b(){assert(!1,"SFAbstractMenuModel: Do not instantiate")}function c(a){this._menuItems=a}function d(a){this._model=a}var a=(Util.browserInfo.ie&&Util.quirksMode()?"":"globalRoundedCorners ")+"globalMenu",e=Util.browserInfo.css3Support,g={menu:{vertical:"top",horizontal:"left"},origin:{vertical:"top",horizontal:"right"}};juic.extend(SFDropMenuPopup,SFAbstractPositionable,{_init:function(a,b){b=b||{};this._subMenus={};this.setModel(a);this._css=b.css;this._fixPoint=b.fixPoint||
{};this._escapeHTML=b.escapeHTML;this._originId=b.originId;this._animate=null==b.animate?!0:b.animate;this._preventRedisplay=b.preventRedisplay;this._refocusId=b.refocusId},renderHtml:function(b){b.push('\x3cdiv id\x3d"',this.id,'" class\x3d"',this._getClassName(),'"\x3e\x3cdiv id\x3d"',this.id,'wrapper" class\x3d"',a,'"');this._minWidth&&b.push(' style\x3d"min-width:',this._minWidth,'px"');b.push("\x3e");this._renderContent(b);b.push("\x3c/div\x3e\x3c/div\x3e")},_getClassName:function(){return"sfDropMenu"+
(this._css?" "+this._css:"")},setMinWidth:function(a){this._minWidth=a;var b=juic.$(this.id+"wrapper");b&&(b.style.minWidth=a+"px")},_renderContent:function(a){a.push('\x3cul id\x3d"',this.id,'wrapperList" class\x3d"wrapperList" role\x3d"application"\x3e');if(this._menuItems)for(var b=0;b<this._menuItems.length;b++)this._renderItem(a,this._menuItems[b],b);else a.push('\x3cli class\x3d"',"sfLoadingContainer",'"\x3e\x3cspan\x3e\x26nbsp;\x3c/span\x3e\x3c/li\x3e');a.push("\x3c/ul\x3e")},_renderItem:function(a,
b,c){var e=!1,d=!1;if(b.header)a.push('\x3cli\x3e\x3ch4 id\x3d"',this.id,c,'" class\x3d"',"menuTitle",'"\x3e',this._checkEscape(b.header,b),"\x3c/h4\x3e\x3c/li\x3e");else if(b.separator)a.push('\x3cli\x3e\x3chr id\x3d"',this.id,c,'" class\x3d"',"separator",'" /\x3e\x3c/li\x3e');else{var g=this._checkEscape(b.label||b.name||b.description,b),k=["menuLink"];b.css&&k.push(b.css);b.subMenu&&k.push("itemWithMenu");(b.sapIcon||b.sfSuppIcon)&&k.push("hasIcon");0==c?k.push("first"):c==this._menuItems.length-
1&&k.push("last");a.push("\x3cli ");b.subMenu&&a.push(' aria-haspopup\x3d"true"');a.push(' aria-disabled\x3d"',b.disabled?"true":"false",'"');b.disabled?k.push("globalDisabledMenuItem"):k.push("globalMenuItem");a.push('\x3e\x3ca role\x3d"menuitem" id\x3d"',this.id,c,'" class\x3d"',k.join(" "),'" href\x3d"');!b.disabled&&(b.href||b.url)?(d=!0,a.push(b.href||b.url)):a.push("javascript:void(0)");!b.disabled&&b.target&&a.push('" target\x3d"',b.target);!b.disabled&&b.actionCommand?(a.push('" onclick\x3d"',
this.fireCode("_clickMenuItem",c),"return false"),e=!0):!b.disabled&&b.onclick?(a.push('" onclick\x3d"',this.fireCode("_clickMenuItem",c),b.onclick,";return false"),e=!0):!b.disabled&&!b.subMenu&&(a.push('" onclick\x3d"',this.fireCode("hide"),"return ",d),e=!0);if(b.altText||b.title)a.push('" title\x3d"',this._checkEscape(b.altText||b.title,b));!b.disabled&&b.subMenu&&(!b.actionCommand&&!d)&&(a.push('" onclick\x3d"',this.fireCode("_showSubMenu",c),"return false"),e=!0);!e&&!d&&a.push('" onclick\x3d"return false');
a.push('" aria-disabled\x3d"',b.disabled?"true":"false");b.disabled||a.push('" onmouseover\x3d"',this.fireCode("_onMenuMouseOver",c),'" onmouseout\x3d"',this.fireCode("_onMenuMouseOut",c));a.push('" onfocus\x3d"',this.fireCode("_onItemFocus",c),'"\x3e');b.sapIcon&&a.push('\x3cspan class\x3d"menuIcon sapIcon"\x3e',b.sapIcon,"\x3c/span\x3e");b.sfSuppIcon&&a.push('\x3cspan class\x3d"menuIcon sfSuppIcon"\x3e',b.sfSuppIcon,"\x3c/span\x3e");a.push(g);b.subMenu&&a.push('\x3cspan class\x3d"menuArrow"\x3e\x3c/span\x3e');
a.push("\x3c/a\x3e");a.push("\x3c/li\x3e")}},_checkEscape:function(a,b){return this._escapeHTML&&!1!==b.escapeHTML?juic.escapeHTML(a):a},show:function(a){this._menuItems||this._model.fetchMenuItems();this._originId=a||this._originId;this._popup||(this._popup=this._createPopup());this._popup.show(this._originId);SFAnimUtil.css3FadeInTransition(this._popup.id,100);this.focus();this._startKeyListener();var b=this,c=null;clearInterval(this._intervalId);this._intervalId=setInterval(function(){var a=SFDom.getXY(b._originId);
c=c||a;(a[0]!=c[0]||a[1]!=c[1])&&b.hide()},500)},_createPopup:function(){var a=new SFContextPopup(this,{visibleOverflow:!0,preventRedisplay:this._preventRedisplay,menu:this._fixPoint.menu,origin:this._fixPoint.origin,offset:this._fixPoint.offset});a.addEventListener("clickedOutsidePopup",this,"hide");a.addEventListener("focusOutside",this,"_onFocusOutside");a.addEventListener("preventBlur",this,"dispatchEvent");return a},isShown:function(){return this._popup&&this._popup.isShown()},hide:function(a){function b(){this._stopKeyListener();
this.dispatch("blur");clearInterval(this._intervalId);this.dispatch("hide");this._visibleSubMenu&&this._visibleSubMenu.hide();this._visibleSubMenu=null;this._refocusId&&SFDom.setFocus(this._refocusId,!0)}a instanceof juic.EventTarget.Event&&(a=!1);this._runningAnimation&&this._runningAnimation.stop();a&&e?this._animateMenu(this._currentFixPoint,!0,b):b.call(this)},cleanup:function(){this.setModel(null);this._popup&&this._popup.cleanup(!1);this._error&&this._error.cleanup();for(var a in this._subMenus)this._subMenus[a].cleanup();
this._super()},setFocusedItem:function(a){this._focusedItem=a},focus:function(a){var b=juic.$(this.id+"wrapper");b&&("undefined"===typeof a&&this._focusedItem?(a=juic.$(this.id+this._focusedItem),SFDom.setFocus(a)):(a=SFDom.findNextFocusableElement(a?b.lastChild:b.firstChild,b,!0,a),SFDom.setFocus(a,!0)))},positionFixed:function(a){var b=juic.$(this.id+"wrapper");if(b){var c=juic.$(this.id+"wrapperList");this._fixedCount=this._fixedCount||0;if(3>++this._fixedCount){var e=a.newComponentHeight,d=a.newComponentWidth;
if(null!=e||null!=d)e=(e-15||c.offsetHeight)-SFDom.getOffsets(b,"y"),d=d-15||c.offsetWidth,b.style.width=d+17+"px",c.style.height=Math.max(e,100)+"px",SFDom.addClass(b,"sfDropMenuScrollable"),this.dispatch("changeDimensions")}this._animateMenu(a.positionInfo.fixPoint,!1,this.focus);if(null==this._fixedTimeout){var g=this;this._fixedTimeout=setTimeout(function(){g._fixedCount=0;g._fixedTimeout=null},50)}}},setModel:function(a){this.setFocusedItem(null);this._model&&(this._model.removeEventListener("menuItemsAvailable",
this,"_onMenuItemsAvailable"),this._model.removeEventListener("menuItemsError",this,"_onMenuItemsError"));this._menuItems=null;Array.isArray(a)?this._model=new c(a):a instanceof b?this._model=a:a instanceof SFDefaultListModel&&(this._model=new d(a));this._model&&(this._model.addEventListener("menuItemsAvailable",this,"_onMenuItemsAvailable"),this._model.addEventListener("menuItemsError",this,"_onMenuItemsError"))},getMenuId:function(){return this.id},getItemId:function(a){return this.id+a},_animateMenu:function(a,
b,c){var d=juic.$(this.id+"wrapper");if(d&&e&&this._animate){this._currentFixPoint=a;var g=document.createElement("div"),n=a.origin.horizontal!=a.menu.horizontal,k={},p=d.offsetWidth,r=d.offsetHeight,m=null;g.style.width=p+"px";g.style.height=r+"px";g.style.position="relative";g.style.overflow="hidden";d.parentNode.replaceChild(g,d);g.appendChild(d);d.style.position="absolute";n?(m="left"==a.menu.horizontal?"left":"right",b?(d.style[m]="0",k[m]=-p):(d.style[m]="right"==m?-p+"px":-Math.min(100,p)+
"px",k[m]=0)):(m="top"==a.menu.vertical?"top":"bottom",b?(d.style[m]="0",k[m]=-r):(d.style[m]=-r+"px",k[m]=0));this._runningAnimation=SFAnimUtil.animate(d,k,{duration:0.2,context:this,complete:function(){this._runningAnimation=null;Util.browserInfo.css3Support&&(d.style.position="",d.style[m]="",g.parentNode.replaceChild(d,g));c&&c.call(this)}})}else c&&c.call(this)},_startKeyListener:function(){SFDOMEvent.addListener(window.document,"keydown",this._onWindowKeyDown,this);SFDOMEvent.addListener(window.document,
"keyup",this._onWindowKeyUp,this)},_stopKeyListener:function(){SFDOMEvent.removeListener(window.document,"keydown",this._onWindowKeyDown,this);SFDOMEvent.removeListener(window.document,"keyup",this._onWindowKeyUp,this)},_focusNext:function(a){if(null!=this._focusedItem){var b=juic.$(this.id+"wrapper");if(b){var c=juic.$(this.id+this._focusedItem);(b=SFDom.findNextFocusableElement(a?c.parentNode.previousSibling:c.parentNode.nextSibling,b,!0,a))&&0==b.id.indexOf(this.id)?b.focus():this.focus(a)}}else this.focus(a);
return!1},_onPreventBlur:function(a){this.dispatch("preventBlur");this._popup&&this._popup.preventClose()},_onWindowKeyDown:function(a){var b=SFDOMEvent.getKeyName(a||window.event);if(a.shiftKey)SFDOMEvent.preventDefault(a);else switch(b){case "TAB":case "ARROWDOWN":case "ARROWUP":this._focusNext("ARROWUP"==b);SFDOMEvent.preventDefault(a);break;case "ARROWLEFT":case "ESCAPE":this.hide(!0);break;case "ARROWRIGHT":null!=this._focusedItem&&this._menuItems[this._focusedItem].subMenu&&this._showSubMenu(this._focusedItem)}},
_onWindowKeyUp:function(a){var b=SFDOMEvent.getKeyName(a||window.event);a.shiftKey&&"TAB"==b&&(this._focusNext(!0),SFDOMEvent.preventDefault(a))},_onItemFocus:function(a){this._focusedItem=a},_onFocusOutside:function(a){this.focus(a.start)},_onMenuItemsAvailable:function(a){this._menuItems=a.menuItems;if(a=juic.$(this.id+"wrapper")){var b=createRenderContext();this._renderContent(b);a.innerHTML=b.join("");this.dispatch("changeDimensions")}},_onMenuItemsError:function(a){this._error=new SFSysMsg("error",
a.message);this._error.render(this.id)},_onMenuMouseOver:function(a,b){if(Util.isMouseLeaveOrEnter(b,juic.$(this.id+a))){this._onMenuMouseOut();var c=this;this._timeout=setTimeout(function(){c._showSubMenu(a)},250);SFDOMEvent.getTarget(b).focus()}},_onMenuMouseOut:function(a,b){(!b||Util.isMouseLeaveOrEnter(b,juic.$(this.id+a)))&&null!=this._timeout&&clearTimeout(this._timeout)},_onSubMenuAction:function(a){this.hide();this.dispatchEvent(a)},_onSubMenuBlur:function(a){this._visibleSubMenu=null;this._startKeyListener();
null!=this._focusedItem?(a=juic.$(this.id+this._focusedItem))&&a.focus():this.focus(!1)},_showSubMenu:function(a){if(this._menuItems[a].subMenu){var b=this._subMenus[a];if(null==b||this._visibleSubMenu!==b){this._hideSubMenu();b||(b=new SFDropMenuPopup(this._menuItems[a].subMenu,{originId:this.id+a,fixPoint:g}),b.addEventListener("blur",this,"_onSubMenuBlur"),b.addEventListener("action",this,"_onSubMenuAction"),b.addEventListener("preventBlur",this,"_onPreventBlur"),b.addEventListener("hide",this,
"_onHideSubMenu"),this._subMenus[a]=b);this._stopKeyListener();b.show();var c=this;setTimeout(function(){c._focusedItem=a},0);this._visibleSubMenu=b;juic.$(this.id+a).className+=" globalMenuItemFocus"}}else this._hideSubMenu()},_hideSubMenu:function(){this._visibleSubMenu&&this._visibleSubMenu.hide()},_onHideSubMenu:function(a){if((a=a.target._originId)&&juic.$(a)){for(var b=" "+juic.$(a).className+" ";-1<b.indexOf(" globalMenuItemFocus ");)b=b.replace(" globalMenuItemFocus "," ");juic.$(a).className=
b.trim()}},_clickMenuItem:function(a){this.hide();var b=this._menuItems[a];this.dispatch("action",{actionCommand:b.actionCommand,menuItem:b,itemIndex:a})},setRefocusId:function(a){this._refocusId=a},getRefocusId:function(){return this._refocusId}});juic.extend(b,juic.EventTarget,{fetchMenuItems:function(){assert(!1,"SFAbstractMenuModel: must implement fetchMenuItems")}});window.SFAbstractMenuModel=b;juic.extend(c,b,{fetchMenuItems:function(){this.dispatch("menuItemsAvailable",{menuItems:this._menuItems})}});
juic.extend(d,b,{fetchMenuItems:function(){for(var a=[],b=0;b<this._model.size();b++)a.push(this._model.get(b));this.dispatch("menuItemsAvailable",{menuItems:a})}})})();function SFDropMenu(b,c){this.register();this._init(b,c)}SFDropMenu.forceExplicitLabelWidth=function(){return Util.quirksMode()||8==Util.ieVersion()};
juic.extend(SFDropMenu,juic.Component,{_init:function(b,c){c=c||{};this._css=c.css;this._hoverCss=c.hoverCss;this._activeCss=c.activeCss;this._content=c.content;this._escapeHTML=c.escapeHTML;this._tag=(this._button=c.button)?"button":"a";this._title=c.title;this._labelWidth=c.labelWidth;this._useTouchEnd=c.useTouchEnd;this._image=c.image;c.showTriangle&&(this._triangleIcon=new SFTriangle({direction:"bottom",inherit:!0}),this.triangleIconId=this._triangleIcon._getDomId());this._menu=new SFDropMenuPopup(b,
{animate:c.animate,preventRedisplay:c.preventRedisplay,fixPoint:c.fixPoint,escapeHTML:c.escapeHTML,css:c.popupCss});this._menu.addEventListener("blur",this,"focus");this._menu.addEventListener("hide",this,"_onPopupHidden");this._menu.addEventListener("action",this,"dispatchEvent");this._menu.addEventListener("preventBlur",this,"dispatchEvent");var d,a=c.activeButton?"globalPrimaryButton":"globalSecondaryButton buttonDefault";switch(c.buttonType){case "command":d="globalRoundedCornersXSmall "+a+" sfDropMenuCommandButton"}this._buttonStyles=
d||""},renderHtml:function(b){b.push("\x3c",this._tag);"a"==this._tag?b.push(' href\x3d"javascript:void(0)"'):b.push(' type\x3d"button"');this._hoverCss&&b.push(' onmouseover\x3d"',this.fireCode("_onMouseOver"),'" onmouseout\x3d"',this.fireCode("_onMouseOut"),'"');b.push(' aria-haspopup\x3d"true" aria-owns\x3d"',this._menu.id,'" id\x3d"',this.id,'" role\x3d"button"');this._useTouchEnd&&(Util.browserInfo.ios||Util.browserInfo.android)?b.push(' ontouchend\x3d"',this.fireCode("_activateMenu"),'"'):b.push(' onclick\x3d"',
this.fireCode("_activateMenu"),'return false;"');b.push(' class\x3d"',this._css," ",this._buttonStyles,'"');this._title&&(b.push(' title\x3d"',this._title,'"'),this._ariaLabel?b.push(' aria-label\x3d"',this._ariaLabel,'"'):b.push(' aria-label\x3d" "'));b.push("\x3e");b.push(this._image);this._iconFont&&b.push('\x3cspan class\x3d"legacyFont1Icon"\x3e',this._iconFont,"\x3c/span\x3e");b.push('\x3cspan id\x3d"',this.id,'label" class\x3d"dropDownButtonText"');this._labelWidth&&SFDropMenu.forceExplicitLabelWidth()?
b.push(' style\x3d"width:',this._labelWidth,'px"'):this._labelWidth&&b.push(' style\x3d"max-width:"',this._labelWidth,'px"');b.push("\x3e");this._renderContent(b);b.push("\x3c/span\x3e");this._triangleIcon&&b.push(this._triangleIcon);b.push("\x3c/",this._tag,"\x3e")},_renderContent:function(b){null!=this._content&&("string"==typeof this._content&&this._escapeHTML?b.push(juic.escapeHTML(this._content)):b.push(this._content))},addDropDownIconFont:function(b){this._iconFont=b},setModel:function(b){this._menu.setModel(b)},
setModel:function(b){this._menu.setModel(b)},updateMinWidth:function(){var b=juic.$(this.id);b&&this._menu.setMinWidth(b.offsetWidth)},setContent:function(b){this._content=b;if(b=juic.$(this.id+"label")){var c=juic.createRenderContext();this._renderContent(c);b.innerHTML=c.join("")}},setTitle:function(b){this._title=b;var c=juic.$(this.id);c&&(c.title=b)},setAriaLabel:function(b){this._ariaLabel=b||" ";var c=juic.$(this.id);c&&(c.ariaLabel=b)},setFocusedItem:function(b){this._menu.setFocusedItem(b)},
focus:function(){var b=juic.$(this.id);if(b)try{b.focus()}catch(c){}},blur:function(){var b=juic.$(this.id);b&&b.blur()},setShowDisabled:function(b){this._showDisabled=b},_activateMenu:function(){this._showDisabled||(this._menu.isShown()?this.hide():this.show())},show:function(){this._menu.show(this.id);this._activeCss&&(this._menu.isShown()?SFDom.addClass(this.id,this._activeCss):(this.hide(),SFDom.setFocus(this.id,!0)))},hide:function(){this._menu.hide()},getOffsetWidth:function(){var b=juic.$(this.id);
return b?b.offsetWidth:0},setLabelWidth:function(b){var c=juic.$(this.id+"label");c&&(SFDropMenu.forceExplicitLabelWidth()?c.style.width=b+"px":c.style.maxWidth=b+"px")},isPopupShown:function(){return this._menu&&this._menu.isShown()},getPopupMenu:function(){return this._menu},_onPopupHidden:function(){this._activeCss&&(SFDom.removeClass(this.id,this._activeCss),SFDom.removeClass(this.id,this._hoverCss))},_onMouseOver:function(b){Util.isMouseLeaveOrEnter(b,juic.$(this.id))&&SFDom.addClass(this.id,
this._hoverCss)},_onMouseOut:function(b){Util.isMouseLeaveOrEnter(b,juic.$(this.id))&&SFDom.removeClass(this.id,this._hoverCss)},cleanup:function(){this._triangleIcon&&this._triangleIcon.cleanup();this._menu.cleanup();this._super()}});function SFMenuDropDown(b,c){this.register();this._init(b,c)}
(function(){function b(a){var b=[];a.css&&b.push(a.css);!1==a.isModule&&b.push(d);return{onclick:a.onclick,actionCommand:a.actionCommand||null,value:a.value||"",label:a.label,url:a.url,title:a.title,target:a.target,css:b.join(" ")}}function c(a){this._model=a}var d="nonmodule";juic.extend(SFMenuDropDown,juic.Component,{_init:function(a,b){b=b||{};assert(a,"[SFMenuDropDown] You need to send in a valid model of menu drop down objects!");this._model=a;this._isLegacy=!!b.isLegacy;this._isMultiLine=!!b.isMultiLine;
this._hasOpacity=!!b.hasOpacity;this._menuTitleFormat=b.menuTitleFormat||MSGS.COMMON_MENU_ALT;this._menuAriaLabel=b.menuAriaLabel;this._updateLabelOnSelect=b.updateLabelOnSelect;var d=[],f=b.cssClassesCore||"globalPlacematNavigationText",h=b.cssClassesAux||"";f&&d.push(f);h&&d.push(h);d=d.join(" ");f=!this._model?null:Array.isArray(this._model)?this._model:new c(this._model);this._menu=new SFDropMenu(f,{popupCss:"menuDefault"+(b.popupCss?" "+b.popupCss:""),css:d,hoverCss:this._hasOpacity?"globalModulePickerHover":
null,activeCss:this._hasOpacity?"globalModulePickerActive":null,button:this._isLegacy?!0:!1,content:this.buttonLabel,title:this.buttonTitle,showTriangle:!1!==b.showTriangle,fixPoint:b.fixPoint,animate:null==b.animate?!1:b.animate,preventRedisplay:null==b.preventRedisplay?!0:b.preventRedisplay,image:b.image});this._menu.triangleIconId&&(this.triangleID=this._menu.triangleIconId);this._menu.addEventListener("action",this,"_handleAction");this._menu.addEventListener("preventBlur",this,"dispatchEvent");
this._updateButtonLabel()},renderHtml:function(a){this._isMultiLine&&a.push('\x3cdiv class\x3d"multiLineLabel" id\x3d"',this.registerAutomationName(this.id+"_multiLineLabel","DropDown-"+this.getButtonText()),'"\x3e');a.push(this._menu);this._isMultiLine&&a.push("\x3c/div\x3e");this._hasOpacity&&a.addAfterRenderListener(this,"_onLoad")},addDropDownIconFont:function(a){this._menu.addDropDownIconFont(a)},cleanup:function(){this._menu.cleanup();this._super()},getButtonText:function(){return this.buttonLabel},
updateButtonText:function(a,b){this.buttonLabel=a;this.buttonTitle=b||a;this._menu.setContent(this.buttonLabel);this._menu.setTitle(this._updateTitleText(this.buttonTitle));this._menu.setAriaLabel(this._menuAriaLabel);this._menu.hide()},blurButton:function(){this._menu.blur()},getOffsetWidth:function(){return this._menu.getOffsetWidth()},getComputedMargins:function(){var a=juic.$(this.id+"_multiLineLabel");return a?SFDom.getMargin(a,"x"):0},adjustTextWidth:function(a){if(this.triangleID){var b=juic.$(this.triangleID);
a-=SFDom.getComputedWidth(b)}b=juic.$(this._menu.id);a-=SFDom.getComputedHorizPadding(b);this._menu.setLabelWidth(a)},setFocusedItem:function(a){this._menu.setFocusedItem(a)},focus:function(){this._menu.focus()},isPopupShown:function(){return this._menu&&this._menu.isPopupShown()},getPopupMenu:function(){return this._menu.getPopupMenu()},setModel:function(a){this._model=a;this._menu&&(a=!a?null:Array.isArray(a)?a:new c(a),this._menu.setModel(a))},show:function(){return this._menu.show()},hide:function(){return this._menu.hide()},
_updateButtonLabel:function(a){this._model instanceof SFDefaultSingleSelectModel&&(a=this._model.getSelectedIndex(),a=this._model.get(a),this.buttonLabel=a.label,this.buttonTitle=a.title,this._menu.setContent(this.buttonLabel),this._menu.setTitle(this._updateTitleText(this.buttonTitle)),this._menu.setAriaLabel(this._menuAriaLabel))},_updateTitleText:function(a){return sfMessageFormat.format(this._menuTitleFormat,a)},_onLoad:function(){this._menu.updateMinWidth()},_handleAction:function(a){this._updateLabelOnSelect&&
this._model instanceof SFDefaultSingleSelectModel&&(this._model.setSelectedIndex(a.itemIndex),this._updateButtonLabel());this.dispatchEvent(a)}});juic.extend(c,SFAbstractMenuModel,{fetchMenuItems:function(){for(var a=this._model.size(),c=[],d=0;d<a;d++)c.push(b(this._model.get(d)));this.dispatch("menuItemsAvailable",{menuItems:c})}})})();function SFDialogBox(b){this.register();this._init.apply(this,arguments)}
(function(){var b="title content buttons width innerHeight scrollable useNameAnchor ariaLabel".split(" "),c={title:void 0,buttons:void 0,content:void 0,width:300,height:"auto",innerHeight:void 0,scrollable:!1,useNameAnchor:!1,closeDialogOnEsc:!1,showCloseIcon:!0,contentHasForm:!1,cancelActionCommand:void 0,cancelActionData:void 0,preventClose:!1,overlayOpacity:void 0,ownChildren:!0,ariaRole:"dialog",ariaLabel:void 0},d={title:["string",juic.Component,null],buttons:[juic.Config.arrayType("*"),"string",
null],content:[juic.Component,"string",null],width:"number",height:["number","auto"],innerHeight:["number","auto","",null],cancelActionCommand:["string",null],overlayOpacity:["number",null],ariaRole:"string",ariaLabel:["string",null]};juic.extend(SFDialogBox,SFRevolutionPanel,{_init:function(a){a=juic.Config.convertArguments(arguments,b,c,d);a.baseButtonWrapperClass="sfDialogBoxButtonWrapper";a.type="sfDialogBox";a.ignoreAccessibility=!0;if(this._responsive=a.responsive){var e=SFDom.getViewportWidth(),
g=a.width,f=a.height;this._originalWidth=g;this._originalHeight=f;SFBodyEventDispatcher.addResizeListener(this,"_setWidthAndHeight");500>=e&&(g=e,f=SFDom.getViewportHeight(),a.width=g,a.height=f)}this._super(a);this._responsive||(this._innerHeight=a.innerHeight?a.innerHeight:void 0);this._contentHasForm=a.contentHasForm;this._preventClose=a.preventClose;this._overlayOpacity=a.overlayOpacity;this._ariaRole=this._getAriaRole(a.ariaRole);this._ariaLabel=a.ariaLabel;this.dialogPanel=this;this.setContent(this._content);
this._focusLoop=new SFFocusLoop(this.id+"_dialogBox");this._focusMarkers=this._focusLoop.getMarkers()},_setWidthAndHeight:function(a){a=SFDom.getViewportWidth();500>=a?(this.setWidth(a),this.setHeight(SFDom.getViewportHeight())):(this.setWidth(this._originalWidth),this.setHeight(this._originalHeight))},_renderSection:function(a,b,c){if(this._isSectionRendered(b,c)){var d=this._getSectionClassName(b);a.push('\x3cdiv id\x3d"',this.id,b,'"');d&&a.push(' class\x3d"',d,'"');SFDom.renderStyle(a,this._getStyle(b));
a.push("\x3e");this._renderContent(a,b,c);a.push("\x3c/div\x3e")}},renderHtml:function(a){a.push(this._focusMarkers[0]);a.push('\x3cdiv id\x3d"',this.id,'_dialogBox"\x3e');a.push('\x3cdiv id\x3d"',this.id,'_dialogContent"\x3e');a.push('\x3cdiv tabindex\x3d"0" role\x3d"',this._ariaRole,'" id\x3d"',this.id,'wrapper" ');this._ariaLabel?a.push('aria-label\x3d"',this._ariaLabel,'"'):a.push('aria-labelledby\x3d"',this.id,'_panelTitle"');a.push(' class\x3d"dialogBoxWrapper');this.isScrollable()&&a.push(" scrollableDialog");
a.push('"\x3e');this._super(a);a.push("\x3c/div\x3e");a.push("\x3c/div\x3e");a.push("\x3c/div\x3e")},cleanup:function(){delete this.dialogPanel;this.isRegistered()&&(this._focusMarkers[0].cleanup(),this._focusMarkers[1].cleanup(),this._super())},showDialog:function(a,b){this.isDialogVisible()||(this._modal=a,this._refocusRef=b,SFOverlayMgr.addEventListener("overlayRendered",this,"_onDialogRendered"),"undefined"==typeof a&&(a=!0),SFOverlayMgr.showOverlay(this,a,null,null,this._getOverlayOptions()),
this._closeDialogOnEsc&&SFOverlayMgr.addEventListener("escKeyPressed",this,"_cancel"))},close:function(){this.isDialogVisible()&&(this._preventClose?this.dispatch("action",{actionCommand:"hideRequest"}):this._hideDialog())},show:function(a){this._dialogHidden=!a;this._updateStyles()},renderContent:function(a){a.push(this._content)},handleButton:function(a){switch(a.actionCommand){case "hide":var b=this;setTimeout(function(){b.close()},0)}this._super(a)},setContent:function(a){this._content instanceof
juic.Component&&this._content.removeEventListener("changeDimensions",this);a instanceof juic.Component&&a.addEventListener("changeDimensions",this,"_handleDialogResized");this._super(a)},isDialogVisible:function(){return!this._dialogHidden&&!!juic.$(this.id)},isShown:function(){return this.isDialogVisible()},setCloseDialogOnEsc:function(a){!!this._closeDialogOnEsc!=!!a&&(this._closeDialogOnEsc=!!a,a&&this.isDialogVisible()&&SFOverlayMgr.addEventListener("escKeyPressed",this,"_cancel"))},setPreventCloseState:function(a){this._preventClose=
a},getPreventCloseState:function(){return this._preventClose},setScrollable:function(a){this._super(a);var b=juic.$(this.id+"wrapper");if(b)SFDom[a?"addClass":"removeClass"](b,"scrollableDialog")},setCancelAction:function(a,b){"object"==typeof a&&(a=a.actionCommand,b=a.data);this._cancelActionData=a?{actionCommand:a,data:b}:null},getCancelAction:function(){return this._cancelActionData},setTitle:function(a){this._super(a);this._setSectionContent("header",null)},setInnerHeight:function(a){this._innerHeight=
a;this._updateStyles("content");this._handleDialogResized()},getInnerHeight:function(){return this._innerHeight||this._getInnerHeight()},setHeader:function(){throw Error("SFDialogBox: setHeader is disabled, use setTitle instead.");},getHeader:function(){throw Error("SFDialogBox: getHeader is disabled, use setTitle instead.");},setAriaRole:function(a){this._ariaRole=this._getAriaRole(a);(a=juic.$(this.id+"wrapper"))&&a.setAttribute(this._ariaRole)},_getAriaRole:function(a){return"dialog"===a?"dialog":
"alertdialog"},_renderContentBody:function(a){this._contentHasForm?(a.push('\x3cform id\x3d"',this.id,'form" onsubmit\x3d"',this.fireCode("_onFormSubmit"),'return false"\x3e'),this.renderContent(a),a.push('\x3cinput type\x3d"image" src\x3d"',IMAGES["/ui/juic/img/_.gif"],'" width\x3d"1" height"1" tabindex\x3d"-1" alt\x3d"" /\x3e\x3c/form\x3e')):this.renderContent(a)},_getInnerHeight:function(){return null!=this._innerHeight?this._innerHeight:this._super()},_getOverlayOptions:function(){return{dispatchEscKeyPress:this._closeDialogOnEsc,
opacity:this._overlayOpacity}},_renderContent:function(a,b){switch(b){case "header":this._renderStandardHeader(a);break;case "content":this._renderContentBody(a);break;case "endMarker":a.push(this._focusMarkers[1]);break;case "closeIcon":this._showCloseIcon&&a.push('\x3cbutton id\x3d"',this.id,'closeIcon" class\x3d"closeDialog globalPortletCloseIcon globalIconFont1Support" title\x3d"',MSGS.COMMON_Close,'"  onclick\x3d"',this.fireCode("_handleClose"),'return false;" style\x3d"display:',this._showCloseIcon?
"block":"none",'"\x3e\x3cspan class\x3d"legacyFont1Icon"\x3e\x3c/span\x3e\x3c/button\x3e');break;default:this._super.apply(this,arguments)}},_usesStandardHeader:function(){return!0},_usesStandardHeader:function(){return!0},_getStyle:function(a){var b=this._super(a);null==a&&(b.display=this._dialogHidden?"none":"block");return b},_isSectionRendered:function(a,b){switch(a){case "header":case "startMarker":case "closeIcon":case "endMarker":return!0}return this._super(a,b)},_renderStandardHeaderContent:function(a){this._renderTitle(a)},
_getSectionOrder:function(){return[].concat(this._super()).concat(["closeIcon","endMarker"])},_cancel:function(a){this._cancelActionData?this.dispatch("action",this._cancelActionData):this.close()},_hideDialog:function(){this._closeDialogOnEsc&&SFOverlayMgr.removeEventListener("escKeyPressed",this);this.dispatch("action",{actionCommand:"hide"});this.dispatch("hide");this._handleRefocus()},_handleClose:function(){this.close.apply(this,arguments)},_onFormSubmit:function(){this.dispatch("action",{actionCommand:"submitForm"})},
_updateStyles:function(a){this._super(a);a||this._handleDialogResized()},_updateClassName:function(a){this._super(a);this._handleDialogResized()},_setSectionContent:function(){this._super.apply(this,arguments);this._handleDialogResized()},_handleDialogResized:function(){this.isDialogVisible()&&(this._modal?SFOverlayMgr.centerComponent(this.id):this.dispatch("changeDimensions"))},_onDialogRendered:function(a){SFOverlayMgr.removeEventListener("overlayRendered",this);this.adjustDOM();this.setFocus()},
setFocus:function(a){this._focusLoop.setFocus(a);this._super(a)},getDialogTitleText:function(){return this.getTitle()},setDialogTitle:function(a){this.setTitle(a)},setOuterHeight:function(a){this.setHeight(a)},getOuterHeight:function(){return this.getHeight()},setContentHeight:function(a){this.setInnerHeight(a);this._handleDialogResized()},setNewButtons:function(a){this.getButtonLayout().setModel(a)},disableButtons:function(){this.getButtonLayout().setButtonsEnabled(!1)},enableButtons:function(){this.getButtonLayout().setButtonsEnabled(!0)},
disableButton:function(a){this.getButtonLayout().setButtonEnabled(a,!1)},enableButton:function(a){this.getButtonLayout().setButtonEnabled(a,!0)},isButtonEnabled:function(a){return(a=this.getButtonModel().get(a))&&a.enabled},setButtonLabel:function(a,b){this.getButtonLayout().setButtonLabel(a,b)},setButtonActionCommand:function(a,b){this.getButtonLayout().setButtonActionCommand(a,b)},setButtonVisible:function(a,b){this.getButtonLayout().setButtonVisible(a,b)},setInnerWidth:function(a){this.setWidth(a)},
getInnerWidth:function(){return this.getWidth()}})})();function SFDialogBoxCloseButton(b,c,d,a,e,g){this._super(b,c,d,a);this._superId=e;this._display=g}
juic.extend(SFDialogBoxCloseButton,SFSimpleLink,{_renderLinkContent:function(b){b.push('\x3cbutton id\x3d"',this._superId,'dialogCloseIcon" type\x3d"button" class\x3d"closeDialog globalPortletCloseIcon globalIconFont1Support" title\x3d"',MSGS.COMMON_Close,'"');b.push(' onclick\x3d"',this.fireCode("_click"),';return false;"','onmouseover\x3d"',this.fireCode("_mouseover"),';return false;" ','onmouseout\x3d"',this.fireCode("_mouseout"),';return false;" ');b.push('style\x3d"',this._display,'"');b.push('\x3e\x3cspan class\x3d"legacyFont1Icon"\x3e\x3c/span\x3e\x3c/button\x3e')}});
(function(){function b(a,b,c){this._message=a;this._value=null==b?"":b;this._required=c;this.register()}function c(a,b){a=a?set({},a):{};return set(a,b)}function d(a,b,c){c=c||{};var d=c.context||window;a="function"==typeof c[a]?c[a]:c.callback;"function"==typeof a&&(Array.isArray(b)||(b=null==b?[]:[b]),a.apply(d,b))}function a(b){if(Array.isArray(b)){for(var c=[],d=0;d<b.length;d++)c.push(e(b[d]));return c}return"string"==typeof b&&f[b]?a(f[b]):[e(b)]}function e(a){a=a||SFMessageBox.OK;switch(typeof a){case "string":return g[a]?
set({},g[a]):{label:a,active:!1,enabled:!0,eventName:a};case "object":return{label:a.label,active:!!a.active,enabled:null==a.enabled?!0:a.enabled,eventName:a.actionCommand||a.eventName||a.command};default:assert(!1,"[SFMessageBox] Invalid button: "+a)}}window.SFMessageBox={OK:"ok",SAVE:"save",CANCEL:"cancel",OK_CANCEL:"okCancel",SAVE_CANCEL:"saveCancel",CLOSE:"close"};var g={};g[SFMessageBox.OK]={label:MSGS.COMMON_Ok,active:!0,enabled:!0,eventName:SFMessageBox.OK};g[SFMessageBox.SAVE]={label:MSGS.COMMON_Save,
active:!0,enabled:!0,eventName:SFMessageBox.SAVE};g[SFMessageBox.CANCEL]={label:MSGS.COMMON_Cancel,active:!1,enabled:!0,eventName:"cancel"};var f={};f[SFMessageBox.OK]=[SFMessageBox.OK];f[SFMessageBox.OK_CANCEL]=[SFMessageBox.CANCEL,SFMessageBox.OK];f[SFMessageBox.SAVE_CANCEL]=[SFMessageBox.CANCEL,SFMessageBox.SAVE];set(SFMessageBox,{alert:function(a,b){return this.show(c(b,{buttons:SFMessageBox.OK,message:a,callback:function(a){d(a,null,b)}}))},confirm:function(a,b){return this.show(c(b,{buttons:"okCancel",
message:a,callback:function(a){d(a,a==SFMessageBox.OK,b)}}))},prompt:function(h,e,f){var g=f&&f.required,n=new b(h,e,g);e=a(g?SFMessageBox.OK:"okCancel");g&&(e[0].enabled=!1);h=this.show(c(f,{buttons:e,message:n,showClose:g?!1:f.showClose,callback:function(a){var b=n.getValue();if(a==SFMessageBox.CANCEL||a==SFMessageBox.CLOSE)b=null;d(a,b,f)}}));f.required&&n.addEventListener("change",{handleEvent:function(a){h.setButtonEnabled(SFMessageBox.OK,!!n.getValue())}});return h},show:function(b){b=b||{};
var c=!0,e=a(b.buttons),f=b.content||b.message,g=null;"string"==typeof f&&b.messageType&&(g=new SFSysMsg(b.messageType,f,b.detail,!1));var k=new SFDialogBox({title:b.title||document.title,content:g||f,buttons:e,width:b.width,innerHeight:b.height,scrollable:b.scrollable,escapeHTML:b.escapeHTML,useNameAnchor:b.useNameAnchor}),p=set(new juic.EventTarget,{setButtonEnabled:function(a,b){for(var c=0;c<e.length;c++)if(e[c].eventName==a)k[b?"enableButton":"disableButton"](c)},close:function(){try{c&&d(SFMessageBox.CLOSE,
SFMessageBox.CLOSE,b)}finally{k.close(),k.cleanup()}}});k.addEventListener("action",{handleEvent:function(a){a=a.actionCommand;switch(a){case "hide":if(c)try{d(SFMessageBox.CLOSE,SFMessageBox.CLOSE,b)}finally{setTimeout(function(){k.cleanup()},1)}break;default:c=!1;try{d(a,a,b)}finally{p.close()}}p.dispatch("action",{actionCommand:a})}});k.showDialog(b.isModal,b.targetId);!1===b.showClose&&k.setShowCloseIcon(!1);return p}});juic.extend(b,juic.Component,{renderHtml:function(a){a.push('\x3cdiv class\x3d"promptContent"\x3e\x3cp\x3e',
this._message,'\x3c/p\x3e\x3cp\x3e\x3cinput id\x3d"',this.id,'value" type\x3d"text" value\x3d"',juic.escapeHTML(this._value),'" style\x3d"width:100%"');this._required&&a.push(' onkeyup\x3d"',this.fireCode("_onChange"),'"');a.push("\x3e\x3c/p\x3e\x3c/div\x3e")},_onChange:function(){this._value=juic.$(this.id+"value").value;this.dispatch("change")},getValue:function(){return this._value}})})();