function SFDefaultListModel(a){this._items=[];"undefined"!=typeof a&&this.setItems(a)}
SFDefaultListModel.prototype=function(){return juic.set(new juic.EventTarget,{add:function(a){this._items.push(a);a=0<this._items.length?this.size()-1:0;this.dispatch("intervalAdded",{index0:a,index1:a});this.intervalAdded(a,a)},getlength:function(){return this._items.length},insertItemAt:function(a,b){a==this.size()?this.add(b):(juic.assert(this._items[a],"ERROR: Invalid index passed to insertItemAt. Index is out of range."),this._items.splice(a,0,b),this.dispatch("intervalAdded",{index0:a,index1:a}),
this.intervalAdded(a,a))},clear:function(){var a=this._items.length-1;this._items.length=0;this.intervalRemoved(0,a);this.dispatch("intervalRemoved",{index0:0,index1:a})},indexOf:function(a){for(var b=this.size();b;){if(this.get(b-1)===a)return b-1;b--}return-1},copyInto:function(a){juic.assert(a.constructor==Array,"[SFDefaultListModel] Invalid object passed into copyInto. Must be an array.");a.concat(this._items)},get:function(a){return this._items[a]},getFirstItem:function(){return this.get(0)},
getLastItem:function(){return this.get(this.size()-1)},size:function(){return this._items.length},isEmpty:function(){return 0==this.size()},remove:function(){this._items.pop();var a=this._items.length-1;this.intervalRemoved(a,a);this.dispatch("intervalRemoved",{index0:a,index1:a})},move:function(a,b,c){null==c&&(c=1);var d=this._items.splice(a,c);d.splice(0,0,b,0);this._items.splice.apply(this._items,d);this.intervalMoved(a,b,c);this.dispatch("intervalMoved",{beforeIndex:a,afterIndex:b,count:c})},
forEach:function(a,b){this._items.forEach(a,b)},removeItemAt:function(a){juic.assert(this._items[a],"ERROR: Invalid index passed to removeItemAt. Index is out of range.");var b=this._items.splice(a,1);this.intervalRemoved(a,a);this.dispatch("intervalRemoved",{index0:a,index1:a});return b},removeItem:function(a){var b=!1;a=this.indexOf(a);0<=a&&(b=!0,this.removeItemAt(a));return b},removeRange:function(a,b){juic.assert(this._items[a]&&this._items[b],"ERROR: Invalid indices passed to removeRange. Either fromIndex or toIndex is out of range.");
var c=this._items.splice(a,b-a+1);this.dispatch("intervalRemoved",{index0:a,index1:b});this.intervalRemoved(a,b);return c},set:function(a,b){this._items[a]=b;this.dispatch("contentsChanged",{index0:a,index1:a})},setItems:function(a){0<this._items.length&&this.clear();this._items=a.constructor==Array?a:[];if(a.constructor==Array)this._items=a;else for(var b in a)this._items.push(b);this.dispatch("intervalAdded",{index0:0,index1:this.size()-1});this.intervalAdded(0,this.size()-1)},getItems:function(){return this._items},
intervalRemoved:function(a,b){},intervalAdded:function(a,b){},intervalMoved:function(a,b,c){}})}();function SFDefaultSingleSelectModel(a){juic.assert(a,"[SFDefaultSingleSelectModel] No items were passed");SFDefaultListModel.call(this,a);0<this.size()&&(this._selectedIndex=0)}
SFDefaultSingleSelectModel.prototype=function(){return juic.set(new SFDefaultListModel,{setSelectedIndex:function(a){this._selectedIndex=a;this.dispatch("contentsChanged",{index0:-1,index1:-1})},getSelectedIndex:function(){return this._selectedIndex},resetSelectedIndex:function(){this._selectedIndex=0;this.dispatch("resetSelection")},intervalAdded:function(a,b){this._selectedIndex>=a&&(this._selectedIndex+=b-a+1,this._selectedIndex>=this.size()&&(this._selectedIndex=this.size()-1))},intervalRemoved:function(a,
b){this._selectedIndex>=a&&(this._selectedIndex=this._selectedIndex<=b?0:this._selectedIndex-(b-a+1),this.dispatch("contentsChanged",{index0:-1,index1:-1}))},intervalMoved:function(a,b,c){this._selectedIndex>=a&&this._selectedIndex<a+c?this._selectedIndex=b+this._selectedIndex-a:(this._selectedIndex>a&&(this._selectedIndex-=c),this._selectedIndex>=b&&(this._selectedIndex+=c))}})}();
function SFDefaultMultiSelectModel(a){juic.assert(a,"[SFDefaultSingleSelectModel] No items were passed");this._selectedIndices=[];SFDefaultListModel.call(this,a)}
SFDefaultMultiSelectModel.prototype=function(){return juic.set(new SFDefaultListModel,{addSelectedIndex:function(a){juic.assert(0<=a&&a<this.size(),"[SFDefaultMultiSelectModel] Invalid index: "+a);this._selectedIndices.contains(a)||this._selectedIndices.push(a);this.dispatch("selectionChanged")},isAllSelected:function(){return this._selectedIndices.length==this.size()},deselectAll:function(){0<this._selectedIndices.length&&(this._selectedIndices.length=0,this.dispatch("selectionChanged"))},selectAll:function(){for(var a=
this._selectedIndices.length=0,b=this.size();a<b;a++)this._selectedIndices.push(a);this.dispatch("selectionChanged")},removeSelectedIndex:function(a){for(var b=0,c=this._selectedIndices.length;b<c;b++)if(this._selectedIndices[b]===a){this._selectedIndices.splice(b,1);this.dispatch("selectionChanged");break}},setSelectedIndices:function(a){this._selectedIndices.length=0;if(a&&0<a.length)for(var b=0,c=a.length;b<c;b++)juic.assert(0<=a[b]&&a[b]<this.size(),"[SFDefaultMultiSelectModel] Invalid index: "+
a[b]+" max "+(this.size()-1)),this._selectedIndices.push(a[b]);this.dispatch("selectionChanged")},isIndexSelected:function(a){return this._selectedIndices.contains(a)},getSelectedCount:function(){return this._selectedIndices.length},getSelectedIndices:function(){return this._selectedIndices.concat()},intervalAdded:function(a,b){this._lastToggled=null;for(var c=0,d=this._selectedIndices.length;c<d;c++)this._selectedIndices[c]>=a&&(this._selectedIndices[c]+=b-a+1)},intervalMoved:function(a,b,c){this._lastToggled=
null;for(var d=0;d<this._selectedIndices.length;){var e=before=this._selectedIndices[d];e>=a&&e<a+c?e=b+e-a:(e>a&&(e-=c),e>=b&&(e+=c));e!=before&&(this._selectedIndices[d]=e);d++}},intervalRemoved:function(a,b){this._lastToggled=null;for(var c=0,d=!1;c<this._selectedIndices.length;)this._selectedIndices[c]>=a&&(this._selectedIndices[c]<=b?(d=!0,this._selectedIndices.splice(c,1),c--):this._selectedIndices[c]-=b-a+1),c++;d&&this.dispatch("selectionChanged")},toggleSelection:function(a,b,c){!this._lastToggled&&
1==this._selectedIndices.length&&(this._lastToggled=this._selectedIndices[0]);b||(this._selectedIndices=[]);if(c&&null!=this._lastToggled){b=Math.max(this._lastToggled,a);for(var d=Math.min(this._lastToggled,a);d<=b;d++)this._selectedIndices.contains(d)||this._selectedIndices.push(d)}else this._selectedIndices.contains(a)?this._selectedIndices.remove(a):this._selectedIndices.push(a);c||(this._lastToggled=a);this.dispatch("selectionChanged")}})}();
function SFFactoryListModel(a){a=juic.Config.convertArguments(arguments,["model","factory","context"],null,{model:SFDefaultListModel,factory:"function"});this._factory=a.factory;this._context=a.context;this.setModel(a.model)}function SFFactorySingleSelectModel(a){a=juic.Config.convertArguments(arguments,["model","factory","context"],null,{model:SFDefaultSingleSelectModel,factory:"function"});SFFactoryListModel.call(this,a);0<this.size()&&(this._selectedIndex=a.model.getSelectedIndex())}
function SFFactoryMultiSelectModel(a){a=juic.Config.convertArguments(arguments,["model","factory","context"],null,{model:SFDefaultMultiSelectModel,factory:"function"});SFFactoryListModel.call(this,a);this._selectedIndices=a.model.getSelectedIndices().concat()}
(function(){function a(a,b){b.forEach(function(b){a[b]=function(){return this._model[b].apply(this._model,arguments)}})}function b(a,b){for(var f in b)(function(f){a[f]=function(){b[f].apply(this,arguments);return c[f].apply(this,arguments)}})(f)}var c={setModel:function(a){this._model&&(this._model.removeEventListener("contentsChanged",this),this._model.removeEventListener("intervalAdded",this),this._model.removeEventListener("intervalRemoved",this),this._model.removeEventListener("intervalMoved",
this),0<this.size()&&this.dispatch("intervalRemoved",{index0:0,index1:this.size()}));this._model=a;this._model.addEventListener("contentsChanged",this,"_onContentsChanged");this._model.addEventListener("intervalAdded",this,"_onIntervalAdded");this._model.addEventListener("intervalRemoved",this,"_onIntervalRemoved");this._model.addEventListener("intervalMoved",this,"_onIntervalMoved");this._items=[];this._items.length=a.size()},get:function(a){var b=this._super(a);null==b&&(b=this._createItem(a),this._items[a]=
b);return b},getItems:function(){this._resolve();return this._super()},forEach:function(a,b){this._resolve();this._super(a,b)},_resolve:function(){for(var a=0;a<this.size();a++)this.get(a)},_createItem:function(a){var b=this._model.get(a);switch(typeof this._factory){case "object":if("function"==typeof this._factory.create)return this._factory.create(b,this._model,a);break;case "function":return this._factory.call(this._context,b,this._model,a)}return b},_onContentsChanged:function(a){if(0<=a.index0)for(var b=
a.index0;b<=a.index1;b++)this._items[b]=null;this.dispatch("contentsChanged",{index0:a.index0,index1:a.index1})},_onIntervalAdded:function(a){if(!a.moving){for(var b=[a.index0,0],f=a.index1-a.index0+1,c=0;c<f;c++)b.push(null);this._items.splice.apply(this._items,b)}this.dispatch("intervalAdded",{index0:a.index0,index1:a.index1})},_onIntervalRemoved:function(a){a.moving||this._items.splice(a.index0,a.index1-a.index0+1);this.dispatch("intervalRemoved",{index0:a.index0,index1:a.index1})},_onIntervalMoved:function(a){var b=
a.afterIndex,f=this._items.splice(a.beforeIndex,a.count);f.splice(0,0,b,0);this._items.splice.apply(this._items,f);this.dispatch("intervalMoved",{beforeIndex:a.beforeIndex,afterIndex:a.afterIndex,count:a.count})}};(function(a,b){b.forEach(function(b){a[b]=function(){throw Error("SFFactoryListModel: Do not call "+b+" on the factory, please call this on the underlying list model and it will be reflected");}})})(c,["add","insertItemAt","copyInto","set","setItems"]);a(c,["remove","removeItemAt","removeRange",
"move"]);var d=juic.set({},c);a(d,["setSelectedIndex"]);var e=juic.set({_onSelectionChanged:function(a){this._selectedIndices=this._model.getSelectedIndices();this.dispatchEvent(a)}},c);b(e,{setModel:function(a){this._model&&this._model.removeEventListener("selectionChanged");a&&a.addEventListener("selectionChanged",this,"_onSelectionChanged")}});a(e,["addSelectedIndex","deselectAll","selectAll","removeSelectedIndex","setSelectedIndices"]);var l={},q={};["_onContentsChanged","_onIntervalAdded","_onIntervalMoved",
"_onIntervalRemoved"].forEach(function(a){l[a]=function(){this._selectedIndex=this._model.getSelectedIndex()};q[a]=function(){this._selectedIndices=this._model.getSelectedIndices()}});b(d,l);b(e,q);juic.extend(SFFactoryListModel,SFDefaultListModel,c);juic.extend(SFFactorySingleSelectModel,SFDefaultSingleSelectModel,d);juic.extend(SFFactoryMultiSelectModel,SFDefaultMultiSelectModel,e)})();function SFAbstractResizable(){juic.assert(!1,"[SFAbstractResizable] Cannot instantiate")}
juic.extend(SFAbstractResizable,juic.Component,{setDimension:function(a){juic.assert(!1,"[SFAbstractResizable] Must implement setDimension")},getDimension:function(){juic.assert(!1,"[SFAbstractResizable] Must implement getDimension")},resize:function(){},getMinDimension:function(){return{width:0,height:0}},getMaxDimension:function(){return null}});
function SFResizer(){this.register();this._referenceContainers=[];this._sizingContainers=[];this._subContainers=[];this._centerContainers=[];this._referenceHeight=0;this.init()}
SFResizer.prototype=function(){return juic.set(new juic.Component,{init:function(){SFDOMEvent.addListener(window,"resize",function(){this.resize();return!1},this)},registerReferenceContainer:function(a){this._referenceContainers.push(a)},registerSizingContainers:function(a){this._sizingContainers.push(a)},registerSubContainer:function(a){this._subContainers.push(a)},registerCenterContainer:function(a){this._centerContainers.push(a)},getReferenceHeight:function(){for(var a=0,b=0,c=this._referenceContainers.length;b<
c;++b)a+=parseInt(juic.$(this._referenceContainers[b]).offsetHeight);return a},centerOnResize:function(){for(var a=0,b=this._centerContainers.length;a<b;++a){var c=juic.$(this._centerContainers[a]);if(c){var d=c.offsetWidth,e=SFDom.getViewportWidth(),d=0<e-d?e-d:0;c.style.left=Util.browserInfo.ie?parseInt(d/2)+"px":parseInt(d/2)+1+"px"}}},resize:function(){var a=window.SFDom;if(a){var b=this.getReferenceHeight(),a=a.getViewportHeight()-b+0;if(0<a){for(var b=0,c=this._sizingContainers.length;b<c;++b)juic.$(this._sizingContainers[b])&&
(juic.$(this._sizingContainers[b]).style.height=a+"px");b=0;for(c=this._subContainers.length;b<c;++b)juic.$(this._subContainers[b])&&(juic.$(this._subContainers[b]).style.height=a+"px")}this.centerOnResize();this.dispatch("resizeEvt",{containerHeight:Math.floor(a-0)})}}})}();function SFScrollBar(a){this.register();this._init(a)}
(function(){extend(SFScrollBar,Component,{_init:function(b){b=b||{};b={autoScroller:b.autoScroller,axisType:b.axisType,minimumScroll:b.minimumScroll||10,enabled:null==b.enabled?!0:b.enabled,css:b.css};this._autoScroller=b.autoScroller;this._autoScroller.addEventListener("autoScroll",this,"adjustDOM");this._axisType=b.axisType;this._axis=a[this._axisType];this._css=b.css;this._minimumScroll=b.minimumScroll;assert(this._axis,"SFScrollBar: Invalid axisType: "+this._axisType);assert(this._autoScroller instanceof
SFAutoScroller,"SFScrollBar: Invalid auto scroller");this._enabled=b.enabled},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'" class\x3d"',this._axisType+"scrollBar scrollBar"+(this._css?" "+this._css:""),' globalRoundedCorners" onmousedown\x3d"',this.fireCode("_pageScroll"),'"');a.push('" ontouchstart\x3d"',this.fireCode("_onDragStart"),'"\x3e');a.push('\x3cdiv id\x3d"',this.id,'handle" onmousedown\x3d"',this.fireCode("_onDragStart"),'" class\x3d"',"scrollHandle globalRoundedCorners",'"\x3e\x3c/div\x3e\x3c/div\x3e');
a.addAfterRenderListener(this,"adjustDOM")},adjustDOM:function(){var a=juic.$(this.id);if(a){var c=a[this._axis.offsetDimension],c=c-SFDom.getOffsets(a,this._axisType),d=this._autoScroller.getScrollInfo()[this._axisType],e=this._enabled&&d.size-d.scrollArea>this._minimumScroll,l=Math.max(10,c*d.scrollArea/d.size);this._ratio=(d.size-d.scrollArea)/(c-l);e?(a.style.display="block",a=juic.$(this.id+"handle"),a.style[this._axis.startRegion]=d.position/this._ratio+"px",a.style[this._axis.dimension]=l+
"px"):a.style.display="none"}},getOffset:function(){return 17},handleDragEvent:function(a){var c=this._autoScroller.getScrollInfo();switch(a.type){case "dragStart":this._positionStart=c[this._axisType].position;break;case "drag":var d=this._positionStart+(a.point[this._axisType]-a.origin[this._axisType])*this._ratio;this._autoScroller.setScrollPosition("x"==this._axisType?d:c.x.position,"y"==this._axisType?d:c.y.position);break;case "dragEnd":this._autoScroller.stopScrolling()}this.dispatch("action",
{actionCommand:a.type})},setEnabled:function(a){this._enabled=a;this.adjustDOM()},_onKeyUp:function(a){this._autoScroller.stopScrolling()},_onKeyDown:function(a){var c=SFDOMEvent.getKeyName(a||window.event);c==this._axis.descendKeyName&&(this._autoScroller.autoScrollAxis(-1,this._axisType),SFDOMEvent.preventDefault(a));c==this._axis.ascendKeyName&&(this._autoScroller.autoScrollAxis(1,this._axisType),SFDOMEvent.preventDefault(a))},_onDragStart:function(a){SFDOMEvent.stopEvent(a);SFDragDropMgr.handleDragStart(a,
this,{useShim:!0,shimCursor:this._axis.cursor,clickTimeThreshold:0})},_pageScroll:function(a){var c=juic.$(this.id);if(c){var d=this._axisType,e=this._autoScroller.getScrollInfo()[d];if(this._enabled&&e.size-e.scrollArea>this._minimumScroll){var c=Util.getAbsPos(c),l=e.position/this._ratio;a=SFDOMEvent.getXY(a)["x"==d?0:1]-c[d]<l?-1:1;e=e.scrollArea*a;this._autoScroller.scrollMove("x"==d?e:0,"y"==d?e:0)}}},cleanup:function(){this._autoScroller.removeEventListener("autoScroll",this)}});var a={x:{opposite:"y",
offsetDimension:"offsetWidth",dimension:"width",scrollOffset:"clientWidth",scrollSize:"scrollWidth",scrollPosition:"scrollLeft",descendKeyName:"ARROWLEFT",ascendKeyName:"ARROWRIGHT",getPoint:"getX",getPagePoint:"getPageX",cursor:"col-resize",startRegion:"left"},y:{opposite:"x",dimension:"height",offsetDimension:"offsetHeight",scrollOffset:"clientHeight",scrollSize:"scrollHeight",scrollPosition:"scrollTop",descendKeyName:"ARROWUP",ascendKeyName:"ARROWDOWN",getPoint:"getY",getPagePoint:"getPageY",cursor:"row-resize",
startRegion:"top"}}})();function SFAutoScroller(a){this._init(a)}
SFAutoScroller.prototype=function(){function a(a,b,h){h=l[h];var f=Math.min(0,b[h.startRegionType]-a[h.startRegionType]);return Math.max(0,b[h.endRegionType]-a[h.endRegionType])+f}function b(a,b,h){var f=l[a],c=null,g,k;b==document.body||b==document.documentElement?(c=SFDom.getViewportRegion(),g=SFDom[f.documentDimension](),k=c[f.dimensionType]):(c=SFDom.getRegion(b),g=b[f.scrollDimensionType],k=b[f.clientDimensionType]);if(g>k&&(g=c[f.startRegionType],c=c[f.endRegionType]-(h[f.offsetDimensionType]-
k||17),k=h[f.startRegionType],h=h[f.endRegionType],g>k||c<h)){var f=Math.min(Math.abs(g-k),Math.abs(g-h)),d=Math.min(Math.abs(c-k),Math.abs(c-h)),e=SFDom.getScrollPosition(b,a),e=f<d?Math.max(0,k-g+e):Math.max(0,h-c+e);SFDom.setScrollPosition(b,e,a)}}function c(a){return a==document.body||a==document.documentElement?SFDom.getViewportRegion():SFDom.getRegion(a)}var d={tickSize:20,interval:200,increaseTickSize:!1},e={tickSize:"number",interval:"number"},l={x:{scrollPositionType:"scrollLeft",dimensionType:"width",
startRegionType:"left",endRegionType:"right",offsetDimensionType:"offsetWidth",clientDimensionType:"clientWidth",scrollDimensionType:"scrollWidth",documentScrollType:"getDocumentScrollLeft",documentDimension:"getDocumentWidth"},y:{scrollPositionType:"scrollTop",dimensionType:"height",startRegionType:"top",endRegionType:"bottom",offsetDimensionType:"offsetHeight",clientDimensionType:"clientHeight",scrollDimensionType:"scrollHeight",documentScrollType:"getDocumentScrollTop",documentDimension:"getDocumentHeight"}};
return juic.set(new juic.EventTarget,{_init:function(a){a=new juic.Config(a,d,e);this._scrollEl=a.scrollEl;this._extenderEl=a.extenderEl;this._interval=a.interval;this._tickSize=a.tickSize;this._increaseTickSize=a.increaseTickSize;this._axisData={x:{},y:{}}},autoScrollAxis:function(b,d,h){juic.assert(this._scrollEl,"Scroll DOM element not available");var f=c(this._scrollEl),m={};m[d]={delta:"number"==typeof b?b:a(f,b,d)};this._startScrolling(m,h)},autoScroll:function(b,d){juic.assert(this._scrollEl,
"Scroll DOM element not available");var h=c(this._scrollEl),f={},m;for(m in l)f[m]={delta:"number"==typeof b?b:a(h,b,m)};this._startScrolling(f,d)},scrollTo:function(a){var c=this.getScrollEl();if(c){var h=SFDom.getScrollPosition(c,"x"),f=SFDom.getScrollPosition(c,"y");b("x",c,a);b("y",c,a);a=SFDom.getScrollPosition(c,"x")-h;c=SFDom.getScrollPosition(c,"y")-f;if(0!=a||0!=c)return this.dispatch("autoScroll",{delta:{x:a,y:c}}),!0}return!1},scrollToAxis:function(a,c){var h=this.getScrollEl();if(h){var f=
SFDom.getScrollPosition(h,a);b(a,h,c);h=SFDom.getScrollPosition(h,a)-f;if(0!=h)return f={},f[a]=h,this.dispatch("autoScroll",{delta:f}),!0}return!1},scrollMove:function(a,b){var h=this.getScrollEl();if(h){var f=SFDom.getScrollLeft(h),c=SFDom.getScrollTop(h);SFDom.setScrollLeft(h,f+a);SFDom.setScrollTop(h,c+b);a=SFDom.getScrollLeft(h)-f;b=SFDom.getScrollTop(h)-c;if(0!=a||0!=b)return this.dispatch("autoScroll",{delta:{x:a,y:b}}),!0}return!1},setScrollPosition:function(a,b){var h=this.getScrollEl();
if(h){var f=SFDom.getScrollPosition(h,"x"),c=SFDom.getScrollPosition(h,"y");SFDom.setScrollTop(h,b);SFDom.setScrollLeft(h,a);f=SFDom.getScrollPosition(h,"x")-f;h=SFDom.getScrollPosition(h,"y")-c;if(0!=f||0!=h)return this.dispatch("autoScroll",{delta:{x:f,y:h}}),!0}return!1},stopScrolling:function(a){if(this.isScrolling()){var b=!a;if(a&&(this._axisData[a].multiplier=0,0==this._axisData["x"==a?"y":"x"].multiplier))b=!0;b&&(clearInterval(this._intervalId),this._intervalId=null)}},getScrollPosition:function(a){var b=
this.getScrollEl();if(b)return SFDom.getScrollPosition(b,a)},getScrollLeft:function(){return this.getScrollPosition("x")},getScrollTop:function(){return this.getScrollPosition("y")},getScrollInfo:function(){var a=this.getScrollEl(),b=null;a&&(b=a==document.body||a==document.documentElement?{y:{size:SFDom.getDocumentHeight(),scrollArea:SFDom.getViewportHeight(),position:SFDom.getScrollPosition(a,"y"),inverse:!1},x:{size:SFDom.getDocumentWidth(),scrollArea:SFDom.getViewportWidth(),position:SFDom.getScrollPosition(a,
"x"),inverse:Util.isRTL()}}:{y:{size:a.scrollHeight,scrollArea:a.clientHeight,position:SFDom.getScrollPosition(a,"y"),inverse:!1},x:{size:a.scrollWidth,scrollArea:a.clientWidth,position:SFDom.getScrollPosition(a,"x"),inverse:Util.isRTL()}},["x","y"].forEach(function(a){a=b[a];a.oppositePosition=a.size-a.position-a.scrollArea}));return b},getScrollEl:function(){return"string"==typeof this._scrollEl?juic.$(this._scrollEl):this._scrollEl},setScrollEl:function(a){this._scrollEl=a},getExtenderEl:function(){return"string"==
typeof this._extenderEl?juic.$(this._extenderEl):this._extenderEl},setExtenderEl:function(a){this._extenderEl=a},isScrolling:function(){return null!=this._intervalId},_startScrolling:function(a,b){juic.assert(a,"axisData required to startScrolling");this._autoIncreaseSize=b;juic.assert(!this._autoIncreaseSize||this._extenderEl,"Must have an extender to auto-increase size");this._axisData=this._createAxisData(a);if(!this.isScrolling()&&(0!=this._axisData.x.multiplier||0!=this._axisData.y.multiplier))this._intervalId=
setInterval(Util.createCallback(this,"_autoScroll"),this._interval),this._autoScroll()},_autoScroll:function(){var a=this._autoScrollAxis("x"),b=this._autoScrollAxis("y");0==a&&0==b?this.stopScrolling():this.dispatch("autoScroll",{delta:{x:a,y:b}})},_autoScrollAxis:function(a){var b=0,h=this._axisData[a],f=h.multiplier;if(0!=f){var c=this.getScrollEl(),g=SFDom.getScrollPosition(c,a),f=f*this._tickSize;var f=g+f,k=h.minPosition,d=h.maxPosition,f=null!=k&&f<k?k:null!=d&&f>d?d:f;0!=f-g&&(this._autoIncreaseSize&&
f>h.clientMaxPosition&&this._increaseClientSize(a,f),SFDom.setScrollPosition(c,f,a),b=SFDom.getScrollPosition(c,a)-g)}return b},_createAxisData:function(a){var b={},c;for(c in l){var f=l[c],m=juic.set({},a[c]);if(m.delta){m.multiplier=0>m.delta?-1:1;if(this._increaseTickSize){var g=Math.floor(Math.abs(m.delta)/25);0<g&&(m.multiplier*=g)}var g=this.getScrollEl(),f=g[f.scrollDimensionType]-g[f.clientDimensionType],g=m.minPosition||0,k=m.maxPosition;k>f&&!this._autoIncreaseSize&&(k=f);m.clientMaxPosition=
f;m.minPosition=g;m.maxPosition=k}else m.multiplier=0;b[c]=m}return b},_increaseClientSize:function(a,b){var c=l[a],f=b-this._axisData[a].clientMaxPosition,m=this.getExtenderEl(),g=m[c.clientDimensionType],g=Math.max(m.firstChild[c.clientDimensionType],g),f=g+f;m.style[c.dimensionType]=f+"px";this.dispatch("clientSizeIncrease",{dimensionType:c.clientDimensionType,oldSize:g,newSize:f})}})}();
"undefined"==typeof SFDragDropMgr&&(window.SFDragDropMgr=function(){function a(a){return a?(xy=SFDOMEvent.getXY(a||window.event),new SFPoint(xy[0],xy[1])):null}function b(a){return a?new SFPoint(a.pageX,a.pageY):null}function c(a,b,c){var g=c&&c.distanceThreshold||r;if(c&&c.axisType){if("x"==c.axisType)return Math.abs(a.x-b.x)>g;if("y"==c.axisType)return Math.abs(a.y-b.y)>g}else return Math.abs(a.x-b.x)>g||Math.abs(a.y-b.y)>g}function d(a){for(var b=[],c=0,g=a.length;c<g;c++){var k=a[c];b.push({pageX:k.pageX,
pageY:k.pageY})}return b}function e(a){var b=a.type,c={type:b,pageX:a.pageX,pageY:a.pageY,clientX:a.clientX,clientY:a.clientY,target:SFDOMEvent.getTarget(a),relatedTarget:SFDOMEvent.getRelatedTarget(a)};0==b.indexOf("touch")&&(c.changedTouches=d(a.changedTouches),c.touches=d(a.touches));0==b.indexOf("gesture")&&(c.scale=a.scale);return c}function l(a,f){var c=a&&a.length;if(c)for(var g=b(f),k=0;k<c;k++){var d=b(a[k]);if(g.equals(d))return k}return-1}function q(a,f,c){if(a&&0<a.length){f=b(f);for(var g=
null,k=null,d=0,e=a.length;d<e;d++){if(a[d].point.equals(f))return d;if(c){var v=a[d].point.getDistance(f);if(null==k||v<k)k=v,g=d}}if(c)return g}return-1}var r=3;return juic.set(new juic.EventTarget,{init:function(){this._dropTargets=[];this._dropTargetLookup={};this._overTargets=[]},handleMouseDown:function(a,b,c){this.handleDragStart(a,b,c)},handleDragStart:function(a,b,c){juic.assert(b&&b.handleDragEvent,"SFDragDropMgr: dragListener is required, and must have a handleDragEvent method");this._activeDrag||
(a=a||window.event,juic.assert(a,"SFDragDropMgr: The origin mouse event is required"),this._activeDrag={handler:b,options:c,startEvent:e(a),isTouch:0==a.type.indexOf("touch"),overThreshold:!1},this._activeDrag.isTouch&&this._updateTouches(a),(!c||!1!=c.refreshCache)&&this.refreshCache(c&&c.refreshDOM),c&&0===c.clickTimeThreshold?(this._activeDrag.overThreshold=!0,this._dragToCurrentPoint()):(this._activeDrag.overThreshold=!1,this._activeDrag.timeoutId=setTimeout(function(){SFDragDropMgr._handleTimeout()},
c&&c.clickTimeThreshold||1E3)),this._activeDrag.isTouch||SFDOMEvent.preventDefault(a),SFDOMEvent.addListener(document,"touchstart",this._onTouchStart,this),SFDOMEvent.addListener(document,"touchend",this._onTouchEnd,this),SFDOMEvent.addListener(document,"touchmove",this._onTouchMove,this),SFDOMEvent.addListener(document,"gesturestart",this._onGestureStart,this),SFDOMEvent.addListener(document,"gesturechange",this._onGestureChange,this),SFDOMEvent.addListener(document,"gestureend",this._onGestureEnd,
this),SFDOMEvent.addListener(document,"mouseup",this._onMouseUp,this),SFDOMEvent.addListener(document,"mousemove",this._onMouseMove,this))},stop:function(){this._dragging?this._stopDrag():(this._clearTimeout(),this._activeDrag=null)},isDragging:function(){return this._dragging},makeDraggable:function(a,b){var c={options:b,id:a,handleDragEvent:function(a){switch(a.type){case "drag":var b=juic.$(this.id);b.style.left=this.originPosition.left-a.origin.x+a.point.x+"px";b.style.top=this.originPosition.top-
a.origin.y+a.point.y+"px"}},onMouseDown:function(a){var c=juic.$(this.id);c&&(this.originXY=SFDom.getXY(this.id),this.originPosition={left:parseInt(SFDom.getStyle(c,"left")),top:parseInt(SFDom.getStyle(c,"top"))},SFDragDropMgr.handleMouseDown(a,this,b))}};SFDOMEvent.addListener(juic.$(b&&b.handleId||a),"mousedown",c.onMouseDown,c)},addDropTarget:function(a,b){var c={id:a,properties:b};this._dropTargets.push(c);this._dropTargetLookup[a]=c},getDropTarget:function(a){return this._dropTargetLookup[a]},
getAllDropTargets:function(){return this._dropTargets},getDropTargets:function(a){var b;if(a){b=[];for(var c=0,d=a.length;c<d;c++)b.push(this.getDropTarget(a[c]))}return b},removeDropTarget:function(a){for(var b=0,c=this._dropTargets.length;b<c;b++)if(this._dropTargets[b].id==a){this._dropTargets.splice(b,1);break}delete this._dropTargetLookup[a]},refreshCache:function(a){for(var b=0,c=this._dropTargets.length;b<c;b++){var d=this._dropTargets[b];delete d.region;a&&delete d.el}this._forceUpdate=!0},
_checkCache:function(){this._forceUpdate&&(this._forceUpdate=!1,this._updateCache())},_updateCache:function(){for(var a=0,b=this._dropTargets.length;a<b;a++){var c=this._dropTargets[a];c.el=c.el||juic.$(c.id);c.region=c.el?SFDom.getRegion(c.el):null}},_clearTimeout:function(){return this._activeDrag&&null!=this._activeDrag.timeoutId?(clearTimeout(this._activeDrag.timeoutId),this._activeDrag.timeoutId=null,!0):!1},_handleTimeout:function(){this._activeDrag.timeoutId=null;this._activeDrag.overThreshold=
!0;this._dragToCurrentPoint()},_onMouseMove:function(a){this._activeDrag&&(SFDOMEvent.stopPropagation(a),Util.browserInfo.ie&&9>Util.ieVersion&&!a.button?this._stopDrag(a):this._moveDrag(a))},_onMouseUp:function(a){this._activeDrag&&(SFDOMEvent.stopPropagation(a),this._stopDrag(a))},_onTouchStart:function(a){this._activeDrag&&(this._activeDrag.options&&this._activeDrag.options.noMultiTouch&&1<a.touches.length?this._stopDrag(a):this._updateTouches(a))},_onTouchEnd:function(a){this._activeDrag&&(this._updateTouches(a),
0==a.touches.length&&this._stopDrag(a))},_onTouchMove:function(a){if(this._activeDrag){var b=!0;this._activeDrag.options&&(this._activeDrag.options.allowTouchMove&&this._activeDrag.overThreshold)&&(b=!1);b&&SFDOMEvent.preventDefault(a);this._updateTouches(a);this._moveDrag(a)}},_onGestureStart:function(a){this._activeDrag&&(this._activeDrag.options.noMultiTouch?this._stopDrag(a):(this._activeDrag.gestureEvent=e(a),this._onGestureChange(a),this._activeDrag.handler.handleDragEvent({type:"gestureStart"})))},
_onGestureChange:function(a){this._activeDrag&&(SFDOMEvent.stopEvent(a),this._activeDrag.gestureEvent=e(a))},_onGestureEnd:function(a){this._activeDrag&&(SFDOMEvent.stopEvent(a),this._activeDrag.gestureEvent=null,this._activeDrag.handler.handleDragEvent({type:"gestureEnd"}))},_checkDragThreshold:function(b){if(this._activeDrag.overThreshold)return!0;if(this._activeDrag.isTouch)for(var f=0;f<this._activeDrag.touches.length;f++){if(b=this._activeDrag.touches[f],c(b.point,b.lastPoint,this._activeDrag.options))return!0}else return f=
a(this._activeDrag.startEvent),b=a(b),c(f,b,this._activeDrag.options);return!1},_moveDrag:function(a){this._checkDragThreshold(a)&&(this._activeDrag.lastMoveEvent=this._activeDrag.moveEvent,this._activeDrag.moveEvent=e(a),this._activeDrag.overThreshold=!0,this._clearTimeout(),this._dragToCurrentPoint())},_dragToCurrentPoint:function(){this._checkCache();if(!this._activeDrag)return!1;var b=this._activeDrag.options,c=this._activeDrag.handler,d=[],g=[],k=[],e={isTouch:this._activeDrag.isTouch,gestureEvent:this._activeDrag.gestureEvent,
startEvent:this._activeDrag.startEvent,lastMoveEvent:this._activeDrag.lastMoveEvent,moveEvent:this._activeDrag.moveEvent,dropTargets:d};this._activeDrag.isTouch?(e.touches=this._activeDrag.touches,e.origin=this._activeDrag.touches[0].origin,e.lastPoint=this._activeDrag.touches[0].lastPoint,e.point=this._activeDrag.touches[0].point):(e.origin=a(this._activeDrag.startEvent),e.lastPoint=a(this._activeDrag.lastMoveEvent||this._activeDrag.startEvent),e.point=a(this._activeDrag.moveEvent||this._activeDrag.startEvent));
for(var n=0,v=this._dropTargets.length;n<v;n++){var p=this._dropTargets[n];if(p.region){var l=this._overTargets.contains(p.id),s=p.region.contains(e.point);s&&!l?(g.push(p),this._overTargets.push(p.id)):!s&&l&&(k.push(p),this._overTargets.remove(p.id));s&&d.push(p)}}this._dragging||(b&&b.useShim&&(this._showShim(),this._shim.style.cursor=b.shimCursor?b.shimCursor:""),c.handleDragEvent(juic.set({type:"dragStart"},e)));this._dragging=!0;c.handleDragEvent(juic.set({type:"drag"},e));0<k.length&&(p=k[0],
c.handleDragEvent(juic.set({type:"dragOut",id:p.id,properties:p.properties,region:p.region},e)));0<g.length&&(p=g[0],c.handleDragEvent(juic.set({type:"dragOver",id:p.id,properties:p.properties,region:p.region},e)))},_stopDrag:function(c){this._shimActive&&this._hideShim();if(!this._clearTimeout()){var f=this.getDropTargets(this._overTargets),d=this._activeDrag.handler,g={type:"dragEnd",isTouch:this._activeDrag.isTouch,dropTargets:f,gestureEvent:this._activeDrag.gestureEvent,startEvent:this._activeDrag.startEvent,
lastMoveEvent:this._activeDrag.moveEvent,endEvent:e(c)},k=this._activeDrag.moveEvent||this._activeDrag.startEvent;this._activeDrag.isTouch?(g.origin=b(this._activeDrag.startEvent.changedTouches[0]),k&&(k.changedTouches&&0<k.changedTouches.length)&&(g.lastPoint=b(k.changedTouches[0])),c&&(c.changedTouches&&0<c.changedTouches.length)&&(g.point=b(c.changedTouches[0]))):(g.origin=a(this._activeDrag.startEvent),g.lastPoint=a(k),c&&(g.point=a(c)));d.handleDragEvent(g);this.dispatch("dragDrop",{dragHandler:d,
dropTargets:f})}SFDOMEvent.removeListener(document,"touchstart",this._onTouchStart);SFDOMEvent.removeListener(document,"touchend",this._onTouchEnd);SFDOMEvent.removeListener(document,"touchmove",this._onTouchMove);SFDOMEvent.removeListener(document,"gesturestart",this._onGestureStart);SFDOMEvent.removeListener(document,"gesturechange",this._onGestureChange);SFDOMEvent.removeListener(document,"gestureend",this._onGestureEnd);SFDOMEvent.removeListener(document,"mouseup",this._onMouseUp);SFDOMEvent.removeListener(document,
"mousemove",this._onMouseMove);this._activeDrag=null;this._dragging=!1;this._overTargets=[]},_showShim:function(){this._shim||this._createShim();this._shimActive=!0;this._sizeShim();this._shim.style.display=""},_hideShim:function(){this._shim&&(this._shim.style.height="0px",this._shim.style.display="none")},_sizeShim:function(){this._shimActive&&(this._shim.style.height=SFDom.getDocumentHeight()-1+"px",this._shim.style.width=SFDom.getDocumentWidth()-1+"px",this._shim.style.top="0",this._shim.style.left=
"0")},_createShim:function(){this._shim||(this._shim=document.createElement("div"),document.body.firstChild?document.body.insertBefore(this._shim,document.body.firstChild):document.body.appendChild(this._shim),this._shim.style.display="none",this._shim.style.backgroundColor="transparent",this._shim.style.position="absolute",this._shim.style.zIndex="100001",this._shim.style.cursor="move",this._shim.unselectable="on",this._shim.onselectstart=function(){return!1},SFDOMEvent.addListener(this._shim,"touchstart",
this._onTouchStart,this),SFDOMEvent.addListener(this._shim,"touchend",this._onTouchEnd,this),SFDOMEvent.addListener(this._shim,"touchmove",this._onTouchMove,this),SFDOMEvent.addListener(this._shim,"gesturestart",this._onGestureStart,this),SFDOMEvent.addListener(this._shim,"gesturechange",this._onGestureChange,this),SFDOMEvent.addListener(this._shim,"gestureend",this._onGestureEnd,this),SFDOMEvent.addListener(this._shim,"mouseup",this._onMouseUp,this),SFDOMEvent.addListener(this._shim,"mousemove",
this._onMouseMove,this),SFDOMEvent.addListener(window,"scroll",this._sizeShim,this))},_createTouchInfo:function(a){var c=b(a);return{origin:c,lastPoint:c,point:c,startTouch:a,lastTouch:a}},_updateTouches:function(a){var c=a.touches,d=a.changedTouches;this._activeDrag.touches||(this._activeDrag.touches=[],this._activeDrag.ordered=[]);switch(a.type){case "touchstart":this._activeDrag.ordered=[];var g=this._activeDrag.touches.concat();a=0;for(var k=c.length;a<k;a++){var e=c[a],n=l(d,e);0<=n?(n=this._createTouchInfo(e),
this._activeDrag.touches.push(n)):(n=q(g,e,!0),0<=n?n=g.splice(n,1)[0]:(n=this._createTouchInfo(e),this._activeDrag.touches.push(n)));this._activeDrag.ordered[a]=n}if(0<g.length){a=0;for(k=g.length;a<k;a++)this._activeDrag.touches.splice(this._activeDrag.touches.indexOf(g[a]),1)}break;case "touchend":a=0;for(k=d.length;a<k;a++)c=q(this._activeDrag.touches,d[a],!0),n=this._activeDrag.touches[c],this._activeDrag.touches.splice(c,1),this._activeDrag.ordered.remove(n);break;case "touchmove":a=0;for(k=
d.length;a<k;a++)e=d[a],g=l(c,e),n=this._activeDrag.ordered[g],n.lastPoint=n.point,n.point=b(e)}}})}(),SFDragDropMgr.init());
function SFContainer(a,b){this.register();!Array.isArray(a)&&"object"==typeof a&&(b=a,a=null);b=new juic.Config(b,null,{printStyleClass:["string",null],styleClass:["string",null],innerClass:["string",null],outerTag:["div","span","ul","ol","table","tr","td",null],innerTag:["div","span","li","tr","td",null]});b.outerTag||(b.outerTag=!1===b.outerBlock?"span":"div");b.innerTag||(b.innerTag="ul"==b.outerTag||"ol"==b.outerTag?"li":!1===b.innerBlock?"span":"div");this._outerRole=b.outerRole;this._innerRole=
b.innerRole;this._outerTag=b.outerTag;this._innerTag=b.innerTag;this._styleClass=b.styleClass;this._printStyleClass=b.printStyleClass;this._innerClass=b.innerClass;this.setChildren(a)}
(function(){document.createElement("div");juic.extend(SFContainer,juic.Component,{renderHtml:function(a){var b=this.getOuterTag();a.push("\x3c",b,' id\x3d"',this.id,'"');this._outerRole&&a.push(' role\x3d"',this._outerRole,'"');this._styleClass&&a.push(' class\x3d"',this._styleClass,'"');a.push("\x3e");this._renderChildren(a);a.push("\x3c/",b,"\x3e")},renderPrintHtml:function(a){var b=this.getOuterTag();a.push("\x3c",b,' id\x3d"',this.id,'"');this._printStyleClass&&a.push(' class\x3d"',this._printStyleClass,
'"');a.push("\x3e");this._renderPrintChildren(a);a.push("\x3c/",b,"\x3e")},get:function(a){return this._isValidIndex(a)&&this._children[a]},set:function(a,b,c){if(this._isValidIndex(a)&&(c&&this._children[a]instanceof juic.Component&&this._children[a].cleanup(),this._children[a]=b,c=juic.$(this.id))){var d=c.childNodes,e=this._createChildDOM(b);c.replaceChild(e,d[a]);this._updateChildDOM(e,b)}},insert:function(a,b,c){if(this._isValidIndex(a,!0))if(b instanceof Array){c=juic.$(this.id);for(var d=0,
e=b.length;d<e;d++)this.insert(a+d,b[d],c)}else if(d=this.size(),this._children.splice(a,0,b),c=c||juic.$(this.id))e=this._createChildDOM(b),a==d?c.appendChild(e):c.insertBefore(e,c.childNodes[a]),this._updateChildDOM(e,b)},add:function(a){this.append(a)},append:function(a){this.insert(this.size(),a)},removeAt:function(a,b){if(this._isValidIndex(a)){var c=this._children.splice(a,1)[0],d=juic.$(this.id);d&&d.removeChild(d.childNodes[a]);b&&c instanceof juic.Component&&c.cleanup();return c}},remove:function(a,
b){var c=this.indexOf(a);if(0<=c){a=this._children.splice(c,1);var d=juic.$(this.id);d&&d.removeChild(d.childNodes[c]);b&&a instanceof juic.Component&&a.cleanup();return a}},reorder:function(a){for(var b=0;b<this._children.length;b++){var c=this._children.indexOf(a[b],b);if(c!=b){if(c<b)return!1;this.move(c,b)}}return!0},move:function(a,b,c){c=c||1;if(this._isValidIndex(a)&&this._isValidIndex(b)&&this._isValidIndex(a+c-1)&&this._isValidIndex(b+c-1)&&a!=b){var d=this._children.splice(a,c);d.splice(0,
0,b,0);this._children.splice.apply(this._children,d);var e=juic.$(this.id);if(e){for(var d=[],l=c-1;0<=l;l--)e.removeChild(d[l]=e.childNodes[a+l]);a=b==e.childNodes.length?null:e.childNodes[b];for(l=0;l<c;l++)a?e.insertBefore(d[l],a):e.appendChild(d[l])}}},size:function(){return this._children.length},indexOf:function(a){for(var b=0,c=this.size();b<c;b++)if(this.get(b)===a)return b;return-1},getChildren:function(){return this._children.concat()},setChildren:function(a,b){this._children&&b&&this.broadcast("cleanup");
this._children=a||[];juic.assert(this._children instanceof Array,"SFContainer: You must provide an array for children");var c=juic.$(this.id);if(c){var d=juic.createRenderContext();this._renderChildren(d);d.renderInto(c)}},getStyleClass:function(){return this._styleClass},setStyleClass:function(a){this._styleClass=a;if(a=juic.$(this.id))a.className=this._styleClass},getInnerClass:function(){return this._innerClass},setInnerClass:function(a){this._innerClass=a;var b=juic.$(this.id);if(b)for(var b=
b.childNodes,c=0,d=b.length;c<d;c++)b[c].className=a},cleanup:function(a){a&&this.broadcast("cleanup");this._super()},broadcast:function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);"function"==typeof a&&b.splice(0,0,null,null);for(var c=0,d=this.size();c<d;c++){var e=this.get(c);switch(typeof a){case "string":e&&(e[a]&&"function"==typeof e[a])&&e[a].apply(e,b);break;case "function":b[0]=e,b[1]=c,a.apply(this,b)}}},getInnerTag:function(){return this._innerTag},getOuterTag:function(){return this._outerTag},
_isValidIndex:function(a,b){var c=0<=a&&a<this.size()+(b?1:0);juic.assert(c,"SFContainer: Invalid index "+a);return c},_renderChildren:function(a){this._children.forEach(function(b){this._renderChild(a,b)},this)},_renderPrintChildren:function(a){this._children.forEach(function(b){this._renderPrintChild(a,b)},this)},_renderChild:function(a,b){var c=this.getInnerTag();a.push("\x3c",c);this._innerRole&&a.push(' role\x3d"',this._innerRole,'"');this._innerClass&&a.push(' class\x3d"',this._innerClass,'"');
a.push("\x3e");this._renderInnerChild(a,b);a.push("\x3c/",c,"\x3e")},_renderPrintChild:function(a,b){var c=this.getInnerTag();a.push("\x3c",c);this._innerClass&&a.push(' class\x3d"',this._innerClass,'"');a.push("\x3e");this._renderPrintInnerChild(a,b);a.push("\x3c/",c,"\x3e")},_renderInnerChild:function(a,b){b&&(b instanceof juic.Component?Array.isArray(a)?b.renderHtml(a):a.push(b):a.push(juic.escapeHTML(b.toString())))},_renderPrintInnerChild:function(a,b){b&&(b instanceof juic.Component?b.renderPrintHtml(a):
a.push(juic.escapeHTML(b.toString())))},_createChildDOM:function(a){a=document.createElement(this.getInnerTag());this._innerRole&&(a.role=this._innerRole);this._innerClass&&(a.className=this._innerClass);return a},_updateChildDOM:function(a,b){var c=juic.createRenderContext();this._renderInnerChild(c,b);c.renderInto(a)}})})();function SFListContainer(a,b){"object"==typeof a&&(!Array.isArray(a)&&!(a instanceof SFDefaultListModel))&&(b=a,a=[]);this._super(b);this.setModel(a)}
juic.extend(SFListContainer,SFContainer,{setModel:function(a){this._model&&(this._model.removeEventListener("contentsChanged",this),this._model.removeEventListener("intervalAdded",this),this._model.removeEventListener("intervalRemoved",this),this._model.removeEventListener("intervalMoved",this),this._model.removeEventListener("selectionChanged",this),this.setChildren(null,!0));if(a){var b=a;Array.isArray(a)&&(b=new SFDefaultListModel(b));assert(b instanceof SFDefaultListModel,"SFListContainer: Invalid model");
this._model=b;this._model.addEventListener("contentsChanged",this,"_onContentsChanged");this._model.addEventListener("intervalAdded",this,"_onIntervalAdded");this._model.addEventListener("intervalRemoved",this,"_onIntervalRemoved");this._model.addEventListener("intervalMoved",this,"_onIntervalMoved");this._model.addEventListener("selectionChanged",this,"_onSelectionChanged");for(a=0;a<this._model.size();a++)this.add(this._model.get(a));this._onSelectionChanged()}this._changeDimensions()},getModel:function(){return this._model},
cleanup:function(){this.isRegistered()&&(this.setModel(null),this._super())},_onSelectionChanged:function(){if(this._model instanceof SFDefaultSingleSelectModel){var a=this._model.getSelectedIndex();0<this._model.size()&&(a=0<=a&&this.get(a),a!==this._selectedComponent&&(this._selectedComponent&&this._setComponentSelected(this._selectedComponent,!1),this._isSelectable(a)?(this._setComponentSelected(a,!0),this._selectedComponent=a):this._selectedComponent=null))}else if(this._model instanceof SFDefaultMultiSelectModel){var b=
this._selectedComponents||[];this._selectedComponents=[];this._model.getSelectedIndices().forEach(function(a){a=this.get(a);this._isSelectable(a)&&(this._selectedComponents.push(a),b.contains(a)||this._setComponentSelected(a,!0))},this);b&&b.forEach(function(a){this._selectedComponents.contains(a)||this._setComponentSelected(a,!1)},this)}},_setComponentSelected:function(a,b){a instanceof juic.Component&&a.isRegistered()&&a.setSelected(b)},_isSelectable:function(a){return a&&a instanceof juic.Component&&
a.isRegistered()&&"function"==typeof a.setSelected&&a!==this._selectedItem},_onContentsChanged:function(a){if(0<=a.index0){for(var b=a.index0;b<=a.index1;b++){var c=this._model.get(b);this.set(b,c,!0)}this._changeDimensions()}this._onSelectionChanged()},_onIntervalAdded:function(a){for(var b=a.index0;b<=a.index1;b++){var c=this._model.get(b);this.insert(b,c)}this._changeDimensions()},_onIntervalRemoved:function(a){for(var b=a.index1;b>=a.index0;b--)this.removeAt(b,!0);this._changeDimensions()},_onIntervalMoved:function(a){this.move(a.beforeIndex,
a.afterIndex,a.count);this._changeDimensions()},_changeDimensions:function(){juic.$(this.id)&&this.dispatch("changeDimensions")}});function SFAbstractOverlayMgr(){}juic.extend(SFAbstractOverlayMgr,juic.EventTarget,{show:function(a,b){throw Error("SFAbstractOverlayMgr: Must implement show");},css:function(a,b){throw Error("SFAbstractOverlayMgr: Must implement css");},animate:function(a,b){throw Error("SFAbstractOverlayMgr: Must implement animate");}});
function SFDefaultOverlayMgr(){this._model=new SFDefaultListModel}
(function(){function a(a){this.register();this._model=a.model;this._context=a.context;this._init(a.component,a.options)}var b={css:void 0,modal:!0,centered:void 0,cleanup:!1,iframeUnderlay:!1,viewport:!1,fullScreen:!1,dispatchEscKeyPress:!1,shadow:!1,autoClose:!1},c=["component","modal","position","alwaysInViewport","options"],d={modal:!0,position:null,fullScreen:!1,alwaysInViewport:!1,iframe:!1,autoClose:!1,options:{dispatchEscKeyPress:!1}},e={component:juic.Component,position:[{left:"number",top:"number"},
null]},l=juic.Logger.getLogger("SFOverlayMgr"),q={},r={},h={};juic.extend(SFDefaultOverlayMgr,SFAbstractOverlayMgr,{_init:function(){var a=new SFListContainer(this._model,{styleClass:"sfOverlayMgr"});div=document.createElement("div");div.setAttribute("id","sfOverlayMgr");AccessibilityPrefs.isLowVisionEnabled()&&(div.className="globalLowVisionSupport "+AccessibilityPrefs.getLowVisionType());this.getContext().appendChild(div);a.render(div);this.attach()},attach:function(){SFBodyEventDispatcher.addResizeListener(this,
"_handleResize");SFDOMEvent.addListener(this.getScrollElement(),"scroll",this._handleScroll,this)},detach:function(){SFBodyEventDispatcher.removeResizeListener(null,this);SFDOMEvent.removeListener(this.getScrollElement(),"scroll",this._handleScroll,this)},getContext:function(){return document.body},getScrollElement:function(){var a=this.getContext();return a==document.body?window:a},show:function(a,c){c=new juic.Config(c,b);c.iframeUnderlay=!(!window.SFOverlayMgrSettings||!window.SFOverlayMgrSettings.iframeUnderlay);
if(c.modal&&"undefined"==typeof c.centered||!c.css)c.centered=!0;c.centered&&(c.viewport=!0);juic.assert(a instanceof juic.Component,"SFOverlayMgr: show requires a component");juic.assert(a.isRegistered(),"SFOverlayMgr: component is not registered");if(this.hasOverlay(a))l.error("Attempted 2 overlays for the same component ",a);else{if(!this._preinit){var d=this;this._preinit=!0;SFDOMEvent.ready({priority:"HIGHEST",callback:function(){d._init()}})}var k=this._createOverlay({component:a,options:c,
model:this._model,context:this.getContext()});this._model.add(k);k.setIframe();return k}},_createOverlay:function(b){return new a(b)},getOverlay:function(a){return"string"==typeof a?r[a]:a&&r[a.id]},animate:function(a,b,c){if(a=this.getOverlay(a))return a.animate(b,c);juic.assert(!1,"SFOverlayMgr: Overlay not found for animate")},css:function(a,b){var c=this.getOverlay(a);c?c.css(b):juic.assert(!1,"SFOverlayMgr: Overlay not found for css")},setModal:function(a,b){var c=this.getOverlay(a);if(c)return c.setModal(b);
juic.assert(!1,"SFOverlayMgr: Overlay not found for setModal")},getOptions:function(a){if(a=this.getOverlay(a))return a.getOptions();juic.assert(!1,"SFOverlayMgr: Overlay not found for getOverlayOptions")},setOptions:function(a,b){var c=this.getOverlay(a);c?c.setOptions(b):juic.assert(!1,"SFOverlayMgr: Overlay not found for setOverlayOption")},getComponent:function(a){if(a=h[a])return a.component},hasOverlay:function(a){return!!this.getOverlay(a)},getOverlayId:function(a){return(a=this.getOverlay(a))&&
a.getReferenceId()},getViewportHeight:function(){return SFDom.getViewportHeight()},getViewportWidth:function(){return SFDom.getViewportWidth()},getAttribute:function(a){return q[a]},setAttribute:function(a,b){q[a]=b},showOverlay:function(a,b,g,k,h){var n=juic.Config.convertArguments(arguments,c,d,e);juic.set(n,n.options||{});g=n.position;var l=n.modal||!g;this.show(n.component,{css:l?void 0:{left:g.left+"px",top:g.top+"px"},centered:l,viewport:l,modal:n.modal,dispatchEscKeyPress:n.dispatchEscKeyPress})},
repositionComponent:function(a,b){var c=this.getComponent(a);c?this.css(c,{left:b.left+"px",top:b.top+"px"}):juic.assert(!1,"SFOverlayMgr: Invalid overlay id")},centerComponent:function(a){this.setOptions(a,{viewport:!0,centered:!0})},removeOverlay:function(a){(a=juic.Component._registry[a])&&a.dispatch("hide")},changeIframeDims:function(a,b,c){(a=juic.Component._registry[c])&&a.dispatch("changeDimensions")},_handleResize:function(){SFOverlayMgr.dispatch("viewportResized");this._model.forEach(function(a){a._reposition()})},
_handleScroll:function(){this._model.forEach(function(a){a._reposition()})}});juic.extend(a,juic.Component,{_init:function(a,b){this._overlayId=this.id+"container";this.component=a;this.component.addEventListener("hide",this,"_hide");this.component.addEventListener("bringToTop",this,"_bringToTop");this.component.addEventListener("changeDimensions",this,"_changeDimensions");this.options=b;h[this._overlayId]=this;r[a.id]=this;b.dispatchEscKeyPress&&this._setKeyListener(!0)},cleanup:function(){delete h[this._overlayId];
delete r[this.component.id];this.options.cleanup&&this.component.isRegistered()?this.component.cleanup():(this.component.removeEventListener("hide",this),this.component.removeEventListener("bringToTop",this),this.component.removeEventListener("changeDimensions",this));this._super()},getReferenceId:function(){return this._overlayId},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'" class\x3d"',this._getClassName(),'" style\x3d"visibility:hidden"\x3e');a.push('\x3cdiv id\x3d"',this.id,'shim" class\x3d"overlayShim"\x3e\x3c/div\x3e');
a.push('\x3cdiv id\x3d"',this._overlayId,'" class\x3d"',"globalContentBackground globalContentForeground sfoverlaycontainer",'"');SFDom.renderStyle(a,this.options.css);a.push("\x3e\x3c/div\x3e\x3c/div\x3e");a.addAfterRenderListener(this,"_postRender")},_postRender:function(){function a(){this._adjustDOM();this._overlayContainer.style.visibility="visible";SFOverlayMgr.dispatch("overlayRendered",{componentId:this.component.id,overlayId:this._overlayId,componentWidth:this._dimension.width,componentHeight:this._dimension.height,
isModal:this.options.modal,context:this._context})}this.component.render(this._overlayId);this._overlayContainer=juic.$(this.id);this._shim=juic.$(this.id+"shim");this._overlay=juic.$(this._overlayId);Util.browserInfo.ieQuirks&&Util.isRTL()&&(this._overlay.style.zoom=1);if(Util.browserInfo.ieQuirks){var b=this;setTimeout(function(){a.call(b)},0)}else a.call(this);SFDOMEvent.addListener(this._shim,"touchstart",this._clickShim,this,!0);SFDOMEvent.addListener(this._shim,"mousedown",this._clickShim,this,
!0)},_hideBodyElements:function(){if(!this._bodyHidden){this._context.style.width="";this._hiddenBodyElements=this._hiddenBodyElements||[];for(var a=this._context.firstChild;a;a=a.nextSibling)"sfOverlayMgr"!==a.id&&(SFDom.isElementNode(a)&&SFDom.isDisplayed(a))&&(this._hiddenBodyElements.push({el:a,display:a.style.display}),a.style.display="none")}},_clickShim:function(){this.options.autoClose&&this.component.dispatch("hide")},_resetBodyElements:function(){this._hiddenBodyElements&&this._hiddenBodyElements.forEach(function(a){a.el.style.display=
a.display});this._hiddenBodyElements=null},_adjustDOM:function(){if(this._overlay){var a=this._overlay.lastChild;this._dimension={width:a.offsetWidth,height:a.offsetHeight};this._reposition();this.options.fullScreen?this._hideBodyElements():this._resetBodyElements()}},_reposition:function(){if(this._doesContainerRequirePosition()&&this._dimension){var a=SFDom.getDocumentScrollTop(),b=SFDom.getDocumentScrollLeft(),c=SFDom.getViewportWidth(),d=SFDom.getViewportHeight(),e=d<this._dimension.height,n=
c<this._dimension.width;Util.browserInfo.ieQuirks&&(this.options.viewport?SFDom.updateStyle(this._overlayContainer,{top:a+"px",left:b+"px"}):this.options.modal&&SFDom.updateStyle(this._shim,{top:a+"px",left:b+"px"}),SFDom.updateStyle(this._overlayContainer,{width:c+"px",height:d+"px"}));if(this.options.centered){if(e||n){this._scrollFirst=this._scrollFirst||{scrollTop:a,scrollLeft:b};var h=this._scrollFirst.scrollTop,l=this._scrollFirst.scrollLeft;n||(l+=(c-this._dimension.width)/2);e||(h+=(d-this._dimension.height)/
2);c={position:"absolute",left:l+"px",top:h+"px"};Util.browserInfo.ieQuirks?(c={position:"absolute",left:l+"px",top:"0px"},juic.set(c,{"margin-left":this._scrollFirst.scrollLeft-b,"margin-top":this._scrollFirst.scrollTop-a})):juic.set(c,{"margin-left":"","margin-top":""})}else delete this._scrollFirst,c={left:"",top:"",position:"","margin-left":-this._dimension.width/2+"px","margin-top":-this._dimension.height/2+"px"};SFDom.updateStyle(this._overlay,c)}this.setIframe()}},setIframe:function(){this.options.iframeUnderlay?
(this._createHiddenIframe(),this.options.modal?juic.set(this._iframe.style,{width:"100%",height:"100%",top:SFDom.getStyle(this._shim,"top"),left:SFDom.getStyle(this._shim,"left")}):juic.set(this._iframe.style,{width:this._dimension.width+"px",height:this._dimension.height+"px",marginLeft:SFDom.getStyle(this._overlay,"margin-left"),marginTop:SFDom.getStyle(this._overlay,"margin-top"),position:SFDom.getStyle(this._overlay,"position"),top:SFDom.getStyle(this._overlay,"top"),left:SFDom.getStyle(this._overlay,
"left")})):this._removeHiddenIframe()},_createHiddenIframe:function(){if(this._overlayContainer&&!this._iframe){this._iframe=document.createElement("iframe");juic.set(this._iframe,{style:{position:"absolute",border:"0",opacity:"0",zIndex:SFDom.getStyle(this._overlay,"z-index"),filter:"alpha(opacity\x3d0)"},title:MSGS.COMMON_HIDDEN_FRAME_TITLE,tabIndex:-1,role:"presentation",src:IMAGES["/ui/juic/img/_.gif"]});var a=this._overlayContainer.firstChild;a?this._overlayContainer.insertBefore(this._iframe,
a):this._overlayContainer.appendChild(this._iframe)}},_removeHiddenIframe:function(){this._iframe&&(this._iframe.parentNode.removeChild(this._iframe),this._iframe=null)},_doesContainerRequirePosition:function(){var a=this.options;if(a.modal||a.centered||a.viewport)return!0;if(a=a.css){if(null!=a.right||null!=a.bottom)return!0;for(var b in a){var c=a[b];if("string"==typeof c&&0<c.indexOf("%"))return!0}}return!1},_keypressHandler:function(a){switch(SFDOMEvent.getKeyName(a)){case "ESCAPE":SFDOMEvent.stopEvent(a),
SFOverlayMgr.dispatch("escKeyPressed",a)}},_getClassName:function(){var a=["sf-overlay"];this.options.modal&&a.push("modalOverlay");this.options.centered&&a.push("centeredOverlay");this.options.viewport?a.push("viewportOverlay"):a.push("documentOverlay");this.options.styleClass&&a.push(this.options.styleClass);return a.join(" ")},_hide:function(){if(this.isRegistered()){var a=this._model.indexOf(this),b=!!juic.$(this.id);0<=a&&this._model.removeItemAt(a);b||this.cleanup();this._setKeyListener(!1);
SFOverlayMgr.dispatch("overlayHidden",{component:this.component,options:this.options});this.options.fullScreen&&this._resetBodyElements();this.dispatch("hide")}},_setKeyListener:function(a){this._keyListening!=a&&(a?SFDOMEvent.addListener(window.document,"keydown",this._keypressHandler,this):SFDOMEvent.removeListener(window.document,"keydown",this._keypressHandler,this),this._keyListening=a)},_bringToTop:function(){var a=this._model.indexOf(this),b=this._model.size()-1;a<b&&this._model.move(a,b,1)},
_changeDimensions:function(){this._adjustDOM()},animate:function(a,b){juic.set(this.options,{css:a});return SFAnimUtil.animate(this._overlay,a,b)},css:function(a){juic.set(this.options,{css:a});SFDom.updateStyle(this._overlay,a)},setOptions:function(a){var b=!1,c;for(c in a){var d=a[c];switch(c){case "dispatchEscKeyPress":this.options[c]=d;this._setKeyListener(!!d);break;case "css":this.css(d);break;case "modal":case "centered":case "viewport":case "styleClass":case "fullScreen":b=!0;default:this.options[c]=
d}}b&&(this._overlayContainer.className=this._getClassName(),this._adjustDOM());this.dispatch("optionsChanged",{options:a})},getOptions:function(){return juic.set({},this.options)},getOption:function(a){return this.options[a]},setModal:function(a){SFDom[a?"addClass":"removeClass"](this.id,"modalOverlay")}});SFAbstractOverlayMgr.Overlay=a;window.SFOverlayMgr=new SFDefaultOverlayMgr})();function SFAbstractPositionManager(){}
juic.extend(SFAbstractPositionManager,juic.EventTarget,{show:function(a){throw Error("SFAbstractPositionManager: Must implement show");},moveTo:function(a,b,c){throw Error("SFAbstractPositionManager: Must implement moveTo");}});
"undefined"==typeof SFPositionManager&&function(){function a(){}function b(a,b,f,g){var p=SFDom.getViewportRegion(),m=SFDom.getRegion(b),s=SFDom.getRegion(a),r=SFDom.getAncestorScale(b),y=q(juic.$(a));0==s.width&&(s.width=document.getElementById(a).scrollWidth);0==s.height&&(s.height=document.getElementById(a).scrollHeight);1!=r&&(m=new SFRegion(m.top,m.left+m.width*r,m.top+m.height*r,m.left));var w={fixPoint:{origin:{originId:b.id},menu:{}},overlay:{overlayId:SFOverlayMgr.getOverlayId(a)||juic.$(a).parentNode.id,
width:s.width,height:s.height}},x={positionInfo:w};l(function(a){var b={axis:a,origin:f&&f.origin&&f.origin[a.direction]||a.origin,menu:f&&f.menu&&f.menu[a.direction]||a.menu,offset:f&&f.offset&&f.offset[a.direction]||a.offset},k=s[a.dimensionType],l=c(b,m,k,!1),t=d(p,a,l,k),r=c(b,m,k,!0),q=d(p,a,r,k),u;u=!1;t&&(u=q?Math.abs(q)+h<Math.abs(t):!0);l=u?r:l;t=u?q:t;q=u?e(a,b.origin):b.origin;b=u?e(a,b.menu):b.menu;t&&(g&&0>t&&(l-=t,0>l&&(l=0)),x[a.newComponentDimension]=k-Math.abs(t));y&&(l-=p[a.regionStart]);
w.fixPoint.origin[a.direction]=q;w.fixPoint.menu[a.direction]=b;w.overlay[a.regionStart]=l});return x}function c(a,b,c,d){var f=a.axis,g=a.origin,h=a.menu;a=a.offset;d&&(g=e(f,g),h=e(f,h),a*=-1);d=a;switch(g){case "middle":d+=(b[f.regionStart]+b[f.regionEnd])/2;break;default:d+=b[g]}switch(h){case "middle":d-=Math.round(c/2);break;case "right":case "bottom":d-=c}return d}function d(a,b,c,d){var e=a[b.regionStart];a=a[b.regionEnd];d=c+d;if(e<=c&&d<=a)return 0;c=e-c;e=d-a;return c>e?-c:e}function e(a,
b){return"middle"==b?"middle":b==a.regionStart?a.regionEnd:a.regionStart}function l(a){a.call(window.SFPositionManager,r.x);a.call(window.SFPositionManager,r.y)}function q(a){return a?"fixed"==SFDom.getStyle(a,"position")?!0:q(a.parentNode):!1}var r={x:{axisType:"x",direction:"horizontal",dimensionType:"width",newComponentDimension:"newComponentWidth",regionStart:"left",regionEnd:"right",origin:Util.isRTL()?"right":"left",menu:Util.isRTL()?"right":"left",offset:0},y:{axisType:"y",direction:"vertical",
dimensionType:"height",newComponentDimension:"newComponentHeight",regionStart:"top",regionEnd:"bottom",origin:"bottom",menu:"top",offset:0}},h=50,f=["component","originId","fixPoint","alwaysInViewport","showRelativeToViewport"],m={component:void 0,originId:void 0,fixPoint:void 0,alwaysInViewport:void 0,showRelativeToViewport:void 0},g={component:juic.Component,originId:["string",juic.Config.htmlElementType(),null],fixPoint:["object","boolean",null],alwaysInViewport:["boolean",null],showRelativeToViewport:["boolean",
null]};juic.extend(a,SFAbstractPositionManager,{showMenu:function(a,b,c){this.show(a,b,c)},show:function(a){a=juic.Config.convertArguments(arguments,f,m,g);juic.assert(a.component instanceof juic.Component,"[SFPositionManager] component must be a Component object");SFOverlayMgr.addEventListener("overlayRendered",this,"_onOverlayRendered");this._componentId=a.component.id;this._origin=juic.$(a.originId);this._fixPoint=a.fixPoint;this._alwaysInViewport=a.alwaysInViewport;var b="boolean"==typeof a.showRelativeToViewport?
a.showRelativeToViewport:q(this._origin);SFOverlayMgr.show(a.component,{modal:!1,viewport:b,css:{top:0,left:0}})},_onOverlayRendered:function(a){SFOverlayMgr.removeEventListener("overlayRendered",this);this._moveMenu(this._componentId,this._origin,this._fixPoint,this._alwaysInViewport)},moveTo:function(a,b,c,d){a instanceof juic.Component&&(a=a.id);juic.assert("string"==typeof a,"[SFPositionManager] componentId must be the string id of the component.");juic.assert(c,"[SFPositionManager] originId is required.");
(c=juic.$(c))&&this._moveMenu(a,c,b,d)},_moveMenu:function(a,c,d,e){juic.$(a)&&juic.$(c)&&(c=b(a,c,d,e),d=c.positionInfo.overlay,c.componentId=a,!isNaN(d.top)&&!isNaN(d.left)&&SFOverlayMgr.css(a,{top:d.top+"px",left:d.left+"px"}),this.dispatch("positionFixed",c))}});window.SFPositionManager=new a}();
"undefined"==typeof window.SFFluidLayout&&function(){function a(a){this.setOptions(a)}juic.extend(a,juic.EventTarget,{_DEFAULT_MIN_LAYOUT_WIDTH:1024,_DEFAULT_MAX_LAYOUT_WIDTH:1168,_LAYOUT_X_PADDING:15,_DEFAULT_SCROLLBAR_WIDTH:40,_containerSize:null,_containerMaxed:!0,_pageContainerDOM:null,_MIN_HEIGHT:25,_pageContentId:"content",_headerId:"renderTopNavFixedWidthV12",_enabledResizeHeight:!1,_getPageContainer:function(){var a=Util.getPageContainerId();this._pageContainerDOM||(this._pageContainerDOM=
juic.$(a));return this._pageContainerDOM},_noPaddingCheck:function(){if(window.fluidPageNoPadding||this.viewportWidth<=this._minLayoutWidth)this._getPageContainer().style.padding="0"},initDims:function(){var a=window.SFDom;if(!a||!this._getPageContainer())return!1;this.viewportWidth=a.getViewportWidth();if(window.fluidPageDefaultTo)switch(window.fluidPageDefaultTo){case "restrictedMaximum":this.restrictedMax();break;case "minimize":this.minimize();break;case "maximize":this.maximize()}else this._makePageFluid();
this._noPaddingCheck();return!0},_makePageFluid:function(){this._getPageContainer().style.padding="";this.viewportWidth<=this._minLayoutWidth?this.minimize():this.viewportWidth>this._minLayoutWidth&&this.viewportWidth<=this._maxLayoutWidth?this.maximize():this.restrictedMax()},_getNumericStyle:function(a,c){return parseInt(SFDom.getComputedStyle(a,c),10)||0},windowResize:function(){this.initDims()&&(!0==this._containerMaxed&&(this._containerSize&&"max"!=this._containerSize&&this.viewportWidth>this._containerSize)&&
(this._getPageContainer().style.width=this._containerSize+"px"),this._noPaddingCheck(),this._enabledResizeHeight&&this._resizeHeight(),this.dispatch("resize"))},_isFooterInsideContent:function(a){if(a)for(;a=a.parentNode;)if(a.id==this._pageContentId)return!0;return!1},_resizeHeight:function(){var a=juic.$(this._pageContentId);if(a){var c=juic.$("footer"),d=juic.$(this._headerId);this._isFooterInsideContent(c)&&(c=null);var e=SFDom.getViewportHeight(),c=c?SFDom.getMargin(c)+c.offsetHeight:0,d=d?SFDom.getMargin(d)+
d.offsetHeight:0,l=SFDom.getOffsets(a),e=Math.max(this._MIN_HEIGHT,e-c-d-l);a.style.height=e+"px"}},resizePageBy:function(a){this._containerSize=a=this._getPageContainer().offsetWidth+a;this._hasMaxedWidth(a)?(this.maximize(),this._containerMaxed=!0):this._getPageContainer().style.width=a+"px";window.fluidPageDefaultTo=null},resizePageTo:function(a){this._containerSize=a;this._hasMaxedWidth(a)?(this.maximize(),this._containerMaxed=!0):this._getPageContainer().style.width=a+"px";window.fluidPageDefaultTo=
null},restrictedMax:function(){this._getPageContainer().style.width=this._maxLayoutWidth+"px";this._getPageContainer().style.minWidth=this._maxLayoutWidth+"px";this._containerSize=this._maxLayoutWidth},maximize:function(){this._containerSize="max";this._containerMaxed=!0;this._getPageContainer().style.width="auto";this._getPageContainer().style.minWidth="auto";this._getPageContainer().style.padding="0 "+this._LAYOUT_X_PADDING+"px"},minimize:function(){var a=this._minLayoutWidth-this._DEFAULT_SCROLLBAR_WIDTH;
this._containerSize=a;this._getPageContainer().style.width=a+"px";this._getPageContainer().style.minWidth=a+"px";this._noPaddingCheck()},_hasMaxedWidth:function(a){return this.viewportWidth<a},setOptions:function(a){a&&a.minWidth?this.setMinLayoutWidth(a.minWidth):this.setMinLayoutWidth(this._DEFAULT_MIN_LAYOUT_WIDTH);a&&a.maxWidth?this.setMaxLayoutWidth(a.maxWidth):this.setMaxLayoutWidth(this._DEFAULT_MAX_LAYOUT_WIDTH);a&&a.headerId&&this.setHeaderId(a.headerId);a&&a.pageContentId&&this.setPageContentId(a.pageContentId);
a&&a.enabledResizeHeight&&this.setEnabledResizeHeight(a.enabledResizeHeight)},setMinLayoutWidth:function(a){this._minLayoutWidth=a},getMinLayoutWidth:function(){return this._minLayoutWidth},setMaxLayoutWidth:function(a){this._maxLayoutWidth=a},getMaxLayoutWidth:function(){return this._maxLayoutWidth},setHeaderId:function(a){this._headerId=a},getHeaderId:function(){return this._headerId},setPageContentId:function(a){this._pageContentId=a},getPageContentId:function(){return this._pageContentId},setEnabledResizeHeight:function(a){this._enabledResizeHeight=
a},getEnabledResizeHeight:function(){return this._enabledResizeHeight}});window.SFFluidLayout=new a;SFDOMEvent.ready(function(){var a=window.SFFluidLayout;a.initDims()&&(SFDOMEvent.addListener(window,"resize",a.windowResize,a,!0),setTimeout(function(){a.windowResize()},2E3))})}();function SFLoading(a,b,c){this.register();this._init(a,b,c)}
juic.extend(SFLoading,juic.Component,{CLASS_ROUNDED_CORNERS:"globalRoundedCornersSmall",CLASS_LOADING_ICON_CONTAINER:"sfV12LoadingIconContainer",CLASS_BODY_LOADING_INDICATOR:"sfV12BodyLoadingIndicator",CLASS_SECTION_LOADING_INDICATOR:"sfV12SectionLoadingIndicator",_init:function(a,b,c){this.setMsg(a||MSGS.COMMON_loading);this._hexColor=AccessibilityPrefs.isLowVisionEnabled()?"inherit":b||"#FFF";this.setConfig(c)},renderHtml:function(a){var b=this._renderNewRevolutionsIndicator?"sfV12LoadingIcon":
"sfloadingIcon",c=this._renderNewRevolutionsIndicator?"sfV12LoadingIconMsg":"sfloadingIconMsg";this._renderNewRevolutionsIndicator&&(a.push('\x3cdiv id\x3d"'+this.id+'" class\x3d"',this.CLASS_LOADING_ICON_CONTAINER,'"\x3e'),a.push('\x3cdiv class\x3d"',this.CLASS_ROUNDED_CORNERS," ",this._loadingIndicatorType,'"\x3e'));a.push('\x3cdiv class\x3d"globalContentForegroundVariant ',b,'"');this._renderNewRevolutionsIndicator||a.push(' id\x3d"',this.id,'"');a.push("\x3e");a.push('\x3cdiv class\x3d"',c,'" style\x3d"color:'+
this._hexColor+';" role\x3d"alert"\x3e'+juic.escapeHTML(this._msg)+"\x3c/div\x3e");a.push("\x3c/div\x3e");this._renderNewRevolutionsIndicator&&(a.push("\x3c/div\x3e"),a.push("\x3c/div\x3e"))},setConfig:function(a){a&&a.isNewLoadingIndicator?(this._renderNewRevolutionsIndicator=!0,this._loadingIndicatorType=a.isSectionLoadingIndicator?this.CLASS_SECTION_LOADING_INDICATOR:this.CLASS_BODY_LOADING_INDICATOR):this._renderNewRevolutionsIndicator=!1},setMsg:function(a){this._msg=a},remove:function(){this.hide();
this.cleanup();var a=juic.$(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)},hide:function(){this.dispatch("hide")}});