function SFScrollBox(d,g){this.register();this._init(d,g)}
(function(){function d(a,b,c){return a&&a[b].size-a[b].scrollArea>c}var g={autoHide:!0,scrollMargin:!0,vertical:!0,horizontal:!0,height:null,scrollTickSize:void 0,scrollInterval:void 0,minimumScroll:10,dragScroll:!1,dragInertia:!1,bubbleMouseWheel:!0};juic.extend(SFScrollBox,SFAbstractAdjustableHeight,{_init:function(a,b){var c=b,f={};set(f,g);if(c)for(var e in c){var d=c[e];null!=d&&(f[e]=d)}b=f;this._child=a;this._child instanceof juic.Component&&this._child.addEventListener("changeDimensions",
this,"adjustDOM");this._autoHide=b.autoHide;this._scrollMargin=b.scrollMargin;this._height=b.height;this._verticalOption=b.vertical;this._horizontalOption=b.horizontal;this._minimumScroll=b.minimumScroll;this._dragScroll=b.dragScroll;this._dragInertia=b.dragInertia;this._bubbleMouseWheel=b.bubbleMouseWheel;Util.browserInfo.ff||(this._focusMarker=new SFFocusMarker,this._focusMarker.addEventListener("focus",this,"_onFocus"),this._focusMarker.addEventListener("blur",this,"_onBlur"));this._autoScroller=
new SFAutoScroller({scrollEl:this.id+"scroller",tickSize:b.scrollTickSize,interval:b.scrollInterval});this._horizontal=this._horizontalOption&&new SFScrollBar({autoScroller:this._autoScroller,minimumScroll:this._minimumScroll,axisType:"x"});this._vertical=this._verticalOption&&new SFScrollBar({autoScroller:this._autoScroller,minimumScroll:this._minimumScroll,axisType:"y"});this._horizontalOption&&this._horizontal.addEventListener("action",this,"_onScrollBarAction");this._verticalOption&&this._vertical.addEventListener("action",
this,"_onScrollBarAction")},renderHtml:function(a){a.push('\x3cdiv id\x3d"',this.id,'" class\x3d"sfScrollBox',this._autoHide?" autoHideScroll":"",'"');SFDom.renderStyle(a,this._getContainerStyle());a.push(' onmouseover\x3d"',this.fireCode("_onHover",!0),'" onmouseout\x3d"',this.fireCode("_onHover",!1),'"\x3e\x3cdiv id\x3d"',this.id,'cutoff" class\x3d"scrollCutoff"');SFDom.renderStyle(a,this._getCutoffStyle());a.push('\x3e\x3cdiv id\x3d"',this.id,'scroller" class\x3d"scrollWrapper"');SFDom.renderStyle(a,
this._getScrollerStyle());a.push(' onscroll\x3d"',this.fireCode("_onScroll"),'" onfocus\x3d"',this.fireCode("_setFocus",!0),'" onblur\x3d"',this.fireCode("_setFocus",!1),'"');this._dragScroll&&a.push('ondragstart\x3d"return false" onmousedown\x3d"',this.fireCode("_onDragStart"),'" ontouchstart\x3d"',this.fireCode("_onDragStart"),'" unselectable\x3d"on" onselectstart\x3d"return false"');a.push("\x3e",this._focusMarker,this._child,'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"scrollBars',this._autoHide?
" autoHideHover":"",'"\x3e');this._verticalOption&&a.push(this._vertical);this._horizontalOption&&a.push(this._horizontal);a.push("\x3c/div\x3e\x3c/div\x3e");a.addAfterRenderListener(this,"_onLoad")},setChild:function(a){this._child=a;var b=juic.createRenderContext();b.push(a);b.renderInto(this.id);this.adjustDOM()},adjustDOM:function(){var a=juic.$(this.id);a&&(this._height||(this._height=parseInt(SFDom.getStyle(a,"height"))),SFDom.updateStyle(a,this._getContainerStyle()),SFDom.updateStyle(this.id+
"scroller",this._getScrollerStyle()),SFDom.updateStyle(this.id+"cutoff",this._getCutoffStyle()),this._horizontal&&this._horizontal.adjustDOM(),this._vertical&&this._vertical.adjustDOM(),this._vertical&&!this._height&&this._vertical.setEnabled(!1),this._child instanceof SFAbstractAdjustableHeight&&(a=a.offsetHeight-SFDom.getOffsets(a),this._child.setHeight(a)))},getAutoScroller:function(){return this._autoScroller},setHeight:function(a){this._height=a;this.adjustDOM()},cleanup:function(){this._child instanceof
juic.Component&&this._child.cleanup();this._focusMarker&&this._focusMarker.cleanup();this._vertical&&this._vertical.cleanup();this._horizontal&&this._horizontal.cleanup();this._super()},handleDragEvent:function(a){switch(a.type){case "dragStart":null!=this._intervalId&&clearInterval(this._intervalId);this._last=this._last2=null;break;case "drag":this._last2=this._last;this._last={x:a.lastPoint.x-a.point.x,y:a.lastPoint.y-a.point.y};this._autoScroller.scrollMove(this._last.x,this._last.y);break;case "dragEnd":try{if(this._last2&&
this._dragInertia){var b=this._autoScroller.getScrollInfo(),c=(this._last2.y+this._last.y)/2,f=b.x.position,e=b.y.position,d=Math.max(0,Math.min(b.x.size-b.x.scrollArea,f+6*((this._last2.x+this._last.x)/2))),h=Math.max(0,Math.min(b.y.size-b.y.scrollArea,e+6*c)),g=(new Date).getTime(),k=this;this._intervalId=setInterval(function(){var a=(new Date).getTime()-g;300<a?(k._autoScroller.setScrollPosition(d,h),clearTimeout(k._intervalId),k._intervalId=null):(a=SFAnimUtil.calculateEasing(a/300,"easeOut"),
k._autoScroller.setScrollPosition(f+a*(d-f),f+a*(h-e)))},10)}}catch(m){console.log(m)}}},_onLoad:function(){if(el=juic.$(this.id))this._loadTime=null,this._bubbleMouseWheel||SFDOMEvent.addListener(el,Util.browserInfo.ff?"DOMMouseScroll":"mousewheel",this._onMouseWheel,this),this.adjustDOM();else{var a=(new Date).getTime();this._loadTime=this._loadTime||a;if(5E3>a-this._loadTime){var b=this;setTimeout(function(){b._onLoad()},10)}}},_onMouseWheel:function(a){if(!this._bubbleMouseWheel){var b=0;a=a||
window.event;a.wheelDelta?(b=a.wheelDelta/120,window.opera&&(b=-b)):a.detail&&(b=-a.detail/3);var b=100*(0>b?1:0<b?-1:0),c=a.axis==a.VERTICAL_AXIS?"y":"x",d=this._autoScroller.getScrollInfo(),e=d[c],b=e.position+b;if(b+e.scrollArea>=e.size||0>b)this._autoScroller.setScrollPosition("x"==c?b:d.x.position,"y"==c?b:d.y.position),SFDOMEvent.stopEvent(a)}},_setFocus:function(a){SFDom[a?"addClass":"removeClass"](this.id,"scrollBoxFocused")},_onFocus:function(){this._setFocus(!0)},_onBlur:function(){this._setFocus(!1)},
_onDragStart:function(a){SFDragDropMgr.handleDragStart(a,this,{useShim:!0,shimCursor:"move"})},_onHover:function(a,b){Util.isMouseLeaveOrEnter(b,juic.$(this.id))&&(SFDom[a?"addClass":"removeClass"](this.id,"scrollBoxHover"),a&&this.adjustDOM())},_onScroll:function(){null!=this._scrollingTimeout?clearTimeout(this._scrollingTimeout):SFDom.addClass(this.id,"scrollBoxScrolling");this.adjustDOM();var a=this;this._scrollingTimeout=setTimeout(function(){SFDom.removeClass(a.id,"scrollBoxScrolling");a._scrollingTimeout=
null},1E3)},_getContainerStyle:function(){var a={};0<this._height&&(a.height=this._height+"px");if(this._scrollMargin){var b=this._autoScroller.getScrollInfo();b&&(this._height?(b=this._verticalOption&&d(b,"y",this._minimumScroll),a["padding-right"]=b?this._vertical.getOffset()+"px":0):(b=this._horizontalOption&&d(b,"x",this._minimumScroll),a["padding-bottom"]=b?this._horizontal.getOffset()+"px":0))}return a},_getCutoffStyle:function(){var a=juic.$(this.id+"scroller");if(a){var b={};if(0<this._height){var c=
this._autoScroller.getScrollInfo(),a=this._horizontalOption&&d(c,"x",this._minimumScroll)?a.offsetHeight-c.y.scrollArea:0;b.height=this._height-a+"px"}return b}},_getScrollerStyle:function(){var a=juic.$(this.id+"scroller");if(a){var b={},c=this._autoScroller.getScrollInfo(),f=this._verticalOption&&d(c,"y",0),e=this._verticalOption&&d(c,"y",this._minimumScroll),g=this._horizontalOption&&d(c,"x",0),h=this._horizontalOption&&d(c,"x",this._minimumScroll),l=e?a.offsetWidth-c.x.scrollArea:0,a=h?a.offsetHeight-
c.y.scrollArea:0,c=Util.isRTL()?"margin-left":"margin-right";b[c]=e?-l+"px":0;0<this._height?b.height=this._height+a+"px":(b["margin-bottom"]=h?-a+"px":0,Util.browserInfo.ie&&8>Util.ieVersion()&&(b["padding-bottom"]=h?a+"px":0,b["overflow-y"]="hidden"));f&&!e&&(b["overflow-y"]="hidden");g&&!h&&(b["overflow-x"]="hidden");return b}},_onScrollBarAction:function(a){var b=juic.$(this.id);switch(a.actionCommand){case "dragStart":SFDom.addClass(b,"scrollBoxDragging");break;case "dragEnd":SFDom.removeClass(b,
"scrollBoxDragging")}}})})();